[2024-01-01T08:43:02.678-0300] {scheduler_job_runner.py:781} ERROR - Executor reports task instance <TaskInstance: postgres_operator.fetch_pageviews_second manual__2024-01-01T11:42:37.443574+00:00 [queued]> finished (failed) although the task says it's queued. (Info: None) Was the task killed externally?
