[2024-01-01T11:41:41.691-0300] {scheduler_job_runner.py:781} ERROR - Executor reports task instance <TaskInstance: stocksense.get_data_oth manual__2024-01-01T14:41:14.347187+00:00 [queued]> finished (failed) although the task says it's queued. (Info: None) Was the task killed externally?
