[2024-01-01T11:40:28.871-0300] {scheduler_job_runner.py:781} ERROR - Executor reports task instance <TaskInstance: postgres_operator.extract_gz manual__2024-01-01T14:39:57.077630+00:00 [queued]> finished (failed) although the task says it's queued. (Info: None) Was the task killed externally?
