[2024-01-01T13:00:21.832-0300] {scheduler_job_runner.py:781} ERROR - Executor reports task instance <TaskInstance: stocksense.get_data_op scheduled__2024-01-01T15:00:00+00:00 [queued]> finished (failed) although the task says it's queued. (Info: None) Was the task killed externally?
