[2024-01-01T11:49:35.979-0300] {scheduler_job_runner.py:781} ERROR - Executor reports task instance <TaskInstance: 04_time_delta.fetch_events scheduled__2023-12-25T00:00:00+00:00 [queued]> finished (failed) although the task says it's queued. (Info: None) Was the task killed externally?
