[2024-01-01T11:46:44.324-0300] {scheduler_job_runner.py:781} ERROR - Executor reports task instance <TaskInstance: stocksense.get_data_oth scheduled__2023-12-31T20:00:00+00:00 [queued]> finished (failed) although the task says it's queued. (Info: None) Was the task killed externally?
