[2024-01-01T11:51:27.387-0300] {scheduler_job_runner.py:781} ERROR - Executor reports task instance <TaskInstance: stocksense.get_data scheduled__2024-01-01T13:00:00+00:00 [queued]> finished (failed) although the task says it's queued. (Info: None) Was the task killed externally?
