[2023-12-31T09:36:44.767-0300] {processor.py:161} INFO - Started process (PID=31975) to work on /home/felipe/airflow/dags/03_with_end_date.py
[2023-12-31T09:36:44.768-0300] {processor.py:830} INFO - Processing file /home/felipe/airflow/dags/03_with_end_date.py for tasks to queue
[2023-12-31T09:36:44.770-0300] {logging_mixin.py:188} INFO - [2023-12-31T09:36:44.769-0300] {dagbag.py:538} INFO - Filling up the DagBag from /home/felipe/airflow/dags/03_with_end_date.py
[2023-12-31T09:36:44.780-0300] {logging_mixin.py:188} INFO - [2023-12-31T09:36:44.779-0300] {dagbag.py:348} ERROR - Failed to import: /home/felipe/airflow/dags/03_with_end_date.py
Traceback (most recent call last):
  File "/home/felipe/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/felipe/airflow/dags/03_with_end_date.py", line 4, in <module>
    import pandas as pd
ModuleNotFoundError: No module named 'pandas'
[2023-12-31T09:36:44.781-0300] {processor.py:842} WARNING - No viable dags retrieved from /home/felipe/airflow/dags/03_with_end_date.py
[2023-12-31T09:36:44.841-0300] {processor.py:183} INFO - Processing /home/felipe/airflow/dags/03_with_end_date.py took 0.083 seconds
[2023-12-31T09:38:36.568-0300] {processor.py:161} INFO - Started process (PID=32175) to work on /home/felipe/airflow/dags/03_with_end_date.py
[2023-12-31T09:38:36.576-0300] {processor.py:830} INFO - Processing file /home/felipe/airflow/dags/03_with_end_date.py for tasks to queue
[2023-12-31T09:38:36.580-0300] {logging_mixin.py:188} INFO - [2023-12-31T09:38:36.579-0300] {dagbag.py:538} INFO - Filling up the DagBag from /home/felipe/airflow/dags/03_with_end_date.py
[2023-12-31T09:38:36.597-0300] {logging_mixin.py:188} INFO - [2023-12-31T09:38:36.589-0300] {dagbag.py:348} ERROR - Failed to import: /home/felipe/airflow/dags/03_with_end_date.py
Traceback (most recent call last):
  File "/home/felipe/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/felipe/airflow/dags/03_with_end_date.py", line 4, in <module>
    import pandas as pd
ModuleNotFoundError: No module named 'pandas'
[2023-12-31T09:38:36.598-0300] {processor.py:842} WARNING - No viable dags retrieved from /home/felipe/airflow/dags/03_with_end_date.py
[2023-12-31T09:38:36.721-0300] {processor.py:183} INFO - Processing /home/felipe/airflow/dags/03_with_end_date.py took 0.173 seconds
[2023-12-31T09:52:05.848-0300] {processor.py:161} INFO - Started process (PID=32775) to work on /home/felipe/airflow/dags/03_with_end_date.py
[2023-12-31T09:52:05.850-0300] {processor.py:830} INFO - Processing file /home/felipe/airflow/dags/03_with_end_date.py for tasks to queue
[2023-12-31T09:52:05.858-0300] {logging_mixin.py:188} INFO - [2023-12-31T09:52:05.857-0300] {dagbag.py:538} INFO - Filling up the DagBag from /home/felipe/airflow/dags/03_with_end_date.py
[2023-12-31T09:52:05.870-0300] {logging_mixin.py:188} INFO - [2023-12-31T09:52:05.868-0300] {dagbag.py:348} ERROR - Failed to import: /home/felipe/airflow/dags/03_with_end_date.py
Traceback (most recent call last):
  File "/home/felipe/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/felipe/airflow/dags/03_with_end_date.py", line 4, in <module>
    import pandas as pd
ModuleNotFoundError: No module named 'pandas'
[2023-12-31T09:52:05.877-0300] {processor.py:842} WARNING - No viable dags retrieved from /home/felipe/airflow/dags/03_with_end_date.py
[2023-12-31T09:52:06.000-0300] {processor.py:183} INFO - Processing /home/felipe/airflow/dags/03_with_end_date.py took 0.164 seconds
[2023-12-31T09:55:24.718-0300] {processor.py:161} INFO - Started process (PID=32937) to work on /home/felipe/airflow/dags/03_with_end_date.py
[2023-12-31T09:55:24.727-0300] {processor.py:830} INFO - Processing file /home/felipe/airflow/dags/03_with_end_date.py for tasks to queue
[2023-12-31T09:55:24.737-0300] {logging_mixin.py:188} INFO - [2023-12-31T09:55:24.730-0300] {dagbag.py:538} INFO - Filling up the DagBag from /home/felipe/airflow/dags/03_with_end_date.py
[2023-12-31T09:55:24.768-0300] {logging_mixin.py:188} INFO - [2023-12-31T09:55:24.759-0300] {dagbag.py:348} ERROR - Failed to import: /home/felipe/airflow/dags/03_with_end_date.py
Traceback (most recent call last):
  File "/home/felipe/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/felipe/airflow/dags/03_with_end_date.py", line 4, in <module>
    import pandas as pd
ModuleNotFoundError: No module named 'pandas'
[2023-12-31T09:55:24.769-0300] {processor.py:842} WARNING - No viable dags retrieved from /home/felipe/airflow/dags/03_with_end_date.py
[2023-12-31T09:55:24.898-0300] {processor.py:183} INFO - Processing /home/felipe/airflow/dags/03_with_end_date.py took 0.200 seconds
[2023-12-31T09:59:59.479-0300] {processor.py:161} INFO - Started process (PID=33148) to work on /home/felipe/airflow/dags/03_with_end_date.py
[2023-12-31T09:59:59.488-0300] {processor.py:830} INFO - Processing file /home/felipe/airflow/dags/03_with_end_date.py for tasks to queue
[2023-12-31T09:59:59.497-0300] {logging_mixin.py:188} INFO - [2023-12-31T09:59:59.496-0300] {dagbag.py:538} INFO - Filling up the DagBag from /home/felipe/airflow/dags/03_with_end_date.py
[2023-12-31T09:59:59.509-0300] {logging_mixin.py:188} INFO - [2023-12-31T09:59:59.507-0300] {dagbag.py:348} ERROR - Failed to import: /home/felipe/airflow/dags/03_with_end_date.py
Traceback (most recent call last):
  File "/home/felipe/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/felipe/airflow/dags/03_with_end_date.py", line 4, in <module>
    import pandas as pd
ModuleNotFoundError: No module named 'pandas'
[2023-12-31T09:59:59.509-0300] {processor.py:842} WARNING - No viable dags retrieved from /home/felipe/airflow/dags/03_with_end_date.py
[2023-12-31T09:59:59.609-0300] {processor.py:183} INFO - Processing /home/felipe/airflow/dags/03_with_end_date.py took 0.141 seconds
[2023-12-31T10:01:26.298-0300] {processor.py:161} INFO - Started process (PID=33278) to work on /home/felipe/airflow/dags/03_with_end_date.py
[2023-12-31T10:01:26.307-0300] {processor.py:830} INFO - Processing file /home/felipe/airflow/dags/03_with_end_date.py for tasks to queue
[2023-12-31T10:01:26.309-0300] {logging_mixin.py:188} INFO - [2023-12-31T10:01:26.308-0300] {dagbag.py:538} INFO - Filling up the DagBag from /home/felipe/airflow/dags/03_with_end_date.py
[2023-12-31T10:01:26.329-0300] {logging_mixin.py:188} INFO - [2023-12-31T10:01:26.327-0300] {dagbag.py:348} ERROR - Failed to import: /home/felipe/airflow/dags/03_with_end_date.py
Traceback (most recent call last):
  File "/home/felipe/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/felipe/airflow/dags/03_with_end_date.py", line 4, in <module>
    import pandas as pd
ModuleNotFoundError: No module named 'pandas'
[2023-12-31T10:01:26.338-0300] {processor.py:842} WARNING - No viable dags retrieved from /home/felipe/airflow/dags/03_with_end_date.py
[2023-12-31T10:01:26.468-0300] {processor.py:183} INFO - Processing /home/felipe/airflow/dags/03_with_end_date.py took 0.209 seconds
[2023-12-31T10:02:34.209-0300] {processor.py:161} INFO - Started process (PID=33343) to work on /home/felipe/airflow/dags/03_with_end_date.py
[2023-12-31T10:02:34.218-0300] {processor.py:830} INFO - Processing file /home/felipe/airflow/dags/03_with_end_date.py for tasks to queue
[2023-12-31T10:02:34.219-0300] {logging_mixin.py:188} INFO - [2023-12-31T10:02:34.219-0300] {dagbag.py:538} INFO - Filling up the DagBag from /home/felipe/airflow/dags/03_with_end_date.py
[2023-12-31T10:02:34.239-0300] {logging_mixin.py:188} INFO - [2023-12-31T10:02:34.237-0300] {dagbag.py:348} ERROR - Failed to import: /home/felipe/airflow/dags/03_with_end_date.py
Traceback (most recent call last):
  File "/home/felipe/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/felipe/airflow/dags/03_with_end_date.py", line 4, in <module>
    import pandas as pd
ModuleNotFoundError: No module named 'pandas'
[2023-12-31T10:02:34.239-0300] {processor.py:842} WARNING - No viable dags retrieved from /home/felipe/airflow/dags/03_with_end_date.py
[2023-12-31T10:02:34.339-0300] {processor.py:183} INFO - Processing /home/felipe/airflow/dags/03_with_end_date.py took 0.140 seconds
[2023-12-31T10:03:40.067-0300] {processor.py:161} INFO - Started process (PID=33415) to work on /home/felipe/airflow/dags/03_with_end_date.py
[2023-12-31T10:03:40.077-0300] {processor.py:830} INFO - Processing file /home/felipe/airflow/dags/03_with_end_date.py for tasks to queue
[2023-12-31T10:03:40.088-0300] {logging_mixin.py:188} INFO - [2023-12-31T10:03:40.079-0300] {dagbag.py:538} INFO - Filling up the DagBag from /home/felipe/airflow/dags/03_with_end_date.py
[2023-12-31T10:03:40.108-0300] {logging_mixin.py:188} INFO - [2023-12-31T10:03:40.100-0300] {dagbag.py:348} ERROR - Failed to import: /home/felipe/airflow/dags/03_with_end_date.py
Traceback (most recent call last):
  File "/home/felipe/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/felipe/airflow/dags/03_with_end_date.py", line 4, in <module>
    import pandas as pd
ModuleNotFoundError: No module named 'pandas'
[2023-12-31T10:03:40.109-0300] {processor.py:842} WARNING - No viable dags retrieved from /home/felipe/airflow/dags/03_with_end_date.py
[2023-12-31T10:03:40.219-0300] {processor.py:183} INFO - Processing /home/felipe/airflow/dags/03_with_end_date.py took 0.182 seconds
[2023-12-31T10:04:51.797-0300] {processor.py:161} INFO - Started process (PID=33501) to work on /home/felipe/airflow/dags/03_with_end_date.py
[2023-12-31T10:04:51.799-0300] {processor.py:830} INFO - Processing file /home/felipe/airflow/dags/03_with_end_date.py for tasks to queue
[2023-12-31T10:04:51.808-0300] {logging_mixin.py:188} INFO - [2023-12-31T10:04:51.807-0300] {dagbag.py:538} INFO - Filling up the DagBag from /home/felipe/airflow/dags/03_with_end_date.py
[2023-12-31T10:04:51.829-0300] {logging_mixin.py:188} INFO - [2023-12-31T10:04:51.828-0300] {dagbag.py:348} ERROR - Failed to import: /home/felipe/airflow/dags/03_with_end_date.py
Traceback (most recent call last):
  File "/home/felipe/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/felipe/airflow/dags/03_with_end_date.py", line 4, in <module>
    import pandas as pd
ModuleNotFoundError: No module named 'pandas'
[2023-12-31T10:04:51.830-0300] {processor.py:842} WARNING - No viable dags retrieved from /home/felipe/airflow/dags/03_with_end_date.py
[2023-12-31T10:04:51.936-0300] {processor.py:183} INFO - Processing /home/felipe/airflow/dags/03_with_end_date.py took 0.150 seconds
[2023-12-31T10:06:02.989-0300] {processor.py:161} INFO - Started process (PID=33581) to work on /home/felipe/airflow/dags/03_with_end_date.py
[2023-12-31T10:06:02.998-0300] {processor.py:830} INFO - Processing file /home/felipe/airflow/dags/03_with_end_date.py for tasks to queue
[2023-12-31T10:06:02.999-0300] {logging_mixin.py:188} INFO - [2023-12-31T10:06:02.999-0300] {dagbag.py:538} INFO - Filling up the DagBag from /home/felipe/airflow/dags/03_with_end_date.py
[2023-12-31T10:06:03.026-0300] {logging_mixin.py:188} INFO - [2023-12-31T10:06:03.017-0300] {dagbag.py:348} ERROR - Failed to import: /home/felipe/airflow/dags/03_with_end_date.py
Traceback (most recent call last):
  File "/home/felipe/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/felipe/airflow/dags/03_with_end_date.py", line 4, in <module>
    import pandas as pd
ModuleNotFoundError: No module named 'pandas'
[2023-12-31T10:06:03.027-0300] {processor.py:842} WARNING - No viable dags retrieved from /home/felipe/airflow/dags/03_with_end_date.py
[2023-12-31T10:06:03.129-0300] {processor.py:183} INFO - Processing /home/felipe/airflow/dags/03_with_end_date.py took 0.151 seconds
[2023-12-31T10:07:13.437-0300] {processor.py:161} INFO - Started process (PID=33693) to work on /home/felipe/airflow/dags/03_with_end_date.py
[2023-12-31T10:07:13.446-0300] {processor.py:830} INFO - Processing file /home/felipe/airflow/dags/03_with_end_date.py for tasks to queue
[2023-12-31T10:07:13.448-0300] {logging_mixin.py:188} INFO - [2023-12-31T10:07:13.448-0300] {dagbag.py:538} INFO - Filling up the DagBag from /home/felipe/airflow/dags/03_with_end_date.py
[2023-12-31T10:07:13.486-0300] {logging_mixin.py:188} INFO - [2023-12-31T10:07:13.477-0300] {dagbag.py:348} ERROR - Failed to import: /home/felipe/airflow/dags/03_with_end_date.py
Traceback (most recent call last):
  File "/home/felipe/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/felipe/airflow/dags/03_with_end_date.py", line 4, in <module>
    import pandas as pd
ModuleNotFoundError: No module named 'pandas'
[2023-12-31T10:07:13.488-0300] {processor.py:842} WARNING - No viable dags retrieved from /home/felipe/airflow/dags/03_with_end_date.py
[2023-12-31T10:07:13.638-0300] {processor.py:183} INFO - Processing /home/felipe/airflow/dags/03_with_end_date.py took 0.218 seconds
[2023-12-31T10:08:26.719-0300] {processor.py:161} INFO - Started process (PID=33776) to work on /home/felipe/airflow/dags/03_with_end_date.py
[2023-12-31T10:08:26.728-0300] {processor.py:830} INFO - Processing file /home/felipe/airflow/dags/03_with_end_date.py for tasks to queue
[2023-12-31T10:08:26.729-0300] {logging_mixin.py:188} INFO - [2023-12-31T10:08:26.729-0300] {dagbag.py:538} INFO - Filling up the DagBag from /home/felipe/airflow/dags/03_with_end_date.py
[2023-12-31T10:08:26.749-0300] {logging_mixin.py:188} INFO - [2023-12-31T10:08:26.746-0300] {dagbag.py:348} ERROR - Failed to import: /home/felipe/airflow/dags/03_with_end_date.py
Traceback (most recent call last):
  File "/home/felipe/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/felipe/airflow/dags/03_with_end_date.py", line 4, in <module>
    import pandas as pd
ModuleNotFoundError: No module named 'pandas'
[2023-12-31T10:08:26.749-0300] {processor.py:842} WARNING - No viable dags retrieved from /home/felipe/airflow/dags/03_with_end_date.py
[2023-12-31T10:08:26.848-0300] {processor.py:183} INFO - Processing /home/felipe/airflow/dags/03_with_end_date.py took 0.140 seconds
[2023-12-31T11:29:01.836-0300] {processor.py:161} INFO - Started process (PID=33969) to work on /home/felipe/airflow/dags/03_with_end_date.py
[2023-12-31T11:29:01.855-0300] {processor.py:830} INFO - Processing file /home/felipe/airflow/dags/03_with_end_date.py for tasks to queue
[2023-12-31T11:29:01.894-0300] {logging_mixin.py:188} INFO - [2023-12-31T11:29:01.876-0300] {dagbag.py:538} INFO - Filling up the DagBag from /home/felipe/airflow/dags/03_with_end_date.py
[2023-12-31T11:29:01.917-0300] {logging_mixin.py:188} INFO - [2023-12-31T11:29:01.915-0300] {dagbag.py:348} ERROR - Failed to import: /home/felipe/airflow/dags/03_with_end_date.py
Traceback (most recent call last):
  File "/home/felipe/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/felipe/airflow/dags/03_with_end_date.py", line 4, in <module>
    import pandas as pd
ModuleNotFoundError: No module named 'pandas'
[2023-12-31T11:29:01.924-0300] {processor.py:842} WARNING - No viable dags retrieved from /home/felipe/airflow/dags/03_with_end_date.py
[2023-12-31T11:29:02.214-0300] {processor.py:183} INFO - Processing /home/felipe/airflow/dags/03_with_end_date.py took 0.420 seconds
[2023-12-31T11:30:52.544-0300] {processor.py:161} INFO - Started process (PID=34239) to work on /home/felipe/airflow/dags/03_with_end_date.py
[2023-12-31T11:30:52.546-0300] {processor.py:830} INFO - Processing file /home/felipe/airflow/dags/03_with_end_date.py for tasks to queue
[2023-12-31T11:30:52.555-0300] {logging_mixin.py:188} INFO - [2023-12-31T11:30:52.554-0300] {dagbag.py:538} INFO - Filling up the DagBag from /home/felipe/airflow/dags/03_with_end_date.py
[2023-12-31T11:30:52.576-0300] {logging_mixin.py:188} INFO - [2023-12-31T11:30:52.567-0300] {dagbag.py:348} ERROR - Failed to import: /home/felipe/airflow/dags/03_with_end_date.py
Traceback (most recent call last):
  File "/home/felipe/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/felipe/airflow/dags/03_with_end_date.py", line 4, in <module>
    import pandas as pd
ModuleNotFoundError: No module named 'pandas'
[2023-12-31T11:30:52.577-0300] {processor.py:842} WARNING - No viable dags retrieved from /home/felipe/airflow/dags/03_with_end_date.py
[2023-12-31T11:30:52.796-0300] {processor.py:183} INFO - Processing /home/felipe/airflow/dags/03_with_end_date.py took 0.271 seconds
[2023-12-31T11:32:23.265-0300] {processor.py:161} INFO - Started process (PID=34344) to work on /home/felipe/airflow/dags/03_with_end_date.py
[2023-12-31T11:32:23.274-0300] {processor.py:830} INFO - Processing file /home/felipe/airflow/dags/03_with_end_date.py for tasks to queue
[2023-12-31T11:32:23.277-0300] {logging_mixin.py:188} INFO - [2023-12-31T11:32:23.276-0300] {dagbag.py:538} INFO - Filling up the DagBag from /home/felipe/airflow/dags/03_with_end_date.py
[2023-12-31T11:32:23.314-0300] {logging_mixin.py:188} INFO - [2023-12-31T11:32:23.305-0300] {dagbag.py:348} ERROR - Failed to import: /home/felipe/airflow/dags/03_with_end_date.py
Traceback (most recent call last):
  File "/home/felipe/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/felipe/airflow/dags/03_with_end_date.py", line 4, in <module>
    import pandas as pd
ModuleNotFoundError: No module named 'pandas'
[2023-12-31T11:32:23.316-0300] {processor.py:842} WARNING - No viable dags retrieved from /home/felipe/airflow/dags/03_with_end_date.py
[2023-12-31T11:32:23.436-0300] {processor.py:183} INFO - Processing /home/felipe/airflow/dags/03_with_end_date.py took 0.189 seconds
[2023-12-31T11:33:54.505-0300] {processor.py:161} INFO - Started process (PID=34446) to work on /home/felipe/airflow/dags/03_with_end_date.py
[2023-12-31T11:33:54.514-0300] {processor.py:830} INFO - Processing file /home/felipe/airflow/dags/03_with_end_date.py for tasks to queue
[2023-12-31T11:33:54.524-0300] {logging_mixin.py:188} INFO - [2023-12-31T11:33:54.516-0300] {dagbag.py:538} INFO - Filling up the DagBag from /home/felipe/airflow/dags/03_with_end_date.py
[2023-12-31T11:33:54.546-0300] {logging_mixin.py:188} INFO - [2023-12-31T11:33:54.536-0300] {dagbag.py:348} ERROR - Failed to import: /home/felipe/airflow/dags/03_with_end_date.py
Traceback (most recent call last):
  File "/home/felipe/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/felipe/airflow/dags/03_with_end_date.py", line 4, in <module>
    import pandas as pd
ModuleNotFoundError: No module named 'pandas'
[2023-12-31T11:33:54.547-0300] {processor.py:842} WARNING - No viable dags retrieved from /home/felipe/airflow/dags/03_with_end_date.py
[2023-12-31T11:33:54.667-0300] {processor.py:183} INFO - Processing /home/felipe/airflow/dags/03_with_end_date.py took 0.181 seconds
[2023-12-31T11:35:16.236-0300] {processor.py:161} INFO - Started process (PID=34564) to work on /home/felipe/airflow/dags/03_with_end_date.py
[2023-12-31T11:35:16.245-0300] {processor.py:830} INFO - Processing file /home/felipe/airflow/dags/03_with_end_date.py for tasks to queue
[2023-12-31T11:35:16.254-0300] {logging_mixin.py:188} INFO - [2023-12-31T11:35:16.246-0300] {dagbag.py:538} INFO - Filling up the DagBag from /home/felipe/airflow/dags/03_with_end_date.py
[2023-12-31T11:35:16.274-0300] {logging_mixin.py:188} INFO - [2023-12-31T11:35:16.266-0300] {dagbag.py:348} ERROR - Failed to import: /home/felipe/airflow/dags/03_with_end_date.py
Traceback (most recent call last):
  File "/home/felipe/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/felipe/airflow/dags/03_with_end_date.py", line 4, in <module>
    import pandas as pd
ModuleNotFoundError: No module named 'pandas'
[2023-12-31T11:35:16.275-0300] {processor.py:842} WARNING - No viable dags retrieved from /home/felipe/airflow/dags/03_with_end_date.py
[2023-12-31T11:35:16.395-0300] {processor.py:183} INFO - Processing /home/felipe/airflow/dags/03_with_end_date.py took 0.179 seconds
[2023-12-31T11:36:39.615-0300] {processor.py:161} INFO - Started process (PID=34653) to work on /home/felipe/airflow/dags/03_with_end_date.py
[2023-12-31T11:36:39.635-0300] {processor.py:830} INFO - Processing file /home/felipe/airflow/dags/03_with_end_date.py for tasks to queue
[2023-12-31T11:36:39.665-0300] {logging_mixin.py:188} INFO - [2023-12-31T11:36:39.636-0300] {dagbag.py:538} INFO - Filling up the DagBag from /home/felipe/airflow/dags/03_with_end_date.py
[2023-12-31T11:36:39.725-0300] {logging_mixin.py:188} INFO - [2023-12-31T11:36:39.714-0300] {dagbag.py:348} ERROR - Failed to import: /home/felipe/airflow/dags/03_with_end_date.py
Traceback (most recent call last):
  File "/home/felipe/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/felipe/airflow/dags/03_with_end_date.py", line 4, in <module>
    import pandas as pd
ModuleNotFoundError: No module named 'pandas'
[2023-12-31T11:36:39.726-0300] {processor.py:842} WARNING - No viable dags retrieved from /home/felipe/airflow/dags/03_with_end_date.py
[2023-12-31T11:36:39.845-0300] {processor.py:183} INFO - Processing /home/felipe/airflow/dags/03_with_end_date.py took 0.289 seconds
[2023-12-31T11:38:03.455-0300] {processor.py:161} INFO - Started process (PID=34748) to work on /home/felipe/airflow/dags/03_with_end_date.py
[2023-12-31T11:38:03.464-0300] {processor.py:830} INFO - Processing file /home/felipe/airflow/dags/03_with_end_date.py for tasks to queue
[2023-12-31T11:38:03.466-0300] {logging_mixin.py:188} INFO - [2023-12-31T11:38:03.465-0300] {dagbag.py:538} INFO - Filling up the DagBag from /home/felipe/airflow/dags/03_with_end_date.py
[2023-12-31T11:38:03.494-0300] {logging_mixin.py:188} INFO - [2023-12-31T11:38:03.485-0300] {dagbag.py:348} ERROR - Failed to import: /home/felipe/airflow/dags/03_with_end_date.py
Traceback (most recent call last):
  File "/home/felipe/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/felipe/airflow/dags/03_with_end_date.py", line 4, in <module>
    import pandas as pd
ModuleNotFoundError: No module named 'pandas'
[2023-12-31T11:38:03.495-0300] {processor.py:842} WARNING - No viable dags retrieved from /home/felipe/airflow/dags/03_with_end_date.py
[2023-12-31T11:38:03.645-0300] {processor.py:183} INFO - Processing /home/felipe/airflow/dags/03_with_end_date.py took 0.209 seconds
[2023-12-31T11:39:25.346-0300] {processor.py:161} INFO - Started process (PID=34835) to work on /home/felipe/airflow/dags/03_with_end_date.py
[2023-12-31T11:39:25.364-0300] {processor.py:830} INFO - Processing file /home/felipe/airflow/dags/03_with_end_date.py for tasks to queue
[2023-12-31T11:39:25.366-0300] {logging_mixin.py:188} INFO - [2023-12-31T11:39:25.365-0300] {dagbag.py:538} INFO - Filling up the DagBag from /home/felipe/airflow/dags/03_with_end_date.py
[2023-12-31T11:39:25.394-0300] {logging_mixin.py:188} INFO - [2023-12-31T11:39:25.386-0300] {dagbag.py:348} ERROR - Failed to import: /home/felipe/airflow/dags/03_with_end_date.py
Traceback (most recent call last):
  File "/home/felipe/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/felipe/airflow/dags/03_with_end_date.py", line 4, in <module>
    import pandas as pd
ModuleNotFoundError: No module named 'pandas'
[2023-12-31T11:39:25.395-0300] {processor.py:842} WARNING - No viable dags retrieved from /home/felipe/airflow/dags/03_with_end_date.py
[2023-12-31T11:39:25.535-0300] {processor.py:183} INFO - Processing /home/felipe/airflow/dags/03_with_end_date.py took 0.200 seconds
[2023-12-31T11:40:48.606-0300] {processor.py:161} INFO - Started process (PID=34951) to work on /home/felipe/airflow/dags/03_with_end_date.py
[2023-12-31T11:40:48.616-0300] {processor.py:830} INFO - Processing file /home/felipe/airflow/dags/03_with_end_date.py for tasks to queue
[2023-12-31T11:40:48.625-0300] {logging_mixin.py:188} INFO - [2023-12-31T11:40:48.624-0300] {dagbag.py:538} INFO - Filling up the DagBag from /home/felipe/airflow/dags/03_with_end_date.py
[2023-12-31T11:40:48.646-0300] {logging_mixin.py:188} INFO - [2023-12-31T11:40:48.645-0300] {dagbag.py:348} ERROR - Failed to import: /home/felipe/airflow/dags/03_with_end_date.py
Traceback (most recent call last):
  File "/home/felipe/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/felipe/airflow/dags/03_with_end_date.py", line 4, in <module>
    import pandas as pd
ModuleNotFoundError: No module named 'pandas'
[2023-12-31T11:40:48.654-0300] {processor.py:842} WARNING - No viable dags retrieved from /home/felipe/airflow/dags/03_with_end_date.py
[2023-12-31T11:40:48.794-0300] {processor.py:183} INFO - Processing /home/felipe/airflow/dags/03_with_end_date.py took 0.200 seconds
[2023-12-31T11:42:22.805-0300] {processor.py:161} INFO - Started process (PID=35057) to work on /home/felipe/airflow/dags/03_with_end_date.py
[2023-12-31T11:42:22.814-0300] {processor.py:830} INFO - Processing file /home/felipe/airflow/dags/03_with_end_date.py for tasks to queue
[2023-12-31T11:42:22.816-0300] {logging_mixin.py:188} INFO - [2023-12-31T11:42:22.815-0300] {dagbag.py:538} INFO - Filling up the DagBag from /home/felipe/airflow/dags/03_with_end_date.py
[2023-12-31T11:42:22.855-0300] {logging_mixin.py:188} INFO - [2023-12-31T11:42:22.844-0300] {dagbag.py:348} ERROR - Failed to import: /home/felipe/airflow/dags/03_with_end_date.py
Traceback (most recent call last):
  File "/home/felipe/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/felipe/airflow/dags/03_with_end_date.py", line 4, in <module>
    import pandas as pd
ModuleNotFoundError: No module named 'pandas'
[2023-12-31T11:42:22.856-0300] {processor.py:842} WARNING - No viable dags retrieved from /home/felipe/airflow/dags/03_with_end_date.py
[2023-12-31T11:42:23.016-0300] {processor.py:183} INFO - Processing /home/felipe/airflow/dags/03_with_end_date.py took 0.231 seconds
[2023-12-31T11:43:58.625-0300] {processor.py:161} INFO - Started process (PID=35170) to work on /home/felipe/airflow/dags/03_with_end_date.py
[2023-12-31T11:43:58.635-0300] {processor.py:830} INFO - Processing file /home/felipe/airflow/dags/03_with_end_date.py for tasks to queue
[2023-12-31T11:43:58.655-0300] {logging_mixin.py:188} INFO - [2023-12-31T11:43:58.645-0300] {dagbag.py:538} INFO - Filling up the DagBag from /home/felipe/airflow/dags/03_with_end_date.py
[2023-12-31T11:43:58.685-0300] {logging_mixin.py:188} INFO - [2023-12-31T11:43:58.675-0300] {dagbag.py:348} ERROR - Failed to import: /home/felipe/airflow/dags/03_with_end_date.py
Traceback (most recent call last):
  File "/home/felipe/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/felipe/airflow/dags/03_with_end_date.py", line 4, in <module>
    import pandas as pd
ModuleNotFoundError: No module named 'pandas'
[2023-12-31T11:43:58.694-0300] {processor.py:842} WARNING - No viable dags retrieved from /home/felipe/airflow/dags/03_with_end_date.py
[2023-12-31T11:43:58.864-0300] {processor.py:183} INFO - Processing /home/felipe/airflow/dags/03_with_end_date.py took 0.259 seconds
[2023-12-31T11:45:40.066-0300] {processor.py:161} INFO - Started process (PID=35306) to work on /home/felipe/airflow/dags/03_with_end_date.py
[2023-12-31T11:45:40.075-0300] {processor.py:830} INFO - Processing file /home/felipe/airflow/dags/03_with_end_date.py for tasks to queue
[2023-12-31T11:45:40.084-0300] {logging_mixin.py:188} INFO - [2023-12-31T11:45:40.076-0300] {dagbag.py:538} INFO - Filling up the DagBag from /home/felipe/airflow/dags/03_with_end_date.py
[2023-12-31T11:45:40.115-0300] {logging_mixin.py:188} INFO - [2023-12-31T11:45:40.104-0300] {dagbag.py:348} ERROR - Failed to import: /home/felipe/airflow/dags/03_with_end_date.py
Traceback (most recent call last):
  File "/home/felipe/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/felipe/airflow/dags/03_with_end_date.py", line 4, in <module>
    import pandas as pd
ModuleNotFoundError: No module named 'pandas'
[2023-12-31T11:45:40.115-0300] {processor.py:842} WARNING - No viable dags retrieved from /home/felipe/airflow/dags/03_with_end_date.py
[2023-12-31T11:45:40.375-0300] {processor.py:183} INFO - Processing /home/felipe/airflow/dags/03_with_end_date.py took 0.330 seconds
[2023-12-31T11:47:16.356-0300] {processor.py:161} INFO - Started process (PID=35433) to work on /home/felipe/airflow/dags/03_with_end_date.py
[2023-12-31T11:47:16.365-0300] {processor.py:830} INFO - Processing file /home/felipe/airflow/dags/03_with_end_date.py for tasks to queue
[2023-12-31T11:47:16.375-0300] {logging_mixin.py:188} INFO - [2023-12-31T11:47:16.374-0300] {dagbag.py:538} INFO - Filling up the DagBag from /home/felipe/airflow/dags/03_with_end_date.py
[2023-12-31T11:47:16.405-0300] {logging_mixin.py:188} INFO - [2023-12-31T11:47:16.396-0300] {dagbag.py:348} ERROR - Failed to import: /home/felipe/airflow/dags/03_with_end_date.py
Traceback (most recent call last):
  File "/home/felipe/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/felipe/airflow/dags/03_with_end_date.py", line 4, in <module>
    import pandas as pd
ModuleNotFoundError: No module named 'pandas'
[2023-12-31T11:47:16.406-0300] {processor.py:842} WARNING - No viable dags retrieved from /home/felipe/airflow/dags/03_with_end_date.py
[2023-12-31T11:47:16.575-0300] {processor.py:183} INFO - Processing /home/felipe/airflow/dags/03_with_end_date.py took 0.239 seconds
[2023-12-31T11:49:30.604-0300] {processor.py:161} INFO - Started process (PID=35595) to work on /home/felipe/airflow/dags/03_with_end_date.py
[2023-12-31T11:49:30.615-0300] {processor.py:830} INFO - Processing file /home/felipe/airflow/dags/03_with_end_date.py for tasks to queue
[2023-12-31T11:49:30.626-0300] {logging_mixin.py:188} INFO - [2023-12-31T11:49:30.625-0300] {dagbag.py:538} INFO - Filling up the DagBag from /home/felipe/airflow/dags/03_with_end_date.py
[2023-12-31T11:49:30.666-0300] {logging_mixin.py:188} INFO - [2023-12-31T11:49:30.664-0300] {dagbag.py:348} ERROR - Failed to import: /home/felipe/airflow/dags/03_with_end_date.py
Traceback (most recent call last):
  File "/home/felipe/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/felipe/airflow/dags/03_with_end_date.py", line 4, in <module>
    import pandas as pd
ModuleNotFoundError: No module named 'pandas'
[2023-12-31T11:49:30.674-0300] {processor.py:842} WARNING - No viable dags retrieved from /home/felipe/airflow/dags/03_with_end_date.py
[2023-12-31T11:49:30.855-0300] {processor.py:183} INFO - Processing /home/felipe/airflow/dags/03_with_end_date.py took 0.270 seconds
[2023-12-31T11:51:40.586-0300] {processor.py:161} INFO - Started process (PID=35743) to work on /home/felipe/airflow/dags/03_with_end_date.py
[2023-12-31T11:51:40.604-0300] {processor.py:830} INFO - Processing file /home/felipe/airflow/dags/03_with_end_date.py for tasks to queue
[2023-12-31T11:51:40.606-0300] {logging_mixin.py:188} INFO - [2023-12-31T11:51:40.605-0300] {dagbag.py:538} INFO - Filling up the DagBag from /home/felipe/airflow/dags/03_with_end_date.py
[2023-12-31T11:51:40.645-0300] {logging_mixin.py:188} INFO - [2023-12-31T11:51:40.634-0300] {dagbag.py:348} ERROR - Failed to import: /home/felipe/airflow/dags/03_with_end_date.py
Traceback (most recent call last):
  File "/home/felipe/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/felipe/airflow/dags/03_with_end_date.py", line 4, in <module>
    import pandas as pd
ModuleNotFoundError: No module named 'pandas'
[2023-12-31T11:51:40.655-0300] {processor.py:842} WARNING - No viable dags retrieved from /home/felipe/airflow/dags/03_with_end_date.py
[2023-12-31T11:51:40.875-0300] {processor.py:183} INFO - Processing /home/felipe/airflow/dags/03_with_end_date.py took 0.330 seconds
[2023-12-31T11:54:24.746-0300] {processor.py:161} INFO - Started process (PID=35873) to work on /home/felipe/airflow/dags/03_with_end_date.py
[2023-12-31T11:54:24.756-0300] {processor.py:830} INFO - Processing file /home/felipe/airflow/dags/03_with_end_date.py for tasks to queue
[2023-12-31T11:54:24.765-0300] {logging_mixin.py:188} INFO - [2023-12-31T11:54:24.764-0300] {dagbag.py:538} INFO - Filling up the DagBag from /home/felipe/airflow/dags/03_with_end_date.py
[2023-12-31T11:54:24.795-0300] {logging_mixin.py:188} INFO - [2023-12-31T11:54:24.785-0300] {dagbag.py:348} ERROR - Failed to import: /home/felipe/airflow/dags/03_with_end_date.py
Traceback (most recent call last):
  File "/home/felipe/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/felipe/airflow/dags/03_with_end_date.py", line 4, in <module>
    import pandas as pd
ModuleNotFoundError: No module named 'pandas'
[2023-12-31T11:54:24.804-0300] {processor.py:842} WARNING - No viable dags retrieved from /home/felipe/airflow/dags/03_with_end_date.py
[2023-12-31T11:54:25.065-0300] {processor.py:183} INFO - Processing /home/felipe/airflow/dags/03_with_end_date.py took 0.331 seconds
[2023-12-31T11:56:15.714-0300] {processor.py:161} INFO - Started process (PID=36008) to work on /home/felipe/airflow/dags/03_with_end_date.py
[2023-12-31T11:56:15.724-0300] {processor.py:830} INFO - Processing file /home/felipe/airflow/dags/03_with_end_date.py for tasks to queue
[2023-12-31T11:56:15.726-0300] {logging_mixin.py:188} INFO - [2023-12-31T11:56:15.725-0300] {dagbag.py:538} INFO - Filling up the DagBag from /home/felipe/airflow/dags/03_with_end_date.py
[2023-12-31T11:56:15.754-0300] {logging_mixin.py:188} INFO - [2023-12-31T11:56:15.745-0300] {dagbag.py:348} ERROR - Failed to import: /home/felipe/airflow/dags/03_with_end_date.py
Traceback (most recent call last):
  File "/home/felipe/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/felipe/airflow/dags/03_with_end_date.py", line 4, in <module>
    import pandas as pd
ModuleNotFoundError: No module named 'pandas'
[2023-12-31T11:56:15.755-0300] {processor.py:842} WARNING - No viable dags retrieved from /home/felipe/airflow/dags/03_with_end_date.py
[2023-12-31T11:56:15.925-0300] {processor.py:183} INFO - Processing /home/felipe/airflow/dags/03_with_end_date.py took 0.240 seconds
[2023-12-31T11:58:01.394-0300] {processor.py:161} INFO - Started process (PID=36113) to work on /home/felipe/airflow/dags/03_with_end_date.py
[2023-12-31T11:58:01.404-0300] {processor.py:830} INFO - Processing file /home/felipe/airflow/dags/03_with_end_date.py for tasks to queue
[2023-12-31T11:58:01.414-0300] {logging_mixin.py:188} INFO - [2023-12-31T11:58:01.414-0300] {dagbag.py:538} INFO - Filling up the DagBag from /home/felipe/airflow/dags/03_with_end_date.py
[2023-12-31T11:58:01.454-0300] {logging_mixin.py:188} INFO - [2023-12-31T11:58:01.444-0300] {dagbag.py:348} ERROR - Failed to import: /home/felipe/airflow/dags/03_with_end_date.py
Traceback (most recent call last):
  File "/home/felipe/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/felipe/airflow/dags/03_with_end_date.py", line 4, in <module>
    import pandas as pd
ModuleNotFoundError: No module named 'pandas'
[2023-12-31T11:58:01.455-0300] {processor.py:842} WARNING - No viable dags retrieved from /home/felipe/airflow/dags/03_with_end_date.py
[2023-12-31T11:58:01.665-0300] {processor.py:183} INFO - Processing /home/felipe/airflow/dags/03_with_end_date.py took 0.300 seconds
[2023-12-31T11:59:47.844-0300] {processor.py:161} INFO - Started process (PID=36218) to work on /home/felipe/airflow/dags/03_with_end_date.py
[2023-12-31T11:59:47.854-0300] {processor.py:830} INFO - Processing file /home/felipe/airflow/dags/03_with_end_date.py for tasks to queue
[2023-12-31T11:59:47.864-0300] {logging_mixin.py:188} INFO - [2023-12-31T11:59:47.855-0300] {dagbag.py:538} INFO - Filling up the DagBag from /home/felipe/airflow/dags/03_with_end_date.py
[2023-12-31T11:59:47.885-0300] {logging_mixin.py:188} INFO - [2023-12-31T11:59:47.884-0300] {dagbag.py:348} ERROR - Failed to import: /home/felipe/airflow/dags/03_with_end_date.py
Traceback (most recent call last):
  File "/home/felipe/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/felipe/airflow/dags/03_with_end_date.py", line 4, in <module>
    import pandas as pd
ModuleNotFoundError: No module named 'pandas'
[2023-12-31T11:59:47.894-0300] {processor.py:842} WARNING - No viable dags retrieved from /home/felipe/airflow/dags/03_with_end_date.py
[2023-12-31T11:59:48.085-0300] {processor.py:183} INFO - Processing /home/felipe/airflow/dags/03_with_end_date.py took 0.269 seconds
[2023-12-31T12:01:37.864-0300] {processor.py:161} INFO - Started process (PID=36350) to work on /home/felipe/airflow/dags/03_with_end_date.py
[2023-12-31T12:01:37.874-0300] {processor.py:830} INFO - Processing file /home/felipe/airflow/dags/03_with_end_date.py for tasks to queue
[2023-12-31T12:01:37.885-0300] {logging_mixin.py:188} INFO - [2023-12-31T12:01:37.884-0300] {dagbag.py:538} INFO - Filling up the DagBag from /home/felipe/airflow/dags/03_with_end_date.py
[2023-12-31T12:01:37.924-0300] {logging_mixin.py:188} INFO - [2023-12-31T12:01:37.914-0300] {dagbag.py:348} ERROR - Failed to import: /home/felipe/airflow/dags/03_with_end_date.py
Traceback (most recent call last):
  File "/home/felipe/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/felipe/airflow/dags/03_with_end_date.py", line 4, in <module>
    import pandas as pd
ModuleNotFoundError: No module named 'pandas'
[2023-12-31T12:01:37.925-0300] {processor.py:842} WARNING - No viable dags retrieved from /home/felipe/airflow/dags/03_with_end_date.py
[2023-12-31T12:01:38.135-0300] {processor.py:183} INFO - Processing /home/felipe/airflow/dags/03_with_end_date.py took 0.300 seconds
[2023-12-31T12:03:37.744-0300] {processor.py:161} INFO - Started process (PID=36463) to work on /home/felipe/airflow/dags/03_with_end_date.py
[2023-12-31T12:03:37.764-0300] {processor.py:830} INFO - Processing file /home/felipe/airflow/dags/03_with_end_date.py for tasks to queue
[2023-12-31T12:03:37.775-0300] {logging_mixin.py:188} INFO - [2023-12-31T12:03:37.774-0300] {dagbag.py:538} INFO - Filling up the DagBag from /home/felipe/airflow/dags/03_with_end_date.py
[2023-12-31T12:03:37.815-0300] {logging_mixin.py:188} INFO - [2023-12-31T12:03:37.805-0300] {dagbag.py:348} ERROR - Failed to import: /home/felipe/airflow/dags/03_with_end_date.py
Traceback (most recent call last):
  File "/home/felipe/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/felipe/airflow/dags/03_with_end_date.py", line 4, in <module>
    import pandas as pd
ModuleNotFoundError: No module named 'pandas'
[2023-12-31T12:03:37.825-0300] {processor.py:842} WARNING - No viable dags retrieved from /home/felipe/airflow/dags/03_with_end_date.py
[2023-12-31T12:03:38.134-0300] {processor.py:183} INFO - Processing /home/felipe/airflow/dags/03_with_end_date.py took 0.430 seconds
[2023-12-31T12:07:03.145-0300] {processor.py:161} INFO - Started process (PID=36721) to work on /home/felipe/airflow/dags/03_with_end_date.py
[2023-12-31T12:07:03.174-0300] {processor.py:830} INFO - Processing file /home/felipe/airflow/dags/03_with_end_date.py for tasks to queue
[2023-12-31T12:07:03.204-0300] {logging_mixin.py:188} INFO - [2023-12-31T12:07:03.195-0300] {dagbag.py:538} INFO - Filling up the DagBag from /home/felipe/airflow/dags/03_with_end_date.py
[2023-12-31T12:07:03.304-0300] {logging_mixin.py:188} INFO - [2023-12-31T12:07:03.275-0300] {dagbag.py:348} ERROR - Failed to import: /home/felipe/airflow/dags/03_with_end_date.py
Traceback (most recent call last):
  File "/home/felipe/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/felipe/airflow/dags/03_with_end_date.py", line 4, in <module>
    import pandas as pd
ModuleNotFoundError: No module named 'pandas'
[2023-12-31T12:07:03.314-0300] {processor.py:842} WARNING - No viable dags retrieved from /home/felipe/airflow/dags/03_with_end_date.py
[2023-12-31T12:07:03.774-0300] {processor.py:183} INFO - Processing /home/felipe/airflow/dags/03_with_end_date.py took 0.719 seconds
[2023-12-31T12:10:36.464-0300] {processor.py:161} INFO - Started process (PID=37115) to work on /home/felipe/airflow/dags/03_with_end_date.py
[2023-12-31T12:10:36.475-0300] {processor.py:830} INFO - Processing file /home/felipe/airflow/dags/03_with_end_date.py for tasks to queue
[2023-12-31T12:10:36.495-0300] {logging_mixin.py:188} INFO - [2023-12-31T12:10:36.494-0300] {dagbag.py:538} INFO - Filling up the DagBag from /home/felipe/airflow/dags/03_with_end_date.py
[2023-12-31T12:10:36.565-0300] {logging_mixin.py:188} INFO - [2023-12-31T12:10:36.545-0300] {dagbag.py:348} ERROR - Failed to import: /home/felipe/airflow/dags/03_with_end_date.py
Traceback (most recent call last):
  File "/home/felipe/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/felipe/airflow/dags/03_with_end_date.py", line 4, in <module>
    import pandas as pd
ModuleNotFoundError: No module named 'pandas'
[2023-12-31T12:10:36.575-0300] {processor.py:842} WARNING - No viable dags retrieved from /home/felipe/airflow/dags/03_with_end_date.py
[2023-12-31T12:10:38.475-0300] {processor.py:183} INFO - Processing /home/felipe/airflow/dags/03_with_end_date.py took 2.060 seconds
[2023-12-31T12:11:50.625-0300] {processor.py:161} INFO - Started process (PID=37209) to work on /home/felipe/airflow/dags/03_with_end_date.py
[2023-12-31T12:11:50.644-0300] {processor.py:830} INFO - Processing file /home/felipe/airflow/dags/03_with_end_date.py for tasks to queue
[2023-12-31T12:11:50.655-0300] {logging_mixin.py:188} INFO - [2023-12-31T12:11:50.654-0300] {dagbag.py:538} INFO - Filling up the DagBag from /home/felipe/airflow/dags/03_with_end_date.py
[2023-12-31T12:11:50.705-0300] {logging_mixin.py:188} INFO - [2023-12-31T12:11:50.694-0300] {dagbag.py:348} ERROR - Failed to import: /home/felipe/airflow/dags/03_with_end_date.py
Traceback (most recent call last):
  File "/home/felipe/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/felipe/airflow/dags/03_with_end_date.py", line 4, in <module>
    import pandas as pd
ModuleNotFoundError: No module named 'pandas'
[2023-12-31T12:11:50.714-0300] {processor.py:842} WARNING - No viable dags retrieved from /home/felipe/airflow/dags/03_with_end_date.py
[2023-12-31T12:11:51.104-0300] {processor.py:183} INFO - Processing /home/felipe/airflow/dags/03_with_end_date.py took 0.519 seconds
[2023-12-31T12:12:49.545-0300] {processor.py:161} INFO - Started process (PID=37290) to work on /home/felipe/airflow/dags/03_with_end_date.py
[2023-12-31T12:12:49.564-0300] {processor.py:830} INFO - Processing file /home/felipe/airflow/dags/03_with_end_date.py for tasks to queue
[2023-12-31T12:12:49.584-0300] {logging_mixin.py:188} INFO - [2023-12-31T12:12:49.575-0300] {dagbag.py:538} INFO - Filling up the DagBag from /home/felipe/airflow/dags/03_with_end_date.py
[2023-12-31T12:12:49.664-0300] {logging_mixin.py:188} INFO - [2023-12-31T12:12:49.635-0300] {dagbag.py:348} ERROR - Failed to import: /home/felipe/airflow/dags/03_with_end_date.py
Traceback (most recent call last):
  File "/home/felipe/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/felipe/airflow/dags/03_with_end_date.py", line 4, in <module>
    import pandas as pd
ModuleNotFoundError: No module named 'pandas'
[2023-12-31T12:12:49.674-0300] {processor.py:842} WARNING - No viable dags retrieved from /home/felipe/airflow/dags/03_with_end_date.py
[2023-12-31T12:12:50.144-0300] {processor.py:183} INFO - Processing /home/felipe/airflow/dags/03_with_end_date.py took 0.620 seconds
[2023-12-31T12:13:55.954-0300] {processor.py:161} INFO - Started process (PID=37377) to work on /home/felipe/airflow/dags/03_with_end_date.py
[2023-12-31T12:13:55.974-0300] {processor.py:830} INFO - Processing file /home/felipe/airflow/dags/03_with_end_date.py for tasks to queue
[2023-12-31T12:13:55.994-0300] {logging_mixin.py:188} INFO - [2023-12-31T12:13:55.984-0300] {dagbag.py:538} INFO - Filling up the DagBag from /home/felipe/airflow/dags/03_with_end_date.py
[2023-12-31T12:13:56.034-0300] {logging_mixin.py:188} INFO - [2023-12-31T12:13:56.024-0300] {dagbag.py:348} ERROR - Failed to import: /home/felipe/airflow/dags/03_with_end_date.py
Traceback (most recent call last):
  File "/home/felipe/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/felipe/airflow/dags/03_with_end_date.py", line 4, in <module>
    import pandas as pd
ModuleNotFoundError: No module named 'pandas'
[2023-12-31T12:13:56.035-0300] {processor.py:842} WARNING - No viable dags retrieved from /home/felipe/airflow/dags/03_with_end_date.py
[2023-12-31T12:13:56.354-0300] {processor.py:183} INFO - Processing /home/felipe/airflow/dags/03_with_end_date.py took 0.440 seconds
[2023-12-31T12:14:51.634-0300] {processor.py:161} INFO - Started process (PID=37476) to work on /home/felipe/airflow/dags/03_with_end_date.py
[2023-12-31T12:14:51.654-0300] {processor.py:830} INFO - Processing file /home/felipe/airflow/dags/03_with_end_date.py for tasks to queue
[2023-12-31T12:14:51.665-0300] {logging_mixin.py:188} INFO - [2023-12-31T12:14:51.664-0300] {dagbag.py:538} INFO - Filling up the DagBag from /home/felipe/airflow/dags/03_with_end_date.py
[2023-12-31T12:14:51.714-0300] {logging_mixin.py:188} INFO - [2023-12-31T12:14:51.695-0300] {dagbag.py:348} ERROR - Failed to import: /home/felipe/airflow/dags/03_with_end_date.py
Traceback (most recent call last):
  File "/home/felipe/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/felipe/airflow/dags/03_with_end_date.py", line 4, in <module>
    import pandas as pd
ModuleNotFoundError: No module named 'pandas'
[2023-12-31T12:14:51.715-0300] {processor.py:842} WARNING - No viable dags retrieved from /home/felipe/airflow/dags/03_with_end_date.py
[2023-12-31T12:14:52.025-0300] {processor.py:183} INFO - Processing /home/felipe/airflow/dags/03_with_end_date.py took 0.451 seconds
[2023-12-31T12:16:02.484-0300] {processor.py:161} INFO - Started process (PID=37568) to work on /home/felipe/airflow/dags/03_with_end_date.py
[2023-12-31T12:16:02.504-0300] {processor.py:830} INFO - Processing file /home/felipe/airflow/dags/03_with_end_date.py for tasks to queue
[2023-12-31T12:16:02.525-0300] {logging_mixin.py:188} INFO - [2023-12-31T12:16:02.515-0300] {dagbag.py:538} INFO - Filling up the DagBag from /home/felipe/airflow/dags/03_with_end_date.py
[2023-12-31T12:16:02.584-0300] {logging_mixin.py:188} INFO - [2023-12-31T12:16:02.564-0300] {dagbag.py:348} ERROR - Failed to import: /home/felipe/airflow/dags/03_with_end_date.py
Traceback (most recent call last):
  File "/home/felipe/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/felipe/airflow/dags/03_with_end_date.py", line 4, in <module>
    import pandas as pd
ModuleNotFoundError: No module named 'pandas'
[2023-12-31T12:16:02.594-0300] {processor.py:842} WARNING - No viable dags retrieved from /home/felipe/airflow/dags/03_with_end_date.py
[2023-12-31T12:16:02.914-0300] {processor.py:183} INFO - Processing /home/felipe/airflow/dags/03_with_end_date.py took 0.470 seconds
[2023-12-31T12:17:13.714-0300] {processor.py:161} INFO - Started process (PID=37659) to work on /home/felipe/airflow/dags/03_with_end_date.py
[2023-12-31T12:17:13.724-0300] {processor.py:830} INFO - Processing file /home/felipe/airflow/dags/03_with_end_date.py for tasks to queue
[2023-12-31T12:17:13.734-0300] {logging_mixin.py:188} INFO - [2023-12-31T12:17:13.734-0300] {dagbag.py:538} INFO - Filling up the DagBag from /home/felipe/airflow/dags/03_with_end_date.py
[2023-12-31T12:17:13.784-0300] {logging_mixin.py:188} INFO - [2023-12-31T12:17:13.765-0300] {dagbag.py:348} ERROR - Failed to import: /home/felipe/airflow/dags/03_with_end_date.py
Traceback (most recent call last):
  File "/home/felipe/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/felipe/airflow/dags/03_with_end_date.py", line 4, in <module>
    import pandas as pd
ModuleNotFoundError: No module named 'pandas'
[2023-12-31T12:17:13.785-0300] {processor.py:842} WARNING - No viable dags retrieved from /home/felipe/airflow/dags/03_with_end_date.py
[2023-12-31T12:17:14.124-0300] {processor.py:183} INFO - Processing /home/felipe/airflow/dags/03_with_end_date.py took 0.479 seconds
[2023-12-31T12:18:10.314-0300] {processor.py:161} INFO - Started process (PID=37735) to work on /home/felipe/airflow/dags/03_with_end_date.py
[2023-12-31T12:18:10.344-0300] {processor.py:830} INFO - Processing file /home/felipe/airflow/dags/03_with_end_date.py for tasks to queue
[2023-12-31T12:18:10.355-0300] {logging_mixin.py:188} INFO - [2023-12-31T12:18:10.354-0300] {dagbag.py:538} INFO - Filling up the DagBag from /home/felipe/airflow/dags/03_with_end_date.py
[2023-12-31T12:18:10.404-0300] {logging_mixin.py:188} INFO - [2023-12-31T12:18:10.394-0300] {dagbag.py:348} ERROR - Failed to import: /home/felipe/airflow/dags/03_with_end_date.py
Traceback (most recent call last):
  File "/home/felipe/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/felipe/airflow/dags/03_with_end_date.py", line 4, in <module>
    import pandas as pd
ModuleNotFoundError: No module named 'pandas'
[2023-12-31T12:18:10.405-0300] {processor.py:842} WARNING - No viable dags retrieved from /home/felipe/airflow/dags/03_with_end_date.py
[2023-12-31T12:18:10.804-0300] {processor.py:183} INFO - Processing /home/felipe/airflow/dags/03_with_end_date.py took 0.540 seconds
[2023-12-31T12:26:23.991-0300] {processor.py:161} INFO - Started process (PID=37986) to work on /home/felipe/airflow/dags/03_with_end_date.py
[2023-12-31T12:26:24.020-0300] {processor.py:830} INFO - Processing file /home/felipe/airflow/dags/03_with_end_date.py for tasks to queue
[2023-12-31T12:26:24.041-0300] {logging_mixin.py:188} INFO - [2023-12-31T12:26:24.031-0300] {dagbag.py:538} INFO - Filling up the DagBag from /home/felipe/airflow/dags/03_with_end_date.py
[2023-12-31T12:26:24.151-0300] {logging_mixin.py:188} INFO - [2023-12-31T12:26:24.121-0300] {dagbag.py:348} ERROR - Failed to import: /home/felipe/airflow/dags/03_with_end_date.py
Traceback (most recent call last):
  File "/home/felipe/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/felipe/airflow/dags/03_with_end_date.py", line 4, in <module>
    import pandas as pd
ModuleNotFoundError: No module named 'pandas'
[2023-12-31T12:26:24.170-0300] {processor.py:842} WARNING - No viable dags retrieved from /home/felipe/airflow/dags/03_with_end_date.py
[2023-12-31T12:26:24.640-0300] {processor.py:183} INFO - Processing /home/felipe/airflow/dags/03_with_end_date.py took 0.720 seconds
[2023-12-31T12:27:33.101-0300] {processor.py:161} INFO - Started process (PID=38056) to work on /home/felipe/airflow/dags/03_with_end_date.py
[2023-12-31T12:27:33.121-0300] {processor.py:830} INFO - Processing file /home/felipe/airflow/dags/03_with_end_date.py for tasks to queue
[2023-12-31T12:27:33.150-0300] {logging_mixin.py:188} INFO - [2023-12-31T12:27:33.140-0300] {dagbag.py:538} INFO - Filling up the DagBag from /home/felipe/airflow/dags/03_with_end_date.py
[2023-12-31T12:27:33.270-0300] {logging_mixin.py:188} INFO - [2023-12-31T12:27:33.241-0300] {dagbag.py:348} ERROR - Failed to import: /home/felipe/airflow/dags/03_with_end_date.py
Traceback (most recent call last):
  File "/home/felipe/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/felipe/airflow/dags/03_with_end_date.py", line 4, in <module>
    import pandas as pd
ModuleNotFoundError: No module named 'pandas'
[2023-12-31T12:27:33.281-0300] {processor.py:842} WARNING - No viable dags retrieved from /home/felipe/airflow/dags/03_with_end_date.py
[2023-12-31T12:27:33.760-0300] {processor.py:183} INFO - Processing /home/felipe/airflow/dags/03_with_end_date.py took 0.700 seconds
[2023-12-31T12:28:49.271-0300] {processor.py:161} INFO - Started process (PID=38118) to work on /home/felipe/airflow/dags/03_with_end_date.py
[2023-12-31T12:28:49.300-0300] {processor.py:830} INFO - Processing file /home/felipe/airflow/dags/03_with_end_date.py for tasks to queue
[2023-12-31T12:28:49.321-0300] {logging_mixin.py:188} INFO - [2023-12-31T12:28:49.311-0300] {dagbag.py:538} INFO - Filling up the DagBag from /home/felipe/airflow/dags/03_with_end_date.py
[2023-12-31T12:28:49.401-0300] {logging_mixin.py:188} INFO - [2023-12-31T12:28:49.371-0300] {dagbag.py:348} ERROR - Failed to import: /home/felipe/airflow/dags/03_with_end_date.py
Traceback (most recent call last):
  File "/home/felipe/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/felipe/airflow/dags/03_with_end_date.py", line 4, in <module>
    import pandas as pd
ModuleNotFoundError: No module named 'pandas'
[2023-12-31T12:28:49.420-0300] {processor.py:842} WARNING - No viable dags retrieved from /home/felipe/airflow/dags/03_with_end_date.py
[2023-12-31T12:28:49.880-0300] {processor.py:183} INFO - Processing /home/felipe/airflow/dags/03_with_end_date.py took 0.680 seconds
[2023-12-31T12:30:02.141-0300] {processor.py:161} INFO - Started process (PID=38169) to work on /home/felipe/airflow/dags/03_with_end_date.py
[2023-12-31T12:30:02.161-0300] {processor.py:830} INFO - Processing file /home/felipe/airflow/dags/03_with_end_date.py for tasks to queue
[2023-12-31T12:30:02.200-0300] {logging_mixin.py:188} INFO - [2023-12-31T12:30:02.190-0300] {dagbag.py:538} INFO - Filling up the DagBag from /home/felipe/airflow/dags/03_with_end_date.py
[2023-12-31T12:30:02.271-0300] {logging_mixin.py:188} INFO - [2023-12-31T12:30:02.241-0300] {dagbag.py:348} ERROR - Failed to import: /home/felipe/airflow/dags/03_with_end_date.py
Traceback (most recent call last):
  File "/home/felipe/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/felipe/airflow/dags/03_with_end_date.py", line 4, in <module>
    import pandas as pd
ModuleNotFoundError: No module named 'pandas'
[2023-12-31T12:30:02.291-0300] {processor.py:842} WARNING - No viable dags retrieved from /home/felipe/airflow/dags/03_with_end_date.py
[2023-12-31T12:30:02.721-0300] {processor.py:183} INFO - Processing /home/felipe/airflow/dags/03_with_end_date.py took 0.640 seconds
[2023-12-31T12:31:17.710-0300] {processor.py:161} INFO - Started process (PID=38244) to work on /home/felipe/airflow/dags/03_with_end_date.py
[2023-12-31T12:31:17.741-0300] {processor.py:830} INFO - Processing file /home/felipe/airflow/dags/03_with_end_date.py for tasks to queue
[2023-12-31T12:31:17.770-0300] {logging_mixin.py:188} INFO - [2023-12-31T12:31:17.761-0300] {dagbag.py:538} INFO - Filling up the DagBag from /home/felipe/airflow/dags/03_with_end_date.py
[2023-12-31T12:31:17.861-0300] {logging_mixin.py:188} INFO - [2023-12-31T12:31:17.830-0300] {dagbag.py:348} ERROR - Failed to import: /home/felipe/airflow/dags/03_with_end_date.py
Traceback (most recent call last):
  File "/home/felipe/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/felipe/airflow/dags/03_with_end_date.py", line 4, in <module>
    import pandas as pd
ModuleNotFoundError: No module named 'pandas'
[2023-12-31T12:31:17.880-0300] {processor.py:842} WARNING - No viable dags retrieved from /home/felipe/airflow/dags/03_with_end_date.py
[2023-12-31T12:31:18.390-0300] {processor.py:183} INFO - Processing /home/felipe/airflow/dags/03_with_end_date.py took 0.740 seconds
[2023-12-31T12:32:39.201-0300] {processor.py:161} INFO - Started process (PID=38298) to work on /home/felipe/airflow/dags/03_with_end_date.py
[2023-12-31T12:32:39.240-0300] {processor.py:830} INFO - Processing file /home/felipe/airflow/dags/03_with_end_date.py for tasks to queue
[2023-12-31T12:32:39.280-0300] {logging_mixin.py:188} INFO - [2023-12-31T12:32:39.261-0300] {dagbag.py:538} INFO - Filling up the DagBag from /home/felipe/airflow/dags/03_with_end_date.py
[2023-12-31T12:32:39.380-0300] {logging_mixin.py:188} INFO - [2023-12-31T12:32:39.360-0300] {dagbag.py:348} ERROR - Failed to import: /home/felipe/airflow/dags/03_with_end_date.py
Traceback (most recent call last):
  File "/home/felipe/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/felipe/airflow/dags/03_with_end_date.py", line 4, in <module>
    import pandas as pd
ModuleNotFoundError: No module named 'pandas'
[2023-12-31T12:32:39.391-0300] {processor.py:842} WARNING - No viable dags retrieved from /home/felipe/airflow/dags/03_with_end_date.py
[2023-12-31T12:32:39.961-0300] {processor.py:183} INFO - Processing /home/felipe/airflow/dags/03_with_end_date.py took 0.830 seconds
[2023-12-31T12:34:10.911-0300] {processor.py:161} INFO - Started process (PID=38353) to work on /home/felipe/airflow/dags/03_with_end_date.py
[2023-12-31T12:34:10.940-0300] {processor.py:830} INFO - Processing file /home/felipe/airflow/dags/03_with_end_date.py for tasks to queue
[2023-12-31T12:34:10.980-0300] {logging_mixin.py:188} INFO - [2023-12-31T12:34:10.960-0300] {dagbag.py:538} INFO - Filling up the DagBag from /home/felipe/airflow/dags/03_with_end_date.py
[2023-12-31T12:34:11.101-0300] {logging_mixin.py:188} INFO - [2023-12-31T12:34:11.061-0300] {dagbag.py:348} ERROR - Failed to import: /home/felipe/airflow/dags/03_with_end_date.py
Traceback (most recent call last):
  File "/home/felipe/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/felipe/airflow/dags/03_with_end_date.py", line 4, in <module>
    import pandas as pd
ModuleNotFoundError: No module named 'pandas'
[2023-12-31T12:34:11.120-0300] {processor.py:842} WARNING - No viable dags retrieved from /home/felipe/airflow/dags/03_with_end_date.py
[2023-12-31T12:34:11.701-0300] {processor.py:183} INFO - Processing /home/felipe/airflow/dags/03_with_end_date.py took 0.870 seconds
[2023-12-31T12:35:50.451-0300] {processor.py:161} INFO - Started process (PID=38443) to work on /home/felipe/airflow/dags/03_with_end_date.py
[2023-12-31T12:35:50.490-0300] {processor.py:830} INFO - Processing file /home/felipe/airflow/dags/03_with_end_date.py for tasks to queue
[2023-12-31T12:35:50.511-0300] {logging_mixin.py:188} INFO - [2023-12-31T12:35:50.501-0300] {dagbag.py:538} INFO - Filling up the DagBag from /home/felipe/airflow/dags/03_with_end_date.py
[2023-12-31T12:35:50.611-0300] {logging_mixin.py:188} INFO - [2023-12-31T12:35:50.580-0300] {dagbag.py:348} ERROR - Failed to import: /home/felipe/airflow/dags/03_with_end_date.py
Traceback (most recent call last):
  File "/home/felipe/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/felipe/airflow/dags/03_with_end_date.py", line 4, in <module>
    import pandas as pd
ModuleNotFoundError: No module named 'pandas'
[2023-12-31T12:35:50.630-0300] {processor.py:842} WARNING - No viable dags retrieved from /home/felipe/airflow/dags/03_with_end_date.py
[2023-12-31T12:35:51.201-0300] {processor.py:183} INFO - Processing /home/felipe/airflow/dags/03_with_end_date.py took 0.850 seconds
[2023-12-31T12:37:59.940-0300] {processor.py:161} INFO - Started process (PID=38512) to work on /home/felipe/airflow/dags/03_with_end_date.py
[2023-12-31T12:37:59.990-0300] {processor.py:830} INFO - Processing file /home/felipe/airflow/dags/03_with_end_date.py for tasks to queue
[2023-12-31T12:38:00.070-0300] {logging_mixin.py:188} INFO - [2023-12-31T12:38:00.031-0300] {dagbag.py:538} INFO - Filling up the DagBag from /home/felipe/airflow/dags/03_with_end_date.py
[2023-12-31T12:38:00.230-0300] {logging_mixin.py:188} INFO - [2023-12-31T12:38:00.180-0300] {dagbag.py:348} ERROR - Failed to import: /home/felipe/airflow/dags/03_with_end_date.py
Traceback (most recent call last):
  File "/home/felipe/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/felipe/airflow/dags/03_with_end_date.py", line 4, in <module>
    import pandas as pd
ModuleNotFoundError: No module named 'pandas'
[2023-12-31T12:38:00.250-0300] {processor.py:842} WARNING - No viable dags retrieved from /home/felipe/airflow/dags/03_with_end_date.py
[2023-12-31T12:38:01.180-0300] {processor.py:183} INFO - Processing /home/felipe/airflow/dags/03_with_end_date.py took 1.370 seconds
[2023-12-31T12:49:30.608-0300] {processor.py:161} INFO - Started process (PID=38824) to work on /home/felipe/airflow/dags/03_with_end_date.py
[2023-12-31T12:49:30.678-0300] {processor.py:830} INFO - Processing file /home/felipe/airflow/dags/03_with_end_date.py for tasks to queue
[2023-12-31T12:49:30.768-0300] {logging_mixin.py:188} INFO - [2023-12-31T12:49:30.728-0300] {dagbag.py:538} INFO - Filling up the DagBag from /home/felipe/airflow/dags/03_with_end_date.py
[2023-12-31T12:49:31.108-0300] {logging_mixin.py:188} INFO - [2023-12-31T12:49:31.017-0300] {dagbag.py:348} ERROR - Failed to import: /home/felipe/airflow/dags/03_with_end_date.py
Traceback (most recent call last):
  File "/home/felipe/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/felipe/airflow/dags/03_with_end_date.py", line 4, in <module>
    import pandas as pd
ModuleNotFoundError: No module named 'pandas'
[2023-12-31T12:49:31.168-0300] {processor.py:842} WARNING - No viable dags retrieved from /home/felipe/airflow/dags/03_with_end_date.py
[2023-12-31T12:49:32.878-0300] {processor.py:183} INFO - Processing /home/felipe/airflow/dags/03_with_end_date.py took 2.480 seconds
