[2023-12-31T09:36:40.989-0300] {processor.py:161} INFO - Started process (PID=31957) to work on /home/felipe/airflow/dags/06_templated_query.py
[2023-12-31T09:36:40.990-0300] {processor.py:830} INFO - Processing file /home/felipe/airflow/dags/06_templated_query.py for tasks to queue
[2023-12-31T09:36:40.996-0300] {logging_mixin.py:188} INFO - [2023-12-31T09:36:40.991-0300] {dagbag.py:538} INFO - Filling up the DagBag from /home/felipe/airflow/dags/06_templated_query.py
[2023-12-31T09:36:41.006-0300] {logging_mixin.py:188} INFO - [2023-12-31T09:36:41.000-0300] {dagbag.py:348} ERROR - Failed to import: /home/felipe/airflow/dags/06_templated_query.py
Traceback (most recent call last):
  File "/home/felipe/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/felipe/airflow/dags/06_templated_query.py", line 4, in <module>
    import pandas as pd
ModuleNotFoundError: No module named 'pandas'
[2023-12-31T09:36:41.007-0300] {processor.py:842} WARNING - No viable dags retrieved from /home/felipe/airflow/dags/06_templated_query.py
[2023-12-31T09:36:41.070-0300] {processor.py:183} INFO - Processing /home/felipe/airflow/dags/06_templated_query.py took 0.092 seconds
[2023-12-31T09:38:31.927-0300] {processor.py:161} INFO - Started process (PID=32172) to work on /home/felipe/airflow/dags/06_templated_query.py
[2023-12-31T09:38:31.937-0300] {processor.py:830} INFO - Processing file /home/felipe/airflow/dags/06_templated_query.py for tasks to queue
[2023-12-31T09:38:31.940-0300] {logging_mixin.py:188} INFO - [2023-12-31T09:38:31.939-0300] {dagbag.py:538} INFO - Filling up the DagBag from /home/felipe/airflow/dags/06_templated_query.py
[2023-12-31T09:38:31.977-0300] {logging_mixin.py:188} INFO - [2023-12-31T09:38:31.968-0300] {dagbag.py:348} ERROR - Failed to import: /home/felipe/airflow/dags/06_templated_query.py
Traceback (most recent call last):
  File "/home/felipe/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/felipe/airflow/dags/06_templated_query.py", line 4, in <module>
    import pandas as pd
ModuleNotFoundError: No module named 'pandas'
[2023-12-31T09:38:31.979-0300] {processor.py:842} WARNING - No viable dags retrieved from /home/felipe/airflow/dags/06_templated_query.py
[2023-12-31T09:38:32.108-0300] {processor.py:183} INFO - Processing /home/felipe/airflow/dags/06_templated_query.py took 0.199 seconds
[2023-12-31T09:52:00.608-0300] {processor.py:161} INFO - Started process (PID=32772) to work on /home/felipe/airflow/dags/06_templated_query.py
[2023-12-31T09:52:00.616-0300] {processor.py:830} INFO - Processing file /home/felipe/airflow/dags/06_templated_query.py for tasks to queue
[2023-12-31T09:52:00.618-0300] {logging_mixin.py:188} INFO - [2023-12-31T09:52:00.618-0300] {dagbag.py:538} INFO - Filling up the DagBag from /home/felipe/airflow/dags/06_templated_query.py
[2023-12-31T09:52:00.640-0300] {logging_mixin.py:188} INFO - [2023-12-31T09:52:00.630-0300] {dagbag.py:348} ERROR - Failed to import: /home/felipe/airflow/dags/06_templated_query.py
Traceback (most recent call last):
  File "/home/felipe/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/felipe/airflow/dags/06_templated_query.py", line 4, in <module>
    import pandas as pd
ModuleNotFoundError: No module named 'pandas'
[2023-12-31T09:52:00.648-0300] {processor.py:842} WARNING - No viable dags retrieved from /home/felipe/airflow/dags/06_templated_query.py
[2023-12-31T09:52:00.916-0300] {processor.py:183} INFO - Processing /home/felipe/airflow/dags/06_templated_query.py took 0.320 seconds
[2023-12-31T09:55:19.477-0300] {processor.py:161} INFO - Started process (PID=32928) to work on /home/felipe/airflow/dags/06_templated_query.py
[2023-12-31T09:55:19.480-0300] {processor.py:830} INFO - Processing file /home/felipe/airflow/dags/06_templated_query.py for tasks to queue
[2023-12-31T09:55:19.488-0300] {logging_mixin.py:188} INFO - [2023-12-31T09:55:19.488-0300] {dagbag.py:538} INFO - Filling up the DagBag from /home/felipe/airflow/dags/06_templated_query.py
[2023-12-31T09:55:19.509-0300] {logging_mixin.py:188} INFO - [2023-12-31T09:55:19.507-0300] {dagbag.py:348} ERROR - Failed to import: /home/felipe/airflow/dags/06_templated_query.py
Traceback (most recent call last):
  File "/home/felipe/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/felipe/airflow/dags/06_templated_query.py", line 4, in <module>
    import pandas as pd
ModuleNotFoundError: No module named 'pandas'
[2023-12-31T09:55:19.517-0300] {processor.py:842} WARNING - No viable dags retrieved from /home/felipe/airflow/dags/06_templated_query.py
[2023-12-31T09:55:19.646-0300] {processor.py:183} INFO - Processing /home/felipe/airflow/dags/06_templated_query.py took 0.174 seconds
[2023-12-31T09:59:56.077-0300] {processor.py:161} INFO - Started process (PID=33145) to work on /home/felipe/airflow/dags/06_templated_query.py
[2023-12-31T09:59:56.079-0300] {processor.py:830} INFO - Processing file /home/felipe/airflow/dags/06_templated_query.py for tasks to queue
[2023-12-31T09:59:56.087-0300] {logging_mixin.py:188} INFO - [2023-12-31T09:59:56.086-0300] {dagbag.py:538} INFO - Filling up the DagBag from /home/felipe/airflow/dags/06_templated_query.py
[2023-12-31T09:59:56.099-0300] {logging_mixin.py:188} INFO - [2023-12-31T09:59:56.097-0300] {dagbag.py:348} ERROR - Failed to import: /home/felipe/airflow/dags/06_templated_query.py
Traceback (most recent call last):
  File "/home/felipe/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/felipe/airflow/dags/06_templated_query.py", line 4, in <module>
    import pandas as pd
ModuleNotFoundError: No module named 'pandas'
[2023-12-31T09:59:56.106-0300] {processor.py:842} WARNING - No viable dags retrieved from /home/felipe/airflow/dags/06_templated_query.py
[2023-12-31T09:59:56.197-0300] {processor.py:183} INFO - Processing /home/felipe/airflow/dags/06_templated_query.py took 0.131 seconds
[2023-12-31T10:01:22.077-0300] {processor.py:161} INFO - Started process (PID=33273) to work on /home/felipe/airflow/dags/06_templated_query.py
[2023-12-31T10:01:22.079-0300] {processor.py:830} INFO - Processing file /home/felipe/airflow/dags/06_templated_query.py for tasks to queue
[2023-12-31T10:01:22.089-0300] {logging_mixin.py:188} INFO - [2023-12-31T10:01:22.089-0300] {dagbag.py:538} INFO - Filling up the DagBag from /home/felipe/airflow/dags/06_templated_query.py
[2023-12-31T10:01:22.108-0300] {logging_mixin.py:188} INFO - [2023-12-31T10:01:22.106-0300] {dagbag.py:348} ERROR - Failed to import: /home/felipe/airflow/dags/06_templated_query.py
Traceback (most recent call last):
  File "/home/felipe/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/felipe/airflow/dags/06_templated_query.py", line 4, in <module>
    import pandas as pd
ModuleNotFoundError: No module named 'pandas'
[2023-12-31T10:01:22.108-0300] {processor.py:842} WARNING - No viable dags retrieved from /home/felipe/airflow/dags/06_templated_query.py
[2023-12-31T10:01:22.209-0300] {processor.py:183} INFO - Processing /home/felipe/airflow/dags/06_templated_query.py took 0.143 seconds
[2023-12-31T10:02:30.620-0300] {processor.py:161} INFO - Started process (PID=33340) to work on /home/felipe/airflow/dags/06_templated_query.py
[2023-12-31T10:02:30.630-0300] {processor.py:830} INFO - Processing file /home/felipe/airflow/dags/06_templated_query.py for tasks to queue
[2023-12-31T10:02:30.638-0300] {logging_mixin.py:188} INFO - [2023-12-31T10:02:30.637-0300] {dagbag.py:538} INFO - Filling up the DagBag from /home/felipe/airflow/dags/06_templated_query.py
[2023-12-31T10:02:30.649-0300] {logging_mixin.py:188} INFO - [2023-12-31T10:02:30.648-0300] {dagbag.py:348} ERROR - Failed to import: /home/felipe/airflow/dags/06_templated_query.py
Traceback (most recent call last):
  File "/home/felipe/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/felipe/airflow/dags/06_templated_query.py", line 4, in <module>
    import pandas as pd
ModuleNotFoundError: No module named 'pandas'
[2023-12-31T10:02:30.656-0300] {processor.py:842} WARNING - No viable dags retrieved from /home/felipe/airflow/dags/06_templated_query.py
[2023-12-31T10:02:30.777-0300] {processor.py:183} INFO - Processing /home/felipe/airflow/dags/06_templated_query.py took 0.168 seconds
[2023-12-31T10:03:36.176-0300] {processor.py:161} INFO - Started process (PID=33412) to work on /home/felipe/airflow/dags/06_templated_query.py
[2023-12-31T10:03:36.179-0300] {processor.py:830} INFO - Processing file /home/felipe/airflow/dags/06_templated_query.py for tasks to queue
[2023-12-31T10:03:36.187-0300] {logging_mixin.py:188} INFO - [2023-12-31T10:03:36.186-0300] {dagbag.py:538} INFO - Filling up the DagBag from /home/felipe/airflow/dags/06_templated_query.py
[2023-12-31T10:03:36.199-0300] {logging_mixin.py:188} INFO - [2023-12-31T10:03:36.197-0300] {dagbag.py:348} ERROR - Failed to import: /home/felipe/airflow/dags/06_templated_query.py
Traceback (most recent call last):
  File "/home/felipe/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/felipe/airflow/dags/06_templated_query.py", line 4, in <module>
    import pandas as pd
ModuleNotFoundError: No module named 'pandas'
[2023-12-31T10:03:36.206-0300] {processor.py:842} WARNING - No viable dags retrieved from /home/felipe/airflow/dags/06_templated_query.py
[2023-12-31T10:03:36.328-0300] {processor.py:183} INFO - Processing /home/felipe/airflow/dags/06_templated_query.py took 0.168 seconds
[2023-12-31T10:04:47.657-0300] {processor.py:161} INFO - Started process (PID=33492) to work on /home/felipe/airflow/dags/06_templated_query.py
[2023-12-31T10:04:47.659-0300] {processor.py:830} INFO - Processing file /home/felipe/airflow/dags/06_templated_query.py for tasks to queue
[2023-12-31T10:04:47.689-0300] {logging_mixin.py:188} INFO - [2023-12-31T10:04:47.688-0300] {dagbag.py:538} INFO - Filling up the DagBag from /home/felipe/airflow/dags/06_templated_query.py
[2023-12-31T10:04:47.707-0300] {logging_mixin.py:188} INFO - [2023-12-31T10:04:47.699-0300] {dagbag.py:348} ERROR - Failed to import: /home/felipe/airflow/dags/06_templated_query.py
Traceback (most recent call last):
  File "/home/felipe/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/felipe/airflow/dags/06_templated_query.py", line 4, in <module>
    import pandas as pd
ModuleNotFoundError: No module named 'pandas'
[2023-12-31T10:04:47.708-0300] {processor.py:842} WARNING - No viable dags retrieved from /home/felipe/airflow/dags/06_templated_query.py
[2023-12-31T10:04:47.808-0300] {processor.py:183} INFO - Processing /home/felipe/airflow/dags/06_templated_query.py took 0.162 seconds
[2023-12-31T10:05:58.889-0300] {processor.py:161} INFO - Started process (PID=33578) to work on /home/felipe/airflow/dags/06_templated_query.py
[2023-12-31T10:05:58.898-0300] {processor.py:830} INFO - Processing file /home/felipe/airflow/dags/06_templated_query.py for tasks to queue
[2023-12-31T10:05:58.906-0300] {logging_mixin.py:188} INFO - [2023-12-31T10:05:58.899-0300] {dagbag.py:538} INFO - Filling up the DagBag from /home/felipe/airflow/dags/06_templated_query.py
[2023-12-31T10:05:58.918-0300] {logging_mixin.py:188} INFO - [2023-12-31T10:05:58.917-0300] {dagbag.py:348} ERROR - Failed to import: /home/felipe/airflow/dags/06_templated_query.py
Traceback (most recent call last):
  File "/home/felipe/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/felipe/airflow/dags/06_templated_query.py", line 4, in <module>
    import pandas as pd
ModuleNotFoundError: No module named 'pandas'
[2023-12-31T10:05:58.919-0300] {processor.py:842} WARNING - No viable dags retrieved from /home/felipe/airflow/dags/06_templated_query.py
[2023-12-31T10:05:59.028-0300] {processor.py:183} INFO - Processing /home/felipe/airflow/dags/06_templated_query.py took 0.149 seconds
[2023-12-31T10:07:09.938-0300] {processor.py:161} INFO - Started process (PID=33687) to work on /home/felipe/airflow/dags/06_templated_query.py
[2023-12-31T10:07:09.946-0300] {processor.py:830} INFO - Processing file /home/felipe/airflow/dags/06_templated_query.py for tasks to queue
[2023-12-31T10:07:09.948-0300] {logging_mixin.py:188} INFO - [2023-12-31T10:07:09.947-0300] {dagbag.py:538} INFO - Filling up the DagBag from /home/felipe/airflow/dags/06_templated_query.py
[2023-12-31T10:07:09.960-0300] {logging_mixin.py:188} INFO - [2023-12-31T10:07:09.958-0300] {dagbag.py:348} ERROR - Failed to import: /home/felipe/airflow/dags/06_templated_query.py
Traceback (most recent call last):
  File "/home/felipe/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/felipe/airflow/dags/06_templated_query.py", line 4, in <module>
    import pandas as pd
ModuleNotFoundError: No module named 'pandas'
[2023-12-31T10:07:09.967-0300] {processor.py:842} WARNING - No viable dags retrieved from /home/felipe/airflow/dags/06_templated_query.py
[2023-12-31T10:07:10.067-0300] {processor.py:183} INFO - Processing /home/felipe/airflow/dags/06_templated_query.py took 0.141 seconds
[2023-12-31T10:08:22.808-0300] {processor.py:161} INFO - Started process (PID=33771) to work on /home/felipe/airflow/dags/06_templated_query.py
[2023-12-31T10:08:22.817-0300] {processor.py:830} INFO - Processing file /home/felipe/airflow/dags/06_templated_query.py for tasks to queue
[2023-12-31T10:08:22.818-0300] {logging_mixin.py:188} INFO - [2023-12-31T10:08:22.818-0300] {dagbag.py:538} INFO - Filling up the DagBag from /home/felipe/airflow/dags/06_templated_query.py
[2023-12-31T10:08:22.836-0300] {logging_mixin.py:188} INFO - [2023-12-31T10:08:22.828-0300] {dagbag.py:348} ERROR - Failed to import: /home/felipe/airflow/dags/06_templated_query.py
Traceback (most recent call last):
  File "/home/felipe/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/felipe/airflow/dags/06_templated_query.py", line 4, in <module>
    import pandas as pd
ModuleNotFoundError: No module named 'pandas'
[2023-12-31T10:08:22.837-0300] {processor.py:842} WARNING - No viable dags retrieved from /home/felipe/airflow/dags/06_templated_query.py
[2023-12-31T10:08:22.948-0300] {processor.py:183} INFO - Processing /home/felipe/airflow/dags/06_templated_query.py took 0.151 seconds
[2023-12-31T11:28:53.996-0300] {processor.py:161} INFO - Started process (PID=33957) to work on /home/felipe/airflow/dags/06_templated_query.py
[2023-12-31T11:28:54.006-0300] {processor.py:830} INFO - Processing file /home/felipe/airflow/dags/06_templated_query.py for tasks to queue
[2023-12-31T11:28:54.015-0300] {logging_mixin.py:188} INFO - [2023-12-31T11:28:54.014-0300] {dagbag.py:538} INFO - Filling up the DagBag from /home/felipe/airflow/dags/06_templated_query.py
[2023-12-31T11:28:54.045-0300] {logging_mixin.py:188} INFO - [2023-12-31T11:28:54.035-0300] {dagbag.py:348} ERROR - Failed to import: /home/felipe/airflow/dags/06_templated_query.py
Traceback (most recent call last):
  File "/home/felipe/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/felipe/airflow/dags/06_templated_query.py", line 4, in <module>
    import pandas as pd
ModuleNotFoundError: No module named 'pandas'
[2023-12-31T11:28:54.046-0300] {processor.py:842} WARNING - No viable dags retrieved from /home/felipe/airflow/dags/06_templated_query.py
[2023-12-31T11:28:54.205-0300] {processor.py:183} INFO - Processing /home/felipe/airflow/dags/06_templated_query.py took 0.228 seconds
[2023-12-31T11:30:48.054-0300] {processor.py:161} INFO - Started process (PID=34233) to work on /home/felipe/airflow/dags/06_templated_query.py
[2023-12-31T11:30:48.064-0300] {processor.py:830} INFO - Processing file /home/felipe/airflow/dags/06_templated_query.py for tasks to queue
[2023-12-31T11:30:48.066-0300] {logging_mixin.py:188} INFO - [2023-12-31T11:30:48.065-0300] {dagbag.py:538} INFO - Filling up the DagBag from /home/felipe/airflow/dags/06_templated_query.py
[2023-12-31T11:30:48.085-0300] {logging_mixin.py:188} INFO - [2023-12-31T11:30:48.076-0300] {dagbag.py:348} ERROR - Failed to import: /home/felipe/airflow/dags/06_templated_query.py
Traceback (most recent call last):
  File "/home/felipe/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/felipe/airflow/dags/06_templated_query.py", line 4, in <module>
    import pandas as pd
ModuleNotFoundError: No module named 'pandas'
[2023-12-31T11:30:48.086-0300] {processor.py:842} WARNING - No viable dags retrieved from /home/felipe/airflow/dags/06_templated_query.py
[2023-12-31T11:30:48.215-0300] {processor.py:183} INFO - Processing /home/felipe/airflow/dags/06_templated_query.py took 0.179 seconds
[2023-12-31T11:32:19.256-0300] {processor.py:161} INFO - Started process (PID=34341) to work on /home/felipe/airflow/dags/06_templated_query.py
[2023-12-31T11:32:19.264-0300] {processor.py:830} INFO - Processing file /home/felipe/airflow/dags/06_templated_query.py for tasks to queue
[2023-12-31T11:32:19.266-0300] {logging_mixin.py:188} INFO - [2023-12-31T11:32:19.266-0300] {dagbag.py:538} INFO - Filling up the DagBag from /home/felipe/airflow/dags/06_templated_query.py
[2023-12-31T11:32:19.285-0300] {logging_mixin.py:188} INFO - [2023-12-31T11:32:19.284-0300] {dagbag.py:348} ERROR - Failed to import: /home/felipe/airflow/dags/06_templated_query.py
Traceback (most recent call last):
  File "/home/felipe/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/felipe/airflow/dags/06_templated_query.py", line 4, in <module>
    import pandas as pd
ModuleNotFoundError: No module named 'pandas'
[2023-12-31T11:32:19.286-0300] {processor.py:842} WARNING - No viable dags retrieved from /home/felipe/airflow/dags/06_templated_query.py
[2023-12-31T11:32:19.426-0300] {processor.py:183} INFO - Processing /home/felipe/airflow/dags/06_templated_query.py took 0.182 seconds
[2023-12-31T11:33:49.856-0300] {processor.py:161} INFO - Started process (PID=34437) to work on /home/felipe/airflow/dags/06_templated_query.py
[2023-12-31T11:33:49.864-0300] {processor.py:830} INFO - Processing file /home/felipe/airflow/dags/06_templated_query.py for tasks to queue
[2023-12-31T11:33:49.874-0300] {logging_mixin.py:188} INFO - [2023-12-31T11:33:49.866-0300] {dagbag.py:538} INFO - Filling up the DagBag from /home/felipe/airflow/dags/06_templated_query.py
[2023-12-31T11:33:49.904-0300] {logging_mixin.py:188} INFO - [2023-12-31T11:33:49.895-0300] {dagbag.py:348} ERROR - Failed to import: /home/felipe/airflow/dags/06_templated_query.py
Traceback (most recent call last):
  File "/home/felipe/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/felipe/airflow/dags/06_templated_query.py", line 4, in <module>
    import pandas as pd
ModuleNotFoundError: No module named 'pandas'
[2023-12-31T11:33:49.906-0300] {processor.py:842} WARNING - No viable dags retrieved from /home/felipe/airflow/dags/06_templated_query.py
[2023-12-31T11:33:50.106-0300] {processor.py:183} INFO - Processing /home/felipe/airflow/dags/06_templated_query.py took 0.279 seconds
[2023-12-31T11:35:12.544-0300] {processor.py:161} INFO - Started process (PID=34561) to work on /home/felipe/airflow/dags/06_templated_query.py
[2023-12-31T11:35:12.547-0300] {processor.py:830} INFO - Processing file /home/felipe/airflow/dags/06_templated_query.py for tasks to queue
[2023-12-31T11:35:12.555-0300] {logging_mixin.py:188} INFO - [2023-12-31T11:35:12.555-0300] {dagbag.py:538} INFO - Filling up the DagBag from /home/felipe/airflow/dags/06_templated_query.py
[2023-12-31T11:35:12.576-0300] {logging_mixin.py:188} INFO - [2023-12-31T11:35:12.574-0300] {dagbag.py:348} ERROR - Failed to import: /home/felipe/airflow/dags/06_templated_query.py
Traceback (most recent call last):
  File "/home/felipe/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/felipe/airflow/dags/06_templated_query.py", line 4, in <module>
    import pandas as pd
ModuleNotFoundError: No module named 'pandas'
[2023-12-31T11:35:12.584-0300] {processor.py:842} WARNING - No viable dags retrieved from /home/felipe/airflow/dags/06_templated_query.py
[2023-12-31T11:35:12.715-0300] {processor.py:183} INFO - Processing /home/felipe/airflow/dags/06_templated_query.py took 0.190 seconds
[2023-12-31T11:36:35.104-0300] {processor.py:161} INFO - Started process (PID=34650) to work on /home/felipe/airflow/dags/06_templated_query.py
[2023-12-31T11:36:35.114-0300] {processor.py:830} INFO - Processing file /home/felipe/airflow/dags/06_templated_query.py for tasks to queue
[2023-12-31T11:36:35.115-0300] {logging_mixin.py:188} INFO - [2023-12-31T11:36:35.115-0300] {dagbag.py:538} INFO - Filling up the DagBag from /home/felipe/airflow/dags/06_templated_query.py
[2023-12-31T11:36:35.134-0300] {logging_mixin.py:188} INFO - [2023-12-31T11:36:35.126-0300] {dagbag.py:348} ERROR - Failed to import: /home/felipe/airflow/dags/06_templated_query.py
Traceback (most recent call last):
  File "/home/felipe/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/felipe/airflow/dags/06_templated_query.py", line 4, in <module>
    import pandas as pd
ModuleNotFoundError: No module named 'pandas'
[2023-12-31T11:36:35.135-0300] {processor.py:842} WARNING - No viable dags retrieved from /home/felipe/airflow/dags/06_templated_query.py
[2023-12-31T11:36:35.255-0300] {processor.py:183} INFO - Processing /home/felipe/airflow/dags/06_templated_query.py took 0.169 seconds
[2023-12-31T11:37:59.045-0300] {processor.py:161} INFO - Started process (PID=34737) to work on /home/felipe/airflow/dags/06_templated_query.py
[2023-12-31T11:37:59.054-0300] {processor.py:830} INFO - Processing file /home/felipe/airflow/dags/06_templated_query.py for tasks to queue
[2023-12-31T11:37:59.056-0300] {logging_mixin.py:188} INFO - [2023-12-31T11:37:59.055-0300] {dagbag.py:538} INFO - Filling up the DagBag from /home/felipe/airflow/dags/06_templated_query.py
[2023-12-31T11:37:59.075-0300] {logging_mixin.py:188} INFO - [2023-12-31T11:37:59.067-0300] {dagbag.py:348} ERROR - Failed to import: /home/felipe/airflow/dags/06_templated_query.py
Traceback (most recent call last):
  File "/home/felipe/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/felipe/airflow/dags/06_templated_query.py", line 4, in <module>
    import pandas as pd
ModuleNotFoundError: No module named 'pandas'
[2023-12-31T11:37:59.076-0300] {processor.py:842} WARNING - No viable dags retrieved from /home/felipe/airflow/dags/06_templated_query.py
[2023-12-31T11:37:59.186-0300] {processor.py:183} INFO - Processing /home/felipe/airflow/dags/06_templated_query.py took 0.160 seconds
[2023-12-31T11:39:21.555-0300] {processor.py:161} INFO - Started process (PID=34832) to work on /home/felipe/airflow/dags/06_templated_query.py
[2023-12-31T11:39:21.565-0300] {processor.py:830} INFO - Processing file /home/felipe/airflow/dags/06_templated_query.py for tasks to queue
[2023-12-31T11:39:21.574-0300] {logging_mixin.py:188} INFO - [2023-12-31T11:39:21.574-0300] {dagbag.py:538} INFO - Filling up the DagBag from /home/felipe/airflow/dags/06_templated_query.py
[2023-12-31T11:39:21.596-0300] {logging_mixin.py:188} INFO - [2023-12-31T11:39:21.594-0300] {dagbag.py:348} ERROR - Failed to import: /home/felipe/airflow/dags/06_templated_query.py
Traceback (most recent call last):
  File "/home/felipe/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/felipe/airflow/dags/06_templated_query.py", line 4, in <module>
    import pandas as pd
ModuleNotFoundError: No module named 'pandas'
[2023-12-31T11:39:21.604-0300] {processor.py:842} WARNING - No viable dags retrieved from /home/felipe/airflow/dags/06_templated_query.py
[2023-12-31T11:39:21.756-0300] {processor.py:183} INFO - Processing /home/felipe/airflow/dags/06_templated_query.py took 0.221 seconds
[2023-12-31T11:40:44.245-0300] {processor.py:161} INFO - Started process (PID=34948) to work on /home/felipe/airflow/dags/06_templated_query.py
[2023-12-31T11:40:44.254-0300] {processor.py:830} INFO - Processing file /home/felipe/airflow/dags/06_templated_query.py for tasks to queue
[2023-12-31T11:40:44.256-0300] {logging_mixin.py:188} INFO - [2023-12-31T11:40:44.255-0300] {dagbag.py:538} INFO - Filling up the DagBag from /home/felipe/airflow/dags/06_templated_query.py
[2023-12-31T11:40:44.276-0300] {logging_mixin.py:188} INFO - [2023-12-31T11:40:44.274-0300] {dagbag.py:348} ERROR - Failed to import: /home/felipe/airflow/dags/06_templated_query.py
Traceback (most recent call last):
  File "/home/felipe/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/felipe/airflow/dags/06_templated_query.py", line 4, in <module>
    import pandas as pd
ModuleNotFoundError: No module named 'pandas'
[2023-12-31T11:40:44.285-0300] {processor.py:842} WARNING - No viable dags retrieved from /home/felipe/airflow/dags/06_templated_query.py
[2023-12-31T11:40:44.485-0300] {processor.py:183} INFO - Processing /home/felipe/airflow/dags/06_templated_query.py took 0.259 seconds
[2023-12-31T11:42:17.996-0300] {processor.py:161} INFO - Started process (PID=35054) to work on /home/felipe/airflow/dags/06_templated_query.py
[2023-12-31T11:42:18.005-0300] {processor.py:830} INFO - Processing file /home/felipe/airflow/dags/06_templated_query.py for tasks to queue
[2023-12-31T11:42:18.014-0300] {logging_mixin.py:188} INFO - [2023-12-31T11:42:18.006-0300] {dagbag.py:538} INFO - Filling up the DagBag from /home/felipe/airflow/dags/06_templated_query.py
[2023-12-31T11:42:18.034-0300] {logging_mixin.py:188} INFO - [2023-12-31T11:42:18.025-0300] {dagbag.py:348} ERROR - Failed to import: /home/felipe/airflow/dags/06_templated_query.py
Traceback (most recent call last):
  File "/home/felipe/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/felipe/airflow/dags/06_templated_query.py", line 4, in <module>
    import pandas as pd
ModuleNotFoundError: No module named 'pandas'
[2023-12-31T11:42:18.035-0300] {processor.py:842} WARNING - No viable dags retrieved from /home/felipe/airflow/dags/06_templated_query.py
[2023-12-31T11:42:18.176-0300] {processor.py:183} INFO - Processing /home/felipe/airflow/dags/06_templated_query.py took 0.192 seconds
[2023-12-31T11:43:54.156-0300] {processor.py:161} INFO - Started process (PID=35164) to work on /home/felipe/airflow/dags/06_templated_query.py
[2023-12-31T11:43:54.166-0300] {processor.py:830} INFO - Processing file /home/felipe/airflow/dags/06_templated_query.py for tasks to queue
[2023-12-31T11:43:54.175-0300] {logging_mixin.py:188} INFO - [2023-12-31T11:43:54.175-0300] {dagbag.py:538} INFO - Filling up the DagBag from /home/felipe/airflow/dags/06_templated_query.py
[2023-12-31T11:43:54.196-0300] {logging_mixin.py:188} INFO - [2023-12-31T11:43:54.194-0300] {dagbag.py:348} ERROR - Failed to import: /home/felipe/airflow/dags/06_templated_query.py
Traceback (most recent call last):
  File "/home/felipe/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/felipe/airflow/dags/06_templated_query.py", line 4, in <module>
    import pandas as pd
ModuleNotFoundError: No module named 'pandas'
[2023-12-31T11:43:54.204-0300] {processor.py:842} WARNING - No viable dags retrieved from /home/felipe/airflow/dags/06_templated_query.py
[2023-12-31T11:43:54.356-0300] {processor.py:183} INFO - Processing /home/felipe/airflow/dags/06_templated_query.py took 0.220 seconds
[2023-12-31T11:45:35.126-0300] {processor.py:161} INFO - Started process (PID=35303) to work on /home/felipe/airflow/dags/06_templated_query.py
[2023-12-31T11:45:35.145-0300] {processor.py:830} INFO - Processing file /home/felipe/airflow/dags/06_templated_query.py for tasks to queue
[2023-12-31T11:45:35.154-0300] {logging_mixin.py:188} INFO - [2023-12-31T11:45:35.146-0300] {dagbag.py:538} INFO - Filling up the DagBag from /home/felipe/airflow/dags/06_templated_query.py
[2023-12-31T11:45:35.196-0300] {logging_mixin.py:188} INFO - [2023-12-31T11:45:35.186-0300] {dagbag.py:348} ERROR - Failed to import: /home/felipe/airflow/dags/06_templated_query.py
Traceback (most recent call last):
  File "/home/felipe/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/felipe/airflow/dags/06_templated_query.py", line 4, in <module>
    import pandas as pd
ModuleNotFoundError: No module named 'pandas'
[2023-12-31T11:45:35.205-0300] {processor.py:842} WARNING - No viable dags retrieved from /home/felipe/airflow/dags/06_templated_query.py
[2023-12-31T11:45:35.406-0300] {processor.py:183} INFO - Processing /home/felipe/airflow/dags/06_templated_query.py took 0.310 seconds
[2023-12-31T11:47:12.926-0300] {processor.py:161} INFO - Started process (PID=35427) to work on /home/felipe/airflow/dags/06_templated_query.py
[2023-12-31T11:47:12.935-0300] {processor.py:830} INFO - Processing file /home/felipe/airflow/dags/06_templated_query.py for tasks to queue
[2023-12-31T11:47:12.945-0300] {logging_mixin.py:188} INFO - [2023-12-31T11:47:12.944-0300] {dagbag.py:538} INFO - Filling up the DagBag from /home/felipe/airflow/dags/06_templated_query.py
[2023-12-31T11:47:12.974-0300] {logging_mixin.py:188} INFO - [2023-12-31T11:47:12.965-0300] {dagbag.py:348} ERROR - Failed to import: /home/felipe/airflow/dags/06_templated_query.py
Traceback (most recent call last):
  File "/home/felipe/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/felipe/airflow/dags/06_templated_query.py", line 4, in <module>
    import pandas as pd
ModuleNotFoundError: No module named 'pandas'
[2023-12-31T11:47:12.975-0300] {processor.py:842} WARNING - No viable dags retrieved from /home/felipe/airflow/dags/06_templated_query.py
[2023-12-31T11:47:13.144-0300] {processor.py:183} INFO - Processing /home/felipe/airflow/dags/06_templated_query.py took 0.231 seconds
[2023-12-31T11:49:25.215-0300] {processor.py:161} INFO - Started process (PID=35586) to work on /home/felipe/airflow/dags/06_templated_query.py
[2023-12-31T11:49:25.254-0300] {processor.py:830} INFO - Processing file /home/felipe/airflow/dags/06_templated_query.py for tasks to queue
[2023-12-31T11:49:25.266-0300] {logging_mixin.py:188} INFO - [2023-12-31T11:49:25.264-0300] {dagbag.py:538} INFO - Filling up the DagBag from /home/felipe/airflow/dags/06_templated_query.py
[2023-12-31T11:49:25.325-0300] {logging_mixin.py:188} INFO - [2023-12-31T11:49:25.305-0300] {dagbag.py:348} ERROR - Failed to import: /home/felipe/airflow/dags/06_templated_query.py
Traceback (most recent call last):
  File "/home/felipe/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/felipe/airflow/dags/06_templated_query.py", line 4, in <module>
    import pandas as pd
ModuleNotFoundError: No module named 'pandas'
[2023-12-31T11:49:25.335-0300] {processor.py:842} WARNING - No viable dags retrieved from /home/felipe/airflow/dags/06_templated_query.py
[2023-12-31T11:49:25.664-0300] {processor.py:183} INFO - Processing /home/felipe/airflow/dags/06_templated_query.py took 0.608 seconds
[2023-12-31T11:51:34.925-0300] {processor.py:161} INFO - Started process (PID=35734) to work on /home/felipe/airflow/dags/06_templated_query.py
[2023-12-31T11:51:34.935-0300] {processor.py:830} INFO - Processing file /home/felipe/airflow/dags/06_templated_query.py for tasks to queue
[2023-12-31T11:51:34.945-0300] {logging_mixin.py:188} INFO - [2023-12-31T11:51:34.944-0300] {dagbag.py:538} INFO - Filling up the DagBag from /home/felipe/airflow/dags/06_templated_query.py
[2023-12-31T11:51:34.985-0300] {logging_mixin.py:188} INFO - [2023-12-31T11:51:34.975-0300] {dagbag.py:348} ERROR - Failed to import: /home/felipe/airflow/dags/06_templated_query.py
Traceback (most recent call last):
  File "/home/felipe/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/felipe/airflow/dags/06_templated_query.py", line 4, in <module>
    import pandas as pd
ModuleNotFoundError: No module named 'pandas'
[2023-12-31T11:51:34.986-0300] {processor.py:842} WARNING - No viable dags retrieved from /home/felipe/airflow/dags/06_templated_query.py
[2023-12-31T11:51:35.244-0300] {processor.py:183} INFO - Processing /home/felipe/airflow/dags/06_templated_query.py took 0.349 seconds
[2023-12-31T11:54:19.264-0300] {processor.py:161} INFO - Started process (PID=35870) to work on /home/felipe/airflow/dags/06_templated_query.py
[2023-12-31T11:54:19.284-0300] {processor.py:830} INFO - Processing file /home/felipe/airflow/dags/06_templated_query.py for tasks to queue
[2023-12-31T11:54:19.294-0300] {logging_mixin.py:188} INFO - [2023-12-31T11:54:19.285-0300] {dagbag.py:538} INFO - Filling up the DagBag from /home/felipe/airflow/dags/06_templated_query.py
[2023-12-31T11:54:19.334-0300] {logging_mixin.py:188} INFO - [2023-12-31T11:54:19.324-0300] {dagbag.py:348} ERROR - Failed to import: /home/felipe/airflow/dags/06_templated_query.py
Traceback (most recent call last):
  File "/home/felipe/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/felipe/airflow/dags/06_templated_query.py", line 4, in <module>
    import pandas as pd
ModuleNotFoundError: No module named 'pandas'
[2023-12-31T11:54:19.335-0300] {processor.py:842} WARNING - No viable dags retrieved from /home/felipe/airflow/dags/06_templated_query.py
[2023-12-31T11:54:19.644-0300] {processor.py:183} INFO - Processing /home/felipe/airflow/dags/06_templated_query.py took 0.410 seconds
[2023-12-31T11:56:12.454-0300] {processor.py:161} INFO - Started process (PID=36005) to work on /home/felipe/airflow/dags/06_templated_query.py
[2023-12-31T11:56:12.464-0300] {processor.py:830} INFO - Processing file /home/felipe/airflow/dags/06_templated_query.py for tasks to queue
[2023-12-31T11:56:12.466-0300] {logging_mixin.py:188} INFO - [2023-12-31T11:56:12.465-0300] {dagbag.py:538} INFO - Filling up the DagBag from /home/felipe/airflow/dags/06_templated_query.py
[2023-12-31T11:56:12.505-0300] {logging_mixin.py:188} INFO - [2023-12-31T11:56:12.495-0300] {dagbag.py:348} ERROR - Failed to import: /home/felipe/airflow/dags/06_templated_query.py
Traceback (most recent call last):
  File "/home/felipe/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/felipe/airflow/dags/06_templated_query.py", line 4, in <module>
    import pandas as pd
ModuleNotFoundError: No module named 'pandas'
[2023-12-31T11:56:12.505-0300] {processor.py:842} WARNING - No viable dags retrieved from /home/felipe/airflow/dags/06_templated_query.py
[2023-12-31T11:56:12.684-0300] {processor.py:183} INFO - Processing /home/felipe/airflow/dags/06_templated_query.py took 0.259 seconds
[2023-12-31T11:57:57.104-0300] {processor.py:161} INFO - Started process (PID=36110) to work on /home/felipe/airflow/dags/06_templated_query.py
[2023-12-31T11:57:57.114-0300] {processor.py:830} INFO - Processing file /home/felipe/airflow/dags/06_templated_query.py for tasks to queue
[2023-12-31T11:57:57.116-0300] {logging_mixin.py:188} INFO - [2023-12-31T11:57:57.115-0300] {dagbag.py:538} INFO - Filling up the DagBag from /home/felipe/airflow/dags/06_templated_query.py
[2023-12-31T11:57:57.145-0300] {logging_mixin.py:188} INFO - [2023-12-31T11:57:57.135-0300] {dagbag.py:348} ERROR - Failed to import: /home/felipe/airflow/dags/06_templated_query.py
Traceback (most recent call last):
  File "/home/felipe/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/felipe/airflow/dags/06_templated_query.py", line 4, in <module>
    import pandas as pd
ModuleNotFoundError: No module named 'pandas'
[2023-12-31T11:57:57.145-0300] {processor.py:842} WARNING - No viable dags retrieved from /home/felipe/airflow/dags/06_templated_query.py
[2023-12-31T11:57:57.334-0300] {processor.py:183} INFO - Processing /home/felipe/airflow/dags/06_templated_query.py took 0.259 seconds
[2023-12-31T11:59:42.865-0300] {processor.py:161} INFO - Started process (PID=36212) to work on /home/felipe/airflow/dags/06_templated_query.py
[2023-12-31T11:59:42.875-0300] {processor.py:830} INFO - Processing file /home/felipe/airflow/dags/06_templated_query.py for tasks to queue
[2023-12-31T11:59:42.885-0300] {logging_mixin.py:188} INFO - [2023-12-31T11:59:42.884-0300] {dagbag.py:538} INFO - Filling up the DagBag from /home/felipe/airflow/dags/06_templated_query.py
[2023-12-31T11:59:42.915-0300] {logging_mixin.py:188} INFO - [2023-12-31T11:59:42.906-0300] {dagbag.py:348} ERROR - Failed to import: /home/felipe/airflow/dags/06_templated_query.py
Traceback (most recent call last):
  File "/home/felipe/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/felipe/airflow/dags/06_templated_query.py", line 4, in <module>
    import pandas as pd
ModuleNotFoundError: No module named 'pandas'
[2023-12-31T11:59:42.924-0300] {processor.py:842} WARNING - No viable dags retrieved from /home/felipe/airflow/dags/06_templated_query.py
[2023-12-31T11:59:43.124-0300] {processor.py:183} INFO - Processing /home/felipe/airflow/dags/06_templated_query.py took 0.280 seconds
[2023-12-31T12:01:32.225-0300] {processor.py:161} INFO - Started process (PID=36345) to work on /home/felipe/airflow/dags/06_templated_query.py
[2023-12-31T12:01:32.235-0300] {processor.py:830} INFO - Processing file /home/felipe/airflow/dags/06_templated_query.py for tasks to queue
[2023-12-31T12:01:32.245-0300] {logging_mixin.py:188} INFO - [2023-12-31T12:01:32.245-0300] {dagbag.py:538} INFO - Filling up the DagBag from /home/felipe/airflow/dags/06_templated_query.py
[2023-12-31T12:01:32.284-0300] {logging_mixin.py:188} INFO - [2023-12-31T12:01:32.274-0300] {dagbag.py:348} ERROR - Failed to import: /home/felipe/airflow/dags/06_templated_query.py
Traceback (most recent call last):
  File "/home/felipe/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/felipe/airflow/dags/06_templated_query.py", line 4, in <module>
    import pandas as pd
ModuleNotFoundError: No module named 'pandas'
[2023-12-31T12:01:32.285-0300] {processor.py:842} WARNING - No viable dags retrieved from /home/felipe/airflow/dags/06_templated_query.py
[2023-12-31T12:01:32.524-0300] {processor.py:183} INFO - Processing /home/felipe/airflow/dags/06_templated_query.py took 0.320 seconds
[2023-12-31T12:03:31.145-0300] {processor.py:161} INFO - Started process (PID=36452) to work on /home/felipe/airflow/dags/06_templated_query.py
[2023-12-31T12:03:31.164-0300] {processor.py:830} INFO - Processing file /home/felipe/airflow/dags/06_templated_query.py for tasks to queue
[2023-12-31T12:03:31.174-0300] {logging_mixin.py:188} INFO - [2023-12-31T12:03:31.165-0300] {dagbag.py:538} INFO - Filling up the DagBag from /home/felipe/airflow/dags/06_templated_query.py
[2023-12-31T12:03:31.214-0300] {logging_mixin.py:188} INFO - [2023-12-31T12:03:31.204-0300] {dagbag.py:348} ERROR - Failed to import: /home/felipe/airflow/dags/06_templated_query.py
Traceback (most recent call last):
  File "/home/felipe/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/felipe/airflow/dags/06_templated_query.py", line 4, in <module>
    import pandas as pd
ModuleNotFoundError: No module named 'pandas'
[2023-12-31T12:03:31.215-0300] {processor.py:842} WARNING - No viable dags retrieved from /home/felipe/airflow/dags/06_templated_query.py
[2023-12-31T12:03:31.415-0300] {processor.py:183} INFO - Processing /home/felipe/airflow/dags/06_templated_query.py took 0.300 seconds
[2023-12-31T12:06:54.074-0300] {processor.py:161} INFO - Started process (PID=36712) to work on /home/felipe/airflow/dags/06_templated_query.py
[2023-12-31T12:06:54.104-0300] {processor.py:830} INFO - Processing file /home/felipe/airflow/dags/06_templated_query.py for tasks to queue
[2023-12-31T12:06:54.124-0300] {logging_mixin.py:188} INFO - [2023-12-31T12:06:54.115-0300] {dagbag.py:538} INFO - Filling up the DagBag from /home/felipe/airflow/dags/06_templated_query.py
[2023-12-31T12:06:54.205-0300] {logging_mixin.py:188} INFO - [2023-12-31T12:06:54.185-0300] {dagbag.py:348} ERROR - Failed to import: /home/felipe/airflow/dags/06_templated_query.py
Traceback (most recent call last):
  File "/home/felipe/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/felipe/airflow/dags/06_templated_query.py", line 4, in <module>
    import pandas as pd
ModuleNotFoundError: No module named 'pandas'
[2023-12-31T12:06:54.224-0300] {processor.py:842} WARNING - No viable dags retrieved from /home/felipe/airflow/dags/06_templated_query.py
[2023-12-31T12:06:54.754-0300] {processor.py:183} INFO - Processing /home/felipe/airflow/dags/06_templated_query.py took 0.749 seconds
[2023-12-31T12:10:23.714-0300] {processor.py:161} INFO - Started process (PID=37098) to work on /home/felipe/airflow/dags/06_templated_query.py
[2023-12-31T12:10:23.734-0300] {processor.py:830} INFO - Processing file /home/felipe/airflow/dags/06_templated_query.py for tasks to queue
[2023-12-31T12:10:23.764-0300] {logging_mixin.py:188} INFO - [2023-12-31T12:10:23.745-0300] {dagbag.py:538} INFO - Filling up the DagBag from /home/felipe/airflow/dags/06_templated_query.py
[2023-12-31T12:10:23.845-0300] {logging_mixin.py:188} INFO - [2023-12-31T12:10:23.824-0300] {dagbag.py:348} ERROR - Failed to import: /home/felipe/airflow/dags/06_templated_query.py
Traceback (most recent call last):
  File "/home/felipe/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/felipe/airflow/dags/06_templated_query.py", line 4, in <module>
    import pandas as pd
ModuleNotFoundError: No module named 'pandas'
[2023-12-31T12:10:23.855-0300] {processor.py:842} WARNING - No viable dags retrieved from /home/felipe/airflow/dags/06_templated_query.py
[2023-12-31T12:10:25.915-0300] {processor.py:183} INFO - Processing /home/felipe/airflow/dags/06_templated_query.py took 2.270 seconds
[2023-12-31T12:11:44.225-0300] {processor.py:161} INFO - Started process (PID=37199) to work on /home/felipe/airflow/dags/06_templated_query.py
[2023-12-31T12:11:44.244-0300] {processor.py:830} INFO - Processing file /home/felipe/airflow/dags/06_templated_query.py for tasks to queue
[2023-12-31T12:11:44.255-0300] {logging_mixin.py:188} INFO - [2023-12-31T12:11:44.254-0300] {dagbag.py:538} INFO - Filling up the DagBag from /home/felipe/airflow/dags/06_templated_query.py
[2023-12-31T12:11:44.344-0300] {logging_mixin.py:188} INFO - [2023-12-31T12:11:44.314-0300] {dagbag.py:348} ERROR - Failed to import: /home/felipe/airflow/dags/06_templated_query.py
Traceback (most recent call last):
  File "/home/felipe/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/felipe/airflow/dags/06_templated_query.py", line 4, in <module>
    import pandas as pd
ModuleNotFoundError: No module named 'pandas'
[2023-12-31T12:11:44.354-0300] {processor.py:842} WARNING - No viable dags retrieved from /home/felipe/airflow/dags/06_templated_query.py
[2023-12-31T12:11:44.644-0300] {processor.py:183} INFO - Processing /home/felipe/airflow/dags/06_templated_query.py took 0.480 seconds
[2023-12-31T12:12:33.665-0300] {processor.py:161} INFO - Started process (PID=37266) to work on /home/felipe/airflow/dags/06_templated_query.py
[2023-12-31T12:12:33.685-0300] {processor.py:830} INFO - Processing file /home/felipe/airflow/dags/06_templated_query.py for tasks to queue
[2023-12-31T12:12:33.705-0300] {logging_mixin.py:188} INFO - [2023-12-31T12:12:33.704-0300] {dagbag.py:538} INFO - Filling up the DagBag from /home/felipe/airflow/dags/06_templated_query.py
[2023-12-31T12:12:33.794-0300] {logging_mixin.py:188} INFO - [2023-12-31T12:12:33.764-0300] {dagbag.py:348} ERROR - Failed to import: /home/felipe/airflow/dags/06_templated_query.py
Traceback (most recent call last):
  File "/home/felipe/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/felipe/airflow/dags/06_templated_query.py", line 4, in <module>
    import pandas as pd
ModuleNotFoundError: No module named 'pandas'
[2023-12-31T12:12:33.804-0300] {processor.py:842} WARNING - No viable dags retrieved from /home/felipe/airflow/dags/06_templated_query.py
[2023-12-31T12:12:34.114-0300] {processor.py:183} INFO - Processing /home/felipe/airflow/dags/06_templated_query.py took 0.480 seconds
[2023-12-31T12:13:36.484-0300] {processor.py:161} INFO - Started process (PID=37351) to work on /home/felipe/airflow/dags/06_templated_query.py
[2023-12-31T12:13:36.505-0300] {processor.py:830} INFO - Processing file /home/felipe/airflow/dags/06_templated_query.py for tasks to queue
[2023-12-31T12:13:36.524-0300] {logging_mixin.py:188} INFO - [2023-12-31T12:13:36.515-0300] {dagbag.py:538} INFO - Filling up the DagBag from /home/felipe/airflow/dags/06_templated_query.py
[2023-12-31T12:13:36.604-0300] {logging_mixin.py:188} INFO - [2023-12-31T12:13:36.584-0300] {dagbag.py:348} ERROR - Failed to import: /home/felipe/airflow/dags/06_templated_query.py
Traceback (most recent call last):
  File "/home/felipe/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/felipe/airflow/dags/06_templated_query.py", line 4, in <module>
    import pandas as pd
ModuleNotFoundError: No module named 'pandas'
[2023-12-31T12:13:36.614-0300] {processor.py:842} WARNING - No viable dags retrieved from /home/felipe/airflow/dags/06_templated_query.py
[2023-12-31T12:13:36.955-0300] {processor.py:183} INFO - Processing /home/felipe/airflow/dags/06_templated_query.py took 0.541 seconds
[2023-12-31T12:14:44.964-0300] {processor.py:161} INFO - Started process (PID=37468) to work on /home/felipe/airflow/dags/06_templated_query.py
[2023-12-31T12:14:44.975-0300] {processor.py:830} INFO - Processing file /home/felipe/airflow/dags/06_templated_query.py for tasks to queue
[2023-12-31T12:14:45.005-0300] {logging_mixin.py:188} INFO - [2023-12-31T12:14:44.995-0300] {dagbag.py:538} INFO - Filling up the DagBag from /home/felipe/airflow/dags/06_templated_query.py
[2023-12-31T12:14:45.094-0300] {logging_mixin.py:188} INFO - [2023-12-31T12:14:45.055-0300] {dagbag.py:348} ERROR - Failed to import: /home/felipe/airflow/dags/06_templated_query.py
Traceback (most recent call last):
  File "/home/felipe/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/felipe/airflow/dags/06_templated_query.py", line 4, in <module>
    import pandas as pd
ModuleNotFoundError: No module named 'pandas'
[2023-12-31T12:14:45.104-0300] {processor.py:842} WARNING - No viable dags retrieved from /home/felipe/airflow/dags/06_templated_query.py
[2023-12-31T12:14:45.465-0300] {processor.py:183} INFO - Processing /home/felipe/airflow/dags/06_templated_query.py took 0.540 seconds
[2023-12-31T12:15:39.444-0300] {processor.py:161} INFO - Started process (PID=37535) to work on /home/felipe/airflow/dags/06_templated_query.py
[2023-12-31T12:15:39.464-0300] {processor.py:830} INFO - Processing file /home/felipe/airflow/dags/06_templated_query.py for tasks to queue
[2023-12-31T12:15:39.494-0300] {logging_mixin.py:188} INFO - [2023-12-31T12:15:39.484-0300] {dagbag.py:538} INFO - Filling up the DagBag from /home/felipe/airflow/dags/06_templated_query.py
[2023-12-31T12:15:39.675-0300] {logging_mixin.py:188} INFO - [2023-12-31T12:15:39.605-0300] {dagbag.py:348} ERROR - Failed to import: /home/felipe/airflow/dags/06_templated_query.py
Traceback (most recent call last):
  File "/home/felipe/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/felipe/airflow/dags/06_templated_query.py", line 4, in <module>
    import pandas as pd
ModuleNotFoundError: No module named 'pandas'
[2023-12-31T12:15:39.704-0300] {processor.py:842} WARNING - No viable dags retrieved from /home/felipe/airflow/dags/06_templated_query.py
[2023-12-31T12:15:40.224-0300] {processor.py:183} INFO - Processing /home/felipe/airflow/dags/06_templated_query.py took 0.839 seconds
[2023-12-31T12:16:47.804-0300] {processor.py:161} INFO - Started process (PID=37625) to work on /home/felipe/airflow/dags/06_templated_query.py
[2023-12-31T12:16:47.825-0300] {processor.py:830} INFO - Processing file /home/felipe/airflow/dags/06_templated_query.py for tasks to queue
[2023-12-31T12:16:47.865-0300] {logging_mixin.py:188} INFO - [2023-12-31T12:16:47.854-0300] {dagbag.py:538} INFO - Filling up the DagBag from /home/felipe/airflow/dags/06_templated_query.py
[2023-12-31T12:16:47.985-0300] {logging_mixin.py:188} INFO - [2023-12-31T12:16:47.954-0300] {dagbag.py:348} ERROR - Failed to import: /home/felipe/airflow/dags/06_templated_query.py
Traceback (most recent call last):
  File "/home/felipe/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/felipe/airflow/dags/06_templated_query.py", line 4, in <module>
    import pandas as pd
ModuleNotFoundError: No module named 'pandas'
[2023-12-31T12:16:48.004-0300] {processor.py:842} WARNING - No viable dags retrieved from /home/felipe/airflow/dags/06_templated_query.py
[2023-12-31T12:16:48.545-0300] {processor.py:183} INFO - Processing /home/felipe/airflow/dags/06_templated_query.py took 0.830 seconds
[2023-12-31T12:17:39.445-0300] {processor.py:161} INFO - Started process (PID=37697) to work on /home/felipe/airflow/dags/06_templated_query.py
[2023-12-31T12:17:39.464-0300] {processor.py:830} INFO - Processing file /home/felipe/airflow/dags/06_templated_query.py for tasks to queue
[2023-12-31T12:17:39.484-0300] {logging_mixin.py:188} INFO - [2023-12-31T12:17:39.474-0300] {dagbag.py:538} INFO - Filling up the DagBag from /home/felipe/airflow/dags/06_templated_query.py
[2023-12-31T12:17:39.654-0300] {logging_mixin.py:188} INFO - [2023-12-31T12:17:39.555-0300] {dagbag.py:348} ERROR - Failed to import: /home/felipe/airflow/dags/06_templated_query.py
Traceback (most recent call last):
  File "/home/felipe/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/felipe/airflow/dags/06_templated_query.py", line 4, in <module>
    import pandas as pd
ModuleNotFoundError: No module named 'pandas'
[2023-12-31T12:17:39.675-0300] {processor.py:842} WARNING - No viable dags retrieved from /home/felipe/airflow/dags/06_templated_query.py
[2023-12-31T12:17:40.084-0300] {processor.py:183} INFO - Processing /home/felipe/airflow/dags/06_templated_query.py took 0.680 seconds
[2023-12-31T12:18:31.664-0300] {processor.py:161} INFO - Started process (PID=37762) to work on /home/felipe/airflow/dags/06_templated_query.py
[2023-12-31T12:18:31.694-0300] {processor.py:830} INFO - Processing file /home/felipe/airflow/dags/06_templated_query.py for tasks to queue
[2023-12-31T12:18:31.714-0300] {logging_mixin.py:188} INFO - [2023-12-31T12:18:31.704-0300] {dagbag.py:538} INFO - Filling up the DagBag from /home/felipe/airflow/dags/06_templated_query.py
[2023-12-31T12:18:31.784-0300] {logging_mixin.py:188} INFO - [2023-12-31T12:18:31.764-0300] {dagbag.py:348} ERROR - Failed to import: /home/felipe/airflow/dags/06_templated_query.py
Traceback (most recent call last):
  File "/home/felipe/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/felipe/airflow/dags/06_templated_query.py", line 4, in <module>
    import pandas as pd
ModuleNotFoundError: No module named 'pandas'
[2023-12-31T12:18:31.794-0300] {processor.py:842} WARNING - No viable dags retrieved from /home/felipe/airflow/dags/06_templated_query.py
[2023-12-31T12:18:32.275-0300] {processor.py:183} INFO - Processing /home/felipe/airflow/dags/06_templated_query.py took 0.680 seconds
[2023-12-31T12:26:16.140-0300] {processor.py:161} INFO - Started process (PID=37980) to work on /home/felipe/airflow/dags/06_templated_query.py
[2023-12-31T12:26:16.161-0300] {processor.py:830} INFO - Processing file /home/felipe/airflow/dags/06_templated_query.py for tasks to queue
[2023-12-31T12:26:16.190-0300] {logging_mixin.py:188} INFO - [2023-12-31T12:26:16.180-0300] {dagbag.py:538} INFO - Filling up the DagBag from /home/felipe/airflow/dags/06_templated_query.py
[2023-12-31T12:26:16.280-0300] {logging_mixin.py:188} INFO - [2023-12-31T12:26:16.250-0300] {dagbag.py:348} ERROR - Failed to import: /home/felipe/airflow/dags/06_templated_query.py
Traceback (most recent call last):
  File "/home/felipe/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/felipe/airflow/dags/06_templated_query.py", line 4, in <module>
    import pandas as pd
ModuleNotFoundError: No module named 'pandas'
[2023-12-31T12:26:16.291-0300] {processor.py:842} WARNING - No viable dags retrieved from /home/felipe/airflow/dags/06_templated_query.py
[2023-12-31T12:26:16.741-0300] {processor.py:183} INFO - Processing /home/felipe/airflow/dags/06_templated_query.py took 0.670 seconds
[2023-12-31T12:27:26.190-0300] {processor.py:161} INFO - Started process (PID=38053) to work on /home/felipe/airflow/dags/06_templated_query.py
[2023-12-31T12:27:26.211-0300] {processor.py:830} INFO - Processing file /home/felipe/airflow/dags/06_templated_query.py for tasks to queue
[2023-12-31T12:27:26.231-0300] {logging_mixin.py:188} INFO - [2023-12-31T12:27:26.230-0300] {dagbag.py:538} INFO - Filling up the DagBag from /home/felipe/airflow/dags/06_templated_query.py
[2023-12-31T12:27:26.311-0300] {logging_mixin.py:188} INFO - [2023-12-31T12:27:26.290-0300] {dagbag.py:348} ERROR - Failed to import: /home/felipe/airflow/dags/06_templated_query.py
Traceback (most recent call last):
  File "/home/felipe/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/felipe/airflow/dags/06_templated_query.py", line 4, in <module>
    import pandas as pd
ModuleNotFoundError: No module named 'pandas'
[2023-12-31T12:27:26.321-0300] {processor.py:842} WARNING - No viable dags retrieved from /home/felipe/airflow/dags/06_templated_query.py
[2023-12-31T12:27:26.750-0300] {processor.py:183} INFO - Processing /home/felipe/airflow/dags/06_templated_query.py took 0.611 seconds
[2023-12-31T12:28:40.821-0300] {processor.py:161} INFO - Started process (PID=38109) to work on /home/felipe/airflow/dags/06_templated_query.py
[2023-12-31T12:28:40.841-0300] {processor.py:830} INFO - Processing file /home/felipe/airflow/dags/06_templated_query.py for tasks to queue
[2023-12-31T12:28:40.861-0300] {logging_mixin.py:188} INFO - [2023-12-31T12:28:40.851-0300] {dagbag.py:538} INFO - Filling up the DagBag from /home/felipe/airflow/dags/06_templated_query.py
[2023-12-31T12:28:40.970-0300] {logging_mixin.py:188} INFO - [2023-12-31T12:28:40.920-0300] {dagbag.py:348} ERROR - Failed to import: /home/felipe/airflow/dags/06_templated_query.py
Traceback (most recent call last):
  File "/home/felipe/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/felipe/airflow/dags/06_templated_query.py", line 4, in <module>
    import pandas as pd
ModuleNotFoundError: No module named 'pandas'
[2023-12-31T12:28:40.981-0300] {processor.py:842} WARNING - No viable dags retrieved from /home/felipe/airflow/dags/06_templated_query.py
[2023-12-31T12:28:41.441-0300] {processor.py:183} INFO - Processing /home/felipe/airflow/dags/06_templated_query.py took 0.670 seconds
[2023-12-31T12:29:53.721-0300] {processor.py:161} INFO - Started process (PID=38160) to work on /home/felipe/airflow/dags/06_templated_query.py
[2023-12-31T12:29:53.741-0300] {processor.py:830} INFO - Processing file /home/felipe/airflow/dags/06_templated_query.py for tasks to queue
[2023-12-31T12:29:53.771-0300] {logging_mixin.py:188} INFO - [2023-12-31T12:29:53.761-0300] {dagbag.py:538} INFO - Filling up the DagBag from /home/felipe/airflow/dags/06_templated_query.py
[2023-12-31T12:29:53.870-0300] {logging_mixin.py:188} INFO - [2023-12-31T12:29:53.841-0300] {dagbag.py:348} ERROR - Failed to import: /home/felipe/airflow/dags/06_templated_query.py
Traceback (most recent call last):
  File "/home/felipe/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/felipe/airflow/dags/06_templated_query.py", line 4, in <module>
    import pandas as pd
ModuleNotFoundError: No module named 'pandas'
[2023-12-31T12:29:53.881-0300] {processor.py:842} WARNING - No viable dags retrieved from /home/felipe/airflow/dags/06_templated_query.py
[2023-12-31T12:29:54.391-0300] {processor.py:183} INFO - Processing /home/felipe/airflow/dags/06_templated_query.py took 0.750 seconds
[2023-12-31T12:31:09.151-0300] {processor.py:161} INFO - Started process (PID=38241) to work on /home/felipe/airflow/dags/06_templated_query.py
[2023-12-31T12:31:09.171-0300] {processor.py:830} INFO - Processing file /home/felipe/airflow/dags/06_templated_query.py for tasks to queue
[2023-12-31T12:31:09.191-0300] {logging_mixin.py:188} INFO - [2023-12-31T12:31:09.181-0300] {dagbag.py:538} INFO - Filling up the DagBag from /home/felipe/airflow/dags/06_templated_query.py
[2023-12-31T12:31:09.291-0300] {logging_mixin.py:188} INFO - [2023-12-31T12:31:09.250-0300] {dagbag.py:348} ERROR - Failed to import: /home/felipe/airflow/dags/06_templated_query.py
Traceback (most recent call last):
  File "/home/felipe/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/felipe/airflow/dags/06_templated_query.py", line 4, in <module>
    import pandas as pd
ModuleNotFoundError: No module named 'pandas'
[2023-12-31T12:31:09.301-0300] {processor.py:842} WARNING - No viable dags retrieved from /home/felipe/airflow/dags/06_templated_query.py
[2023-12-31T12:31:09.881-0300] {processor.py:183} INFO - Processing /home/felipe/airflow/dags/06_templated_query.py took 0.810 seconds
[2023-12-31T12:32:30.370-0300] {processor.py:161} INFO - Started process (PID=38295) to work on /home/felipe/airflow/dags/06_templated_query.py
[2023-12-31T12:32:30.391-0300] {processor.py:830} INFO - Processing file /home/felipe/airflow/dags/06_templated_query.py for tasks to queue
[2023-12-31T12:32:30.421-0300] {logging_mixin.py:188} INFO - [2023-12-31T12:32:30.411-0300] {dagbag.py:538} INFO - Filling up the DagBag from /home/felipe/airflow/dags/06_templated_query.py
[2023-12-31T12:32:30.500-0300] {logging_mixin.py:188} INFO - [2023-12-31T12:32:30.471-0300] {dagbag.py:348} ERROR - Failed to import: /home/felipe/airflow/dags/06_templated_query.py
Traceback (most recent call last):
  File "/home/felipe/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/felipe/airflow/dags/06_templated_query.py", line 4, in <module>
    import pandas as pd
ModuleNotFoundError: No module named 'pandas'
[2023-12-31T12:32:30.510-0300] {processor.py:842} WARNING - No viable dags retrieved from /home/felipe/airflow/dags/06_templated_query.py
[2023-12-31T12:32:30.990-0300] {processor.py:183} INFO - Processing /home/felipe/airflow/dags/06_templated_query.py took 0.680 seconds
[2023-12-31T12:34:01.260-0300] {processor.py:161} INFO - Started process (PID=38350) to work on /home/felipe/airflow/dags/06_templated_query.py
[2023-12-31T12:34:01.300-0300] {processor.py:830} INFO - Processing file /home/felipe/airflow/dags/06_templated_query.py for tasks to queue
[2023-12-31T12:34:01.330-0300] {logging_mixin.py:188} INFO - [2023-12-31T12:34:01.311-0300] {dagbag.py:538} INFO - Filling up the DagBag from /home/felipe/airflow/dags/06_templated_query.py
[2023-12-31T12:34:01.460-0300] {logging_mixin.py:188} INFO - [2023-12-31T12:34:01.401-0300] {dagbag.py:348} ERROR - Failed to import: /home/felipe/airflow/dags/06_templated_query.py
Traceback (most recent call last):
  File "/home/felipe/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/felipe/airflow/dags/06_templated_query.py", line 4, in <module>
    import pandas as pd
ModuleNotFoundError: No module named 'pandas'
[2023-12-31T12:34:01.471-0300] {processor.py:842} WARNING - No viable dags retrieved from /home/felipe/airflow/dags/06_templated_query.py
[2023-12-31T12:34:02.041-0300] {processor.py:183} INFO - Processing /home/felipe/airflow/dags/06_templated_query.py took 0.890 seconds
[2023-12-31T12:35:39.690-0300] {processor.py:161} INFO - Started process (PID=38432) to work on /home/felipe/airflow/dags/06_templated_query.py
[2023-12-31T12:35:39.720-0300] {processor.py:830} INFO - Processing file /home/felipe/airflow/dags/06_templated_query.py for tasks to queue
[2023-12-31T12:35:39.750-0300] {logging_mixin.py:188} INFO - [2023-12-31T12:35:39.740-0300] {dagbag.py:538} INFO - Filling up the DagBag from /home/felipe/airflow/dags/06_templated_query.py
[2023-12-31T12:35:39.860-0300] {logging_mixin.py:188} INFO - [2023-12-31T12:35:39.830-0300] {dagbag.py:348} ERROR - Failed to import: /home/felipe/airflow/dags/06_templated_query.py
Traceback (most recent call last):
  File "/home/felipe/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/felipe/airflow/dags/06_templated_query.py", line 4, in <module>
    import pandas as pd
ModuleNotFoundError: No module named 'pandas'
[2023-12-31T12:35:39.870-0300] {processor.py:842} WARNING - No viable dags retrieved from /home/felipe/airflow/dags/06_templated_query.py
[2023-12-31T12:35:40.480-0300] {processor.py:183} INFO - Processing /home/felipe/airflow/dags/06_templated_query.py took 0.880 seconds
[2023-12-31T12:37:45.690-0300] {processor.py:161} INFO - Started process (PID=38503) to work on /home/felipe/airflow/dags/06_templated_query.py
[2023-12-31T12:37:45.730-0300] {processor.py:830} INFO - Processing file /home/felipe/airflow/dags/06_templated_query.py for tasks to queue
[2023-12-31T12:37:45.780-0300] {logging_mixin.py:188} INFO - [2023-12-31T12:37:45.760-0300] {dagbag.py:538} INFO - Filling up the DagBag from /home/felipe/airflow/dags/06_templated_query.py
[2023-12-31T12:37:45.940-0300] {logging_mixin.py:188} INFO - [2023-12-31T12:37:45.900-0300] {dagbag.py:348} ERROR - Failed to import: /home/felipe/airflow/dags/06_templated_query.py
Traceback (most recent call last):
  File "/home/felipe/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/felipe/airflow/dags/06_templated_query.py", line 4, in <module>
    import pandas as pd
ModuleNotFoundError: No module named 'pandas'
[2023-12-31T12:37:45.960-0300] {processor.py:842} WARNING - No viable dags retrieved from /home/felipe/airflow/dags/06_templated_query.py
[2023-12-31T12:37:46.901-0300] {processor.py:183} INFO - Processing /home/felipe/airflow/dags/06_templated_query.py took 1.340 seconds
[2023-12-31T12:49:05.678-0300] {processor.py:161} INFO - Started process (PID=38815) to work on /home/felipe/airflow/dags/06_templated_query.py
[2023-12-31T12:49:05.738-0300] {processor.py:830} INFO - Processing file /home/felipe/airflow/dags/06_templated_query.py for tasks to queue
[2023-12-31T12:49:05.827-0300] {logging_mixin.py:188} INFO - [2023-12-31T12:49:05.788-0300] {dagbag.py:538} INFO - Filling up the DagBag from /home/felipe/airflow/dags/06_templated_query.py
[2023-12-31T12:49:06.097-0300] {logging_mixin.py:188} INFO - [2023-12-31T12:49:06.027-0300] {dagbag.py:348} ERROR - Failed to import: /home/felipe/airflow/dags/06_templated_query.py
Traceback (most recent call last):
  File "/home/felipe/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/felipe/airflow/dags/06_templated_query.py", line 4, in <module>
    import pandas as pd
ModuleNotFoundError: No module named 'pandas'
[2023-12-31T12:49:06.127-0300] {processor.py:842} WARNING - No viable dags retrieved from /home/felipe/airflow/dags/06_templated_query.py
[2023-12-31T12:49:07.767-0300] {processor.py:183} INFO - Processing /home/felipe/airflow/dags/06_templated_query.py took 2.280 seconds
