[2023-12-31T09:36:39.659-0300] {processor.py:161} INFO - Started process (PID=31956) to work on /home/felipe/airflow/dags/07_templated_query_ds.py
[2023-12-31T09:36:39.661-0300] {processor.py:830} INFO - Processing file /home/felipe/airflow/dags/07_templated_query_ds.py for tasks to queue
[2023-12-31T09:36:39.667-0300] {logging_mixin.py:188} INFO - [2023-12-31T09:36:39.667-0300] {dagbag.py:538} INFO - Filling up the DagBag from /home/felipe/airflow/dags/07_templated_query_ds.py
[2023-12-31T09:36:39.677-0300] {logging_mixin.py:188} INFO - [2023-12-31T09:36:39.670-0300] {dagbag.py:348} ERROR - Failed to import: /home/felipe/airflow/dags/07_templated_query_ds.py
Traceback (most recent call last):
  File "/home/felipe/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/felipe/airflow/dags/07_templated_query_ds.py", line 4, in <module>
    import pandas as pd
ModuleNotFoundError: No module named 'pandas'
[2023-12-31T09:36:39.677-0300] {processor.py:842} WARNING - No viable dags retrieved from /home/felipe/airflow/dags/07_templated_query_ds.py
[2023-12-31T09:36:39.759-0300] {processor.py:183} INFO - Processing /home/felipe/airflow/dags/07_templated_query_ds.py took 0.108 seconds
[2023-12-31T09:38:30.979-0300] {processor.py:161} INFO - Started process (PID=32171) to work on /home/felipe/airflow/dags/07_templated_query_ds.py
[2023-12-31T09:38:30.987-0300] {processor.py:830} INFO - Processing file /home/felipe/airflow/dags/07_templated_query_ds.py for tasks to queue
[2023-12-31T09:38:30.990-0300] {logging_mixin.py:188} INFO - [2023-12-31T09:38:30.989-0300] {dagbag.py:538} INFO - Filling up the DagBag from /home/felipe/airflow/dags/07_templated_query_ds.py
[2023-12-31T09:38:31.017-0300] {logging_mixin.py:188} INFO - [2023-12-31T09:38:31.008-0300] {dagbag.py:348} ERROR - Failed to import: /home/felipe/airflow/dags/07_templated_query_ds.py
Traceback (most recent call last):
  File "/home/felipe/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/felipe/airflow/dags/07_templated_query_ds.py", line 4, in <module>
    import pandas as pd
ModuleNotFoundError: No module named 'pandas'
[2023-12-31T09:38:31.019-0300] {processor.py:842} WARNING - No viable dags retrieved from /home/felipe/airflow/dags/07_templated_query_ds.py
[2023-12-31T09:38:31.187-0300] {processor.py:183} INFO - Processing /home/felipe/airflow/dags/07_templated_query_ds.py took 0.220 seconds
[2023-12-31T09:51:59.106-0300] {processor.py:161} INFO - Started process (PID=32765) to work on /home/felipe/airflow/dags/07_templated_query_ds.py
[2023-12-31T09:51:59.109-0300] {processor.py:830} INFO - Processing file /home/felipe/airflow/dags/07_templated_query_ds.py for tasks to queue
[2023-12-31T09:51:59.117-0300] {logging_mixin.py:188} INFO - [2023-12-31T09:51:59.116-0300] {dagbag.py:538} INFO - Filling up the DagBag from /home/felipe/airflow/dags/07_templated_query_ds.py
[2023-12-31T09:51:59.130-0300] {logging_mixin.py:188} INFO - [2023-12-31T09:51:59.128-0300] {dagbag.py:348} ERROR - Failed to import: /home/felipe/airflow/dags/07_templated_query_ds.py
Traceback (most recent call last):
  File "/home/felipe/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/felipe/airflow/dags/07_templated_query_ds.py", line 4, in <module>
    import pandas as pd
ModuleNotFoundError: No module named 'pandas'
[2023-12-31T09:51:59.136-0300] {processor.py:842} WARNING - No viable dags retrieved from /home/felipe/airflow/dags/07_templated_query_ds.py
[2023-12-31T09:51:59.260-0300] {processor.py:183} INFO - Processing /home/felipe/airflow/dags/07_templated_query_ds.py took 0.172 seconds
[2023-12-31T09:55:18.099-0300] {processor.py:161} INFO - Started process (PID=32927) to work on /home/felipe/airflow/dags/07_templated_query_ds.py
[2023-12-31T09:55:18.108-0300] {processor.py:830} INFO - Processing file /home/felipe/airflow/dags/07_templated_query_ds.py for tasks to queue
[2023-12-31T09:55:18.110-0300] {logging_mixin.py:188} INFO - [2023-12-31T09:55:18.109-0300] {dagbag.py:538} INFO - Filling up the DagBag from /home/felipe/airflow/dags/07_templated_query_ds.py
[2023-12-31T09:55:18.129-0300] {logging_mixin.py:188} INFO - [2023-12-31T09:55:18.120-0300] {dagbag.py:348} ERROR - Failed to import: /home/felipe/airflow/dags/07_templated_query_ds.py
Traceback (most recent call last):
  File "/home/felipe/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/felipe/airflow/dags/07_templated_query_ds.py", line 4, in <module>
    import pandas as pd
ModuleNotFoundError: No module named 'pandas'
[2023-12-31T09:55:18.130-0300] {processor.py:842} WARNING - No viable dags retrieved from /home/felipe/airflow/dags/07_templated_query_ds.py
[2023-12-31T09:55:18.229-0300] {processor.py:183} INFO - Processing /home/felipe/airflow/dags/07_templated_query_ds.py took 0.149 seconds
[2023-12-31T09:59:54.598-0300] {processor.py:161} INFO - Started process (PID=33141) to work on /home/felipe/airflow/dags/07_templated_query_ds.py
[2023-12-31T09:59:54.607-0300] {processor.py:830} INFO - Processing file /home/felipe/airflow/dags/07_templated_query_ds.py for tasks to queue
[2023-12-31T09:59:54.609-0300] {logging_mixin.py:188} INFO - [2023-12-31T09:59:54.608-0300] {dagbag.py:538} INFO - Filling up the DagBag from /home/felipe/airflow/dags/07_templated_query_ds.py
[2023-12-31T09:59:54.639-0300] {logging_mixin.py:188} INFO - [2023-12-31T09:59:54.630-0300] {dagbag.py:348} ERROR - Failed to import: /home/felipe/airflow/dags/07_templated_query_ds.py
Traceback (most recent call last):
  File "/home/felipe/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/felipe/airflow/dags/07_templated_query_ds.py", line 4, in <module>
    import pandas as pd
ModuleNotFoundError: No module named 'pandas'
[2023-12-31T09:59:54.647-0300] {processor.py:842} WARNING - No viable dags retrieved from /home/felipe/airflow/dags/07_templated_query_ds.py
[2023-12-31T09:59:54.799-0300] {processor.py:183} INFO - Processing /home/felipe/airflow/dags/07_templated_query_ds.py took 0.213 seconds
[2023-12-31T10:01:20.709-0300] {processor.py:161} INFO - Started process (PID=33272) to work on /home/felipe/airflow/dags/07_templated_query_ds.py
[2023-12-31T10:01:20.718-0300] {processor.py:830} INFO - Processing file /home/felipe/airflow/dags/07_templated_query_ds.py for tasks to queue
[2023-12-31T10:01:20.727-0300] {logging_mixin.py:188} INFO - [2023-12-31T10:01:20.719-0300] {dagbag.py:538} INFO - Filling up the DagBag from /home/felipe/airflow/dags/07_templated_query_ds.py
[2023-12-31T10:01:20.738-0300] {logging_mixin.py:188} INFO - [2023-12-31T10:01:20.737-0300] {dagbag.py:348} ERROR - Failed to import: /home/felipe/airflow/dags/07_templated_query_ds.py
Traceback (most recent call last):
  File "/home/felipe/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/felipe/airflow/dags/07_templated_query_ds.py", line 4, in <module>
    import pandas as pd
ModuleNotFoundError: No module named 'pandas'
[2023-12-31T10:01:20.739-0300] {processor.py:842} WARNING - No viable dags retrieved from /home/felipe/airflow/dags/07_templated_query_ds.py
[2023-12-31T10:01:20.838-0300] {processor.py:183} INFO - Processing /home/felipe/airflow/dags/07_templated_query_ds.py took 0.139 seconds
[2023-12-31T10:02:30.169-0300] {processor.py:161} INFO - Started process (PID=33339) to work on /home/felipe/airflow/dags/07_templated_query_ds.py
[2023-12-31T10:02:30.177-0300] {processor.py:830} INFO - Processing file /home/felipe/airflow/dags/07_templated_query_ds.py for tasks to queue
[2023-12-31T10:02:30.178-0300] {logging_mixin.py:188} INFO - [2023-12-31T10:02:30.178-0300] {dagbag.py:538} INFO - Filling up the DagBag from /home/felipe/airflow/dags/07_templated_query_ds.py
[2023-12-31T10:02:30.197-0300] {logging_mixin.py:188} INFO - [2023-12-31T10:02:30.189-0300] {dagbag.py:348} ERROR - Failed to import: /home/felipe/airflow/dags/07_templated_query_ds.py
Traceback (most recent call last):
  File "/home/felipe/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/felipe/airflow/dags/07_templated_query_ds.py", line 4, in <module>
    import pandas as pd
ModuleNotFoundError: No module named 'pandas'
[2023-12-31T10:02:30.198-0300] {processor.py:842} WARNING - No viable dags retrieved from /home/felipe/airflow/dags/07_templated_query_ds.py
[2023-12-31T10:02:30.298-0300] {processor.py:183} INFO - Processing /home/felipe/airflow/dags/07_templated_query_ds.py took 0.140 seconds
[2023-12-31T10:03:34.757-0300] {processor.py:161} INFO - Started process (PID=33411) to work on /home/felipe/airflow/dags/07_templated_query_ds.py
[2023-12-31T10:03:34.759-0300] {processor.py:830} INFO - Processing file /home/felipe/airflow/dags/07_templated_query_ds.py for tasks to queue
[2023-12-31T10:03:34.767-0300] {logging_mixin.py:188} INFO - [2023-12-31T10:03:34.766-0300] {dagbag.py:538} INFO - Filling up the DagBag from /home/felipe/airflow/dags/07_templated_query_ds.py
[2023-12-31T10:03:34.778-0300] {logging_mixin.py:188} INFO - [2023-12-31T10:03:34.777-0300] {dagbag.py:348} ERROR - Failed to import: /home/felipe/airflow/dags/07_templated_query_ds.py
Traceback (most recent call last):
  File "/home/felipe/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/felipe/airflow/dags/07_templated_query_ds.py", line 4, in <module>
    import pandas as pd
ModuleNotFoundError: No module named 'pandas'
[2023-12-31T10:03:34.779-0300] {processor.py:842} WARNING - No viable dags retrieved from /home/felipe/airflow/dags/07_templated_query_ds.py
[2023-12-31T10:03:34.888-0300] {processor.py:183} INFO - Processing /home/felipe/airflow/dags/07_templated_query_ds.py took 0.141 seconds
[2023-12-31T10:04:46.296-0300] {processor.py:161} INFO - Started process (PID=33491) to work on /home/felipe/airflow/dags/07_templated_query_ds.py
[2023-12-31T10:04:46.298-0300] {processor.py:830} INFO - Processing file /home/felipe/airflow/dags/07_templated_query_ds.py for tasks to queue
[2023-12-31T10:04:46.306-0300] {logging_mixin.py:188} INFO - [2023-12-31T10:04:46.299-0300] {dagbag.py:538} INFO - Filling up the DagBag from /home/felipe/airflow/dags/07_templated_query_ds.py
[2023-12-31T10:04:46.318-0300] {logging_mixin.py:188} INFO - [2023-12-31T10:04:46.317-0300] {dagbag.py:348} ERROR - Failed to import: /home/felipe/airflow/dags/07_templated_query_ds.py
Traceback (most recent call last):
  File "/home/felipe/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/felipe/airflow/dags/07_templated_query_ds.py", line 4, in <module>
    import pandas as pd
ModuleNotFoundError: No module named 'pandas'
[2023-12-31T10:04:46.319-0300] {processor.py:842} WARNING - No viable dags retrieved from /home/felipe/airflow/dags/07_templated_query_ds.py
[2023-12-31T10:04:46.420-0300] {processor.py:183} INFO - Processing /home/felipe/airflow/dags/07_templated_query_ds.py took 0.141 seconds
[2023-12-31T10:05:57.599-0300] {processor.py:161} INFO - Started process (PID=33577) to work on /home/felipe/airflow/dags/07_templated_query_ds.py
[2023-12-31T10:05:57.608-0300] {processor.py:830} INFO - Processing file /home/felipe/airflow/dags/07_templated_query_ds.py for tasks to queue
[2023-12-31T10:05:57.618-0300] {logging_mixin.py:188} INFO - [2023-12-31T10:05:57.617-0300] {dagbag.py:538} INFO - Filling up the DagBag from /home/felipe/airflow/dags/07_templated_query_ds.py
[2023-12-31T10:05:57.638-0300] {logging_mixin.py:188} INFO - [2023-12-31T10:05:57.629-0300] {dagbag.py:348} ERROR - Failed to import: /home/felipe/airflow/dags/07_templated_query_ds.py
Traceback (most recent call last):
  File "/home/felipe/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/felipe/airflow/dags/07_templated_query_ds.py", line 4, in <module>
    import pandas as pd
ModuleNotFoundError: No module named 'pandas'
[2023-12-31T10:05:57.638-0300] {processor.py:842} WARNING - No viable dags retrieved from /home/felipe/airflow/dags/07_templated_query_ds.py
[2023-12-31T10:05:57.759-0300] {processor.py:183} INFO - Processing /home/felipe/airflow/dags/07_templated_query_ds.py took 0.180 seconds
[2023-12-31T10:07:08.587-0300] {processor.py:161} INFO - Started process (PID=33686) to work on /home/felipe/airflow/dags/07_templated_query_ds.py
[2023-12-31T10:07:08.596-0300] {processor.py:830} INFO - Processing file /home/felipe/airflow/dags/07_templated_query_ds.py for tasks to queue
[2023-12-31T10:07:08.598-0300] {logging_mixin.py:188} INFO - [2023-12-31T10:07:08.597-0300] {dagbag.py:538} INFO - Filling up the DagBag from /home/felipe/airflow/dags/07_templated_query_ds.py
[2023-12-31T10:07:08.616-0300] {logging_mixin.py:188} INFO - [2023-12-31T10:07:08.608-0300] {dagbag.py:348} ERROR - Failed to import: /home/felipe/airflow/dags/07_templated_query_ds.py
Traceback (most recent call last):
  File "/home/felipe/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/felipe/airflow/dags/07_templated_query_ds.py", line 4, in <module>
    import pandas as pd
ModuleNotFoundError: No module named 'pandas'
[2023-12-31T10:07:08.617-0300] {processor.py:842} WARNING - No viable dags retrieved from /home/felipe/airflow/dags/07_templated_query_ds.py
[2023-12-31T10:07:08.717-0300] {processor.py:183} INFO - Processing /home/felipe/airflow/dags/07_templated_query_ds.py took 0.141 seconds
[2023-12-31T10:08:21.348-0300] {processor.py:161} INFO - Started process (PID=33770) to work on /home/felipe/airflow/dags/07_templated_query_ds.py
[2023-12-31T10:08:21.357-0300] {processor.py:830} INFO - Processing file /home/felipe/airflow/dags/07_templated_query_ds.py for tasks to queue
[2023-12-31T10:08:21.359-0300] {logging_mixin.py:188} INFO - [2023-12-31T10:08:21.358-0300] {dagbag.py:538} INFO - Filling up the DagBag from /home/felipe/airflow/dags/07_templated_query_ds.py
[2023-12-31T10:08:21.377-0300] {logging_mixin.py:188} INFO - [2023-12-31T10:08:21.369-0300] {dagbag.py:348} ERROR - Failed to import: /home/felipe/airflow/dags/07_templated_query_ds.py
Traceback (most recent call last):
  File "/home/felipe/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/felipe/airflow/dags/07_templated_query_ds.py", line 4, in <module>
    import pandas as pd
ModuleNotFoundError: No module named 'pandas'
[2023-12-31T10:08:21.378-0300] {processor.py:842} WARNING - No viable dags retrieved from /home/felipe/airflow/dags/07_templated_query_ds.py
[2023-12-31T10:08:21.486-0300] {processor.py:183} INFO - Processing /home/felipe/airflow/dags/07_templated_query_ds.py took 0.142 seconds
[2023-12-31T11:28:52.305-0300] {processor.py:161} INFO - Started process (PID=33956) to work on /home/felipe/airflow/dags/07_templated_query_ds.py
[2023-12-31T11:28:52.317-0300] {processor.py:830} INFO - Processing file /home/felipe/airflow/dags/07_templated_query_ds.py for tasks to queue
[2023-12-31T11:28:52.336-0300] {logging_mixin.py:188} INFO - [2023-12-31T11:28:52.335-0300] {dagbag.py:538} INFO - Filling up the DagBag from /home/felipe/airflow/dags/07_templated_query_ds.py
[2023-12-31T11:28:52.367-0300] {logging_mixin.py:188} INFO - [2023-12-31T11:28:52.357-0300] {dagbag.py:348} ERROR - Failed to import: /home/felipe/airflow/dags/07_templated_query_ds.py
Traceback (most recent call last):
  File "/home/felipe/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/felipe/airflow/dags/07_templated_query_ds.py", line 4, in <module>
    import pandas as pd
ModuleNotFoundError: No module named 'pandas'
[2023-12-31T11:28:52.375-0300] {processor.py:842} WARNING - No viable dags retrieved from /home/felipe/airflow/dags/07_templated_query_ds.py
[2023-12-31T11:28:52.585-0300] {processor.py:183} INFO - Processing /home/felipe/airflow/dags/07_templated_query_ds.py took 0.308 seconds
[2023-12-31T11:30:47.334-0300] {processor.py:161} INFO - Started process (PID=34232) to work on /home/felipe/airflow/dags/07_templated_query_ds.py
[2023-12-31T11:30:47.337-0300] {processor.py:830} INFO - Processing file /home/felipe/airflow/dags/07_templated_query_ds.py for tasks to queue
[2023-12-31T11:30:47.345-0300] {logging_mixin.py:188} INFO - [2023-12-31T11:30:47.345-0300] {dagbag.py:538} INFO - Filling up the DagBag from /home/felipe/airflow/dags/07_templated_query_ds.py
[2023-12-31T11:30:47.364-0300] {logging_mixin.py:188} INFO - [2023-12-31T11:30:47.356-0300] {dagbag.py:348} ERROR - Failed to import: /home/felipe/airflow/dags/07_templated_query_ds.py
Traceback (most recent call last):
  File "/home/felipe/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/felipe/airflow/dags/07_templated_query_ds.py", line 4, in <module>
    import pandas as pd
ModuleNotFoundError: No module named 'pandas'
[2023-12-31T11:30:47.365-0300] {processor.py:842} WARNING - No viable dags retrieved from /home/felipe/airflow/dags/07_templated_query_ds.py
[2023-12-31T11:30:47.526-0300] {processor.py:183} INFO - Processing /home/felipe/airflow/dags/07_templated_query_ds.py took 0.210 seconds
[2023-12-31T11:32:17.824-0300] {processor.py:161} INFO - Started process (PID=34334) to work on /home/felipe/airflow/dags/07_templated_query_ds.py
[2023-12-31T11:32:17.826-0300] {processor.py:830} INFO - Processing file /home/felipe/airflow/dags/07_templated_query_ds.py for tasks to queue
[2023-12-31T11:32:17.834-0300] {logging_mixin.py:188} INFO - [2023-12-31T11:32:17.834-0300] {dagbag.py:538} INFO - Filling up the DagBag from /home/felipe/airflow/dags/07_templated_query_ds.py
[2023-12-31T11:32:17.846-0300] {logging_mixin.py:188} INFO - [2023-12-31T11:32:17.845-0300] {dagbag.py:348} ERROR - Failed to import: /home/felipe/airflow/dags/07_templated_query_ds.py
Traceback (most recent call last):
  File "/home/felipe/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/felipe/airflow/dags/07_templated_query_ds.py", line 4, in <module>
    import pandas as pd
ModuleNotFoundError: No module named 'pandas'
[2023-12-31T11:32:17.854-0300] {processor.py:842} WARNING - No viable dags retrieved from /home/felipe/airflow/dags/07_templated_query_ds.py
[2023-12-31T11:32:17.965-0300] {processor.py:183} INFO - Processing /home/felipe/airflow/dags/07_templated_query_ds.py took 0.168 seconds
[2023-12-31T11:33:48.426-0300] {processor.py:161} INFO - Started process (PID=34436) to work on /home/felipe/airflow/dags/07_templated_query_ds.py
[2023-12-31T11:33:48.435-0300] {processor.py:830} INFO - Processing file /home/felipe/airflow/dags/07_templated_query_ds.py for tasks to queue
[2023-12-31T11:33:48.444-0300] {logging_mixin.py:188} INFO - [2023-12-31T11:33:48.436-0300] {dagbag.py:538} INFO - Filling up the DagBag from /home/felipe/airflow/dags/07_templated_query_ds.py
[2023-12-31T11:33:48.464-0300] {logging_mixin.py:188} INFO - [2023-12-31T11:33:48.455-0300] {dagbag.py:348} ERROR - Failed to import: /home/felipe/airflow/dags/07_templated_query_ds.py
Traceback (most recent call last):
  File "/home/felipe/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/felipe/airflow/dags/07_templated_query_ds.py", line 4, in <module>
    import pandas as pd
ModuleNotFoundError: No module named 'pandas'
[2023-12-31T11:33:48.465-0300] {processor.py:842} WARNING - No viable dags retrieved from /home/felipe/airflow/dags/07_templated_query_ds.py
[2023-12-31T11:33:48.614-0300] {processor.py:183} INFO - Processing /home/felipe/airflow/dags/07_templated_query_ds.py took 0.208 seconds
[2023-12-31T11:35:11.144-0300] {processor.py:161} INFO - Started process (PID=34560) to work on /home/felipe/airflow/dags/07_templated_query_ds.py
[2023-12-31T11:35:11.146-0300] {processor.py:830} INFO - Processing file /home/felipe/airflow/dags/07_templated_query_ds.py for tasks to queue
[2023-12-31T11:35:11.155-0300] {logging_mixin.py:188} INFO - [2023-12-31T11:35:11.154-0300] {dagbag.py:538} INFO - Filling up the DagBag from /home/felipe/airflow/dags/07_templated_query_ds.py
[2023-12-31T11:35:11.174-0300] {logging_mixin.py:188} INFO - [2023-12-31T11:35:11.166-0300] {dagbag.py:348} ERROR - Failed to import: /home/felipe/airflow/dags/07_templated_query_ds.py
Traceback (most recent call last):
  File "/home/felipe/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/felipe/airflow/dags/07_templated_query_ds.py", line 4, in <module>
    import pandas as pd
ModuleNotFoundError: No module named 'pandas'
[2023-12-31T11:35:11.175-0300] {processor.py:842} WARNING - No viable dags retrieved from /home/felipe/airflow/dags/07_templated_query_ds.py
[2023-12-31T11:35:11.294-0300] {processor.py:183} INFO - Processing /home/felipe/airflow/dags/07_templated_query_ds.py took 0.161 seconds
[2023-12-31T11:36:33.606-0300] {processor.py:161} INFO - Started process (PID=34647) to work on /home/felipe/airflow/dags/07_templated_query_ds.py
[2023-12-31T11:36:33.615-0300] {processor.py:830} INFO - Processing file /home/felipe/airflow/dags/07_templated_query_ds.py for tasks to queue
[2023-12-31T11:36:33.617-0300] {logging_mixin.py:188} INFO - [2023-12-31T11:36:33.616-0300] {dagbag.py:538} INFO - Filling up the DagBag from /home/felipe/airflow/dags/07_templated_query_ds.py
[2023-12-31T11:36:33.644-0300] {logging_mixin.py:188} INFO - [2023-12-31T11:36:33.635-0300] {dagbag.py:348} ERROR - Failed to import: /home/felipe/airflow/dags/07_templated_query_ds.py
Traceback (most recent call last):
  File "/home/felipe/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/felipe/airflow/dags/07_templated_query_ds.py", line 4, in <module>
    import pandas as pd
ModuleNotFoundError: No module named 'pandas'
[2023-12-31T11:36:33.645-0300] {processor.py:842} WARNING - No viable dags retrieved from /home/felipe/airflow/dags/07_templated_query_ds.py
[2023-12-31T11:36:33.785-0300] {processor.py:183} INFO - Processing /home/felipe/airflow/dags/07_templated_query_ds.py took 0.190 seconds
[2023-12-31T11:37:57.866-0300] {processor.py:161} INFO - Started process (PID=34736) to work on /home/felipe/airflow/dags/07_templated_query_ds.py
[2023-12-31T11:37:57.876-0300] {processor.py:830} INFO - Processing file /home/felipe/airflow/dags/07_templated_query_ds.py for tasks to queue
[2023-12-31T11:37:57.886-0300] {logging_mixin.py:188} INFO - [2023-12-31T11:37:57.885-0300] {dagbag.py:538} INFO - Filling up the DagBag from /home/felipe/airflow/dags/07_templated_query_ds.py
[2023-12-31T11:37:57.915-0300] {logging_mixin.py:188} INFO - [2023-12-31T11:37:57.906-0300] {dagbag.py:348} ERROR - Failed to import: /home/felipe/airflow/dags/07_templated_query_ds.py
Traceback (most recent call last):
  File "/home/felipe/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/felipe/airflow/dags/07_templated_query_ds.py", line 4, in <module>
    import pandas as pd
ModuleNotFoundError: No module named 'pandas'
[2023-12-31T11:37:57.924-0300] {processor.py:842} WARNING - No viable dags retrieved from /home/felipe/airflow/dags/07_templated_query_ds.py
[2023-12-31T11:37:58.075-0300] {processor.py:183} INFO - Processing /home/felipe/airflow/dags/07_templated_query_ds.py took 0.229 seconds
[2023-12-31T11:39:20.465-0300] {processor.py:161} INFO - Started process (PID=34831) to work on /home/felipe/airflow/dags/07_templated_query_ds.py
[2023-12-31T11:39:20.474-0300] {processor.py:830} INFO - Processing file /home/felipe/airflow/dags/07_templated_query_ds.py for tasks to queue
[2023-12-31T11:39:20.475-0300] {logging_mixin.py:188} INFO - [2023-12-31T11:39:20.475-0300] {dagbag.py:538} INFO - Filling up the DagBag from /home/felipe/airflow/dags/07_templated_query_ds.py
[2023-12-31T11:39:20.495-0300] {logging_mixin.py:188} INFO - [2023-12-31T11:39:20.487-0300] {dagbag.py:348} ERROR - Failed to import: /home/felipe/airflow/dags/07_templated_query_ds.py
Traceback (most recent call last):
  File "/home/felipe/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/felipe/airflow/dags/07_templated_query_ds.py", line 4, in <module>
    import pandas as pd
ModuleNotFoundError: No module named 'pandas'
[2023-12-31T11:39:20.496-0300] {processor.py:842} WARNING - No viable dags retrieved from /home/felipe/airflow/dags/07_templated_query_ds.py
[2023-12-31T11:39:20.625-0300] {processor.py:183} INFO - Processing /home/felipe/airflow/dags/07_templated_query_ds.py took 0.179 seconds
[2023-12-31T11:40:42.724-0300] {processor.py:161} INFO - Started process (PID=34947) to work on /home/felipe/airflow/dags/07_templated_query_ds.py
[2023-12-31T11:40:42.734-0300] {processor.py:830} INFO - Processing file /home/felipe/airflow/dags/07_templated_query_ds.py for tasks to queue
[2023-12-31T11:40:42.736-0300] {logging_mixin.py:188} INFO - [2023-12-31T11:40:42.735-0300] {dagbag.py:538} INFO - Filling up the DagBag from /home/felipe/airflow/dags/07_templated_query_ds.py
[2023-12-31T11:40:42.755-0300] {logging_mixin.py:188} INFO - [2023-12-31T11:40:42.754-0300] {dagbag.py:348} ERROR - Failed to import: /home/felipe/airflow/dags/07_templated_query_ds.py
Traceback (most recent call last):
  File "/home/felipe/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/felipe/airflow/dags/07_templated_query_ds.py", line 4, in <module>
    import pandas as pd
ModuleNotFoundError: No module named 'pandas'
[2023-12-31T11:40:42.756-0300] {processor.py:842} WARNING - No viable dags retrieved from /home/felipe/airflow/dags/07_templated_query_ds.py
[2023-12-31T11:40:42.905-0300] {processor.py:183} INFO - Processing /home/felipe/airflow/dags/07_templated_query_ds.py took 0.200 seconds
[2023-12-31T11:42:16.865-0300] {processor.py:161} INFO - Started process (PID=35053) to work on /home/felipe/airflow/dags/07_templated_query_ds.py
[2023-12-31T11:42:16.874-0300] {processor.py:830} INFO - Processing file /home/felipe/airflow/dags/07_templated_query_ds.py for tasks to queue
[2023-12-31T11:42:16.876-0300] {logging_mixin.py:188} INFO - [2023-12-31T11:42:16.875-0300] {dagbag.py:538} INFO - Filling up the DagBag from /home/felipe/airflow/dags/07_templated_query_ds.py
[2023-12-31T11:42:16.906-0300] {logging_mixin.py:188} INFO - [2023-12-31T11:42:16.896-0300] {dagbag.py:348} ERROR - Failed to import: /home/felipe/airflow/dags/07_templated_query_ds.py
Traceback (most recent call last):
  File "/home/felipe/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/felipe/airflow/dags/07_templated_query_ds.py", line 4, in <module>
    import pandas as pd
ModuleNotFoundError: No module named 'pandas'
[2023-12-31T11:42:16.914-0300] {processor.py:842} WARNING - No viable dags retrieved from /home/felipe/airflow/dags/07_templated_query_ds.py
[2023-12-31T11:42:17.115-0300] {processor.py:183} INFO - Processing /home/felipe/airflow/dags/07_templated_query_ds.py took 0.269 seconds
[2023-12-31T11:43:52.545-0300] {processor.py:161} INFO - Started process (PID=35163) to work on /home/felipe/airflow/dags/07_templated_query_ds.py
[2023-12-31T11:43:52.554-0300] {processor.py:830} INFO - Processing file /home/felipe/airflow/dags/07_templated_query_ds.py for tasks to queue
[2023-12-31T11:43:52.556-0300] {logging_mixin.py:188} INFO - [2023-12-31T11:43:52.555-0300] {dagbag.py:538} INFO - Filling up the DagBag from /home/felipe/airflow/dags/07_templated_query_ds.py
[2023-12-31T11:43:52.586-0300] {logging_mixin.py:188} INFO - [2023-12-31T11:43:52.584-0300] {dagbag.py:348} ERROR - Failed to import: /home/felipe/airflow/dags/07_templated_query_ds.py
Traceback (most recent call last):
  File "/home/felipe/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/felipe/airflow/dags/07_templated_query_ds.py", line 4, in <module>
    import pandas as pd
ModuleNotFoundError: No module named 'pandas'
[2023-12-31T11:43:52.594-0300] {processor.py:842} WARNING - No viable dags retrieved from /home/felipe/airflow/dags/07_templated_query_ds.py
[2023-12-31T11:43:52.796-0300] {processor.py:183} INFO - Processing /home/felipe/airflow/dags/07_templated_query_ds.py took 0.271 seconds
[2023-12-31T11:45:33.406-0300] {processor.py:161} INFO - Started process (PID=35302) to work on /home/felipe/airflow/dags/07_templated_query_ds.py
[2023-12-31T11:45:33.425-0300] {processor.py:830} INFO - Processing file /home/felipe/airflow/dags/07_templated_query_ds.py for tasks to queue
[2023-12-31T11:45:33.435-0300] {logging_mixin.py:188} INFO - [2023-12-31T11:45:33.434-0300] {dagbag.py:538} INFO - Filling up the DagBag from /home/felipe/airflow/dags/07_templated_query_ds.py
[2023-12-31T11:45:33.465-0300] {logging_mixin.py:188} INFO - [2023-12-31T11:45:33.455-0300] {dagbag.py:348} ERROR - Failed to import: /home/felipe/airflow/dags/07_templated_query_ds.py
Traceback (most recent call last):
  File "/home/felipe/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/felipe/airflow/dags/07_templated_query_ds.py", line 4, in <module>
    import pandas as pd
ModuleNotFoundError: No module named 'pandas'
[2023-12-31T11:45:33.474-0300] {processor.py:842} WARNING - No viable dags retrieved from /home/felipe/airflow/dags/07_templated_query_ds.py
[2023-12-31T11:45:33.695-0300] {processor.py:183} INFO - Processing /home/felipe/airflow/dags/07_templated_query_ds.py took 0.321 seconds
[2023-12-31T11:47:11.365-0300] {processor.py:161} INFO - Started process (PID=35426) to work on /home/felipe/airflow/dags/07_templated_query_ds.py
[2023-12-31T11:47:11.374-0300] {processor.py:830} INFO - Processing file /home/felipe/airflow/dags/07_templated_query_ds.py for tasks to queue
[2023-12-31T11:47:11.376-0300] {logging_mixin.py:188} INFO - [2023-12-31T11:47:11.375-0300] {dagbag.py:538} INFO - Filling up the DagBag from /home/felipe/airflow/dags/07_templated_query_ds.py
[2023-12-31T11:47:11.405-0300] {logging_mixin.py:188} INFO - [2023-12-31T11:47:11.404-0300] {dagbag.py:348} ERROR - Failed to import: /home/felipe/airflow/dags/07_templated_query_ds.py
Traceback (most recent call last):
  File "/home/felipe/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/felipe/airflow/dags/07_templated_query_ds.py", line 4, in <module>
    import pandas as pd
ModuleNotFoundError: No module named 'pandas'
[2023-12-31T11:47:11.406-0300] {processor.py:842} WARNING - No viable dags retrieved from /home/felipe/airflow/dags/07_templated_query_ds.py
[2023-12-31T11:47:11.585-0300] {processor.py:183} INFO - Processing /home/felipe/airflow/dags/07_templated_query_ds.py took 0.240 seconds
[2023-12-31T11:49:23.045-0300] {processor.py:161} INFO - Started process (PID=35585) to work on /home/felipe/airflow/dags/07_templated_query_ds.py
[2023-12-31T11:49:23.054-0300] {processor.py:830} INFO - Processing file /home/felipe/airflow/dags/07_templated_query_ds.py for tasks to queue
[2023-12-31T11:49:23.056-0300] {logging_mixin.py:188} INFO - [2023-12-31T11:49:23.055-0300] {dagbag.py:538} INFO - Filling up the DagBag from /home/felipe/airflow/dags/07_templated_query_ds.py
[2023-12-31T11:49:23.085-0300] {logging_mixin.py:188} INFO - [2023-12-31T11:49:23.076-0300] {dagbag.py:348} ERROR - Failed to import: /home/felipe/airflow/dags/07_templated_query_ds.py
Traceback (most recent call last):
  File "/home/felipe/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/felipe/airflow/dags/07_templated_query_ds.py", line 4, in <module>
    import pandas as pd
ModuleNotFoundError: No module named 'pandas'
[2023-12-31T11:49:23.086-0300] {processor.py:842} WARNING - No viable dags retrieved from /home/felipe/airflow/dags/07_templated_query_ds.py
[2023-12-31T11:49:23.275-0300] {processor.py:183} INFO - Processing /home/felipe/airflow/dags/07_templated_query_ds.py took 0.250 seconds
[2023-12-31T11:51:33.544-0300] {processor.py:161} INFO - Started process (PID=35733) to work on /home/felipe/airflow/dags/07_templated_query_ds.py
[2023-12-31T11:51:33.554-0300] {processor.py:830} INFO - Processing file /home/felipe/airflow/dags/07_templated_query_ds.py for tasks to queue
[2023-12-31T11:51:33.556-0300] {logging_mixin.py:188} INFO - [2023-12-31T11:51:33.555-0300] {dagbag.py:538} INFO - Filling up the DagBag from /home/felipe/airflow/dags/07_templated_query_ds.py
[2023-12-31T11:51:33.585-0300] {logging_mixin.py:188} INFO - [2023-12-31T11:51:33.584-0300] {dagbag.py:348} ERROR - Failed to import: /home/felipe/airflow/dags/07_templated_query_ds.py
Traceback (most recent call last):
  File "/home/felipe/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/felipe/airflow/dags/07_templated_query_ds.py", line 4, in <module>
    import pandas as pd
ModuleNotFoundError: No module named 'pandas'
[2023-12-31T11:51:33.594-0300] {processor.py:842} WARNING - No viable dags retrieved from /home/felipe/airflow/dags/07_templated_query_ds.py
[2023-12-31T11:51:33.824-0300] {processor.py:183} INFO - Processing /home/felipe/airflow/dags/07_templated_query_ds.py took 0.319 seconds
[2023-12-31T11:54:17.436-0300] {processor.py:161} INFO - Started process (PID=35867) to work on /home/felipe/airflow/dags/07_templated_query_ds.py
[2023-12-31T11:54:17.454-0300] {processor.py:830} INFO - Processing file /home/felipe/airflow/dags/07_templated_query_ds.py for tasks to queue
[2023-12-31T11:54:17.465-0300] {logging_mixin.py:188} INFO - [2023-12-31T11:54:17.464-0300] {dagbag.py:538} INFO - Filling up the DagBag from /home/felipe/airflow/dags/07_templated_query_ds.py
[2023-12-31T11:54:17.505-0300] {logging_mixin.py:188} INFO - [2023-12-31T11:54:17.495-0300] {dagbag.py:348} ERROR - Failed to import: /home/felipe/airflow/dags/07_templated_query_ds.py
Traceback (most recent call last):
  File "/home/felipe/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/felipe/airflow/dags/07_templated_query_ds.py", line 4, in <module>
    import pandas as pd
ModuleNotFoundError: No module named 'pandas'
[2023-12-31T11:54:17.514-0300] {processor.py:842} WARNING - No viable dags retrieved from /home/felipe/airflow/dags/07_templated_query_ds.py
[2023-12-31T11:54:17.725-0300] {processor.py:183} INFO - Processing /home/felipe/airflow/dags/07_templated_query_ds.py took 0.320 seconds
[2023-12-31T11:56:10.865-0300] {processor.py:161} INFO - Started process (PID=36004) to work on /home/felipe/airflow/dags/07_templated_query_ds.py
[2023-12-31T11:56:10.874-0300] {processor.py:830} INFO - Processing file /home/felipe/airflow/dags/07_templated_query_ds.py for tasks to queue
[2023-12-31T11:56:10.884-0300] {logging_mixin.py:188} INFO - [2023-12-31T11:56:10.875-0300] {dagbag.py:538} INFO - Filling up the DagBag from /home/felipe/airflow/dags/07_templated_query_ds.py
[2023-12-31T11:56:10.905-0300] {logging_mixin.py:188} INFO - [2023-12-31T11:56:10.904-0300] {dagbag.py:348} ERROR - Failed to import: /home/felipe/airflow/dags/07_templated_query_ds.py
Traceback (most recent call last):
  File "/home/felipe/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/felipe/airflow/dags/07_templated_query_ds.py", line 4, in <module>
    import pandas as pd
ModuleNotFoundError: No module named 'pandas'
[2023-12-31T11:56:10.914-0300] {processor.py:842} WARNING - No viable dags retrieved from /home/felipe/airflow/dags/07_templated_query_ds.py
[2023-12-31T11:56:11.094-0300] {processor.py:183} INFO - Processing /home/felipe/airflow/dags/07_templated_query_ds.py took 0.241 seconds
[2023-12-31T11:57:55.454-0300] {processor.py:161} INFO - Started process (PID=36109) to work on /home/felipe/airflow/dags/07_templated_query_ds.py
[2023-12-31T11:57:55.464-0300] {processor.py:830} INFO - Processing file /home/felipe/airflow/dags/07_templated_query_ds.py for tasks to queue
[2023-12-31T11:57:55.466-0300] {logging_mixin.py:188} INFO - [2023-12-31T11:57:55.465-0300] {dagbag.py:538} INFO - Filling up the DagBag from /home/felipe/airflow/dags/07_templated_query_ds.py
[2023-12-31T11:57:55.495-0300] {logging_mixin.py:188} INFO - [2023-12-31T11:57:55.485-0300] {dagbag.py:348} ERROR - Failed to import: /home/felipe/airflow/dags/07_templated_query_ds.py
Traceback (most recent call last):
  File "/home/felipe/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/felipe/airflow/dags/07_templated_query_ds.py", line 4, in <module>
    import pandas as pd
ModuleNotFoundError: No module named 'pandas'
[2023-12-31T11:57:55.495-0300] {processor.py:842} WARNING - No viable dags retrieved from /home/felipe/airflow/dags/07_templated_query_ds.py
[2023-12-31T11:57:55.694-0300] {processor.py:183} INFO - Processing /home/felipe/airflow/dags/07_templated_query_ds.py took 0.269 seconds
[2023-12-31T11:59:41.725-0300] {processor.py:161} INFO - Started process (PID=36208) to work on /home/felipe/airflow/dags/07_templated_query_ds.py
[2023-12-31T11:59:41.744-0300] {processor.py:830} INFO - Processing file /home/felipe/airflow/dags/07_templated_query_ds.py for tasks to queue
[2023-12-31T11:59:41.754-0300] {logging_mixin.py:188} INFO - [2023-12-31T11:59:41.745-0300] {dagbag.py:538} INFO - Filling up the DagBag from /home/felipe/airflow/dags/07_templated_query_ds.py
[2023-12-31T11:59:41.784-0300] {logging_mixin.py:188} INFO - [2023-12-31T11:59:41.774-0300] {dagbag.py:348} ERROR - Failed to import: /home/felipe/airflow/dags/07_templated_query_ds.py
Traceback (most recent call last):
  File "/home/felipe/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/felipe/airflow/dags/07_templated_query_ds.py", line 4, in <module>
    import pandas as pd
ModuleNotFoundError: No module named 'pandas'
[2023-12-31T11:59:41.785-0300] {processor.py:842} WARNING - No viable dags retrieved from /home/felipe/airflow/dags/07_templated_query_ds.py
[2023-12-31T11:59:41.974-0300] {processor.py:183} INFO - Processing /home/felipe/airflow/dags/07_templated_query_ds.py took 0.279 seconds
[2023-12-31T12:01:30.334-0300] {processor.py:161} INFO - Started process (PID=36338) to work on /home/felipe/airflow/dags/07_templated_query_ds.py
[2023-12-31T12:01:30.344-0300] {processor.py:830} INFO - Processing file /home/felipe/airflow/dags/07_templated_query_ds.py for tasks to queue
[2023-12-31T12:01:30.354-0300] {logging_mixin.py:188} INFO - [2023-12-31T12:01:30.345-0300] {dagbag.py:538} INFO - Filling up the DagBag from /home/felipe/airflow/dags/07_templated_query_ds.py
[2023-12-31T12:01:30.394-0300] {logging_mixin.py:188} INFO - [2023-12-31T12:01:30.384-0300] {dagbag.py:348} ERROR - Failed to import: /home/felipe/airflow/dags/07_templated_query_ds.py
Traceback (most recent call last):
  File "/home/felipe/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/felipe/airflow/dags/07_templated_query_ds.py", line 4, in <module>
    import pandas as pd
ModuleNotFoundError: No module named 'pandas'
[2023-12-31T12:01:30.395-0300] {processor.py:842} WARNING - No viable dags retrieved from /home/felipe/airflow/dags/07_templated_query_ds.py
[2023-12-31T12:01:30.634-0300] {processor.py:183} INFO - Processing /home/felipe/airflow/dags/07_templated_query_ds.py took 0.329 seconds
[2023-12-31T12:03:29.964-0300] {processor.py:161} INFO - Started process (PID=36451) to work on /home/felipe/airflow/dags/07_templated_query_ds.py
[2023-12-31T12:03:29.974-0300] {processor.py:830} INFO - Processing file /home/felipe/airflow/dags/07_templated_query_ds.py for tasks to queue
[2023-12-31T12:03:29.984-0300] {logging_mixin.py:188} INFO - [2023-12-31T12:03:29.975-0300] {dagbag.py:538} INFO - Filling up the DagBag from /home/felipe/airflow/dags/07_templated_query_ds.py
[2023-12-31T12:03:30.014-0300] {logging_mixin.py:188} INFO - [2023-12-31T12:03:30.004-0300] {dagbag.py:348} ERROR - Failed to import: /home/felipe/airflow/dags/07_templated_query_ds.py
Traceback (most recent call last):
  File "/home/felipe/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/felipe/airflow/dags/07_templated_query_ds.py", line 4, in <module>
    import pandas as pd
ModuleNotFoundError: No module named 'pandas'
[2023-12-31T12:03:30.014-0300] {processor.py:842} WARNING - No viable dags retrieved from /home/felipe/airflow/dags/07_templated_query_ds.py
[2023-12-31T12:03:30.265-0300] {processor.py:183} INFO - Processing /home/felipe/airflow/dags/07_templated_query_ds.py took 0.330 seconds
[2023-12-31T12:06:51.105-0300] {processor.py:161} INFO - Started process (PID=36704) to work on /home/felipe/airflow/dags/07_templated_query_ds.py
[2023-12-31T12:06:51.135-0300] {processor.py:830} INFO - Processing file /home/felipe/airflow/dags/07_templated_query_ds.py for tasks to queue
[2023-12-31T12:06:51.174-0300] {logging_mixin.py:188} INFO - [2023-12-31T12:06:51.164-0300] {dagbag.py:538} INFO - Filling up the DagBag from /home/felipe/airflow/dags/07_templated_query_ds.py
[2023-12-31T12:06:51.325-0300] {logging_mixin.py:188} INFO - [2023-12-31T12:06:51.295-0300] {dagbag.py:348} ERROR - Failed to import: /home/felipe/airflow/dags/07_templated_query_ds.py
Traceback (most recent call last):
  File "/home/felipe/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/felipe/airflow/dags/07_templated_query_ds.py", line 4, in <module>
    import pandas as pd
ModuleNotFoundError: No module named 'pandas'
[2023-12-31T12:06:51.344-0300] {processor.py:842} WARNING - No viable dags retrieved from /home/felipe/airflow/dags/07_templated_query_ds.py
[2023-12-31T12:06:51.835-0300] {processor.py:183} INFO - Processing /home/felipe/airflow/dags/07_templated_query_ds.py took 0.830 seconds
[2023-12-31T12:10:19.675-0300] {processor.py:161} INFO - Started process (PID=37094) to work on /home/felipe/airflow/dags/07_templated_query_ds.py
[2023-12-31T12:10:19.695-0300] {processor.py:830} INFO - Processing file /home/felipe/airflow/dags/07_templated_query_ds.py for tasks to queue
[2023-12-31T12:10:19.724-0300] {logging_mixin.py:188} INFO - [2023-12-31T12:10:19.714-0300] {dagbag.py:538} INFO - Filling up the DagBag from /home/felipe/airflow/dags/07_templated_query_ds.py
[2023-12-31T12:10:19.785-0300] {logging_mixin.py:188} INFO - [2023-12-31T12:10:19.774-0300] {dagbag.py:348} ERROR - Failed to import: /home/felipe/airflow/dags/07_templated_query_ds.py
Traceback (most recent call last):
  File "/home/felipe/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/felipe/airflow/dags/07_templated_query_ds.py", line 4, in <module>
    import pandas as pd
ModuleNotFoundError: No module named 'pandas'
[2023-12-31T12:10:19.804-0300] {processor.py:842} WARNING - No viable dags retrieved from /home/felipe/airflow/dags/07_templated_query_ds.py
[2023-12-31T12:10:21.855-0300] {processor.py:183} INFO - Processing /home/felipe/airflow/dags/07_templated_query_ds.py took 2.220 seconds
[2023-12-31T12:11:35.164-0300] {processor.py:161} INFO - Started process (PID=37190) to work on /home/felipe/airflow/dags/07_templated_query_ds.py
[2023-12-31T12:11:35.174-0300] {processor.py:830} INFO - Processing file /home/felipe/airflow/dags/07_templated_query_ds.py for tasks to queue
[2023-12-31T12:11:35.204-0300] {logging_mixin.py:188} INFO - [2023-12-31T12:11:35.194-0300] {dagbag.py:538} INFO - Filling up the DagBag from /home/felipe/airflow/dags/07_templated_query_ds.py
[2023-12-31T12:11:35.274-0300] {logging_mixin.py:188} INFO - [2023-12-31T12:11:35.254-0300] {dagbag.py:348} ERROR - Failed to import: /home/felipe/airflow/dags/07_templated_query_ds.py
Traceback (most recent call last):
  File "/home/felipe/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/felipe/airflow/dags/07_templated_query_ds.py", line 4, in <module>
    import pandas as pd
ModuleNotFoundError: No module named 'pandas'
[2023-12-31T12:11:35.284-0300] {processor.py:842} WARNING - No viable dags retrieved from /home/felipe/airflow/dags/07_templated_query_ds.py
[2023-12-31T12:11:35.645-0300] {processor.py:183} INFO - Processing /home/felipe/airflow/dags/07_templated_query_ds.py took 0.530 seconds
[2023-12-31T12:12:31.445-0300] {processor.py:161} INFO - Started process (PID=37265) to work on /home/felipe/airflow/dags/07_templated_query_ds.py
[2023-12-31T12:12:31.464-0300] {processor.py:830} INFO - Processing file /home/felipe/airflow/dags/07_templated_query_ds.py for tasks to queue
[2023-12-31T12:12:31.474-0300] {logging_mixin.py:188} INFO - [2023-12-31T12:12:31.465-0300] {dagbag.py:538} INFO - Filling up the DagBag from /home/felipe/airflow/dags/07_templated_query_ds.py
[2023-12-31T12:12:31.515-0300] {logging_mixin.py:188} INFO - [2023-12-31T12:12:31.505-0300] {dagbag.py:348} ERROR - Failed to import: /home/felipe/airflow/dags/07_templated_query_ds.py
Traceback (most recent call last):
  File "/home/felipe/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/felipe/airflow/dags/07_templated_query_ds.py", line 4, in <module>
    import pandas as pd
ModuleNotFoundError: No module named 'pandas'
[2023-12-31T12:12:31.524-0300] {processor.py:842} WARNING - No viable dags retrieved from /home/felipe/airflow/dags/07_templated_query_ds.py
[2023-12-31T12:12:31.834-0300] {processor.py:183} INFO - Processing /home/felipe/airflow/dags/07_templated_query_ds.py took 0.420 seconds
[2023-12-31T12:13:34.185-0300] {processor.py:161} INFO - Started process (PID=37345) to work on /home/felipe/airflow/dags/07_templated_query_ds.py
[2023-12-31T12:13:34.205-0300] {processor.py:830} INFO - Processing file /home/felipe/airflow/dags/07_templated_query_ds.py for tasks to queue
[2023-12-31T12:13:34.234-0300] {logging_mixin.py:188} INFO - [2023-12-31T12:13:34.224-0300] {dagbag.py:538} INFO - Filling up the DagBag from /home/felipe/airflow/dags/07_templated_query_ds.py
[2023-12-31T12:13:34.304-0300] {logging_mixin.py:188} INFO - [2023-12-31T12:13:34.275-0300] {dagbag.py:348} ERROR - Failed to import: /home/felipe/airflow/dags/07_templated_query_ds.py
Traceback (most recent call last):
  File "/home/felipe/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/felipe/airflow/dags/07_templated_query_ds.py", line 4, in <module>
    import pandas as pd
ModuleNotFoundError: No module named 'pandas'
[2023-12-31T12:13:34.305-0300] {processor.py:842} WARNING - No viable dags retrieved from /home/felipe/airflow/dags/07_templated_query_ds.py
[2023-12-31T12:13:34.674-0300] {processor.py:183} INFO - Processing /home/felipe/airflow/dags/07_templated_query_ds.py took 0.529 seconds
[2023-12-31T12:14:25.925-0300] {processor.py:161} INFO - Started process (PID=37417) to work on /home/felipe/airflow/dags/07_templated_query_ds.py
[2023-12-31T12:14:25.945-0300] {processor.py:830} INFO - Processing file /home/felipe/airflow/dags/07_templated_query_ds.py for tasks to queue
[2023-12-31T12:14:25.984-0300] {logging_mixin.py:188} INFO - [2023-12-31T12:14:25.965-0300] {dagbag.py:538} INFO - Filling up the DagBag from /home/felipe/airflow/dags/07_templated_query_ds.py
[2023-12-31T12:14:26.074-0300] {logging_mixin.py:188} INFO - [2023-12-31T12:14:26.034-0300] {dagbag.py:348} ERROR - Failed to import: /home/felipe/airflow/dags/07_templated_query_ds.py
Traceback (most recent call last):
  File "/home/felipe/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/felipe/airflow/dags/07_templated_query_ds.py", line 4, in <module>
    import pandas as pd
ModuleNotFoundError: No module named 'pandas'
[2023-12-31T12:14:26.084-0300] {processor.py:842} WARNING - No viable dags retrieved from /home/felipe/airflow/dags/07_templated_query_ds.py
[2023-12-31T12:14:26.584-0300] {processor.py:183} INFO - Processing /home/felipe/airflow/dags/07_templated_query_ds.py took 0.710 seconds
[2023-12-31T12:15:37.264-0300] {processor.py:161} INFO - Started process (PID=37534) to work on /home/felipe/airflow/dags/07_templated_query_ds.py
[2023-12-31T12:15:37.275-0300] {processor.py:830} INFO - Processing file /home/felipe/airflow/dags/07_templated_query_ds.py for tasks to queue
[2023-12-31T12:15:37.294-0300] {logging_mixin.py:188} INFO - [2023-12-31T12:15:37.284-0300] {dagbag.py:538} INFO - Filling up the DagBag from /home/felipe/airflow/dags/07_templated_query_ds.py
[2023-12-31T12:15:37.334-0300] {logging_mixin.py:188} INFO - [2023-12-31T12:15:37.324-0300] {dagbag.py:348} ERROR - Failed to import: /home/felipe/airflow/dags/07_templated_query_ds.py
Traceback (most recent call last):
  File "/home/felipe/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/felipe/airflow/dags/07_templated_query_ds.py", line 4, in <module>
    import pandas as pd
ModuleNotFoundError: No module named 'pandas'
[2023-12-31T12:15:37.335-0300] {processor.py:842} WARNING - No viable dags retrieved from /home/felipe/airflow/dags/07_templated_query_ds.py
[2023-12-31T12:15:37.654-0300] {processor.py:183} INFO - Processing /home/felipe/airflow/dags/07_templated_query_ds.py took 0.430 seconds
[2023-12-31T12:16:25.604-0300] {processor.py:161} INFO - Started process (PID=37597) to work on /home/felipe/airflow/dags/07_templated_query_ds.py
[2023-12-31T12:16:25.615-0300] {processor.py:830} INFO - Processing file /home/felipe/airflow/dags/07_templated_query_ds.py for tasks to queue
[2023-12-31T12:16:25.634-0300] {logging_mixin.py:188} INFO - [2023-12-31T12:16:25.625-0300] {dagbag.py:538} INFO - Filling up the DagBag from /home/felipe/airflow/dags/07_templated_query_ds.py
[2023-12-31T12:16:25.684-0300] {logging_mixin.py:188} INFO - [2023-12-31T12:16:25.664-0300] {dagbag.py:348} ERROR - Failed to import: /home/felipe/airflow/dags/07_templated_query_ds.py
Traceback (most recent call last):
  File "/home/felipe/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/felipe/airflow/dags/07_templated_query_ds.py", line 4, in <module>
    import pandas as pd
ModuleNotFoundError: No module named 'pandas'
[2023-12-31T12:16:25.685-0300] {processor.py:842} WARNING - No viable dags retrieved from /home/felipe/airflow/dags/07_templated_query_ds.py
[2023-12-31T12:16:26.004-0300] {processor.py:183} INFO - Processing /home/felipe/airflow/dags/07_templated_query_ds.py took 0.439 seconds
[2023-12-31T12:17:37.094-0300] {processor.py:161} INFO - Started process (PID=37693) to work on /home/felipe/airflow/dags/07_templated_query_ds.py
[2023-12-31T12:17:37.114-0300] {processor.py:830} INFO - Processing file /home/felipe/airflow/dags/07_templated_query_ds.py for tasks to queue
[2023-12-31T12:17:37.125-0300] {logging_mixin.py:188} INFO - [2023-12-31T12:17:37.124-0300] {dagbag.py:538} INFO - Filling up the DagBag from /home/felipe/airflow/dags/07_templated_query_ds.py
[2023-12-31T12:17:37.194-0300] {logging_mixin.py:188} INFO - [2023-12-31T12:17:37.174-0300] {dagbag.py:348} ERROR - Failed to import: /home/felipe/airflow/dags/07_templated_query_ds.py
Traceback (most recent call last):
  File "/home/felipe/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/felipe/airflow/dags/07_templated_query_ds.py", line 4, in <module>
    import pandas as pd
ModuleNotFoundError: No module named 'pandas'
[2023-12-31T12:17:37.204-0300] {processor.py:842} WARNING - No viable dags retrieved from /home/felipe/airflow/dags/07_templated_query_ds.py
[2023-12-31T12:17:37.544-0300] {processor.py:183} INFO - Processing /home/felipe/airflow/dags/07_templated_query_ds.py took 0.490 seconds
[2023-12-31T12:18:29.214-0300] {processor.py:161} INFO - Started process (PID=37758) to work on /home/felipe/airflow/dags/07_templated_query_ds.py
[2023-12-31T12:18:29.235-0300] {processor.py:830} INFO - Processing file /home/felipe/airflow/dags/07_templated_query_ds.py for tasks to queue
[2023-12-31T12:18:29.264-0300] {logging_mixin.py:188} INFO - [2023-12-31T12:18:29.254-0300] {dagbag.py:538} INFO - Filling up the DagBag from /home/felipe/airflow/dags/07_templated_query_ds.py
[2023-12-31T12:18:29.315-0300] {logging_mixin.py:188} INFO - [2023-12-31T12:18:29.304-0300] {dagbag.py:348} ERROR - Failed to import: /home/felipe/airflow/dags/07_templated_query_ds.py
Traceback (most recent call last):
  File "/home/felipe/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/felipe/airflow/dags/07_templated_query_ds.py", line 4, in <module>
    import pandas as pd
ModuleNotFoundError: No module named 'pandas'
[2023-12-31T12:18:29.334-0300] {processor.py:842} WARNING - No viable dags retrieved from /home/felipe/airflow/dags/07_templated_query_ds.py
[2023-12-31T12:18:29.784-0300] {processor.py:183} INFO - Processing /home/felipe/airflow/dags/07_templated_query_ds.py took 0.601 seconds
[2023-12-31T12:26:13.461-0300] {processor.py:161} INFO - Started process (PID=37979) to work on /home/felipe/airflow/dags/07_templated_query_ds.py
[2023-12-31T12:26:13.491-0300] {processor.py:830} INFO - Processing file /home/felipe/airflow/dags/07_templated_query_ds.py for tasks to queue
[2023-12-31T12:26:13.520-0300] {logging_mixin.py:188} INFO - [2023-12-31T12:26:13.510-0300] {dagbag.py:538} INFO - Filling up the DagBag from /home/felipe/airflow/dags/07_templated_query_ds.py
[2023-12-31T12:26:13.600-0300] {logging_mixin.py:188} INFO - [2023-12-31T12:26:13.571-0300] {dagbag.py:348} ERROR - Failed to import: /home/felipe/airflow/dags/07_templated_query_ds.py
Traceback (most recent call last):
  File "/home/felipe/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/felipe/airflow/dags/07_templated_query_ds.py", line 4, in <module>
    import pandas as pd
ModuleNotFoundError: No module named 'pandas'
[2023-12-31T12:26:13.610-0300] {processor.py:842} WARNING - No viable dags retrieved from /home/felipe/airflow/dags/07_templated_query_ds.py
[2023-12-31T12:26:14.030-0300] {processor.py:183} INFO - Processing /home/felipe/airflow/dags/07_templated_query_ds.py took 0.619 seconds
[2023-12-31T12:27:22.901-0300] {processor.py:161} INFO - Started process (PID=38049) to work on /home/felipe/airflow/dags/07_templated_query_ds.py
[2023-12-31T12:27:22.921-0300] {processor.py:830} INFO - Processing file /home/felipe/airflow/dags/07_templated_query_ds.py for tasks to queue
[2023-12-31T12:27:22.950-0300] {logging_mixin.py:188} INFO - [2023-12-31T12:27:22.941-0300] {dagbag.py:538} INFO - Filling up the DagBag from /home/felipe/airflow/dags/07_templated_query_ds.py
[2023-12-31T12:27:23.031-0300] {logging_mixin.py:188} INFO - [2023-12-31T12:27:23.010-0300] {dagbag.py:348} ERROR - Failed to import: /home/felipe/airflow/dags/07_templated_query_ds.py
Traceback (most recent call last):
  File "/home/felipe/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/felipe/airflow/dags/07_templated_query_ds.py", line 4, in <module>
    import pandas as pd
ModuleNotFoundError: No module named 'pandas'
[2023-12-31T12:27:23.041-0300] {processor.py:842} WARNING - No viable dags retrieved from /home/felipe/airflow/dags/07_templated_query_ds.py
[2023-12-31T12:27:23.510-0300] {processor.py:183} INFO - Processing /home/felipe/airflow/dags/07_templated_query_ds.py took 0.670 seconds
[2023-12-31T12:28:38.960-0300] {processor.py:161} INFO - Started process (PID=38108) to work on /home/felipe/airflow/dags/07_templated_query_ds.py
[2023-12-31T12:28:38.981-0300] {processor.py:830} INFO - Processing file /home/felipe/airflow/dags/07_templated_query_ds.py for tasks to queue
[2023-12-31T12:28:39.011-0300] {logging_mixin.py:188} INFO - [2023-12-31T12:28:39.001-0300] {dagbag.py:538} INFO - Filling up the DagBag from /home/felipe/airflow/dags/07_templated_query_ds.py
[2023-12-31T12:28:39.101-0300] {logging_mixin.py:188} INFO - [2023-12-31T12:28:39.081-0300] {dagbag.py:348} ERROR - Failed to import: /home/felipe/airflow/dags/07_templated_query_ds.py
Traceback (most recent call last):
  File "/home/felipe/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/felipe/airflow/dags/07_templated_query_ds.py", line 4, in <module>
    import pandas as pd
ModuleNotFoundError: No module named 'pandas'
[2023-12-31T12:28:39.111-0300] {processor.py:842} WARNING - No viable dags retrieved from /home/felipe/airflow/dags/07_templated_query_ds.py
[2023-12-31T12:28:39.611-0300] {processor.py:183} INFO - Processing /home/felipe/airflow/dags/07_templated_query_ds.py took 0.730 seconds
[2023-12-31T12:29:50.901-0300] {processor.py:161} INFO - Started process (PID=38157) to work on /home/felipe/airflow/dags/07_templated_query_ds.py
[2023-12-31T12:29:50.921-0300] {processor.py:830} INFO - Processing file /home/felipe/airflow/dags/07_templated_query_ds.py for tasks to queue
[2023-12-31T12:29:50.940-0300] {logging_mixin.py:188} INFO - [2023-12-31T12:29:50.931-0300] {dagbag.py:538} INFO - Filling up the DagBag from /home/felipe/airflow/dags/07_templated_query_ds.py
[2023-12-31T12:29:51.011-0300] {logging_mixin.py:188} INFO - [2023-12-31T12:29:50.990-0300] {dagbag.py:348} ERROR - Failed to import: /home/felipe/airflow/dags/07_templated_query_ds.py
Traceback (most recent call last):
  File "/home/felipe/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/felipe/airflow/dags/07_templated_query_ds.py", line 4, in <module>
    import pandas as pd
ModuleNotFoundError: No module named 'pandas'
[2023-12-31T12:29:51.021-0300] {processor.py:842} WARNING - No viable dags retrieved from /home/felipe/airflow/dags/07_templated_query_ds.py
[2023-12-31T12:29:51.431-0300] {processor.py:183} INFO - Processing /home/felipe/airflow/dags/07_templated_query_ds.py took 0.590 seconds
[2023-12-31T12:31:06.220-0300] {processor.py:161} INFO - Started process (PID=38238) to work on /home/felipe/airflow/dags/07_templated_query_ds.py
[2023-12-31T12:31:06.241-0300] {processor.py:830} INFO - Processing file /home/felipe/airflow/dags/07_templated_query_ds.py for tasks to queue
[2023-12-31T12:31:06.280-0300] {logging_mixin.py:188} INFO - [2023-12-31T12:31:06.261-0300] {dagbag.py:538} INFO - Filling up the DagBag from /home/felipe/airflow/dags/07_templated_query_ds.py
[2023-12-31T12:31:06.360-0300] {logging_mixin.py:188} INFO - [2023-12-31T12:31:06.340-0300] {dagbag.py:348} ERROR - Failed to import: /home/felipe/airflow/dags/07_templated_query_ds.py
Traceback (most recent call last):
  File "/home/felipe/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/felipe/airflow/dags/07_templated_query_ds.py", line 4, in <module>
    import pandas as pd
ModuleNotFoundError: No module named 'pandas'
[2023-12-31T12:31:06.371-0300] {processor.py:842} WARNING - No viable dags retrieved from /home/felipe/airflow/dags/07_templated_query_ds.py
[2023-12-31T12:31:06.841-0300] {processor.py:183} INFO - Processing /home/felipe/airflow/dags/07_templated_query_ds.py took 0.700 seconds
[2023-12-31T12:32:27.040-0300] {processor.py:161} INFO - Started process (PID=38288) to work on /home/felipe/airflow/dags/07_templated_query_ds.py
[2023-12-31T12:32:27.080-0300] {processor.py:830} INFO - Processing file /home/felipe/airflow/dags/07_templated_query_ds.py for tasks to queue
[2023-12-31T12:32:27.110-0300] {logging_mixin.py:188} INFO - [2023-12-31T12:32:27.100-0300] {dagbag.py:538} INFO - Filling up the DagBag from /home/felipe/airflow/dags/07_templated_query_ds.py
[2023-12-31T12:32:27.221-0300] {logging_mixin.py:188} INFO - [2023-12-31T12:32:27.200-0300] {dagbag.py:348} ERROR - Failed to import: /home/felipe/airflow/dags/07_templated_query_ds.py
Traceback (most recent call last):
  File "/home/felipe/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/felipe/airflow/dags/07_templated_query_ds.py", line 4, in <module>
    import pandas as pd
ModuleNotFoundError: No module named 'pandas'
[2023-12-31T12:32:27.231-0300] {processor.py:842} WARNING - No viable dags retrieved from /home/felipe/airflow/dags/07_templated_query_ds.py
[2023-12-31T12:32:27.720-0300] {processor.py:183} INFO - Processing /home/felipe/airflow/dags/07_templated_query_ds.py took 0.770 seconds
[2023-12-31T12:33:58.151-0300] {processor.py:161} INFO - Started process (PID=38349) to work on /home/felipe/airflow/dags/07_templated_query_ds.py
[2023-12-31T12:33:58.171-0300] {processor.py:830} INFO - Processing file /home/felipe/airflow/dags/07_templated_query_ds.py for tasks to queue
[2023-12-31T12:33:58.200-0300] {logging_mixin.py:188} INFO - [2023-12-31T12:33:58.190-0300] {dagbag.py:538} INFO - Filling up the DagBag from /home/felipe/airflow/dags/07_templated_query_ds.py
[2023-12-31T12:33:58.281-0300] {logging_mixin.py:188} INFO - [2023-12-31T12:33:58.260-0300] {dagbag.py:348} ERROR - Failed to import: /home/felipe/airflow/dags/07_templated_query_ds.py
Traceback (most recent call last):
  File "/home/felipe/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/felipe/airflow/dags/07_templated_query_ds.py", line 4, in <module>
    import pandas as pd
ModuleNotFoundError: No module named 'pandas'
[2023-12-31T12:33:58.300-0300] {processor.py:842} WARNING - No viable dags retrieved from /home/felipe/airflow/dags/07_templated_query_ds.py
[2023-12-31T12:33:58.861-0300] {processor.py:183} INFO - Processing /home/felipe/airflow/dags/07_templated_query_ds.py took 0.780 seconds
[2023-12-31T12:35:36.100-0300] {processor.py:161} INFO - Started process (PID=38431) to work on /home/felipe/airflow/dags/07_templated_query_ds.py
[2023-12-31T12:35:36.121-0300] {processor.py:830} INFO - Processing file /home/felipe/airflow/dags/07_templated_query_ds.py for tasks to queue
[2023-12-31T12:35:36.151-0300] {logging_mixin.py:188} INFO - [2023-12-31T12:35:36.141-0300] {dagbag.py:538} INFO - Filling up the DagBag from /home/felipe/airflow/dags/07_templated_query_ds.py
[2023-12-31T12:35:36.271-0300] {logging_mixin.py:188} INFO - [2023-12-31T12:35:36.241-0300] {dagbag.py:348} ERROR - Failed to import: /home/felipe/airflow/dags/07_templated_query_ds.py
Traceback (most recent call last):
  File "/home/felipe/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/felipe/airflow/dags/07_templated_query_ds.py", line 4, in <module>
    import pandas as pd
ModuleNotFoundError: No module named 'pandas'
[2023-12-31T12:35:36.291-0300] {processor.py:842} WARNING - No viable dags retrieved from /home/felipe/airflow/dags/07_templated_query_ds.py
[2023-12-31T12:35:36.920-0300] {processor.py:183} INFO - Processing /home/felipe/airflow/dags/07_templated_query_ds.py took 0.900 seconds
[2023-12-31T12:37:40.541-0300] {processor.py:161} INFO - Started process (PID=38502) to work on /home/felipe/airflow/dags/07_templated_query_ds.py
[2023-12-31T12:37:40.590-0300] {processor.py:830} INFO - Processing file /home/felipe/airflow/dags/07_templated_query_ds.py for tasks to queue
[2023-12-31T12:37:40.650-0300] {logging_mixin.py:188} INFO - [2023-12-31T12:37:40.630-0300] {dagbag.py:538} INFO - Filling up the DagBag from /home/felipe/airflow/dags/07_templated_query_ds.py
[2023-12-31T12:37:40.830-0300] {logging_mixin.py:188} INFO - [2023-12-31T12:37:40.790-0300] {dagbag.py:348} ERROR - Failed to import: /home/felipe/airflow/dags/07_templated_query_ds.py
Traceback (most recent call last):
  File "/home/felipe/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/felipe/airflow/dags/07_templated_query_ds.py", line 4, in <module>
    import pandas as pd
ModuleNotFoundError: No module named 'pandas'
[2023-12-31T12:37:40.851-0300] {processor.py:842} WARNING - No viable dags retrieved from /home/felipe/airflow/dags/07_templated_query_ds.py
[2023-12-31T12:37:41.790-0300] {processor.py:183} INFO - Processing /home/felipe/airflow/dags/07_templated_query_ds.py took 1.390 seconds
[2023-12-31T12:47:07.348-0300] {processor.py:161} INFO - Started process (PID=38758) to work on /home/felipe/airflow/dags/07_templated_query_ds.py
[2023-12-31T12:47:07.427-0300] {processor.py:830} INFO - Processing file /home/felipe/airflow/dags/07_templated_query_ds.py for tasks to queue
[2023-12-31T12:47:07.518-0300] {logging_mixin.py:188} INFO - [2023-12-31T12:47:07.478-0300] {dagbag.py:538} INFO - Filling up the DagBag from /home/felipe/airflow/dags/07_templated_query_ds.py
[2023-12-31T12:47:07.898-0300] {logging_mixin.py:188} INFO - [2023-12-31T12:47:07.818-0300] {dagbag.py:348} ERROR - Failed to import: /home/felipe/airflow/dags/07_templated_query_ds.py
Traceback (most recent call last):
  File "/home/felipe/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/felipe/airflow/dags/07_templated_query_ds.py", line 4, in <module>
    import pandas as pd
ModuleNotFoundError: No module named 'pandas'
[2023-12-31T12:47:07.938-0300] {processor.py:842} WARNING - No viable dags retrieved from /home/felipe/airflow/dags/07_templated_query_ds.py
[2023-12-31T12:47:09.568-0300] {processor.py:183} INFO - Processing /home/felipe/airflow/dags/07_templated_query_ds.py took 2.440 seconds
