[2023-12-31T09:36:36.037-0300] {processor.py:161} INFO - Started process (PID=31950) to work on /home/felipe/airflow/dags/10_non_atomic_send.py
[2023-12-31T09:36:36.038-0300] {processor.py:830} INFO - Processing file /home/felipe/airflow/dags/10_non_atomic_send.py for tasks to queue
[2023-12-31T09:36:36.039-0300] {logging_mixin.py:188} INFO - [2023-12-31T09:36:36.039-0300] {dagbag.py:538} INFO - Filling up the DagBag from /home/felipe/airflow/dags/10_non_atomic_send.py
[2023-12-31T09:36:36.049-0300] {logging_mixin.py:188} INFO - [2023-12-31T09:36:36.048-0300] {dagbag.py:348} ERROR - Failed to import: /home/felipe/airflow/dags/10_non_atomic_send.py
Traceback (most recent call last):
  File "/home/felipe/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/felipe/airflow/dags/10_non_atomic_send.py", line 12, in <module>
    import pandas as pd
ModuleNotFoundError: No module named 'pandas'
[2023-12-31T09:36:36.050-0300] {processor.py:842} WARNING - No viable dags retrieved from /home/felipe/airflow/dags/10_non_atomic_send.py
[2023-12-31T09:36:36.139-0300] {processor.py:183} INFO - Processing /home/felipe/airflow/dags/10_non_atomic_send.py took 0.111 seconds
[2023-12-31T09:38:25.979-0300] {processor.py:161} INFO - Started process (PID=32165) to work on /home/felipe/airflow/dags/10_non_atomic_send.py
[2023-12-31T09:38:26.020-0300] {processor.py:830} INFO - Processing file /home/felipe/airflow/dags/10_non_atomic_send.py for tasks to queue
[2023-12-31T09:38:26.047-0300] {logging_mixin.py:188} INFO - [2023-12-31T09:38:26.039-0300] {dagbag.py:538} INFO - Filling up the DagBag from /home/felipe/airflow/dags/10_non_atomic_send.py
[2023-12-31T09:38:26.097-0300] {logging_mixin.py:188} INFO - [2023-12-31T09:38:26.078-0300] {dagbag.py:348} ERROR - Failed to import: /home/felipe/airflow/dags/10_non_atomic_send.py
Traceback (most recent call last):
  File "/home/felipe/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/felipe/airflow/dags/10_non_atomic_send.py", line 12, in <module>
    import pandas as pd
ModuleNotFoundError: No module named 'pandas'
[2023-12-31T09:38:26.110-0300] {processor.py:842} WARNING - No viable dags retrieved from /home/felipe/airflow/dags/10_non_atomic_send.py
[2023-12-31T09:38:26.387-0300] {processor.py:183} INFO - Processing /home/felipe/airflow/dags/10_non_atomic_send.py took 0.447 seconds
[2023-12-31T09:51:55.207-0300] {processor.py:161} INFO - Started process (PID=32762) to work on /home/felipe/airflow/dags/10_non_atomic_send.py
[2023-12-31T09:51:55.209-0300] {processor.py:830} INFO - Processing file /home/felipe/airflow/dags/10_non_atomic_send.py for tasks to queue
[2023-12-31T09:51:55.217-0300] {logging_mixin.py:188} INFO - [2023-12-31T09:51:55.216-0300] {dagbag.py:538} INFO - Filling up the DagBag from /home/felipe/airflow/dags/10_non_atomic_send.py
[2023-12-31T09:51:55.229-0300] {logging_mixin.py:188} INFO - [2023-12-31T09:51:55.227-0300] {dagbag.py:348} ERROR - Failed to import: /home/felipe/airflow/dags/10_non_atomic_send.py
Traceback (most recent call last):
  File "/home/felipe/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/felipe/airflow/dags/10_non_atomic_send.py", line 12, in <module>
    import pandas as pd
ModuleNotFoundError: No module named 'pandas'
[2023-12-31T09:51:55.230-0300] {processor.py:842} WARNING - No viable dags retrieved from /home/felipe/airflow/dags/10_non_atomic_send.py
[2023-12-31T09:51:55.358-0300] {processor.py:183} INFO - Processing /home/felipe/airflow/dags/10_non_atomic_send.py took 0.162 seconds
[2023-12-31T09:55:14.368-0300] {processor.py:161} INFO - Started process (PID=32924) to work on /home/felipe/airflow/dags/10_non_atomic_send.py
[2023-12-31T09:55:14.376-0300] {processor.py:830} INFO - Processing file /home/felipe/airflow/dags/10_non_atomic_send.py for tasks to queue
[2023-12-31T09:55:14.378-0300] {logging_mixin.py:188} INFO - [2023-12-31T09:55:14.378-0300] {dagbag.py:538} INFO - Filling up the DagBag from /home/felipe/airflow/dags/10_non_atomic_send.py
[2023-12-31T09:55:14.390-0300] {logging_mixin.py:188} INFO - [2023-12-31T09:55:14.388-0300] {dagbag.py:348} ERROR - Failed to import: /home/felipe/airflow/dags/10_non_atomic_send.py
Traceback (most recent call last):
  File "/home/felipe/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/felipe/airflow/dags/10_non_atomic_send.py", line 12, in <module>
    import pandas as pd
ModuleNotFoundError: No module named 'pandas'
[2023-12-31T09:55:14.397-0300] {processor.py:842} WARNING - No viable dags retrieved from /home/felipe/airflow/dags/10_non_atomic_send.py
[2023-12-31T09:55:14.508-0300] {processor.py:183} INFO - Processing /home/felipe/airflow/dags/10_non_atomic_send.py took 0.150 seconds
[2023-12-31T09:59:51.266-0300] {processor.py:161} INFO - Started process (PID=33135) to work on /home/felipe/airflow/dags/10_non_atomic_send.py
[2023-12-31T09:59:51.269-0300] {processor.py:830} INFO - Processing file /home/felipe/airflow/dags/10_non_atomic_send.py for tasks to queue
[2023-12-31T09:59:51.276-0300] {logging_mixin.py:188} INFO - [2023-12-31T09:59:51.270-0300] {dagbag.py:538} INFO - Filling up the DagBag from /home/felipe/airflow/dags/10_non_atomic_send.py
[2023-12-31T09:59:51.288-0300] {logging_mixin.py:188} INFO - [2023-12-31T09:59:51.287-0300] {dagbag.py:348} ERROR - Failed to import: /home/felipe/airflow/dags/10_non_atomic_send.py
Traceback (most recent call last):
  File "/home/felipe/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/felipe/airflow/dags/10_non_atomic_send.py", line 12, in <module>
    import pandas as pd
ModuleNotFoundError: No module named 'pandas'
[2023-12-31T09:59:51.289-0300] {processor.py:842} WARNING - No viable dags retrieved from /home/felipe/airflow/dags/10_non_atomic_send.py
[2023-12-31T09:59:51.407-0300] {processor.py:183} INFO - Processing /home/felipe/airflow/dags/10_non_atomic_send.py took 0.157 seconds
[2023-12-31T10:01:17.318-0300] {processor.py:161} INFO - Started process (PID=33269) to work on /home/felipe/airflow/dags/10_non_atomic_send.py
[2023-12-31T10:01:17.327-0300] {processor.py:830} INFO - Processing file /home/felipe/airflow/dags/10_non_atomic_send.py for tasks to queue
[2023-12-31T10:01:17.328-0300] {logging_mixin.py:188} INFO - [2023-12-31T10:01:17.328-0300] {dagbag.py:538} INFO - Filling up the DagBag from /home/felipe/airflow/dags/10_non_atomic_send.py
[2023-12-31T10:01:17.346-0300] {logging_mixin.py:188} INFO - [2023-12-31T10:01:17.339-0300] {dagbag.py:348} ERROR - Failed to import: /home/felipe/airflow/dags/10_non_atomic_send.py
Traceback (most recent call last):
  File "/home/felipe/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/felipe/airflow/dags/10_non_atomic_send.py", line 12, in <module>
    import pandas as pd
ModuleNotFoundError: No module named 'pandas'
[2023-12-31T10:01:17.347-0300] {processor.py:842} WARNING - No viable dags retrieved from /home/felipe/airflow/dags/10_non_atomic_send.py
[2023-12-31T10:01:17.438-0300] {processor.py:183} INFO - Processing /home/felipe/airflow/dags/10_non_atomic_send.py took 0.131 seconds
[2023-12-31T10:02:26.636-0300] {processor.py:161} INFO - Started process (PID=33336) to work on /home/felipe/airflow/dags/10_non_atomic_send.py
[2023-12-31T10:02:26.638-0300] {processor.py:830} INFO - Processing file /home/felipe/airflow/dags/10_non_atomic_send.py for tasks to queue
[2023-12-31T10:02:26.646-0300] {logging_mixin.py:188} INFO - [2023-12-31T10:02:26.640-0300] {dagbag.py:538} INFO - Filling up the DagBag from /home/felipe/airflow/dags/10_non_atomic_send.py
[2023-12-31T10:02:26.658-0300] {logging_mixin.py:188} INFO - [2023-12-31T10:02:26.657-0300] {dagbag.py:348} ERROR - Failed to import: /home/felipe/airflow/dags/10_non_atomic_send.py
Traceback (most recent call last):
  File "/home/felipe/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/felipe/airflow/dags/10_non_atomic_send.py", line 12, in <module>
    import pandas as pd
ModuleNotFoundError: No module named 'pandas'
[2023-12-31T10:02:26.659-0300] {processor.py:842} WARNING - No viable dags retrieved from /home/felipe/airflow/dags/10_non_atomic_send.py
[2023-12-31T10:02:26.768-0300] {processor.py:183} INFO - Processing /home/felipe/airflow/dags/10_non_atomic_send.py took 0.149 seconds
[2023-12-31T10:03:31.539-0300] {processor.py:161} INFO - Started process (PID=33402) to work on /home/felipe/airflow/dags/10_non_atomic_send.py
[2023-12-31T10:03:31.548-0300] {processor.py:830} INFO - Processing file /home/felipe/airflow/dags/10_non_atomic_send.py for tasks to queue
[2023-12-31T10:03:31.549-0300] {logging_mixin.py:188} INFO - [2023-12-31T10:03:31.549-0300] {dagbag.py:538} INFO - Filling up the DagBag from /home/felipe/airflow/dags/10_non_atomic_send.py
[2023-12-31T10:03:31.567-0300] {logging_mixin.py:188} INFO - [2023-12-31T10:03:31.559-0300] {dagbag.py:348} ERROR - Failed to import: /home/felipe/airflow/dags/10_non_atomic_send.py
Traceback (most recent call last):
  File "/home/felipe/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/felipe/airflow/dags/10_non_atomic_send.py", line 12, in <module>
    import pandas as pd
ModuleNotFoundError: No module named 'pandas'
[2023-12-31T10:03:31.568-0300] {processor.py:842} WARNING - No viable dags retrieved from /home/felipe/airflow/dags/10_non_atomic_send.py
[2023-12-31T10:03:31.659-0300] {processor.py:183} INFO - Processing /home/felipe/airflow/dags/10_non_atomic_send.py took 0.130 seconds
[2023-12-31T10:04:42.418-0300] {processor.py:161} INFO - Started process (PID=33488) to work on /home/felipe/airflow/dags/10_non_atomic_send.py
[2023-12-31T10:04:42.427-0300] {processor.py:830} INFO - Processing file /home/felipe/airflow/dags/10_non_atomic_send.py for tasks to queue
[2023-12-31T10:04:42.429-0300] {logging_mixin.py:188} INFO - [2023-12-31T10:04:42.428-0300] {dagbag.py:538} INFO - Filling up the DagBag from /home/felipe/airflow/dags/10_non_atomic_send.py
[2023-12-31T10:04:42.447-0300] {logging_mixin.py:188} INFO - [2023-12-31T10:04:42.439-0300] {dagbag.py:348} ERROR - Failed to import: /home/felipe/airflow/dags/10_non_atomic_send.py
Traceback (most recent call last):
  File "/home/felipe/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/felipe/airflow/dags/10_non_atomic_send.py", line 12, in <module>
    import pandas as pd
ModuleNotFoundError: No module named 'pandas'
[2023-12-31T10:04:42.447-0300] {processor.py:842} WARNING - No viable dags retrieved from /home/felipe/airflow/dags/10_non_atomic_send.py
[2023-12-31T10:04:42.547-0300] {processor.py:183} INFO - Processing /home/felipe/airflow/dags/10_non_atomic_send.py took 0.147 seconds
[2023-12-31T10:05:53.530-0300] {processor.py:161} INFO - Started process (PID=33568) to work on /home/felipe/airflow/dags/10_non_atomic_send.py
[2023-12-31T10:05:53.539-0300] {processor.py:830} INFO - Processing file /home/felipe/airflow/dags/10_non_atomic_send.py for tasks to queue
[2023-12-31T10:05:53.549-0300] {logging_mixin.py:188} INFO - [2023-12-31T10:05:53.548-0300] {dagbag.py:538} INFO - Filling up the DagBag from /home/felipe/airflow/dags/10_non_atomic_send.py
[2023-12-31T10:05:53.578-0300] {logging_mixin.py:188} INFO - [2023-12-31T10:05:53.569-0300] {dagbag.py:348} ERROR - Failed to import: /home/felipe/airflow/dags/10_non_atomic_send.py
Traceback (most recent call last):
  File "/home/felipe/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/felipe/airflow/dags/10_non_atomic_send.py", line 12, in <module>
    import pandas as pd
ModuleNotFoundError: No module named 'pandas'
[2023-12-31T10:05:53.579-0300] {processor.py:842} WARNING - No viable dags retrieved from /home/felipe/airflow/dags/10_non_atomic_send.py
[2023-12-31T10:05:53.729-0300] {processor.py:183} INFO - Processing /home/felipe/airflow/dags/10_non_atomic_send.py took 0.211 seconds
[2023-12-31T10:07:04.547-0300] {processor.py:161} INFO - Started process (PID=33683) to work on /home/felipe/airflow/dags/10_non_atomic_send.py
[2023-12-31T10:07:04.550-0300] {processor.py:830} INFO - Processing file /home/felipe/airflow/dags/10_non_atomic_send.py for tasks to queue
[2023-12-31T10:07:04.558-0300] {logging_mixin.py:188} INFO - [2023-12-31T10:07:04.557-0300] {dagbag.py:538} INFO - Filling up the DagBag from /home/felipe/airflow/dags/10_non_atomic_send.py
[2023-12-31T10:07:04.576-0300] {logging_mixin.py:188} INFO - [2023-12-31T10:07:04.568-0300] {dagbag.py:348} ERROR - Failed to import: /home/felipe/airflow/dags/10_non_atomic_send.py
Traceback (most recent call last):
  File "/home/felipe/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/felipe/airflow/dags/10_non_atomic_send.py", line 12, in <module>
    import pandas as pd
ModuleNotFoundError: No module named 'pandas'
[2023-12-31T10:07:04.577-0300] {processor.py:842} WARNING - No viable dags retrieved from /home/felipe/airflow/dags/10_non_atomic_send.py
[2023-12-31T10:07:04.679-0300] {processor.py:183} INFO - Processing /home/felipe/airflow/dags/10_non_atomic_send.py took 0.143 seconds
[2023-12-31T10:08:17.348-0300] {processor.py:161} INFO - Started process (PID=33761) to work on /home/felipe/airflow/dags/10_non_atomic_send.py
[2023-12-31T10:08:17.357-0300] {processor.py:830} INFO - Processing file /home/felipe/airflow/dags/10_non_atomic_send.py for tasks to queue
[2023-12-31T10:08:17.358-0300] {logging_mixin.py:188} INFO - [2023-12-31T10:08:17.358-0300] {dagbag.py:538} INFO - Filling up the DagBag from /home/felipe/airflow/dags/10_non_atomic_send.py
[2023-12-31T10:08:17.376-0300] {logging_mixin.py:188} INFO - [2023-12-31T10:08:17.368-0300] {dagbag.py:348} ERROR - Failed to import: /home/felipe/airflow/dags/10_non_atomic_send.py
Traceback (most recent call last):
  File "/home/felipe/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/felipe/airflow/dags/10_non_atomic_send.py", line 12, in <module>
    import pandas as pd
ModuleNotFoundError: No module named 'pandas'
[2023-12-31T10:08:17.377-0300] {processor.py:842} WARNING - No viable dags retrieved from /home/felipe/airflow/dags/10_non_atomic_send.py
[2023-12-31T10:08:17.469-0300] {processor.py:183} INFO - Processing /home/felipe/airflow/dags/10_non_atomic_send.py took 0.132 seconds
[2023-12-31T11:28:46.516-0300] {processor.py:161} INFO - Started process (PID=33949) to work on /home/felipe/airflow/dags/10_non_atomic_send.py
[2023-12-31T11:28:46.525-0300] {processor.py:830} INFO - Processing file /home/felipe/airflow/dags/10_non_atomic_send.py for tasks to queue
[2023-12-31T11:28:46.536-0300] {logging_mixin.py:188} INFO - [2023-12-31T11:28:46.527-0300] {dagbag.py:538} INFO - Filling up the DagBag from /home/felipe/airflow/dags/10_non_atomic_send.py
[2023-12-31T11:28:46.567-0300] {logging_mixin.py:188} INFO - [2023-12-31T11:28:46.564-0300] {dagbag.py:348} ERROR - Failed to import: /home/felipe/airflow/dags/10_non_atomic_send.py
Traceback (most recent call last):
  File "/home/felipe/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/felipe/airflow/dags/10_non_atomic_send.py", line 12, in <module>
    import pandas as pd
ModuleNotFoundError: No module named 'pandas'
[2023-12-31T11:28:46.575-0300] {processor.py:842} WARNING - No viable dags retrieved from /home/felipe/airflow/dags/10_non_atomic_send.py
[2023-12-31T11:28:46.727-0300] {processor.py:183} INFO - Processing /home/felipe/airflow/dags/10_non_atomic_send.py took 0.232 seconds
[2023-12-31T11:30:43.306-0300] {processor.py:161} INFO - Started process (PID=34220) to work on /home/felipe/airflow/dags/10_non_atomic_send.py
[2023-12-31T11:30:43.314-0300] {processor.py:830} INFO - Processing file /home/felipe/airflow/dags/10_non_atomic_send.py for tasks to queue
[2023-12-31T11:30:43.316-0300] {logging_mixin.py:188} INFO - [2023-12-31T11:30:43.316-0300] {dagbag.py:538} INFO - Filling up the DagBag from /home/felipe/airflow/dags/10_non_atomic_send.py
[2023-12-31T11:30:43.345-0300] {logging_mixin.py:188} INFO - [2023-12-31T11:30:43.336-0300] {dagbag.py:348} ERROR - Failed to import: /home/felipe/airflow/dags/10_non_atomic_send.py
Traceback (most recent call last):
  File "/home/felipe/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/felipe/airflow/dags/10_non_atomic_send.py", line 12, in <module>
    import pandas as pd
ModuleNotFoundError: No module named 'pandas'
[2023-12-31T11:30:43.354-0300] {processor.py:842} WARNING - No viable dags retrieved from /home/felipe/airflow/dags/10_non_atomic_send.py
[2023-12-31T11:30:43.507-0300] {processor.py:183} INFO - Processing /home/felipe/airflow/dags/10_non_atomic_send.py took 0.213 seconds
[2023-12-31T11:32:13.804-0300] {processor.py:161} INFO - Started process (PID=34331) to work on /home/felipe/airflow/dags/10_non_atomic_send.py
[2023-12-31T11:32:13.806-0300] {processor.py:830} INFO - Processing file /home/felipe/airflow/dags/10_non_atomic_send.py for tasks to queue
[2023-12-31T11:32:13.815-0300] {logging_mixin.py:188} INFO - [2023-12-31T11:32:13.814-0300] {dagbag.py:538} INFO - Filling up the DagBag from /home/felipe/airflow/dags/10_non_atomic_send.py
[2023-12-31T11:32:13.835-0300] {logging_mixin.py:188} INFO - [2023-12-31T11:32:13.826-0300] {dagbag.py:348} ERROR - Failed to import: /home/felipe/airflow/dags/10_non_atomic_send.py
Traceback (most recent call last):
  File "/home/felipe/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/felipe/airflow/dags/10_non_atomic_send.py", line 12, in <module>
    import pandas as pd
ModuleNotFoundError: No module named 'pandas'
[2023-12-31T11:32:13.836-0300] {processor.py:842} WARNING - No viable dags retrieved from /home/felipe/airflow/dags/10_non_atomic_send.py
[2023-12-31T11:32:13.985-0300] {processor.py:183} INFO - Processing /home/felipe/airflow/dags/10_non_atomic_send.py took 0.200 seconds
[2023-12-31T11:33:44.204-0300] {processor.py:161} INFO - Started process (PID=34433) to work on /home/felipe/airflow/dags/10_non_atomic_send.py
[2023-12-31T11:33:44.206-0300] {processor.py:830} INFO - Processing file /home/felipe/airflow/dags/10_non_atomic_send.py for tasks to queue
[2023-12-31T11:33:44.215-0300] {logging_mixin.py:188} INFO - [2023-12-31T11:33:44.214-0300] {dagbag.py:538} INFO - Filling up the DagBag from /home/felipe/airflow/dags/10_non_atomic_send.py
[2023-12-31T11:33:44.235-0300] {logging_mixin.py:188} INFO - [2023-12-31T11:33:44.227-0300] {dagbag.py:348} ERROR - Failed to import: /home/felipe/airflow/dags/10_non_atomic_send.py
Traceback (most recent call last):
  File "/home/felipe/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/felipe/airflow/dags/10_non_atomic_send.py", line 12, in <module>
    import pandas as pd
ModuleNotFoundError: No module named 'pandas'
[2023-12-31T11:33:44.236-0300] {processor.py:842} WARNING - No viable dags retrieved from /home/felipe/airflow/dags/10_non_atomic_send.py
[2023-12-31T11:33:44.386-0300] {processor.py:183} INFO - Processing /home/felipe/airflow/dags/10_non_atomic_send.py took 0.200 seconds
[2023-12-31T11:35:07.034-0300] {processor.py:161} INFO - Started process (PID=34551) to work on /home/felipe/airflow/dags/10_non_atomic_send.py
[2023-12-31T11:35:07.044-0300] {processor.py:830} INFO - Processing file /home/felipe/airflow/dags/10_non_atomic_send.py for tasks to queue
[2023-12-31T11:35:07.046-0300] {logging_mixin.py:188} INFO - [2023-12-31T11:35:07.045-0300] {dagbag.py:538} INFO - Filling up the DagBag from /home/felipe/airflow/dags/10_non_atomic_send.py
[2023-12-31T11:35:07.066-0300] {logging_mixin.py:188} INFO - [2023-12-31T11:35:07.065-0300] {dagbag.py:348} ERROR - Failed to import: /home/felipe/airflow/dags/10_non_atomic_send.py
Traceback (most recent call last):
  File "/home/felipe/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/felipe/airflow/dags/10_non_atomic_send.py", line 12, in <module>
    import pandas as pd
ModuleNotFoundError: No module named 'pandas'
[2023-12-31T11:35:07.074-0300] {processor.py:842} WARNING - No viable dags retrieved from /home/felipe/airflow/dags/10_non_atomic_send.py
[2023-12-31T11:35:07.227-0300] {processor.py:183} INFO - Processing /home/felipe/airflow/dags/10_non_atomic_send.py took 0.213 seconds
[2023-12-31T11:36:30.415-0300] {processor.py:161} INFO - Started process (PID=34644) to work on /home/felipe/airflow/dags/10_non_atomic_send.py
[2023-12-31T11:36:30.424-0300] {processor.py:830} INFO - Processing file /home/felipe/airflow/dags/10_non_atomic_send.py for tasks to queue
[2023-12-31T11:36:30.426-0300] {logging_mixin.py:188} INFO - [2023-12-31T11:36:30.425-0300] {dagbag.py:538} INFO - Filling up the DagBag from /home/felipe/airflow/dags/10_non_atomic_send.py
[2023-12-31T11:36:30.445-0300] {logging_mixin.py:188} INFO - [2023-12-31T11:36:30.444-0300] {dagbag.py:348} ERROR - Failed to import: /home/felipe/airflow/dags/10_non_atomic_send.py
Traceback (most recent call last):
  File "/home/felipe/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/felipe/airflow/dags/10_non_atomic_send.py", line 12, in <module>
    import pandas as pd
ModuleNotFoundError: No module named 'pandas'
[2023-12-31T11:36:30.446-0300] {processor.py:842} WARNING - No viable dags retrieved from /home/felipe/airflow/dags/10_non_atomic_send.py
[2023-12-31T11:36:30.564-0300] {processor.py:183} INFO - Processing /home/felipe/airflow/dags/10_non_atomic_send.py took 0.160 seconds
[2023-12-31T11:37:53.856-0300] {processor.py:161} INFO - Started process (PID=34733) to work on /home/felipe/airflow/dags/10_non_atomic_send.py
[2023-12-31T11:37:53.865-0300] {processor.py:830} INFO - Processing file /home/felipe/airflow/dags/10_non_atomic_send.py for tasks to queue
[2023-12-31T11:37:53.867-0300] {logging_mixin.py:188} INFO - [2023-12-31T11:37:53.866-0300] {dagbag.py:538} INFO - Filling up the DagBag from /home/felipe/airflow/dags/10_non_atomic_send.py
[2023-12-31T11:37:53.895-0300] {logging_mixin.py:188} INFO - [2023-12-31T11:37:53.886-0300] {dagbag.py:348} ERROR - Failed to import: /home/felipe/airflow/dags/10_non_atomic_send.py
Traceback (most recent call last):
  File "/home/felipe/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/felipe/airflow/dags/10_non_atomic_send.py", line 12, in <module>
    import pandas as pd
ModuleNotFoundError: No module named 'pandas'
[2023-12-31T11:37:53.896-0300] {processor.py:842} WARNING - No viable dags retrieved from /home/felipe/airflow/dags/10_non_atomic_send.py
[2023-12-31T11:37:54.025-0300] {processor.py:183} INFO - Processing /home/felipe/airflow/dags/10_non_atomic_send.py took 0.181 seconds
[2023-12-31T11:39:15.956-0300] {processor.py:161} INFO - Started process (PID=34822) to work on /home/felipe/airflow/dags/10_non_atomic_send.py
[2023-12-31T11:39:15.974-0300] {processor.py:830} INFO - Processing file /home/felipe/airflow/dags/10_non_atomic_send.py for tasks to queue
[2023-12-31T11:39:15.976-0300] {logging_mixin.py:188} INFO - [2023-12-31T11:39:15.975-0300] {dagbag.py:538} INFO - Filling up the DagBag from /home/felipe/airflow/dags/10_non_atomic_send.py
[2023-12-31T11:39:15.995-0300] {logging_mixin.py:188} INFO - [2023-12-31T11:39:15.986-0300] {dagbag.py:348} ERROR - Failed to import: /home/felipe/airflow/dags/10_non_atomic_send.py
Traceback (most recent call last):
  File "/home/felipe/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/felipe/airflow/dags/10_non_atomic_send.py", line 12, in <module>
    import pandas as pd
ModuleNotFoundError: No module named 'pandas'
[2023-12-31T11:39:15.996-0300] {processor.py:842} WARNING - No viable dags retrieved from /home/felipe/airflow/dags/10_non_atomic_send.py
[2023-12-31T11:39:16.155-0300] {processor.py:183} INFO - Processing /home/felipe/airflow/dags/10_non_atomic_send.py took 0.220 seconds
[2023-12-31T11:40:39.005-0300] {processor.py:161} INFO - Started process (PID=34942) to work on /home/felipe/airflow/dags/10_non_atomic_send.py
[2023-12-31T11:40:39.014-0300] {processor.py:830} INFO - Processing file /home/felipe/airflow/dags/10_non_atomic_send.py for tasks to queue
[2023-12-31T11:40:39.015-0300] {logging_mixin.py:188} INFO - [2023-12-31T11:40:39.015-0300] {dagbag.py:538} INFO - Filling up the DagBag from /home/felipe/airflow/dags/10_non_atomic_send.py
[2023-12-31T11:40:39.036-0300] {logging_mixin.py:188} INFO - [2023-12-31T11:40:39.034-0300] {dagbag.py:348} ERROR - Failed to import: /home/felipe/airflow/dags/10_non_atomic_send.py
Traceback (most recent call last):
  File "/home/felipe/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/felipe/airflow/dags/10_non_atomic_send.py", line 12, in <module>
    import pandas as pd
ModuleNotFoundError: No module named 'pandas'
[2023-12-31T11:40:39.044-0300] {processor.py:842} WARNING - No viable dags retrieved from /home/felipe/airflow/dags/10_non_atomic_send.py
[2023-12-31T11:40:39.185-0300] {processor.py:183} INFO - Processing /home/felipe/airflow/dags/10_non_atomic_send.py took 0.200 seconds
[2023-12-31T11:42:12.695-0300] {processor.py:161} INFO - Started process (PID=35050) to work on /home/felipe/airflow/dags/10_non_atomic_send.py
[2023-12-31T11:42:12.705-0300] {processor.py:830} INFO - Processing file /home/felipe/airflow/dags/10_non_atomic_send.py for tasks to queue
[2023-12-31T11:42:12.714-0300] {logging_mixin.py:188} INFO - [2023-12-31T11:42:12.706-0300] {dagbag.py:538} INFO - Filling up the DagBag from /home/felipe/airflow/dags/10_non_atomic_send.py
[2023-12-31T11:42:12.736-0300] {logging_mixin.py:188} INFO - [2023-12-31T11:42:12.734-0300] {dagbag.py:348} ERROR - Failed to import: /home/felipe/airflow/dags/10_non_atomic_send.py
Traceback (most recent call last):
  File "/home/felipe/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/felipe/airflow/dags/10_non_atomic_send.py", line 12, in <module>
    import pandas as pd
ModuleNotFoundError: No module named 'pandas'
[2023-12-31T11:42:12.744-0300] {processor.py:842} WARNING - No viable dags retrieved from /home/felipe/airflow/dags/10_non_atomic_send.py
[2023-12-31T11:42:12.886-0300] {processor.py:183} INFO - Processing /home/felipe/airflow/dags/10_non_atomic_send.py took 0.210 seconds
[2023-12-31T11:43:48.935-0300] {processor.py:161} INFO - Started process (PID=35160) to work on /home/felipe/airflow/dags/10_non_atomic_send.py
[2023-12-31T11:43:48.944-0300] {processor.py:830} INFO - Processing file /home/felipe/airflow/dags/10_non_atomic_send.py for tasks to queue
[2023-12-31T11:43:48.946-0300] {logging_mixin.py:188} INFO - [2023-12-31T11:43:48.946-0300] {dagbag.py:538} INFO - Filling up the DagBag from /home/felipe/airflow/dags/10_non_atomic_send.py
[2023-12-31T11:43:48.966-0300] {logging_mixin.py:188} INFO - [2023-12-31T11:43:48.965-0300] {dagbag.py:348} ERROR - Failed to import: /home/felipe/airflow/dags/10_non_atomic_send.py
Traceback (most recent call last):
  File "/home/felipe/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/felipe/airflow/dags/10_non_atomic_send.py", line 12, in <module>
    import pandas as pd
ModuleNotFoundError: No module named 'pandas'
[2023-12-31T11:43:48.974-0300] {processor.py:842} WARNING - No viable dags retrieved from /home/felipe/airflow/dags/10_non_atomic_send.py
[2023-12-31T11:43:49.106-0300] {processor.py:183} INFO - Processing /home/felipe/airflow/dags/10_non_atomic_send.py took 0.190 seconds
[2023-12-31T11:45:29.636-0300] {processor.py:161} INFO - Started process (PID=35293) to work on /home/felipe/airflow/dags/10_non_atomic_send.py
[2023-12-31T11:45:29.655-0300] {processor.py:830} INFO - Processing file /home/felipe/airflow/dags/10_non_atomic_send.py for tasks to queue
[2023-12-31T11:45:29.664-0300] {logging_mixin.py:188} INFO - [2023-12-31T11:45:29.656-0300] {dagbag.py:538} INFO - Filling up the DagBag from /home/felipe/airflow/dags/10_non_atomic_send.py
[2023-12-31T11:45:29.685-0300] {logging_mixin.py:188} INFO - [2023-12-31T11:45:29.684-0300] {dagbag.py:348} ERROR - Failed to import: /home/felipe/airflow/dags/10_non_atomic_send.py
Traceback (most recent call last):
  File "/home/felipe/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/felipe/airflow/dags/10_non_atomic_send.py", line 12, in <module>
    import pandas as pd
ModuleNotFoundError: No module named 'pandas'
[2023-12-31T11:45:29.686-0300] {processor.py:842} WARNING - No viable dags retrieved from /home/felipe/airflow/dags/10_non_atomic_send.py
[2023-12-31T11:45:29.876-0300] {processor.py:183} INFO - Processing /home/felipe/airflow/dags/10_non_atomic_send.py took 0.252 seconds
[2023-12-31T11:47:07.355-0300] {processor.py:161} INFO - Started process (PID=35420) to work on /home/felipe/airflow/dags/10_non_atomic_send.py
[2023-12-31T11:47:07.364-0300] {processor.py:830} INFO - Processing file /home/felipe/airflow/dags/10_non_atomic_send.py for tasks to queue
[2023-12-31T11:47:07.374-0300] {logging_mixin.py:188} INFO - [2023-12-31T11:47:07.366-0300] {dagbag.py:538} INFO - Filling up the DagBag from /home/felipe/airflow/dags/10_non_atomic_send.py
[2023-12-31T11:47:07.394-0300] {logging_mixin.py:188} INFO - [2023-12-31T11:47:07.385-0300] {dagbag.py:348} ERROR - Failed to import: /home/felipe/airflow/dags/10_non_atomic_send.py
Traceback (most recent call last):
  File "/home/felipe/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/felipe/airflow/dags/10_non_atomic_send.py", line 12, in <module>
    import pandas as pd
ModuleNotFoundError: No module named 'pandas'
[2023-12-31T11:47:07.395-0300] {processor.py:842} WARNING - No viable dags retrieved from /home/felipe/airflow/dags/10_non_atomic_send.py
[2023-12-31T11:47:07.574-0300] {processor.py:183} INFO - Processing /home/felipe/airflow/dags/10_non_atomic_send.py took 0.240 seconds
[2023-12-31T11:49:18.425-0300] {processor.py:161} INFO - Started process (PID=35582) to work on /home/felipe/airflow/dags/10_non_atomic_send.py
[2023-12-31T11:49:18.434-0300] {processor.py:830} INFO - Processing file /home/felipe/airflow/dags/10_non_atomic_send.py for tasks to queue
[2023-12-31T11:49:18.436-0300] {logging_mixin.py:188} INFO - [2023-12-31T11:49:18.435-0300] {dagbag.py:538} INFO - Filling up the DagBag from /home/felipe/airflow/dags/10_non_atomic_send.py
[2023-12-31T11:49:18.466-0300] {logging_mixin.py:188} INFO - [2023-12-31T11:49:18.464-0300] {dagbag.py:348} ERROR - Failed to import: /home/felipe/airflow/dags/10_non_atomic_send.py
Traceback (most recent call last):
  File "/home/felipe/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/felipe/airflow/dags/10_non_atomic_send.py", line 12, in <module>
    import pandas as pd
ModuleNotFoundError: No module named 'pandas'
[2023-12-31T11:49:18.475-0300] {processor.py:842} WARNING - No viable dags retrieved from /home/felipe/airflow/dags/10_non_atomic_send.py
[2023-12-31T11:49:18.655-0300] {processor.py:183} INFO - Processing /home/felipe/airflow/dags/10_non_atomic_send.py took 0.250 seconds
[2023-12-31T11:51:28.554-0300] {processor.py:161} INFO - Started process (PID=35730) to work on /home/felipe/airflow/dags/10_non_atomic_send.py
[2023-12-31T11:51:28.565-0300] {processor.py:830} INFO - Processing file /home/felipe/airflow/dags/10_non_atomic_send.py for tasks to queue
[2023-12-31T11:51:28.584-0300] {logging_mixin.py:188} INFO - [2023-12-31T11:51:28.575-0300] {dagbag.py:538} INFO - Filling up the DagBag from /home/felipe/airflow/dags/10_non_atomic_send.py
[2023-12-31T11:51:28.644-0300] {logging_mixin.py:188} INFO - [2023-12-31T11:51:28.624-0300] {dagbag.py:348} ERROR - Failed to import: /home/felipe/airflow/dags/10_non_atomic_send.py
Traceback (most recent call last):
  File "/home/felipe/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/felipe/airflow/dags/10_non_atomic_send.py", line 12, in <module>
    import pandas as pd
ModuleNotFoundError: No module named 'pandas'
[2023-12-31T11:51:28.646-0300] {processor.py:842} WARNING - No viable dags retrieved from /home/felipe/airflow/dags/10_non_atomic_send.py
[2023-12-31T11:51:28.915-0300] {processor.py:183} INFO - Processing /home/felipe/airflow/dags/10_non_atomic_send.py took 0.401 seconds
[2023-12-31T11:54:12.256-0300] {processor.py:161} INFO - Started process (PID=35858) to work on /home/felipe/airflow/dags/10_non_atomic_send.py
[2023-12-31T11:54:12.275-0300] {processor.py:830} INFO - Processing file /home/felipe/airflow/dags/10_non_atomic_send.py for tasks to queue
[2023-12-31T11:54:12.285-0300] {logging_mixin.py:188} INFO - [2023-12-31T11:54:12.284-0300] {dagbag.py:538} INFO - Filling up the DagBag from /home/felipe/airflow/dags/10_non_atomic_send.py
[2023-12-31T11:54:12.325-0300] {logging_mixin.py:188} INFO - [2023-12-31T11:54:12.306-0300] {dagbag.py:348} ERROR - Failed to import: /home/felipe/airflow/dags/10_non_atomic_send.py
Traceback (most recent call last):
  File "/home/felipe/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/felipe/airflow/dags/10_non_atomic_send.py", line 12, in <module>
    import pandas as pd
ModuleNotFoundError: No module named 'pandas'
[2023-12-31T11:54:12.334-0300] {processor.py:842} WARNING - No viable dags retrieved from /home/felipe/airflow/dags/10_non_atomic_send.py
[2023-12-31T11:54:12.575-0300] {processor.py:183} INFO - Processing /home/felipe/airflow/dags/10_non_atomic_send.py took 0.341 seconds
[2023-12-31T11:56:06.705-0300] {processor.py:161} INFO - Started process (PID=36001) to work on /home/felipe/airflow/dags/10_non_atomic_send.py
[2023-12-31T11:56:06.714-0300] {processor.py:830} INFO - Processing file /home/felipe/airflow/dags/10_non_atomic_send.py for tasks to queue
[2023-12-31T11:56:06.724-0300] {logging_mixin.py:188} INFO - [2023-12-31T11:56:06.715-0300] {dagbag.py:538} INFO - Filling up the DagBag from /home/felipe/airflow/dags/10_non_atomic_send.py
[2023-12-31T11:56:06.745-0300] {logging_mixin.py:188} INFO - [2023-12-31T11:56:06.735-0300] {dagbag.py:348} ERROR - Failed to import: /home/felipe/airflow/dags/10_non_atomic_send.py
Traceback (most recent call last):
  File "/home/felipe/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/felipe/airflow/dags/10_non_atomic_send.py", line 12, in <module>
    import pandas as pd
ModuleNotFoundError: No module named 'pandas'
[2023-12-31T11:56:06.745-0300] {processor.py:842} WARNING - No viable dags retrieved from /home/felipe/airflow/dags/10_non_atomic_send.py
[2023-12-31T11:56:06.925-0300] {processor.py:183} INFO - Processing /home/felipe/airflow/dags/10_non_atomic_send.py took 0.241 seconds
[2023-12-31T11:57:51.534-0300] {processor.py:161} INFO - Started process (PID=36098) to work on /home/felipe/airflow/dags/10_non_atomic_send.py
[2023-12-31T11:57:51.546-0300] {processor.py:830} INFO - Processing file /home/felipe/airflow/dags/10_non_atomic_send.py for tasks to queue
[2023-12-31T11:57:51.555-0300] {logging_mixin.py:188} INFO - [2023-12-31T11:57:51.555-0300] {dagbag.py:538} INFO - Filling up the DagBag from /home/felipe/airflow/dags/10_non_atomic_send.py
[2023-12-31T11:57:51.586-0300] {logging_mixin.py:188} INFO - [2023-12-31T11:57:51.575-0300] {dagbag.py:348} ERROR - Failed to import: /home/felipe/airflow/dags/10_non_atomic_send.py
Traceback (most recent call last):
  File "/home/felipe/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/felipe/airflow/dags/10_non_atomic_send.py", line 12, in <module>
    import pandas as pd
ModuleNotFoundError: No module named 'pandas'
[2023-12-31T11:57:51.595-0300] {processor.py:842} WARNING - No viable dags retrieved from /home/felipe/airflow/dags/10_non_atomic_send.py
[2023-12-31T11:57:51.776-0300] {processor.py:183} INFO - Processing /home/felipe/airflow/dags/10_non_atomic_send.py took 0.262 seconds
[2023-12-31T11:59:36.785-0300] {processor.py:161} INFO - Started process (PID=36205) to work on /home/felipe/airflow/dags/10_non_atomic_send.py
[2023-12-31T11:59:36.795-0300] {processor.py:830} INFO - Processing file /home/felipe/airflow/dags/10_non_atomic_send.py for tasks to queue
[2023-12-31T11:59:36.805-0300] {logging_mixin.py:188} INFO - [2023-12-31T11:59:36.804-0300] {dagbag.py:538} INFO - Filling up the DagBag from /home/felipe/airflow/dags/10_non_atomic_send.py
[2023-12-31T11:59:36.844-0300] {logging_mixin.py:188} INFO - [2023-12-31T11:59:36.834-0300] {dagbag.py:348} ERROR - Failed to import: /home/felipe/airflow/dags/10_non_atomic_send.py
Traceback (most recent call last):
  File "/home/felipe/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/felipe/airflow/dags/10_non_atomic_send.py", line 12, in <module>
    import pandas as pd
ModuleNotFoundError: No module named 'pandas'
[2023-12-31T11:59:36.845-0300] {processor.py:842} WARNING - No viable dags retrieved from /home/felipe/airflow/dags/10_non_atomic_send.py
[2023-12-31T11:59:37.065-0300] {processor.py:183} INFO - Processing /home/felipe/airflow/dags/10_non_atomic_send.py took 0.301 seconds
[2023-12-31T12:01:24.855-0300] {processor.py:161} INFO - Started process (PID=36335) to work on /home/felipe/airflow/dags/10_non_atomic_send.py
[2023-12-31T12:01:24.874-0300] {processor.py:830} INFO - Processing file /home/felipe/airflow/dags/10_non_atomic_send.py for tasks to queue
[2023-12-31T12:01:24.884-0300] {logging_mixin.py:188} INFO - [2023-12-31T12:01:24.884-0300] {dagbag.py:538} INFO - Filling up the DagBag from /home/felipe/airflow/dags/10_non_atomic_send.py
[2023-12-31T12:01:24.915-0300] {logging_mixin.py:188} INFO - [2023-12-31T12:01:24.905-0300] {dagbag.py:348} ERROR - Failed to import: /home/felipe/airflow/dags/10_non_atomic_send.py
Traceback (most recent call last):
  File "/home/felipe/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/felipe/airflow/dags/10_non_atomic_send.py", line 12, in <module>
    import pandas as pd
ModuleNotFoundError: No module named 'pandas'
[2023-12-31T12:01:24.924-0300] {processor.py:842} WARNING - No viable dags retrieved from /home/felipe/airflow/dags/10_non_atomic_send.py
[2023-12-31T12:01:25.145-0300] {processor.py:183} INFO - Processing /home/felipe/airflow/dags/10_non_atomic_send.py took 0.311 seconds
[2023-12-31T12:03:24.534-0300] {processor.py:161} INFO - Started process (PID=36448) to work on /home/felipe/airflow/dags/10_non_atomic_send.py
[2023-12-31T12:03:24.544-0300] {processor.py:830} INFO - Processing file /home/felipe/airflow/dags/10_non_atomic_send.py for tasks to queue
[2023-12-31T12:03:24.554-0300] {logging_mixin.py:188} INFO - [2023-12-31T12:03:24.545-0300] {dagbag.py:538} INFO - Filling up the DagBag from /home/felipe/airflow/dags/10_non_atomic_send.py
[2023-12-31T12:03:24.585-0300] {logging_mixin.py:188} INFO - [2023-12-31T12:03:24.575-0300] {dagbag.py:348} ERROR - Failed to import: /home/felipe/airflow/dags/10_non_atomic_send.py
Traceback (most recent call last):
  File "/home/felipe/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/felipe/airflow/dags/10_non_atomic_send.py", line 12, in <module>
    import pandas as pd
ModuleNotFoundError: No module named 'pandas'
[2023-12-31T12:03:24.585-0300] {processor.py:842} WARNING - No viable dags retrieved from /home/felipe/airflow/dags/10_non_atomic_send.py
[2023-12-31T12:03:24.824-0300] {processor.py:183} INFO - Processing /home/felipe/airflow/dags/10_non_atomic_send.py took 0.311 seconds
[2023-12-31T12:06:44.255-0300] {processor.py:161} INFO - Started process (PID=36694) to work on /home/felipe/airflow/dags/10_non_atomic_send.py
[2023-12-31T12:06:44.275-0300] {processor.py:830} INFO - Processing file /home/felipe/airflow/dags/10_non_atomic_send.py for tasks to queue
[2023-12-31T12:06:44.295-0300] {logging_mixin.py:188} INFO - [2023-12-31T12:06:44.285-0300] {dagbag.py:538} INFO - Filling up the DagBag from /home/felipe/airflow/dags/10_non_atomic_send.py
[2023-12-31T12:06:44.344-0300] {logging_mixin.py:188} INFO - [2023-12-31T12:06:44.325-0300] {dagbag.py:348} ERROR - Failed to import: /home/felipe/airflow/dags/10_non_atomic_send.py
Traceback (most recent call last):
  File "/home/felipe/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/felipe/airflow/dags/10_non_atomic_send.py", line 12, in <module>
    import pandas as pd
ModuleNotFoundError: No module named 'pandas'
[2023-12-31T12:06:44.354-0300] {processor.py:842} WARNING - No viable dags retrieved from /home/felipe/airflow/dags/10_non_atomic_send.py
[2023-12-31T12:06:44.755-0300] {processor.py:183} INFO - Processing /home/felipe/airflow/dags/10_non_atomic_send.py took 0.541 seconds
[2023-12-31T12:10:09.634-0300] {processor.py:161} INFO - Started process (PID=37079) to work on /home/felipe/airflow/dags/10_non_atomic_send.py
[2023-12-31T12:10:09.655-0300] {processor.py:830} INFO - Processing file /home/felipe/airflow/dags/10_non_atomic_send.py for tasks to queue
[2023-12-31T12:10:09.674-0300] {logging_mixin.py:188} INFO - [2023-12-31T12:10:09.665-0300] {dagbag.py:538} INFO - Filling up the DagBag from /home/felipe/airflow/dags/10_non_atomic_send.py
[2023-12-31T12:10:09.735-0300] {logging_mixin.py:188} INFO - [2023-12-31T12:10:09.715-0300] {dagbag.py:348} ERROR - Failed to import: /home/felipe/airflow/dags/10_non_atomic_send.py
Traceback (most recent call last):
  File "/home/felipe/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/felipe/airflow/dags/10_non_atomic_send.py", line 12, in <module>
    import pandas as pd
ModuleNotFoundError: No module named 'pandas'
[2023-12-31T12:10:09.745-0300] {processor.py:842} WARNING - No viable dags retrieved from /home/felipe/airflow/dags/10_non_atomic_send.py
[2023-12-31T12:10:10.144-0300] {processor.py:183} INFO - Processing /home/felipe/airflow/dags/10_non_atomic_send.py took 0.559 seconds
[2023-12-31T12:11:28.945-0300] {processor.py:161} INFO - Started process (PID=37181) to work on /home/felipe/airflow/dags/10_non_atomic_send.py
[2023-12-31T12:11:28.964-0300] {processor.py:830} INFO - Processing file /home/felipe/airflow/dags/10_non_atomic_send.py for tasks to queue
[2023-12-31T12:11:28.974-0300] {logging_mixin.py:188} INFO - [2023-12-31T12:11:28.974-0300] {dagbag.py:538} INFO - Filling up the DagBag from /home/felipe/airflow/dags/10_non_atomic_send.py
[2023-12-31T12:11:29.014-0300] {logging_mixin.py:188} INFO - [2023-12-31T12:11:29.004-0300] {dagbag.py:348} ERROR - Failed to import: /home/felipe/airflow/dags/10_non_atomic_send.py
Traceback (most recent call last):
  File "/home/felipe/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/felipe/airflow/dags/10_non_atomic_send.py", line 12, in <module>
    import pandas as pd
ModuleNotFoundError: No module named 'pandas'
[2023-12-31T12:11:29.015-0300] {processor.py:842} WARNING - No viable dags retrieved from /home/felipe/airflow/dags/10_non_atomic_send.py
[2023-12-31T12:11:29.265-0300] {processor.py:183} INFO - Processing /home/felipe/airflow/dags/10_non_atomic_send.py took 0.350 seconds
[2023-12-31T12:12:18.584-0300] {processor.py:161} INFO - Started process (PID=37243) to work on /home/felipe/airflow/dags/10_non_atomic_send.py
[2023-12-31T12:12:18.604-0300] {processor.py:830} INFO - Processing file /home/felipe/airflow/dags/10_non_atomic_send.py for tasks to queue
[2023-12-31T12:12:18.624-0300] {logging_mixin.py:188} INFO - [2023-12-31T12:12:18.615-0300] {dagbag.py:538} INFO - Filling up the DagBag from /home/felipe/airflow/dags/10_non_atomic_send.py
[2023-12-31T12:12:18.694-0300] {logging_mixin.py:188} INFO - [2023-12-31T12:12:18.675-0300] {dagbag.py:348} ERROR - Failed to import: /home/felipe/airflow/dags/10_non_atomic_send.py
Traceback (most recent call last):
  File "/home/felipe/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/felipe/airflow/dags/10_non_atomic_send.py", line 12, in <module>
    import pandas as pd
ModuleNotFoundError: No module named 'pandas'
[2023-12-31T12:12:18.704-0300] {processor.py:842} WARNING - No viable dags retrieved from /home/felipe/airflow/dags/10_non_atomic_send.py
[2023-12-31T12:12:18.984-0300] {processor.py:183} INFO - Processing /home/felipe/airflow/dags/10_non_atomic_send.py took 0.470 seconds
[2023-12-31T12:13:15.214-0300] {processor.py:161} INFO - Started process (PID=37321) to work on /home/felipe/airflow/dags/10_non_atomic_send.py
[2023-12-31T12:13:15.225-0300] {processor.py:830} INFO - Processing file /home/felipe/airflow/dags/10_non_atomic_send.py for tasks to queue
[2023-12-31T12:13:15.244-0300] {logging_mixin.py:188} INFO - [2023-12-31T12:13:15.235-0300] {dagbag.py:538} INFO - Filling up the DagBag from /home/felipe/airflow/dags/10_non_atomic_send.py
[2023-12-31T12:13:15.285-0300] {logging_mixin.py:188} INFO - [2023-12-31T12:13:15.274-0300] {dagbag.py:348} ERROR - Failed to import: /home/felipe/airflow/dags/10_non_atomic_send.py
Traceback (most recent call last):
  File "/home/felipe/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/felipe/airflow/dags/10_non_atomic_send.py", line 12, in <module>
    import pandas as pd
ModuleNotFoundError: No module named 'pandas'
[2023-12-31T12:13:15.295-0300] {processor.py:842} WARNING - No viable dags retrieved from /home/felipe/airflow/dags/10_non_atomic_send.py
[2023-12-31T12:13:15.584-0300] {processor.py:183} INFO - Processing /home/felipe/airflow/dags/10_non_atomic_send.py took 0.400 seconds
[2023-12-31T12:14:19.474-0300] {processor.py:161} INFO - Started process (PID=37403) to work on /home/felipe/airflow/dags/10_non_atomic_send.py
[2023-12-31T12:14:19.494-0300] {processor.py:830} INFO - Processing file /home/felipe/airflow/dags/10_non_atomic_send.py for tasks to queue
[2023-12-31T12:14:19.524-0300] {logging_mixin.py:188} INFO - [2023-12-31T12:14:19.514-0300] {dagbag.py:538} INFO - Filling up the DagBag from /home/felipe/airflow/dags/10_non_atomic_send.py
[2023-12-31T12:14:19.594-0300] {logging_mixin.py:188} INFO - [2023-12-31T12:14:19.574-0300] {dagbag.py:348} ERROR - Failed to import: /home/felipe/airflow/dags/10_non_atomic_send.py
Traceback (most recent call last):
  File "/home/felipe/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/felipe/airflow/dags/10_non_atomic_send.py", line 12, in <module>
    import pandas as pd
ModuleNotFoundError: No module named 'pandas'
[2023-12-31T12:14:19.604-0300] {processor.py:842} WARNING - No viable dags retrieved from /home/felipe/airflow/dags/10_non_atomic_send.py
[2023-12-31T12:14:19.874-0300] {processor.py:183} INFO - Processing /home/felipe/airflow/dags/10_non_atomic_send.py took 0.459 seconds
[2023-12-31T12:15:08.544-0300] {processor.py:161} INFO - Started process (PID=37499) to work on /home/felipe/airflow/dags/10_non_atomic_send.py
[2023-12-31T12:15:08.565-0300] {processor.py:830} INFO - Processing file /home/felipe/airflow/dags/10_non_atomic_send.py for tasks to queue
[2023-12-31T12:15:08.585-0300] {logging_mixin.py:188} INFO - [2023-12-31T12:15:08.575-0300] {dagbag.py:538} INFO - Filling up the DagBag from /home/felipe/airflow/dags/10_non_atomic_send.py
[2023-12-31T12:15:08.654-0300] {logging_mixin.py:188} INFO - [2023-12-31T12:15:08.625-0300] {dagbag.py:348} ERROR - Failed to import: /home/felipe/airflow/dags/10_non_atomic_send.py
Traceback (most recent call last):
  File "/home/felipe/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/felipe/airflow/dags/10_non_atomic_send.py", line 12, in <module>
    import pandas as pd
ModuleNotFoundError: No module named 'pandas'
[2023-12-31T12:15:08.664-0300] {processor.py:842} WARNING - No viable dags retrieved from /home/felipe/airflow/dags/10_non_atomic_send.py
[2023-12-31T12:15:09.094-0300] {processor.py:183} INFO - Processing /home/felipe/airflow/dags/10_non_atomic_send.py took 0.610 seconds
[2023-12-31T12:15:58.555-0300] {processor.py:161} INFO - Started process (PID=37560) to work on /home/felipe/airflow/dags/10_non_atomic_send.py
[2023-12-31T12:15:58.584-0300] {processor.py:830} INFO - Processing file /home/felipe/airflow/dags/10_non_atomic_send.py for tasks to queue
[2023-12-31T12:15:58.604-0300] {logging_mixin.py:188} INFO - [2023-12-31T12:15:58.595-0300] {dagbag.py:538} INFO - Filling up the DagBag from /home/felipe/airflow/dags/10_non_atomic_send.py
[2023-12-31T12:15:58.674-0300] {logging_mixin.py:188} INFO - [2023-12-31T12:15:58.654-0300] {dagbag.py:348} ERROR - Failed to import: /home/felipe/airflow/dags/10_non_atomic_send.py
Traceback (most recent call last):
  File "/home/felipe/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/felipe/airflow/dags/10_non_atomic_send.py", line 12, in <module>
    import pandas as pd
ModuleNotFoundError: No module named 'pandas'
[2023-12-31T12:15:58.684-0300] {processor.py:842} WARNING - No viable dags retrieved from /home/felipe/airflow/dags/10_non_atomic_send.py
[2023-12-31T12:15:59.064-0300] {processor.py:183} INFO - Processing /home/felipe/airflow/dags/10_non_atomic_send.py took 0.579 seconds
[2023-12-31T12:16:44.794-0300] {processor.py:161} INFO - Started process (PID=37619) to work on /home/felipe/airflow/dags/10_non_atomic_send.py
[2023-12-31T12:16:44.824-0300] {processor.py:830} INFO - Processing file /home/felipe/airflow/dags/10_non_atomic_send.py for tasks to queue
[2023-12-31T12:16:44.844-0300] {logging_mixin.py:188} INFO - [2023-12-31T12:16:44.834-0300] {dagbag.py:538} INFO - Filling up the DagBag from /home/felipe/airflow/dags/10_non_atomic_send.py
[2023-12-31T12:16:44.895-0300] {logging_mixin.py:188} INFO - [2023-12-31T12:16:44.875-0300] {dagbag.py:348} ERROR - Failed to import: /home/felipe/airflow/dags/10_non_atomic_send.py
Traceback (most recent call last):
  File "/home/felipe/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/felipe/airflow/dags/10_non_atomic_send.py", line 12, in <module>
    import pandas as pd
ModuleNotFoundError: No module named 'pandas'
[2023-12-31T12:16:44.905-0300] {processor.py:842} WARNING - No viable dags retrieved from /home/felipe/airflow/dags/10_non_atomic_send.py
[2023-12-31T12:16:45.335-0300] {processor.py:183} INFO - Processing /home/felipe/airflow/dags/10_non_atomic_send.py took 0.581 seconds
[2023-12-31T12:17:34.405-0300] {processor.py:161} INFO - Started process (PID=37689) to work on /home/felipe/airflow/dags/10_non_atomic_send.py
[2023-12-31T12:17:34.424-0300] {processor.py:830} INFO - Processing file /home/felipe/airflow/dags/10_non_atomic_send.py for tasks to queue
[2023-12-31T12:17:34.445-0300] {logging_mixin.py:188} INFO - [2023-12-31T12:17:34.444-0300] {dagbag.py:538} INFO - Filling up the DagBag from /home/felipe/airflow/dags/10_non_atomic_send.py
[2023-12-31T12:17:34.524-0300] {logging_mixin.py:188} INFO - [2023-12-31T12:17:34.504-0300] {dagbag.py:348} ERROR - Failed to import: /home/felipe/airflow/dags/10_non_atomic_send.py
Traceback (most recent call last):
  File "/home/felipe/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/felipe/airflow/dags/10_non_atomic_send.py", line 12, in <module>
    import pandas as pd
ModuleNotFoundError: No module named 'pandas'
[2023-12-31T12:17:34.534-0300] {processor.py:842} WARNING - No viable dags retrieved from /home/felipe/airflow/dags/10_non_atomic_send.py
[2023-12-31T12:17:34.925-0300] {processor.py:183} INFO - Processing /home/felipe/airflow/dags/10_non_atomic_send.py took 0.590 seconds
[2023-12-31T12:18:26.424-0300] {processor.py:161} INFO - Started process (PID=37755) to work on /home/felipe/airflow/dags/10_non_atomic_send.py
[2023-12-31T12:18:26.444-0300] {processor.py:830} INFO - Processing file /home/felipe/airflow/dags/10_non_atomic_send.py for tasks to queue
[2023-12-31T12:18:26.465-0300] {logging_mixin.py:188} INFO - [2023-12-31T12:18:26.464-0300] {dagbag.py:538} INFO - Filling up the DagBag from /home/felipe/airflow/dags/10_non_atomic_send.py
[2023-12-31T12:18:26.524-0300] {logging_mixin.py:188} INFO - [2023-12-31T12:18:26.514-0300] {dagbag.py:348} ERROR - Failed to import: /home/felipe/airflow/dags/10_non_atomic_send.py
Traceback (most recent call last):
  File "/home/felipe/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/felipe/airflow/dags/10_non_atomic_send.py", line 12, in <module>
    import pandas as pd
ModuleNotFoundError: No module named 'pandas'
[2023-12-31T12:18:26.534-0300] {processor.py:842} WARNING - No viable dags retrieved from /home/felipe/airflow/dags/10_non_atomic_send.py
[2023-12-31T12:18:26.844-0300] {processor.py:183} INFO - Processing /home/felipe/airflow/dags/10_non_atomic_send.py took 0.479 seconds
[2023-12-31T12:26:04.660-0300] {processor.py:161} INFO - Started process (PID=37970) to work on /home/felipe/airflow/dags/10_non_atomic_send.py
[2023-12-31T12:26:04.671-0300] {processor.py:830} INFO - Processing file /home/felipe/airflow/dags/10_non_atomic_send.py for tasks to queue
[2023-12-31T12:26:04.691-0300] {logging_mixin.py:188} INFO - [2023-12-31T12:26:04.690-0300] {dagbag.py:538} INFO - Filling up the DagBag from /home/felipe/airflow/dags/10_non_atomic_send.py
[2023-12-31T12:26:04.751-0300] {logging_mixin.py:188} INFO - [2023-12-31T12:26:04.731-0300] {dagbag.py:348} ERROR - Failed to import: /home/felipe/airflow/dags/10_non_atomic_send.py
Traceback (most recent call last):
  File "/home/felipe/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/felipe/airflow/dags/10_non_atomic_send.py", line 12, in <module>
    import pandas as pd
ModuleNotFoundError: No module named 'pandas'
[2023-12-31T12:26:04.771-0300] {processor.py:842} WARNING - No viable dags retrieved from /home/felipe/airflow/dags/10_non_atomic_send.py
[2023-12-31T12:26:05.321-0300] {processor.py:183} INFO - Processing /home/felipe/airflow/dags/10_non_atomic_send.py took 0.720 seconds
[2023-12-31T12:27:14.201-0300] {processor.py:161} INFO - Started process (PID=38034) to work on /home/felipe/airflow/dags/10_non_atomic_send.py
[2023-12-31T12:27:14.221-0300] {processor.py:830} INFO - Processing file /home/felipe/airflow/dags/10_non_atomic_send.py for tasks to queue
[2023-12-31T12:27:14.250-0300] {logging_mixin.py:188} INFO - [2023-12-31T12:27:14.240-0300] {dagbag.py:538} INFO - Filling up the DagBag from /home/felipe/airflow/dags/10_non_atomic_send.py
[2023-12-31T12:27:14.321-0300] {logging_mixin.py:188} INFO - [2023-12-31T12:27:14.301-0300] {dagbag.py:348} ERROR - Failed to import: /home/felipe/airflow/dags/10_non_atomic_send.py
Traceback (most recent call last):
  File "/home/felipe/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/felipe/airflow/dags/10_non_atomic_send.py", line 12, in <module>
    import pandas as pd
ModuleNotFoundError: No module named 'pandas'
[2023-12-31T12:27:14.331-0300] {processor.py:842} WARNING - No viable dags retrieved from /home/felipe/airflow/dags/10_non_atomic_send.py
[2023-12-31T12:27:14.820-0300] {processor.py:183} INFO - Processing /home/felipe/airflow/dags/10_non_atomic_send.py took 0.670 seconds
[2023-12-31T12:28:32.070-0300] {processor.py:161} INFO - Started process (PID=38105) to work on /home/felipe/airflow/dags/10_non_atomic_send.py
[2023-12-31T12:28:32.090-0300] {processor.py:830} INFO - Processing file /home/felipe/airflow/dags/10_non_atomic_send.py for tasks to queue
[2023-12-31T12:28:32.111-0300] {logging_mixin.py:188} INFO - [2023-12-31T12:28:32.101-0300] {dagbag.py:538} INFO - Filling up the DagBag from /home/felipe/airflow/dags/10_non_atomic_send.py
[2023-12-31T12:28:32.190-0300] {logging_mixin.py:188} INFO - [2023-12-31T12:28:32.161-0300] {dagbag.py:348} ERROR - Failed to import: /home/felipe/airflow/dags/10_non_atomic_send.py
Traceback (most recent call last):
  File "/home/felipe/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/felipe/airflow/dags/10_non_atomic_send.py", line 12, in <module>
    import pandas as pd
ModuleNotFoundError: No module named 'pandas'
[2023-12-31T12:28:32.201-0300] {processor.py:842} WARNING - No viable dags retrieved from /home/felipe/airflow/dags/10_non_atomic_send.py
[2023-12-31T12:28:32.691-0300] {processor.py:183} INFO - Processing /home/felipe/airflow/dags/10_non_atomic_send.py took 0.700 seconds
[2023-12-31T12:29:42.060-0300] {processor.py:161} INFO - Started process (PID=38154) to work on /home/felipe/airflow/dags/10_non_atomic_send.py
[2023-12-31T12:29:42.091-0300] {processor.py:830} INFO - Processing file /home/felipe/airflow/dags/10_non_atomic_send.py for tasks to queue
[2023-12-31T12:29:42.121-0300] {logging_mixin.py:188} INFO - [2023-12-31T12:29:42.111-0300] {dagbag.py:538} INFO - Filling up the DagBag from /home/felipe/airflow/dags/10_non_atomic_send.py
[2023-12-31T12:29:42.261-0300] {logging_mixin.py:188} INFO - [2023-12-31T12:29:42.211-0300] {dagbag.py:348} ERROR - Failed to import: /home/felipe/airflow/dags/10_non_atomic_send.py
Traceback (most recent call last):
  File "/home/felipe/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/felipe/airflow/dags/10_non_atomic_send.py", line 12, in <module>
    import pandas as pd
ModuleNotFoundError: No module named 'pandas'
[2023-12-31T12:29:42.280-0300] {processor.py:842} WARNING - No viable dags retrieved from /home/felipe/airflow/dags/10_non_atomic_send.py
[2023-12-31T12:29:42.820-0300] {processor.py:183} INFO - Processing /home/felipe/airflow/dags/10_non_atomic_send.py took 0.880 seconds
[2023-12-31T12:30:57.741-0300] {processor.py:161} INFO - Started process (PID=38229) to work on /home/felipe/airflow/dags/10_non_atomic_send.py
[2023-12-31T12:30:57.771-0300] {processor.py:830} INFO - Processing file /home/felipe/airflow/dags/10_non_atomic_send.py for tasks to queue
[2023-12-31T12:30:57.800-0300] {logging_mixin.py:188} INFO - [2023-12-31T12:30:57.790-0300] {dagbag.py:538} INFO - Filling up the DagBag from /home/felipe/airflow/dags/10_non_atomic_send.py
[2023-12-31T12:30:57.871-0300] {logging_mixin.py:188} INFO - [2023-12-31T12:30:57.850-0300] {dagbag.py:348} ERROR - Failed to import: /home/felipe/airflow/dags/10_non_atomic_send.py
Traceback (most recent call last):
  File "/home/felipe/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/felipe/airflow/dags/10_non_atomic_send.py", line 12, in <module>
    import pandas as pd
ModuleNotFoundError: No module named 'pandas'
[2023-12-31T12:30:57.890-0300] {processor.py:842} WARNING - No viable dags retrieved from /home/felipe/airflow/dags/10_non_atomic_send.py
[2023-12-31T12:30:58.311-0300] {processor.py:183} INFO - Processing /home/felipe/airflow/dags/10_non_atomic_send.py took 0.640 seconds
[2023-12-31T12:32:18.041-0300] {processor.py:161} INFO - Started process (PID=38285) to work on /home/felipe/airflow/dags/10_non_atomic_send.py
[2023-12-31T12:32:18.080-0300] {processor.py:830} INFO - Processing file /home/felipe/airflow/dags/10_non_atomic_send.py for tasks to queue
[2023-12-31T12:32:18.110-0300] {logging_mixin.py:188} INFO - [2023-12-31T12:32:18.100-0300] {dagbag.py:538} INFO - Filling up the DagBag from /home/felipe/airflow/dags/10_non_atomic_send.py
[2023-12-31T12:32:18.221-0300] {logging_mixin.py:188} INFO - [2023-12-31T12:32:18.190-0300] {dagbag.py:348} ERROR - Failed to import: /home/felipe/airflow/dags/10_non_atomic_send.py
Traceback (most recent call last):
  File "/home/felipe/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/felipe/airflow/dags/10_non_atomic_send.py", line 12, in <module>
    import pandas as pd
ModuleNotFoundError: No module named 'pandas'
[2023-12-31T12:32:18.240-0300] {processor.py:842} WARNING - No viable dags retrieved from /home/felipe/airflow/dags/10_non_atomic_send.py
[2023-12-31T12:32:18.841-0300] {processor.py:183} INFO - Processing /home/felipe/airflow/dags/10_non_atomic_send.py took 0.891 seconds
[2023-12-31T12:33:27.940-0300] {processor.py:161} INFO - Started process (PID=38330) to work on /home/felipe/airflow/dags/10_non_atomic_send.py
[2023-12-31T12:33:27.971-0300] {processor.py:830} INFO - Processing file /home/felipe/airflow/dags/10_non_atomic_send.py for tasks to queue
[2023-12-31T12:33:28.000-0300] {logging_mixin.py:188} INFO - [2023-12-31T12:33:27.990-0300] {dagbag.py:538} INFO - Filling up the DagBag from /home/felipe/airflow/dags/10_non_atomic_send.py
[2023-12-31T12:33:28.111-0300] {logging_mixin.py:188} INFO - [2023-12-31T12:33:28.081-0300] {dagbag.py:348} ERROR - Failed to import: /home/felipe/airflow/dags/10_non_atomic_send.py
Traceback (most recent call last):
  File "/home/felipe/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/felipe/airflow/dags/10_non_atomic_send.py", line 12, in <module>
    import pandas as pd
ModuleNotFoundError: No module named 'pandas'
[2023-12-31T12:33:28.130-0300] {processor.py:842} WARNING - No viable dags retrieved from /home/felipe/airflow/dags/10_non_atomic_send.py
[2023-12-31T12:33:28.701-0300] {processor.py:183} INFO - Processing /home/felipe/airflow/dags/10_non_atomic_send.py took 0.860 seconds
[2023-12-31T12:34:56.670-0300] {processor.py:161} INFO - Started process (PID=38384) to work on /home/felipe/airflow/dags/10_non_atomic_send.py
[2023-12-31T12:34:56.691-0300] {processor.py:830} INFO - Processing file /home/felipe/airflow/dags/10_non_atomic_send.py for tasks to queue
[2023-12-31T12:34:56.731-0300] {logging_mixin.py:188} INFO - [2023-12-31T12:34:56.721-0300] {dagbag.py:538} INFO - Filling up the DagBag from /home/felipe/airflow/dags/10_non_atomic_send.py
[2023-12-31T12:34:56.840-0300] {logging_mixin.py:188} INFO - [2023-12-31T12:34:56.810-0300] {dagbag.py:348} ERROR - Failed to import: /home/felipe/airflow/dags/10_non_atomic_send.py
Traceback (most recent call last):
  File "/home/felipe/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/felipe/airflow/dags/10_non_atomic_send.py", line 12, in <module>
    import pandas as pd
ModuleNotFoundError: No module named 'pandas'
[2023-12-31T12:34:56.851-0300] {processor.py:842} WARNING - No viable dags retrieved from /home/felipe/airflow/dags/10_non_atomic_send.py
[2023-12-31T12:34:57.520-0300] {processor.py:183} INFO - Processing /home/felipe/airflow/dags/10_non_atomic_send.py took 0.930 seconds
[2023-12-31T12:36:44.501-0300] {processor.py:161} INFO - Started process (PID=38473) to work on /home/felipe/airflow/dags/10_non_atomic_send.py
[2023-12-31T12:36:44.540-0300] {processor.py:830} INFO - Processing file /home/felipe/airflow/dags/10_non_atomic_send.py for tasks to queue
[2023-12-31T12:36:44.570-0300] {logging_mixin.py:188} INFO - [2023-12-31T12:36:44.551-0300] {dagbag.py:538} INFO - Filling up the DagBag from /home/felipe/airflow/dags/10_non_atomic_send.py
[2023-12-31T12:36:44.680-0300] {logging_mixin.py:188} INFO - [2023-12-31T12:36:44.641-0300] {dagbag.py:348} ERROR - Failed to import: /home/felipe/airflow/dags/10_non_atomic_send.py
Traceback (most recent call last):
  File "/home/felipe/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/felipe/airflow/dags/10_non_atomic_send.py", line 12, in <module>
    import pandas as pd
ModuleNotFoundError: No module named 'pandas'
[2023-12-31T12:36:44.690-0300] {processor.py:842} WARNING - No viable dags retrieved from /home/felipe/airflow/dags/10_non_atomic_send.py
[2023-12-31T12:36:45.421-0300] {processor.py:183} INFO - Processing /home/felipe/airflow/dags/10_non_atomic_send.py took 1.010 seconds
[2023-12-31T12:46:48.138-0300] {processor.py:161} INFO - Started process (PID=38723) to work on /home/felipe/airflow/dags/10_non_atomic_send.py
[2023-12-31T12:46:48.178-0300] {processor.py:830} INFO - Processing file /home/felipe/airflow/dags/10_non_atomic_send.py for tasks to queue
[2023-12-31T12:46:48.228-0300] {logging_mixin.py:188} INFO - [2023-12-31T12:46:48.208-0300] {dagbag.py:538} INFO - Filling up the DagBag from /home/felipe/airflow/dags/10_non_atomic_send.py
[2023-12-31T12:46:48.458-0300] {logging_mixin.py:188} INFO - [2023-12-31T12:46:48.398-0300] {dagbag.py:348} ERROR - Failed to import: /home/felipe/airflow/dags/10_non_atomic_send.py
Traceback (most recent call last):
  File "/home/felipe/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/felipe/airflow/dags/10_non_atomic_send.py", line 12, in <module>
    import pandas as pd
ModuleNotFoundError: No module named 'pandas'
[2023-12-31T12:46:48.488-0300] {processor.py:842} WARNING - No viable dags retrieved from /home/felipe/airflow/dags/10_non_atomic_send.py
[2023-12-31T12:46:49.498-0300] {processor.py:183} INFO - Processing /home/felipe/airflow/dags/10_non_atomic_send.py took 1.500 seconds
[2023-12-31T12:48:57.217-0300] {processor.py:161} INFO - Started process (PID=38812) to work on /home/felipe/airflow/dags/10_non_atomic_send.py
[2023-12-31T12:48:57.298-0300] {processor.py:830} INFO - Processing file /home/felipe/airflow/dags/10_non_atomic_send.py for tasks to queue
[2023-12-31T12:48:57.388-0300] {logging_mixin.py:188} INFO - [2023-12-31T12:48:57.348-0300] {dagbag.py:538} INFO - Filling up the DagBag from /home/felipe/airflow/dags/10_non_atomic_send.py
[2023-12-31T12:48:57.647-0300] {logging_mixin.py:188} INFO - [2023-12-31T12:48:57.577-0300] {dagbag.py:348} ERROR - Failed to import: /home/felipe/airflow/dags/10_non_atomic_send.py
Traceback (most recent call last):
  File "/home/felipe/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/felipe/airflow/dags/10_non_atomic_send.py", line 12, in <module>
    import pandas as pd
ModuleNotFoundError: No module named 'pandas'
[2023-12-31T12:48:57.678-0300] {processor.py:842} WARNING - No viable dags retrieved from /home/felipe/airflow/dags/10_non_atomic_send.py
[2023-12-31T12:48:59.008-0300] {processor.py:183} INFO - Processing /home/felipe/airflow/dags/10_non_atomic_send.py took 2.030 seconds
