[2023-12-31T09:36:21.347-0300] {processor.py:161} INFO - Started process (PID=31850) to work on /home/felipe/airflow/dags/13_wikipedia.py
[2023-12-31T09:36:21.349-0300] {processor.py:830} INFO - Processing file /home/felipe/airflow/dags/13_wikipedia.py for tasks to queue
[2023-12-31T09:36:21.366-0300] {logging_mixin.py:188} INFO - [2023-12-31T09:36:21.358-0300] {dagbag.py:538} INFO - Filling up the DagBag from /home/felipe/airflow/dags/13_wikipedia.py
[2023-12-31T09:36:21.379-0300] {logging_mixin.py:188} INFO - [2023-12-31T09:36:21.378-0300] {dagbag.py:348} ERROR - Failed to import: /home/felipe/airflow/dags/13_wikipedia.py
Traceback (most recent call last):
  File "/home/felipe/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/felipe/airflow/dags/13_wikipedia.py", line 4, in <module>
    import pandas as pd
ModuleNotFoundError: No module named 'pandas'
[2023-12-31T09:36:21.381-0300] {processor.py:842} WARNING - No viable dags retrieved from /home/felipe/airflow/dags/13_wikipedia.py
[2023-12-31T09:36:21.468-0300] {processor.py:183} INFO - Processing /home/felipe/airflow/dags/13_wikipedia.py took 0.141 seconds
[2023-12-31T09:38:20.319-0300] {processor.py:161} INFO - Started process (PID=32159) to work on /home/felipe/airflow/dags/13_wikipedia.py
[2023-12-31T09:38:20.337-0300] {processor.py:830} INFO - Processing file /home/felipe/airflow/dags/13_wikipedia.py for tasks to queue
[2023-12-31T09:38:20.348-0300] {logging_mixin.py:188} INFO - [2023-12-31T09:38:20.341-0300] {dagbag.py:538} INFO - Filling up the DagBag from /home/felipe/airflow/dags/13_wikipedia.py
[2023-12-31T09:38:20.378-0300] {logging_mixin.py:188} INFO - [2023-12-31T09:38:20.370-0300] {dagbag.py:348} ERROR - Failed to import: /home/felipe/airflow/dags/13_wikipedia.py
Traceback (most recent call last):
  File "/home/felipe/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/felipe/airflow/dags/13_wikipedia.py", line 4, in <module>
    import pandas as pd
ModuleNotFoundError: No module named 'pandas'
[2023-12-31T09:38:20.379-0300] {processor.py:842} WARNING - No viable dags retrieved from /home/felipe/airflow/dags/13_wikipedia.py
[2023-12-31T09:38:20.640-0300] {processor.py:183} INFO - Processing /home/felipe/airflow/dags/13_wikipedia.py took 0.340 seconds
[2023-12-31T09:51:50.099-0300] {processor.py:161} INFO - Started process (PID=32759) to work on /home/felipe/airflow/dags/13_wikipedia.py
[2023-12-31T09:51:50.117-0300] {processor.py:830} INFO - Processing file /home/felipe/airflow/dags/13_wikipedia.py for tasks to queue
[2023-12-31T09:51:50.120-0300] {logging_mixin.py:188} INFO - [2023-12-31T09:51:50.119-0300] {dagbag.py:538} INFO - Filling up the DagBag from /home/felipe/airflow/dags/13_wikipedia.py
[2023-12-31T09:51:50.147-0300] {logging_mixin.py:188} INFO - [2023-12-31T09:51:50.138-0300] {dagbag.py:348} ERROR - Failed to import: /home/felipe/airflow/dags/13_wikipedia.py
Traceback (most recent call last):
  File "/home/felipe/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/felipe/airflow/dags/13_wikipedia.py", line 4, in <module>
    import pandas as pd
ModuleNotFoundError: No module named 'pandas'
[2023-12-31T09:51:50.149-0300] {processor.py:842} WARNING - No viable dags retrieved from /home/felipe/airflow/dags/13_wikipedia.py
[2023-12-31T09:51:50.348-0300] {processor.py:183} INFO - Processing /home/felipe/airflow/dags/13_wikipedia.py took 0.269 seconds
[2023-12-31T09:55:09.538-0300] {processor.py:161} INFO - Started process (PID=32915) to work on /home/felipe/airflow/dags/13_wikipedia.py
[2023-12-31T09:55:09.546-0300] {processor.py:830} INFO - Processing file /home/felipe/airflow/dags/13_wikipedia.py for tasks to queue
[2023-12-31T09:55:09.549-0300] {logging_mixin.py:188} INFO - [2023-12-31T09:55:09.548-0300] {dagbag.py:538} INFO - Filling up the DagBag from /home/felipe/airflow/dags/13_wikipedia.py
[2023-12-31T09:55:09.570-0300] {logging_mixin.py:188} INFO - [2023-12-31T09:55:09.567-0300] {dagbag.py:348} ERROR - Failed to import: /home/felipe/airflow/dags/13_wikipedia.py
Traceback (most recent call last):
  File "/home/felipe/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/felipe/airflow/dags/13_wikipedia.py", line 4, in <module>
    import pandas as pd
ModuleNotFoundError: No module named 'pandas'
[2023-12-31T09:55:09.578-0300] {processor.py:842} WARNING - No viable dags retrieved from /home/felipe/airflow/dags/13_wikipedia.py
[2023-12-31T09:55:09.768-0300] {processor.py:183} INFO - Processing /home/felipe/airflow/dags/13_wikipedia.py took 0.241 seconds
[2023-12-31T09:59:47.269-0300] {processor.py:161} INFO - Started process (PID=33132) to work on /home/felipe/airflow/dags/13_wikipedia.py
[2023-12-31T09:59:47.277-0300] {processor.py:830} INFO - Processing file /home/felipe/airflow/dags/13_wikipedia.py for tasks to queue
[2023-12-31T09:59:47.279-0300] {logging_mixin.py:188} INFO - [2023-12-31T09:59:47.278-0300] {dagbag.py:538} INFO - Filling up the DagBag from /home/felipe/airflow/dags/13_wikipedia.py
[2023-12-31T09:59:47.298-0300] {logging_mixin.py:188} INFO - [2023-12-31T09:59:47.296-0300] {dagbag.py:348} ERROR - Failed to import: /home/felipe/airflow/dags/13_wikipedia.py
Traceback (most recent call last):
  File "/home/felipe/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/felipe/airflow/dags/13_wikipedia.py", line 4, in <module>
    import pandas as pd
ModuleNotFoundError: No module named 'pandas'
[2023-12-31T09:59:47.300-0300] {processor.py:842} WARNING - No viable dags retrieved from /home/felipe/airflow/dags/13_wikipedia.py
[2023-12-31T09:59:47.419-0300] {processor.py:183} INFO - Processing /home/felipe/airflow/dags/13_wikipedia.py took 0.161 seconds
[2023-12-31T10:01:13.848-0300] {processor.py:161} INFO - Started process (PID=33239) to work on /home/felipe/airflow/dags/13_wikipedia.py
[2023-12-31T10:01:13.857-0300] {processor.py:830} INFO - Processing file /home/felipe/airflow/dags/13_wikipedia.py for tasks to queue
[2023-12-31T10:01:13.859-0300] {logging_mixin.py:188} INFO - [2023-12-31T10:01:13.858-0300] {dagbag.py:538} INFO - Filling up the DagBag from /home/felipe/airflow/dags/13_wikipedia.py
[2023-12-31T10:01:13.878-0300] {logging_mixin.py:188} INFO - [2023-12-31T10:01:13.876-0300] {dagbag.py:348} ERROR - Failed to import: /home/felipe/airflow/dags/13_wikipedia.py
Traceback (most recent call last):
  File "/home/felipe/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/felipe/airflow/dags/13_wikipedia.py", line 4, in <module>
    import pandas as pd
ModuleNotFoundError: No module named 'pandas'
[2023-12-31T10:01:13.879-0300] {processor.py:842} WARNING - No viable dags retrieved from /home/felipe/airflow/dags/13_wikipedia.py
[2023-12-31T10:01:13.979-0300] {processor.py:183} INFO - Processing /home/felipe/airflow/dags/13_wikipedia.py took 0.142 seconds
[2023-12-31T10:02:22.869-0300] {processor.py:161} INFO - Started process (PID=33333) to work on /home/felipe/airflow/dags/13_wikipedia.py
[2023-12-31T10:02:22.878-0300] {processor.py:830} INFO - Processing file /home/felipe/airflow/dags/13_wikipedia.py for tasks to queue
[2023-12-31T10:02:22.879-0300] {logging_mixin.py:188} INFO - [2023-12-31T10:02:22.879-0300] {dagbag.py:538} INFO - Filling up the DagBag from /home/felipe/airflow/dags/13_wikipedia.py
[2023-12-31T10:02:22.898-0300] {logging_mixin.py:188} INFO - [2023-12-31T10:02:22.896-0300] {dagbag.py:348} ERROR - Failed to import: /home/felipe/airflow/dags/13_wikipedia.py
Traceback (most recent call last):
  File "/home/felipe/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/felipe/airflow/dags/13_wikipedia.py", line 4, in <module>
    import pandas as pd
ModuleNotFoundError: No module named 'pandas'
[2023-12-31T10:02:22.898-0300] {processor.py:842} WARNING - No viable dags retrieved from /home/felipe/airflow/dags/13_wikipedia.py
[2023-12-31T10:02:22.999-0300] {processor.py:183} INFO - Processing /home/felipe/airflow/dags/13_wikipedia.py took 0.140 seconds
[2023-12-31T10:03:29.099-0300] {processor.py:161} INFO - Started process (PID=33399) to work on /home/felipe/airflow/dags/13_wikipedia.py
[2023-12-31T10:03:29.108-0300] {processor.py:830} INFO - Processing file /home/felipe/airflow/dags/13_wikipedia.py for tasks to queue
[2023-12-31T10:03:29.109-0300] {logging_mixin.py:188} INFO - [2023-12-31T10:03:29.109-0300] {dagbag.py:538} INFO - Filling up the DagBag from /home/felipe/airflow/dags/13_wikipedia.py
[2023-12-31T10:03:29.127-0300] {logging_mixin.py:188} INFO - [2023-12-31T10:03:29.120-0300] {dagbag.py:348} ERROR - Failed to import: /home/felipe/airflow/dags/13_wikipedia.py
Traceback (most recent call last):
  File "/home/felipe/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/felipe/airflow/dags/13_wikipedia.py", line 4, in <module>
    import pandas as pd
ModuleNotFoundError: No module named 'pandas'
[2023-12-31T10:03:29.129-0300] {processor.py:842} WARNING - No viable dags retrieved from /home/felipe/airflow/dags/13_wikipedia.py
[2023-12-31T10:03:29.228-0300] {processor.py:183} INFO - Processing /home/felipe/airflow/dags/13_wikipedia.py took 0.139 seconds
[2023-12-31T10:04:38.108-0300] {processor.py:161} INFO - Started process (PID=33485) to work on /home/felipe/airflow/dags/13_wikipedia.py
[2023-12-31T10:04:38.116-0300] {processor.py:830} INFO - Processing file /home/felipe/airflow/dags/13_wikipedia.py for tasks to queue
[2023-12-31T10:04:38.118-0300] {logging_mixin.py:188} INFO - [2023-12-31T10:04:38.117-0300] {dagbag.py:538} INFO - Filling up the DagBag from /home/felipe/airflow/dags/13_wikipedia.py
[2023-12-31T10:04:38.129-0300] {logging_mixin.py:188} INFO - [2023-12-31T10:04:38.128-0300] {dagbag.py:348} ERROR - Failed to import: /home/felipe/airflow/dags/13_wikipedia.py
Traceback (most recent call last):
  File "/home/felipe/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/felipe/airflow/dags/13_wikipedia.py", line 4, in <module>
    import pandas as pd
ModuleNotFoundError: No module named 'pandas'
[2023-12-31T10:04:38.136-0300] {processor.py:842} WARNING - No viable dags retrieved from /home/felipe/airflow/dags/13_wikipedia.py
[2023-12-31T10:04:38.229-0300] {processor.py:183} INFO - Processing /home/felipe/airflow/dags/13_wikipedia.py took 0.132 seconds
[2023-12-31T10:05:49.339-0300] {processor.py:161} INFO - Started process (PID=33565) to work on /home/felipe/airflow/dags/13_wikipedia.py
[2023-12-31T10:05:49.348-0300] {processor.py:830} INFO - Processing file /home/felipe/airflow/dags/13_wikipedia.py for tasks to queue
[2023-12-31T10:05:49.349-0300] {logging_mixin.py:188} INFO - [2023-12-31T10:05:49.349-0300] {dagbag.py:538} INFO - Filling up the DagBag from /home/felipe/airflow/dags/13_wikipedia.py
[2023-12-31T10:05:49.368-0300] {logging_mixin.py:188} INFO - [2023-12-31T10:05:49.366-0300] {dagbag.py:348} ERROR - Failed to import: /home/felipe/airflow/dags/13_wikipedia.py
Traceback (most recent call last):
  File "/home/felipe/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/felipe/airflow/dags/13_wikipedia.py", line 4, in <module>
    import pandas as pd
ModuleNotFoundError: No module named 'pandas'
[2023-12-31T10:05:49.369-0300] {processor.py:842} WARNING - No viable dags retrieved from /home/felipe/airflow/dags/13_wikipedia.py
[2023-12-31T10:05:49.477-0300] {processor.py:183} INFO - Processing /home/felipe/airflow/dags/13_wikipedia.py took 0.148 seconds
[2023-12-31T10:07:00.397-0300] {processor.py:161} INFO - Started process (PID=33677) to work on /home/felipe/airflow/dags/13_wikipedia.py
[2023-12-31T10:07:00.399-0300] {processor.py:830} INFO - Processing file /home/felipe/airflow/dags/13_wikipedia.py for tasks to queue
[2023-12-31T10:07:00.407-0300] {logging_mixin.py:188} INFO - [2023-12-31T10:07:00.406-0300] {dagbag.py:538} INFO - Filling up the DagBag from /home/felipe/airflow/dags/13_wikipedia.py
[2023-12-31T10:07:00.426-0300] {logging_mixin.py:188} INFO - [2023-12-31T10:07:00.418-0300] {dagbag.py:348} ERROR - Failed to import: /home/felipe/airflow/dags/13_wikipedia.py
Traceback (most recent call last):
  File "/home/felipe/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/felipe/airflow/dags/13_wikipedia.py", line 4, in <module>
    import pandas as pd
ModuleNotFoundError: No module named 'pandas'
[2023-12-31T10:07:00.427-0300] {processor.py:842} WARNING - No viable dags retrieved from /home/felipe/airflow/dags/13_wikipedia.py
[2023-12-31T10:07:00.529-0300] {processor.py:183} INFO - Processing /home/felipe/airflow/dags/13_wikipedia.py took 0.150 seconds
[2023-12-31T10:08:13.529-0300] {processor.py:161} INFO - Started process (PID=33758) to work on /home/felipe/airflow/dags/13_wikipedia.py
[2023-12-31T10:08:13.538-0300] {processor.py:830} INFO - Processing file /home/felipe/airflow/dags/13_wikipedia.py for tasks to queue
[2023-12-31T10:08:13.539-0300] {logging_mixin.py:188} INFO - [2023-12-31T10:08:13.539-0300] {dagbag.py:538} INFO - Filling up the DagBag from /home/felipe/airflow/dags/13_wikipedia.py
[2023-12-31T10:08:13.558-0300] {logging_mixin.py:188} INFO - [2023-12-31T10:08:13.556-0300] {dagbag.py:348} ERROR - Failed to import: /home/felipe/airflow/dags/13_wikipedia.py
Traceback (most recent call last):
  File "/home/felipe/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/felipe/airflow/dags/13_wikipedia.py", line 4, in <module>
    import pandas as pd
ModuleNotFoundError: No module named 'pandas'
[2023-12-31T10:08:13.559-0300] {processor.py:842} WARNING - No viable dags retrieved from /home/felipe/airflow/dags/13_wikipedia.py
[2023-12-31T10:08:13.687-0300] {processor.py:183} INFO - Processing /home/felipe/airflow/dags/13_wikipedia.py took 0.170 seconds
[2023-12-31T11:28:40.465-0300] {processor.py:161} INFO - Started process (PID=33943) to work on /home/felipe/airflow/dags/13_wikipedia.py
[2023-12-31T11:28:40.476-0300] {processor.py:830} INFO - Processing file /home/felipe/airflow/dags/13_wikipedia.py for tasks to queue
[2023-12-31T11:28:40.494-0300] {logging_mixin.py:188} INFO - [2023-12-31T11:28:40.485-0300] {dagbag.py:538} INFO - Filling up the DagBag from /home/felipe/airflow/dags/13_wikipedia.py
[2023-12-31T11:28:40.535-0300] {logging_mixin.py:188} INFO - [2023-12-31T11:28:40.525-0300] {dagbag.py:348} ERROR - Failed to import: /home/felipe/airflow/dags/13_wikipedia.py
Traceback (most recent call last):
  File "/home/felipe/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/felipe/airflow/dags/13_wikipedia.py", line 4, in <module>
    import pandas as pd
ModuleNotFoundError: No module named 'pandas'
[2023-12-31T11:28:40.544-0300] {processor.py:842} WARNING - No viable dags retrieved from /home/felipe/airflow/dags/13_wikipedia.py
[2023-12-31T11:28:40.745-0300] {processor.py:183} INFO - Processing /home/felipe/airflow/dags/13_wikipedia.py took 0.310 seconds
[2023-12-31T11:30:38.704-0300] {processor.py:161} INFO - Started process (PID=34214) to work on /home/felipe/airflow/dags/13_wikipedia.py
[2023-12-31T11:30:38.707-0300] {processor.py:830} INFO - Processing file /home/felipe/airflow/dags/13_wikipedia.py for tasks to queue
[2023-12-31T11:30:38.715-0300] {logging_mixin.py:188} INFO - [2023-12-31T11:30:38.715-0300] {dagbag.py:538} INFO - Filling up the DagBag from /home/felipe/airflow/dags/13_wikipedia.py
[2023-12-31T11:30:38.736-0300] {logging_mixin.py:188} INFO - [2023-12-31T11:30:38.734-0300] {dagbag.py:348} ERROR - Failed to import: /home/felipe/airflow/dags/13_wikipedia.py
Traceback (most recent call last):
  File "/home/felipe/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/felipe/airflow/dags/13_wikipedia.py", line 4, in <module>
    import pandas as pd
ModuleNotFoundError: No module named 'pandas'
[2023-12-31T11:30:38.744-0300] {processor.py:842} WARNING - No viable dags retrieved from /home/felipe/airflow/dags/13_wikipedia.py
[2023-12-31T11:30:38.875-0300] {processor.py:183} INFO - Processing /home/felipe/airflow/dags/13_wikipedia.py took 0.190 seconds
[2023-12-31T11:32:10.146-0300] {processor.py:161} INFO - Started process (PID=34328) to work on /home/felipe/airflow/dags/13_wikipedia.py
[2023-12-31T11:32:10.156-0300] {processor.py:830} INFO - Processing file /home/felipe/airflow/dags/13_wikipedia.py for tasks to queue
[2023-12-31T11:32:10.164-0300] {logging_mixin.py:188} INFO - [2023-12-31T11:32:10.164-0300] {dagbag.py:538} INFO - Filling up the DagBag from /home/felipe/airflow/dags/13_wikipedia.py
[2023-12-31T11:32:10.184-0300] {logging_mixin.py:188} INFO - [2023-12-31T11:32:10.176-0300] {dagbag.py:348} ERROR - Failed to import: /home/felipe/airflow/dags/13_wikipedia.py
Traceback (most recent call last):
  File "/home/felipe/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/felipe/airflow/dags/13_wikipedia.py", line 4, in <module>
    import pandas as pd
ModuleNotFoundError: No module named 'pandas'
[2023-12-31T11:32:10.185-0300] {processor.py:842} WARNING - No viable dags retrieved from /home/felipe/airflow/dags/13_wikipedia.py
[2023-12-31T11:32:10.307-0300] {processor.py:183} INFO - Processing /home/felipe/airflow/dags/13_wikipedia.py took 0.181 seconds
[2023-12-31T11:33:39.637-0300] {processor.py:161} INFO - Started process (PID=34428) to work on /home/felipe/airflow/dags/13_wikipedia.py
[2023-12-31T11:33:39.646-0300] {processor.py:830} INFO - Processing file /home/felipe/airflow/dags/13_wikipedia.py for tasks to queue
[2023-12-31T11:33:39.655-0300] {logging_mixin.py:188} INFO - [2023-12-31T11:33:39.654-0300] {dagbag.py:538} INFO - Filling up the DagBag from /home/felipe/airflow/dags/13_wikipedia.py
[2023-12-31T11:33:39.675-0300] {logging_mixin.py:188} INFO - [2023-12-31T11:33:39.666-0300] {dagbag.py:348} ERROR - Failed to import: /home/felipe/airflow/dags/13_wikipedia.py
Traceback (most recent call last):
  File "/home/felipe/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/felipe/airflow/dags/13_wikipedia.py", line 4, in <module>
    import pandas as pd
ModuleNotFoundError: No module named 'pandas'
[2023-12-31T11:33:39.677-0300] {processor.py:842} WARNING - No viable dags retrieved from /home/felipe/airflow/dags/13_wikipedia.py
[2023-12-31T11:33:39.826-0300] {processor.py:183} INFO - Processing /home/felipe/airflow/dags/13_wikipedia.py took 0.210 seconds
[2023-12-31T11:35:02.685-0300] {processor.py:161} INFO - Started process (PID=34519) to work on /home/felipe/airflow/dags/13_wikipedia.py
[2023-12-31T11:35:02.694-0300] {processor.py:830} INFO - Processing file /home/felipe/airflow/dags/13_wikipedia.py for tasks to queue
[2023-12-31T11:35:02.696-0300] {logging_mixin.py:188} INFO - [2023-12-31T11:35:02.695-0300] {dagbag.py:538} INFO - Filling up the DagBag from /home/felipe/airflow/dags/13_wikipedia.py
[2023-12-31T11:35:02.715-0300] {logging_mixin.py:188} INFO - [2023-12-31T11:35:02.706-0300] {dagbag.py:348} ERROR - Failed to import: /home/felipe/airflow/dags/13_wikipedia.py
Traceback (most recent call last):
  File "/home/felipe/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/felipe/airflow/dags/13_wikipedia.py", line 4, in <module>
    import pandas as pd
ModuleNotFoundError: No module named 'pandas'
[2023-12-31T11:35:02.715-0300] {processor.py:842} WARNING - No viable dags retrieved from /home/felipe/airflow/dags/13_wikipedia.py
[2023-12-31T11:35:02.816-0300] {processor.py:183} INFO - Processing /home/felipe/airflow/dags/13_wikipedia.py took 0.142 seconds
[2023-12-31T11:36:25.735-0300] {processor.py:161} INFO - Started process (PID=34635) to work on /home/felipe/airflow/dags/13_wikipedia.py
[2023-12-31T11:36:25.744-0300] {processor.py:830} INFO - Processing file /home/felipe/airflow/dags/13_wikipedia.py for tasks to queue
[2023-12-31T11:36:25.746-0300] {logging_mixin.py:188} INFO - [2023-12-31T11:36:25.745-0300] {dagbag.py:538} INFO - Filling up the DagBag from /home/felipe/airflow/dags/13_wikipedia.py
[2023-12-31T11:36:25.766-0300] {logging_mixin.py:188} INFO - [2023-12-31T11:36:25.764-0300] {dagbag.py:348} ERROR - Failed to import: /home/felipe/airflow/dags/13_wikipedia.py
Traceback (most recent call last):
  File "/home/felipe/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/felipe/airflow/dags/13_wikipedia.py", line 4, in <module>
    import pandas as pd
ModuleNotFoundError: No module named 'pandas'
[2023-12-31T11:36:25.766-0300] {processor.py:842} WARNING - No viable dags retrieved from /home/felipe/airflow/dags/13_wikipedia.py
[2023-12-31T11:36:25.906-0300] {processor.py:183} INFO - Processing /home/felipe/airflow/dags/13_wikipedia.py took 0.182 seconds
[2023-12-31T11:37:49.604-0300] {processor.py:161} INFO - Started process (PID=34730) to work on /home/felipe/airflow/dags/13_wikipedia.py
[2023-12-31T11:37:49.606-0300] {processor.py:830} INFO - Processing file /home/felipe/airflow/dags/13_wikipedia.py for tasks to queue
[2023-12-31T11:37:49.615-0300] {logging_mixin.py:188} INFO - [2023-12-31T11:37:49.614-0300] {dagbag.py:538} INFO - Filling up the DagBag from /home/felipe/airflow/dags/13_wikipedia.py
[2023-12-31T11:37:49.634-0300] {logging_mixin.py:188} INFO - [2023-12-31T11:37:49.626-0300] {dagbag.py:348} ERROR - Failed to import: /home/felipe/airflow/dags/13_wikipedia.py
Traceback (most recent call last):
  File "/home/felipe/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/felipe/airflow/dags/13_wikipedia.py", line 4, in <module>
    import pandas as pd
ModuleNotFoundError: No module named 'pandas'
[2023-12-31T11:37:49.635-0300] {processor.py:842} WARNING - No viable dags retrieved from /home/felipe/airflow/dags/13_wikipedia.py
[2023-12-31T11:37:49.765-0300] {processor.py:183} INFO - Processing /home/felipe/airflow/dags/13_wikipedia.py took 0.179 seconds
[2023-12-31T11:39:11.946-0300] {processor.py:161} INFO - Started process (PID=34819) to work on /home/felipe/airflow/dags/13_wikipedia.py
[2023-12-31T11:39:11.964-0300] {processor.py:830} INFO - Processing file /home/felipe/airflow/dags/13_wikipedia.py for tasks to queue
[2023-12-31T11:39:11.966-0300] {logging_mixin.py:188} INFO - [2023-12-31T11:39:11.965-0300] {dagbag.py:538} INFO - Filling up the DagBag from /home/felipe/airflow/dags/13_wikipedia.py
[2023-12-31T11:39:11.985-0300] {logging_mixin.py:188} INFO - [2023-12-31T11:39:11.984-0300] {dagbag.py:348} ERROR - Failed to import: /home/felipe/airflow/dags/13_wikipedia.py
Traceback (most recent call last):
  File "/home/felipe/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/felipe/airflow/dags/13_wikipedia.py", line 4, in <module>
    import pandas as pd
ModuleNotFoundError: No module named 'pandas'
[2023-12-31T11:39:11.986-0300] {processor.py:842} WARNING - No viable dags retrieved from /home/felipe/airflow/dags/13_wikipedia.py
[2023-12-31T11:39:12.136-0300] {processor.py:183} INFO - Processing /home/felipe/airflow/dags/13_wikipedia.py took 0.202 seconds
[2023-12-31T11:40:34.366-0300] {processor.py:161} INFO - Started process (PID=34935) to work on /home/felipe/airflow/dags/13_wikipedia.py
[2023-12-31T11:40:34.375-0300] {processor.py:830} INFO - Processing file /home/felipe/airflow/dags/13_wikipedia.py for tasks to queue
[2023-12-31T11:40:34.385-0300] {logging_mixin.py:188} INFO - [2023-12-31T11:40:34.376-0300] {dagbag.py:538} INFO - Filling up the DagBag from /home/felipe/airflow/dags/13_wikipedia.py
[2023-12-31T11:40:34.405-0300] {logging_mixin.py:188} INFO - [2023-12-31T11:40:34.396-0300] {dagbag.py:348} ERROR - Failed to import: /home/felipe/airflow/dags/13_wikipedia.py
Traceback (most recent call last):
  File "/home/felipe/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/felipe/airflow/dags/13_wikipedia.py", line 4, in <module>
    import pandas as pd
ModuleNotFoundError: No module named 'pandas'
[2023-12-31T11:40:34.405-0300] {processor.py:842} WARNING - No viable dags retrieved from /home/felipe/airflow/dags/13_wikipedia.py
[2023-12-31T11:40:34.545-0300] {processor.py:183} INFO - Processing /home/felipe/airflow/dags/13_wikipedia.py took 0.191 seconds
[2023-12-31T11:42:07.974-0300] {processor.py:161} INFO - Started process (PID=35041) to work on /home/felipe/airflow/dags/13_wikipedia.py
[2023-12-31T11:42:07.976-0300] {processor.py:830} INFO - Processing file /home/felipe/airflow/dags/13_wikipedia.py for tasks to queue
[2023-12-31T11:42:07.986-0300] {logging_mixin.py:188} INFO - [2023-12-31T11:42:07.985-0300] {dagbag.py:538} INFO - Filling up the DagBag from /home/felipe/airflow/dags/13_wikipedia.py
[2023-12-31T11:42:08.024-0300] {logging_mixin.py:188} INFO - [2023-12-31T11:42:08.015-0300] {dagbag.py:348} ERROR - Failed to import: /home/felipe/airflow/dags/13_wikipedia.py
Traceback (most recent call last):
  File "/home/felipe/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/felipe/airflow/dags/13_wikipedia.py", line 4, in <module>
    import pandas as pd
ModuleNotFoundError: No module named 'pandas'
[2023-12-31T11:42:08.025-0300] {processor.py:842} WARNING - No viable dags retrieved from /home/felipe/airflow/dags/13_wikipedia.py
[2023-12-31T11:42:08.166-0300] {processor.py:183} INFO - Processing /home/felipe/airflow/dags/13_wikipedia.py took 0.211 seconds
[2023-12-31T11:43:44.086-0300] {processor.py:161} INFO - Started process (PID=35151) to work on /home/felipe/airflow/dags/13_wikipedia.py
[2023-12-31T11:43:44.096-0300] {processor.py:830} INFO - Processing file /home/felipe/airflow/dags/13_wikipedia.py for tasks to queue
[2023-12-31T11:43:44.106-0300] {logging_mixin.py:188} INFO - [2023-12-31T11:43:44.105-0300] {dagbag.py:538} INFO - Filling up the DagBag from /home/felipe/airflow/dags/13_wikipedia.py
[2023-12-31T11:43:44.135-0300] {logging_mixin.py:188} INFO - [2023-12-31T11:43:44.126-0300] {dagbag.py:348} ERROR - Failed to import: /home/felipe/airflow/dags/13_wikipedia.py
Traceback (most recent call last):
  File "/home/felipe/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/felipe/airflow/dags/13_wikipedia.py", line 4, in <module>
    import pandas as pd
ModuleNotFoundError: No module named 'pandas'
[2023-12-31T11:43:44.136-0300] {processor.py:842} WARNING - No viable dags retrieved from /home/felipe/airflow/dags/13_wikipedia.py
[2023-12-31T11:43:44.335-0300] {processor.py:183} INFO - Processing /home/felipe/airflow/dags/13_wikipedia.py took 0.271 seconds
[2023-12-31T11:45:25.645-0300] {processor.py:161} INFO - Started process (PID=35290) to work on /home/felipe/airflow/dags/13_wikipedia.py
[2023-12-31T11:45:25.654-0300] {processor.py:830} INFO - Processing file /home/felipe/airflow/dags/13_wikipedia.py for tasks to queue
[2023-12-31T11:45:25.665-0300] {logging_mixin.py:188} INFO - [2023-12-31T11:45:25.656-0300] {dagbag.py:538} INFO - Filling up the DagBag from /home/felipe/airflow/dags/13_wikipedia.py
[2023-12-31T11:45:25.694-0300] {logging_mixin.py:188} INFO - [2023-12-31T11:45:25.685-0300] {dagbag.py:348} ERROR - Failed to import: /home/felipe/airflow/dags/13_wikipedia.py
Traceback (most recent call last):
  File "/home/felipe/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/felipe/airflow/dags/13_wikipedia.py", line 4, in <module>
    import pandas as pd
ModuleNotFoundError: No module named 'pandas'
[2023-12-31T11:45:25.695-0300] {processor.py:842} WARNING - No viable dags retrieved from /home/felipe/airflow/dags/13_wikipedia.py
[2023-12-31T11:45:25.915-0300] {processor.py:183} INFO - Processing /home/felipe/airflow/dags/13_wikipedia.py took 0.291 seconds
[2023-12-31T11:47:02.436-0300] {processor.py:161} INFO - Started process (PID=35406) to work on /home/felipe/airflow/dags/13_wikipedia.py
[2023-12-31T11:47:02.445-0300] {processor.py:830} INFO - Processing file /home/felipe/airflow/dags/13_wikipedia.py for tasks to queue
[2023-12-31T11:47:02.454-0300] {logging_mixin.py:188} INFO - [2023-12-31T11:47:02.446-0300] {dagbag.py:538} INFO - Filling up the DagBag from /home/felipe/airflow/dags/13_wikipedia.py
[2023-12-31T11:47:02.484-0300] {logging_mixin.py:188} INFO - [2023-12-31T11:47:02.475-0300] {dagbag.py:348} ERROR - Failed to import: /home/felipe/airflow/dags/13_wikipedia.py
Traceback (most recent call last):
  File "/home/felipe/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/felipe/airflow/dags/13_wikipedia.py", line 4, in <module>
    import pandas as pd
ModuleNotFoundError: No module named 'pandas'
[2023-12-31T11:47:02.485-0300] {processor.py:842} WARNING - No viable dags retrieved from /home/felipe/airflow/dags/13_wikipedia.py
[2023-12-31T11:47:02.654-0300] {processor.py:183} INFO - Processing /home/felipe/airflow/dags/13_wikipedia.py took 0.238 seconds
[2023-12-31T11:49:12.814-0300] {processor.py:161} INFO - Started process (PID=35573) to work on /home/felipe/airflow/dags/13_wikipedia.py
[2023-12-31T11:49:12.825-0300] {processor.py:830} INFO - Processing file /home/felipe/airflow/dags/13_wikipedia.py for tasks to queue
[2023-12-31T11:49:12.835-0300] {logging_mixin.py:188} INFO - [2023-12-31T11:49:12.834-0300] {dagbag.py:538} INFO - Filling up the DagBag from /home/felipe/airflow/dags/13_wikipedia.py
[2023-12-31T11:49:12.855-0300] {logging_mixin.py:188} INFO - [2023-12-31T11:49:12.854-0300] {dagbag.py:348} ERROR - Failed to import: /home/felipe/airflow/dags/13_wikipedia.py
Traceback (most recent call last):
  File "/home/felipe/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/felipe/airflow/dags/13_wikipedia.py", line 4, in <module>
    import pandas as pd
ModuleNotFoundError: No module named 'pandas'
[2023-12-31T11:49:12.856-0300] {processor.py:842} WARNING - No viable dags retrieved from /home/felipe/airflow/dags/13_wikipedia.py
[2023-12-31T11:49:13.106-0300] {processor.py:183} INFO - Processing /home/felipe/airflow/dags/13_wikipedia.py took 0.311 seconds
[2023-12-31T11:51:23.036-0300] {processor.py:161} INFO - Started process (PID=35724) to work on /home/felipe/airflow/dags/13_wikipedia.py
[2023-12-31T11:51:23.086-0300] {processor.py:830} INFO - Processing file /home/felipe/airflow/dags/13_wikipedia.py for tasks to queue
[2023-12-31T11:51:23.125-0300] {logging_mixin.py:188} INFO - [2023-12-31T11:51:23.115-0300] {dagbag.py:538} INFO - Filling up the DagBag from /home/felipe/airflow/dags/13_wikipedia.py
[2023-12-31T11:51:23.245-0300] {logging_mixin.py:188} INFO - [2023-12-31T11:51:23.196-0300] {dagbag.py:348} ERROR - Failed to import: /home/felipe/airflow/dags/13_wikipedia.py
Traceback (most recent call last):
  File "/home/felipe/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/felipe/airflow/dags/13_wikipedia.py", line 4, in <module>
    import pandas as pd
ModuleNotFoundError: No module named 'pandas'
[2023-12-31T11:51:23.255-0300] {processor.py:842} WARNING - No viable dags retrieved from /home/felipe/airflow/dags/13_wikipedia.py
[2023-12-31T11:51:23.746-0300] {processor.py:183} INFO - Processing /home/felipe/airflow/dags/13_wikipedia.py took 0.962 seconds
[2023-12-31T11:54:06.336-0300] {processor.py:161} INFO - Started process (PID=35853) to work on /home/felipe/airflow/dags/13_wikipedia.py
[2023-12-31T11:54:06.354-0300] {processor.py:830} INFO - Processing file /home/felipe/airflow/dags/13_wikipedia.py for tasks to queue
[2023-12-31T11:54:06.364-0300] {logging_mixin.py:188} INFO - [2023-12-31T11:54:06.355-0300] {dagbag.py:538} INFO - Filling up the DagBag from /home/felipe/airflow/dags/13_wikipedia.py
[2023-12-31T11:54:06.394-0300] {logging_mixin.py:188} INFO - [2023-12-31T11:54:06.385-0300] {dagbag.py:348} ERROR - Failed to import: /home/felipe/airflow/dags/13_wikipedia.py
Traceback (most recent call last):
  File "/home/felipe/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/felipe/airflow/dags/13_wikipedia.py", line 4, in <module>
    import pandas as pd
ModuleNotFoundError: No module named 'pandas'
[2023-12-31T11:54:06.395-0300] {processor.py:842} WARNING - No viable dags retrieved from /home/felipe/airflow/dags/13_wikipedia.py
[2023-12-31T11:54:06.656-0300] {processor.py:183} INFO - Processing /home/felipe/airflow/dags/13_wikipedia.py took 0.341 seconds
[2023-12-31T11:56:01.814-0300] {processor.py:161} INFO - Started process (PID=35992) to work on /home/felipe/airflow/dags/13_wikipedia.py
[2023-12-31T11:56:01.824-0300] {processor.py:830} INFO - Processing file /home/felipe/airflow/dags/13_wikipedia.py for tasks to queue
[2023-12-31T11:56:01.834-0300] {logging_mixin.py:188} INFO - [2023-12-31T11:56:01.825-0300] {dagbag.py:538} INFO - Filling up the DagBag from /home/felipe/airflow/dags/13_wikipedia.py
[2023-12-31T11:56:01.865-0300] {logging_mixin.py:188} INFO - [2023-12-31T11:56:01.855-0300] {dagbag.py:348} ERROR - Failed to import: /home/felipe/airflow/dags/13_wikipedia.py
Traceback (most recent call last):
  File "/home/felipe/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/felipe/airflow/dags/13_wikipedia.py", line 4, in <module>
    import pandas as pd
ModuleNotFoundError: No module named 'pandas'
[2023-12-31T11:56:01.874-0300] {processor.py:842} WARNING - No viable dags retrieved from /home/felipe/airflow/dags/13_wikipedia.py
[2023-12-31T11:56:02.054-0300] {processor.py:183} INFO - Processing /home/felipe/airflow/dags/13_wikipedia.py took 0.270 seconds
[2023-12-31T11:57:46.485-0300] {processor.py:161} INFO - Started process (PID=36095) to work on /home/felipe/airflow/dags/13_wikipedia.py
[2023-12-31T11:57:46.504-0300] {processor.py:830} INFO - Processing file /home/felipe/airflow/dags/13_wikipedia.py for tasks to queue
[2023-12-31T11:57:46.514-0300] {logging_mixin.py:188} INFO - [2023-12-31T11:57:46.505-0300] {dagbag.py:538} INFO - Filling up the DagBag from /home/felipe/airflow/dags/13_wikipedia.py
[2023-12-31T11:57:46.546-0300] {logging_mixin.py:188} INFO - [2023-12-31T11:57:46.544-0300] {dagbag.py:348} ERROR - Failed to import: /home/felipe/airflow/dags/13_wikipedia.py
Traceback (most recent call last):
  File "/home/felipe/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/felipe/airflow/dags/13_wikipedia.py", line 4, in <module>
    import pandas as pd
ModuleNotFoundError: No module named 'pandas'
[2023-12-31T11:57:46.554-0300] {processor.py:842} WARNING - No viable dags retrieved from /home/felipe/airflow/dags/13_wikipedia.py
[2023-12-31T11:57:46.755-0300] {processor.py:183} INFO - Processing /home/felipe/airflow/dags/13_wikipedia.py took 0.291 seconds
[2023-12-31T11:59:32.085-0300] {processor.py:161} INFO - Started process (PID=36202) to work on /home/felipe/airflow/dags/13_wikipedia.py
[2023-12-31T11:59:32.095-0300] {processor.py:830} INFO - Processing file /home/felipe/airflow/dags/13_wikipedia.py for tasks to queue
[2023-12-31T11:59:32.105-0300] {logging_mixin.py:188} INFO - [2023-12-31T11:59:32.104-0300] {dagbag.py:538} INFO - Filling up the DagBag from /home/felipe/airflow/dags/13_wikipedia.py
[2023-12-31T11:59:32.145-0300] {logging_mixin.py:188} INFO - [2023-12-31T11:59:32.135-0300] {dagbag.py:348} ERROR - Failed to import: /home/felipe/airflow/dags/13_wikipedia.py
Traceback (most recent call last):
  File "/home/felipe/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/felipe/airflow/dags/13_wikipedia.py", line 4, in <module>
    import pandas as pd
ModuleNotFoundError: No module named 'pandas'
[2023-12-31T11:59:32.154-0300] {processor.py:842} WARNING - No viable dags retrieved from /home/felipe/airflow/dags/13_wikipedia.py
[2023-12-31T11:59:32.375-0300] {processor.py:183} INFO - Processing /home/felipe/airflow/dags/13_wikipedia.py took 0.311 seconds
[2023-12-31T12:01:20.215-0300] {processor.py:161} INFO - Started process (PID=36332) to work on /home/felipe/airflow/dags/13_wikipedia.py
[2023-12-31T12:01:20.225-0300] {processor.py:830} INFO - Processing file /home/felipe/airflow/dags/13_wikipedia.py for tasks to queue
[2023-12-31T12:01:20.245-0300] {logging_mixin.py:188} INFO - [2023-12-31T12:01:20.244-0300] {dagbag.py:538} INFO - Filling up the DagBag from /home/felipe/airflow/dags/13_wikipedia.py
[2023-12-31T12:01:20.284-0300] {logging_mixin.py:188} INFO - [2023-12-31T12:01:20.274-0300] {dagbag.py:348} ERROR - Failed to import: /home/felipe/airflow/dags/13_wikipedia.py
Traceback (most recent call last):
  File "/home/felipe/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/felipe/airflow/dags/13_wikipedia.py", line 4, in <module>
    import pandas as pd
ModuleNotFoundError: No module named 'pandas'
[2023-12-31T12:01:20.285-0300] {processor.py:842} WARNING - No viable dags retrieved from /home/felipe/airflow/dags/13_wikipedia.py
[2023-12-31T12:01:20.485-0300] {processor.py:183} INFO - Processing /home/felipe/airflow/dags/13_wikipedia.py took 0.300 seconds
[2023-12-31T12:03:19.135-0300] {processor.py:161} INFO - Started process (PID=36439) to work on /home/felipe/airflow/dags/13_wikipedia.py
[2023-12-31T12:03:19.154-0300] {processor.py:830} INFO - Processing file /home/felipe/airflow/dags/13_wikipedia.py for tasks to queue
[2023-12-31T12:03:19.155-0300] {logging_mixin.py:188} INFO - [2023-12-31T12:03:19.155-0300] {dagbag.py:538} INFO - Filling up the DagBag from /home/felipe/airflow/dags/13_wikipedia.py
[2023-12-31T12:03:19.195-0300] {logging_mixin.py:188} INFO - [2023-12-31T12:03:19.185-0300] {dagbag.py:348} ERROR - Failed to import: /home/felipe/airflow/dags/13_wikipedia.py
Traceback (most recent call last):
  File "/home/felipe/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/felipe/airflow/dags/13_wikipedia.py", line 4, in <module>
    import pandas as pd
ModuleNotFoundError: No module named 'pandas'
[2023-12-31T12:03:19.195-0300] {processor.py:842} WARNING - No viable dags retrieved from /home/felipe/airflow/dags/13_wikipedia.py
[2023-12-31T12:03:19.404-0300] {processor.py:183} INFO - Processing /home/felipe/airflow/dags/13_wikipedia.py took 0.309 seconds
[2023-12-31T12:06:37.315-0300] {processor.py:161} INFO - Started process (PID=36688) to work on /home/felipe/airflow/dags/13_wikipedia.py
[2023-12-31T12:06:37.355-0300] {processor.py:830} INFO - Processing file /home/felipe/airflow/dags/13_wikipedia.py for tasks to queue
[2023-12-31T12:06:37.395-0300] {logging_mixin.py:188} INFO - [2023-12-31T12:06:37.385-0300] {dagbag.py:538} INFO - Filling up the DagBag from /home/felipe/airflow/dags/13_wikipedia.py
[2023-12-31T12:06:37.474-0300] {logging_mixin.py:188} INFO - [2023-12-31T12:06:37.454-0300] {dagbag.py:348} ERROR - Failed to import: /home/felipe/airflow/dags/13_wikipedia.py
Traceback (most recent call last):
  File "/home/felipe/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/felipe/airflow/dags/13_wikipedia.py", line 4, in <module>
    import pandas as pd
ModuleNotFoundError: No module named 'pandas'
[2023-12-31T12:06:37.484-0300] {processor.py:842} WARNING - No viable dags retrieved from /home/felipe/airflow/dags/13_wikipedia.py
[2023-12-31T12:06:37.885-0300] {processor.py:183} INFO - Processing /home/felipe/airflow/dags/13_wikipedia.py took 0.630 seconds
[2023-12-31T12:10:01.065-0300] {processor.py:161} INFO - Started process (PID=37068) to work on /home/felipe/airflow/dags/13_wikipedia.py
[2023-12-31T12:10:01.104-0300] {processor.py:830} INFO - Processing file /home/felipe/airflow/dags/13_wikipedia.py for tasks to queue
[2023-12-31T12:10:01.134-0300] {logging_mixin.py:188} INFO - [2023-12-31T12:10:01.124-0300] {dagbag.py:538} INFO - Filling up the DagBag from /home/felipe/airflow/dags/13_wikipedia.py
[2023-12-31T12:10:01.224-0300] {logging_mixin.py:188} INFO - [2023-12-31T12:10:01.194-0300] {dagbag.py:348} ERROR - Failed to import: /home/felipe/airflow/dags/13_wikipedia.py
Traceback (most recent call last):
  File "/home/felipe/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/felipe/airflow/dags/13_wikipedia.py", line 4, in <module>
    import pandas as pd
ModuleNotFoundError: No module named 'pandas'
[2023-12-31T12:10:01.235-0300] {processor.py:842} WARNING - No viable dags retrieved from /home/felipe/airflow/dags/13_wikipedia.py
[2023-12-31T12:10:01.674-0300] {processor.py:183} INFO - Processing /home/felipe/airflow/dags/13_wikipedia.py took 0.661 seconds
[2023-12-31T12:11:22.944-0300] {processor.py:161} INFO - Started process (PID=37175) to work on /home/felipe/airflow/dags/13_wikipedia.py
[2023-12-31T12:11:22.964-0300] {processor.py:830} INFO - Processing file /home/felipe/airflow/dags/13_wikipedia.py for tasks to queue
[2023-12-31T12:11:22.984-0300] {logging_mixin.py:188} INFO - [2023-12-31T12:11:22.975-0300] {dagbag.py:538} INFO - Filling up the DagBag from /home/felipe/airflow/dags/13_wikipedia.py
[2023-12-31T12:11:23.035-0300] {logging_mixin.py:188} INFO - [2023-12-31T12:11:23.024-0300] {dagbag.py:348} ERROR - Failed to import: /home/felipe/airflow/dags/13_wikipedia.py
Traceback (most recent call last):
  File "/home/felipe/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/felipe/airflow/dags/13_wikipedia.py", line 4, in <module>
    import pandas as pd
ModuleNotFoundError: No module named 'pandas'
[2023-12-31T12:11:23.045-0300] {processor.py:842} WARNING - No viable dags retrieved from /home/felipe/airflow/dags/13_wikipedia.py
[2023-12-31T12:11:23.355-0300] {processor.py:183} INFO - Processing /home/felipe/airflow/dags/13_wikipedia.py took 0.491 seconds
[2023-12-31T12:12:12.185-0300] {processor.py:161} INFO - Started process (PID=37237) to work on /home/felipe/airflow/dags/13_wikipedia.py
[2023-12-31T12:12:12.204-0300] {processor.py:830} INFO - Processing file /home/felipe/airflow/dags/13_wikipedia.py for tasks to queue
[2023-12-31T12:12:12.225-0300] {logging_mixin.py:188} INFO - [2023-12-31T12:12:12.215-0300] {dagbag.py:538} INFO - Filling up the DagBag from /home/felipe/airflow/dags/13_wikipedia.py
[2023-12-31T12:12:12.285-0300] {logging_mixin.py:188} INFO - [2023-12-31T12:12:12.265-0300] {dagbag.py:348} ERROR - Failed to import: /home/felipe/airflow/dags/13_wikipedia.py
Traceback (most recent call last):
  File "/home/felipe/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/felipe/airflow/dags/13_wikipedia.py", line 4, in <module>
    import pandas as pd
ModuleNotFoundError: No module named 'pandas'
[2023-12-31T12:12:12.295-0300] {processor.py:842} WARNING - No viable dags retrieved from /home/felipe/airflow/dags/13_wikipedia.py
[2023-12-31T12:12:12.585-0300] {processor.py:183} INFO - Processing /home/felipe/airflow/dags/13_wikipedia.py took 0.430 seconds
[2023-12-31T12:13:08.874-0300] {processor.py:161} INFO - Started process (PID=37315) to work on /home/felipe/airflow/dags/13_wikipedia.py
[2023-12-31T12:13:08.894-0300] {processor.py:830} INFO - Processing file /home/felipe/airflow/dags/13_wikipedia.py for tasks to queue
[2023-12-31T12:13:08.915-0300] {logging_mixin.py:188} INFO - [2023-12-31T12:13:08.905-0300] {dagbag.py:538} INFO - Filling up the DagBag from /home/felipe/airflow/dags/13_wikipedia.py
[2023-12-31T12:13:08.985-0300] {logging_mixin.py:188} INFO - [2023-12-31T12:13:08.975-0300] {dagbag.py:348} ERROR - Failed to import: /home/felipe/airflow/dags/13_wikipedia.py
Traceback (most recent call last):
  File "/home/felipe/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/felipe/airflow/dags/13_wikipedia.py", line 4, in <module>
    import pandas as pd
ModuleNotFoundError: No module named 'pandas'
[2023-12-31T12:13:08.995-0300] {processor.py:842} WARNING - No viable dags retrieved from /home/felipe/airflow/dags/13_wikipedia.py
[2023-12-31T12:13:09.295-0300] {processor.py:183} INFO - Processing /home/felipe/airflow/dags/13_wikipedia.py took 0.470 seconds
[2023-12-31T12:13:51.194-0300] {processor.py:161} INFO - Started process (PID=37371) to work on /home/felipe/airflow/dags/13_wikipedia.py
[2023-12-31T12:13:51.214-0300] {processor.py:830} INFO - Processing file /home/felipe/airflow/dags/13_wikipedia.py for tasks to queue
[2023-12-31T12:13:51.225-0300] {logging_mixin.py:188} INFO - [2023-12-31T12:13:51.224-0300] {dagbag.py:538} INFO - Filling up the DagBag from /home/felipe/airflow/dags/13_wikipedia.py
[2023-12-31T12:13:51.275-0300] {logging_mixin.py:188} INFO - [2023-12-31T12:13:51.264-0300] {dagbag.py:348} ERROR - Failed to import: /home/felipe/airflow/dags/13_wikipedia.py
Traceback (most recent call last):
  File "/home/felipe/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/felipe/airflow/dags/13_wikipedia.py", line 4, in <module>
    import pandas as pd
ModuleNotFoundError: No module named 'pandas'
[2023-12-31T12:13:51.284-0300] {processor.py:842} WARNING - No viable dags retrieved from /home/felipe/airflow/dags/13_wikipedia.py
[2023-12-31T12:13:51.704-0300] {processor.py:183} INFO - Processing /home/felipe/airflow/dags/13_wikipedia.py took 0.569 seconds
[2023-12-31T12:14:39.865-0300] {processor.py:161} INFO - Started process (PID=37463) to work on /home/felipe/airflow/dags/13_wikipedia.py
[2023-12-31T12:14:39.895-0300] {processor.py:830} INFO - Processing file /home/felipe/airflow/dags/13_wikipedia.py for tasks to queue
[2023-12-31T12:14:39.934-0300] {logging_mixin.py:188} INFO - [2023-12-31T12:14:39.915-0300] {dagbag.py:538} INFO - Filling up the DagBag from /home/felipe/airflow/dags/13_wikipedia.py
[2023-12-31T12:14:40.035-0300] {logging_mixin.py:188} INFO - [2023-12-31T12:14:40.014-0300] {dagbag.py:348} ERROR - Failed to import: /home/felipe/airflow/dags/13_wikipedia.py
Traceback (most recent call last):
  File "/home/felipe/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/felipe/airflow/dags/13_wikipedia.py", line 4, in <module>
    import pandas as pd
ModuleNotFoundError: No module named 'pandas'
[2023-12-31T12:14:40.054-0300] {processor.py:842} WARNING - No viable dags retrieved from /home/felipe/airflow/dags/13_wikipedia.py
[2023-12-31T12:14:40.525-0300] {processor.py:183} INFO - Processing /home/felipe/airflow/dags/13_wikipedia.py took 0.740 seconds
[2023-12-31T12:15:30.364-0300] {processor.py:161} INFO - Started process (PID=37526) to work on /home/felipe/airflow/dags/13_wikipedia.py
[2023-12-31T12:15:30.374-0300] {processor.py:830} INFO - Processing file /home/felipe/airflow/dags/13_wikipedia.py for tasks to queue
[2023-12-31T12:15:30.394-0300] {logging_mixin.py:188} INFO - [2023-12-31T12:15:30.384-0300] {dagbag.py:538} INFO - Filling up the DagBag from /home/felipe/airflow/dags/13_wikipedia.py
[2023-12-31T12:15:30.454-0300] {logging_mixin.py:188} INFO - [2023-12-31T12:15:30.435-0300] {dagbag.py:348} ERROR - Failed to import: /home/felipe/airflow/dags/13_wikipedia.py
Traceback (most recent call last):
  File "/home/felipe/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/felipe/airflow/dags/13_wikipedia.py", line 4, in <module>
    import pandas as pd
ModuleNotFoundError: No module named 'pandas'
[2023-12-31T12:15:30.464-0300] {processor.py:842} WARNING - No viable dags retrieved from /home/felipe/airflow/dags/13_wikipedia.py
[2023-12-31T12:15:30.955-0300] {processor.py:183} INFO - Processing /home/felipe/airflow/dags/13_wikipedia.py took 0.631 seconds
[2023-12-31T12:16:19.284-0300] {processor.py:161} INFO - Started process (PID=37591) to work on /home/felipe/airflow/dags/13_wikipedia.py
[2023-12-31T12:16:19.304-0300] {processor.py:830} INFO - Processing file /home/felipe/airflow/dags/13_wikipedia.py for tasks to queue
[2023-12-31T12:16:19.324-0300] {logging_mixin.py:188} INFO - [2023-12-31T12:16:19.314-0300] {dagbag.py:538} INFO - Filling up the DagBag from /home/felipe/airflow/dags/13_wikipedia.py
[2023-12-31T12:16:19.364-0300] {logging_mixin.py:188} INFO - [2023-12-31T12:16:19.354-0300] {dagbag.py:348} ERROR - Failed to import: /home/felipe/airflow/dags/13_wikipedia.py
Traceback (most recent call last):
  File "/home/felipe/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/felipe/airflow/dags/13_wikipedia.py", line 4, in <module>
    import pandas as pd
ModuleNotFoundError: No module named 'pandas'
[2023-12-31T12:16:19.374-0300] {processor.py:842} WARNING - No viable dags retrieved from /home/felipe/airflow/dags/13_wikipedia.py
[2023-12-31T12:16:19.704-0300] {processor.py:183} INFO - Processing /home/felipe/airflow/dags/13_wikipedia.py took 0.470 seconds
[2023-12-31T12:17:03.534-0300] {processor.py:161} INFO - Started process (PID=37649) to work on /home/felipe/airflow/dags/13_wikipedia.py
[2023-12-31T12:17:03.554-0300] {processor.py:830} INFO - Processing file /home/felipe/airflow/dags/13_wikipedia.py for tasks to queue
[2023-12-31T12:17:03.564-0300] {logging_mixin.py:188} INFO - [2023-12-31T12:17:03.555-0300] {dagbag.py:538} INFO - Filling up the DagBag from /home/felipe/airflow/dags/13_wikipedia.py
[2023-12-31T12:17:03.614-0300] {logging_mixin.py:188} INFO - [2023-12-31T12:17:03.595-0300] {dagbag.py:348} ERROR - Failed to import: /home/felipe/airflow/dags/13_wikipedia.py
Traceback (most recent call last):
  File "/home/felipe/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/felipe/airflow/dags/13_wikipedia.py", line 4, in <module>
    import pandas as pd
ModuleNotFoundError: No module named 'pandas'
[2023-12-31T12:17:03.624-0300] {processor.py:842} WARNING - No viable dags retrieved from /home/felipe/airflow/dags/13_wikipedia.py
[2023-12-31T12:17:04.044-0300] {processor.py:183} INFO - Processing /home/felipe/airflow/dags/13_wikipedia.py took 0.550 seconds
[2023-12-31T12:17:55.784-0300] {processor.py:161} INFO - Started process (PID=37714) to work on /home/felipe/airflow/dags/13_wikipedia.py
[2023-12-31T12:17:55.804-0300] {processor.py:830} INFO - Processing file /home/felipe/airflow/dags/13_wikipedia.py for tasks to queue
[2023-12-31T12:17:55.834-0300] {logging_mixin.py:188} INFO - [2023-12-31T12:17:55.824-0300] {dagbag.py:538} INFO - Filling up the DagBag from /home/felipe/airflow/dags/13_wikipedia.py
[2023-12-31T12:17:55.934-0300] {logging_mixin.py:188} INFO - [2023-12-31T12:17:55.904-0300] {dagbag.py:348} ERROR - Failed to import: /home/felipe/airflow/dags/13_wikipedia.py
Traceback (most recent call last):
  File "/home/felipe/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/felipe/airflow/dags/13_wikipedia.py", line 4, in <module>
    import pandas as pd
ModuleNotFoundError: No module named 'pandas'
[2023-12-31T12:17:55.944-0300] {processor.py:842} WARNING - No viable dags retrieved from /home/felipe/airflow/dags/13_wikipedia.py
[2023-12-31T12:17:56.514-0300] {processor.py:183} INFO - Processing /home/felipe/airflow/dags/13_wikipedia.py took 0.799 seconds
[2023-12-31T12:18:49.244-0300] {processor.py:161} INFO - Started process (PID=37783) to work on /home/felipe/airflow/dags/13_wikipedia.py
[2023-12-31T12:18:49.264-0300] {processor.py:830} INFO - Processing file /home/felipe/airflow/dags/13_wikipedia.py for tasks to queue
[2023-12-31T12:18:49.294-0300] {logging_mixin.py:188} INFO - [2023-12-31T12:18:49.284-0300] {dagbag.py:538} INFO - Filling up the DagBag from /home/felipe/airflow/dags/13_wikipedia.py
[2023-12-31T12:18:49.374-0300] {logging_mixin.py:188} INFO - [2023-12-31T12:18:49.344-0300] {dagbag.py:348} ERROR - Failed to import: /home/felipe/airflow/dags/13_wikipedia.py
Traceback (most recent call last):
  File "/home/felipe/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/felipe/airflow/dags/13_wikipedia.py", line 4, in <module>
    import pandas as pd
ModuleNotFoundError: No module named 'pandas'
[2023-12-31T12:18:49.384-0300] {processor.py:842} WARNING - No viable dags retrieved from /home/felipe/airflow/dags/13_wikipedia.py
[2023-12-31T12:18:49.724-0300] {processor.py:183} INFO - Processing /home/felipe/airflow/dags/13_wikipedia.py took 0.531 seconds
[2023-12-31T12:25:51.710-0300] {processor.py:161} INFO - Started process (PID=37967) to work on /home/felipe/airflow/dags/13_wikipedia.py
[2023-12-31T12:25:51.731-0300] {processor.py:830} INFO - Processing file /home/felipe/airflow/dags/13_wikipedia.py for tasks to queue
[2023-12-31T12:25:51.771-0300] {logging_mixin.py:188} INFO - [2023-12-31T12:25:51.761-0300] {dagbag.py:538} INFO - Filling up the DagBag from /home/felipe/airflow/dags/13_wikipedia.py
[2023-12-31T12:25:51.881-0300] {logging_mixin.py:188} INFO - [2023-12-31T12:25:51.851-0300] {dagbag.py:348} ERROR - Failed to import: /home/felipe/airflow/dags/13_wikipedia.py
Traceback (most recent call last):
  File "/home/felipe/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/felipe/airflow/dags/13_wikipedia.py", line 4, in <module>
    import pandas as pd
ModuleNotFoundError: No module named 'pandas'
[2023-12-31T12:25:51.901-0300] {processor.py:842} WARNING - No viable dags retrieved from /home/felipe/airflow/dags/13_wikipedia.py
[2023-12-31T12:25:52.960-0300] {processor.py:183} INFO - Processing /home/felipe/airflow/dags/13_wikipedia.py took 1.340 seconds
[2023-12-31T12:26:58.161-0300] {processor.py:161} INFO - Started process (PID=38017) to work on /home/felipe/airflow/dags/13_wikipedia.py
[2023-12-31T12:26:58.191-0300] {processor.py:830} INFO - Processing file /home/felipe/airflow/dags/13_wikipedia.py for tasks to queue
[2023-12-31T12:26:58.221-0300] {logging_mixin.py:188} INFO - [2023-12-31T12:26:58.210-0300] {dagbag.py:538} INFO - Filling up the DagBag from /home/felipe/airflow/dags/13_wikipedia.py
[2023-12-31T12:26:58.321-0300] {logging_mixin.py:188} INFO - [2023-12-31T12:26:58.300-0300] {dagbag.py:348} ERROR - Failed to import: /home/felipe/airflow/dags/13_wikipedia.py
Traceback (most recent call last):
  File "/home/felipe/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/felipe/airflow/dags/13_wikipedia.py", line 4, in <module>
    import pandas as pd
ModuleNotFoundError: No module named 'pandas'
[2023-12-31T12:26:58.340-0300] {processor.py:842} WARNING - No viable dags retrieved from /home/felipe/airflow/dags/13_wikipedia.py
[2023-12-31T12:26:58.791-0300] {processor.py:183} INFO - Processing /home/felipe/airflow/dags/13_wikipedia.py took 0.691 seconds
[2023-12-31T12:28:13.220-0300] {processor.py:161} INFO - Started process (PID=38090) to work on /home/felipe/airflow/dags/13_wikipedia.py
[2023-12-31T12:28:13.250-0300] {processor.py:830} INFO - Processing file /home/felipe/airflow/dags/13_wikipedia.py for tasks to queue
[2023-12-31T12:28:13.271-0300] {logging_mixin.py:188} INFO - [2023-12-31T12:28:13.261-0300] {dagbag.py:538} INFO - Filling up the DagBag from /home/felipe/airflow/dags/13_wikipedia.py
[2023-12-31T12:28:13.370-0300] {logging_mixin.py:188} INFO - [2023-12-31T12:28:13.341-0300] {dagbag.py:348} ERROR - Failed to import: /home/felipe/airflow/dags/13_wikipedia.py
Traceback (most recent call last):
  File "/home/felipe/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/felipe/airflow/dags/13_wikipedia.py", line 4, in <module>
    import pandas as pd
ModuleNotFoundError: No module named 'pandas'
[2023-12-31T12:28:13.381-0300] {processor.py:842} WARNING - No viable dags retrieved from /home/felipe/airflow/dags/13_wikipedia.py
[2023-12-31T12:28:13.910-0300] {processor.py:183} INFO - Processing /home/felipe/airflow/dags/13_wikipedia.py took 0.760 seconds
[2023-12-31T12:29:19.161-0300] {processor.py:161} INFO - Started process (PID=38134) to work on /home/felipe/airflow/dags/13_wikipedia.py
[2023-12-31T12:29:19.181-0300] {processor.py:830} INFO - Processing file /home/felipe/airflow/dags/13_wikipedia.py for tasks to queue
[2023-12-31T12:29:19.211-0300] {logging_mixin.py:188} INFO - [2023-12-31T12:29:19.201-0300] {dagbag.py:538} INFO - Filling up the DagBag from /home/felipe/airflow/dags/13_wikipedia.py
[2023-12-31T12:29:19.301-0300] {logging_mixin.py:188} INFO - [2023-12-31T12:29:19.281-0300] {dagbag.py:348} ERROR - Failed to import: /home/felipe/airflow/dags/13_wikipedia.py
Traceback (most recent call last):
  File "/home/felipe/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/felipe/airflow/dags/13_wikipedia.py", line 4, in <module>
    import pandas as pd
ModuleNotFoundError: No module named 'pandas'
[2023-12-31T12:29:19.320-0300] {processor.py:842} WARNING - No viable dags retrieved from /home/felipe/airflow/dags/13_wikipedia.py
[2023-12-31T12:29:19.871-0300] {processor.py:183} INFO - Processing /home/felipe/airflow/dags/13_wikipedia.py took 0.779 seconds
[2023-12-31T12:30:35.390-0300] {processor.py:161} INFO - Started process (PID=38217) to work on /home/felipe/airflow/dags/13_wikipedia.py
[2023-12-31T12:30:35.420-0300] {processor.py:830} INFO - Processing file /home/felipe/airflow/dags/13_wikipedia.py for tasks to queue
[2023-12-31T12:30:35.440-0300] {logging_mixin.py:188} INFO - [2023-12-31T12:30:35.431-0300] {dagbag.py:538} INFO - Filling up the DagBag from /home/felipe/airflow/dags/13_wikipedia.py
[2023-12-31T12:30:35.510-0300] {logging_mixin.py:188} INFO - [2023-12-31T12:30:35.490-0300] {dagbag.py:348} ERROR - Failed to import: /home/felipe/airflow/dags/13_wikipedia.py
Traceback (most recent call last):
  File "/home/felipe/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/felipe/airflow/dags/13_wikipedia.py", line 4, in <module>
    import pandas as pd
ModuleNotFoundError: No module named 'pandas'
[2023-12-31T12:30:35.521-0300] {processor.py:842} WARNING - No viable dags retrieved from /home/felipe/airflow/dags/13_wikipedia.py
[2023-12-31T12:30:35.931-0300] {processor.py:183} INFO - Processing /home/felipe/airflow/dags/13_wikipedia.py took 0.600 seconds
[2023-12-31T12:31:52.480-0300] {processor.py:161} INFO - Started process (PID=38265) to work on /home/felipe/airflow/dags/13_wikipedia.py
[2023-12-31T12:31:52.501-0300] {processor.py:830} INFO - Processing file /home/felipe/airflow/dags/13_wikipedia.py for tasks to queue
[2023-12-31T12:31:52.531-0300] {logging_mixin.py:188} INFO - [2023-12-31T12:31:52.521-0300] {dagbag.py:538} INFO - Filling up the DagBag from /home/felipe/airflow/dags/13_wikipedia.py
[2023-12-31T12:31:52.630-0300] {logging_mixin.py:188} INFO - [2023-12-31T12:31:52.600-0300] {dagbag.py:348} ERROR - Failed to import: /home/felipe/airflow/dags/13_wikipedia.py
Traceback (most recent call last):
  File "/home/felipe/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/felipe/airflow/dags/13_wikipedia.py", line 4, in <module>
    import pandas as pd
ModuleNotFoundError: No module named 'pandas'
[2023-12-31T12:31:52.641-0300] {processor.py:842} WARNING - No viable dags retrieved from /home/felipe/airflow/dags/13_wikipedia.py
[2023-12-31T12:31:53.191-0300] {processor.py:183} INFO - Processing /home/felipe/airflow/dags/13_wikipedia.py took 0.800 seconds
[2023-12-31T12:33:18.481-0300] {processor.py:161} INFO - Started process (PID=38319) to work on /home/felipe/airflow/dags/13_wikipedia.py
[2023-12-31T12:33:18.501-0300] {processor.py:830} INFO - Processing file /home/felipe/airflow/dags/13_wikipedia.py for tasks to queue
[2023-12-31T12:33:18.540-0300] {logging_mixin.py:188} INFO - [2023-12-31T12:33:18.521-0300] {dagbag.py:538} INFO - Filling up the DagBag from /home/felipe/airflow/dags/13_wikipedia.py
[2023-12-31T12:33:18.631-0300] {logging_mixin.py:188} INFO - [2023-12-31T12:33:18.591-0300] {dagbag.py:348} ERROR - Failed to import: /home/felipe/airflow/dags/13_wikipedia.py
Traceback (most recent call last):
  File "/home/felipe/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/felipe/airflow/dags/13_wikipedia.py", line 4, in <module>
    import pandas as pd
ModuleNotFoundError: No module named 'pandas'
[2023-12-31T12:33:18.641-0300] {processor.py:842} WARNING - No viable dags retrieved from /home/felipe/airflow/dags/13_wikipedia.py
[2023-12-31T12:33:19.171-0300] {processor.py:183} INFO - Processing /home/felipe/airflow/dags/13_wikipedia.py took 0.750 seconds
[2023-12-31T12:34:45.701-0300] {processor.py:161} INFO - Started process (PID=38375) to work on /home/felipe/airflow/dags/13_wikipedia.py
[2023-12-31T12:34:45.741-0300] {processor.py:830} INFO - Processing file /home/felipe/airflow/dags/13_wikipedia.py for tasks to queue
[2023-12-31T12:34:45.770-0300] {logging_mixin.py:188} INFO - [2023-12-31T12:34:45.760-0300] {dagbag.py:538} INFO - Filling up the DagBag from /home/felipe/airflow/dags/13_wikipedia.py
[2023-12-31T12:34:45.881-0300] {logging_mixin.py:188} INFO - [2023-12-31T12:34:45.841-0300] {dagbag.py:348} ERROR - Failed to import: /home/felipe/airflow/dags/13_wikipedia.py
Traceback (most recent call last):
  File "/home/felipe/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/felipe/airflow/dags/13_wikipedia.py", line 4, in <module>
    import pandas as pd
ModuleNotFoundError: No module named 'pandas'
[2023-12-31T12:34:45.900-0300] {processor.py:842} WARNING - No viable dags retrieved from /home/felipe/airflow/dags/13_wikipedia.py
[2023-12-31T12:34:46.521-0300] {processor.py:183} INFO - Processing /home/felipe/airflow/dags/13_wikipedia.py took 0.910 seconds
[2023-12-31T12:36:33.801-0300] {processor.py:161} INFO - Started process (PID=38464) to work on /home/felipe/airflow/dags/13_wikipedia.py
[2023-12-31T12:36:33.840-0300] {processor.py:830} INFO - Processing file /home/felipe/airflow/dags/13_wikipedia.py for tasks to queue
[2023-12-31T12:36:33.871-0300] {logging_mixin.py:188} INFO - [2023-12-31T12:36:33.860-0300] {dagbag.py:538} INFO - Filling up the DagBag from /home/felipe/airflow/dags/13_wikipedia.py
[2023-12-31T12:36:34.010-0300] {logging_mixin.py:188} INFO - [2023-12-31T12:36:33.970-0300] {dagbag.py:348} ERROR - Failed to import: /home/felipe/airflow/dags/13_wikipedia.py
Traceback (most recent call last):
  File "/home/felipe/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/felipe/airflow/dags/13_wikipedia.py", line 4, in <module>
    import pandas as pd
ModuleNotFoundError: No module named 'pandas'
[2023-12-31T12:36:34.021-0300] {processor.py:842} WARNING - No viable dags retrieved from /home/felipe/airflow/dags/13_wikipedia.py
[2023-12-31T12:36:34.740-0300] {processor.py:183} INFO - Processing /home/felipe/airflow/dags/13_wikipedia.py took 1.030 seconds
[2023-12-31T12:46:15.308-0300] {processor.py:161} INFO - Started process (PID=38711) to work on /home/felipe/airflow/dags/13_wikipedia.py
[2023-12-31T12:46:15.388-0300] {processor.py:830} INFO - Processing file /home/felipe/airflow/dags/13_wikipedia.py for tasks to queue
[2023-12-31T12:46:15.497-0300] {logging_mixin.py:188} INFO - [2023-12-31T12:46:15.448-0300] {dagbag.py:538} INFO - Filling up the DagBag from /home/felipe/airflow/dags/13_wikipedia.py
[2023-12-31T12:46:15.948-0300] {logging_mixin.py:188} INFO - [2023-12-31T12:46:15.868-0300] {dagbag.py:348} ERROR - Failed to import: /home/felipe/airflow/dags/13_wikipedia.py
Traceback (most recent call last):
  File "/home/felipe/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/felipe/airflow/dags/13_wikipedia.py", line 4, in <module>
    import pandas as pd
ModuleNotFoundError: No module named 'pandas'
[2023-12-31T12:46:15.998-0300] {processor.py:842} WARNING - No viable dags retrieved from /home/felipe/airflow/dags/13_wikipedia.py
[2023-12-31T12:46:18.698-0300] {processor.py:183} INFO - Processing /home/felipe/airflow/dags/13_wikipedia.py took 3.620 seconds
[2023-12-31T12:48:34.608-0300] {processor.py:161} INFO - Started process (PID=38803) to work on /home/felipe/airflow/dags/13_wikipedia.py
[2023-12-31T12:48:34.668-0300] {processor.py:830} INFO - Processing file /home/felipe/airflow/dags/13_wikipedia.py for tasks to queue
[2023-12-31T12:48:34.728-0300] {logging_mixin.py:188} INFO - [2023-12-31T12:48:34.708-0300] {dagbag.py:538} INFO - Filling up the DagBag from /home/felipe/airflow/dags/13_wikipedia.py
[2023-12-31T12:48:34.987-0300] {logging_mixin.py:188} INFO - [2023-12-31T12:48:34.907-0300] {dagbag.py:348} ERROR - Failed to import: /home/felipe/airflow/dags/13_wikipedia.py
Traceback (most recent call last):
  File "/home/felipe/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/felipe/airflow/dags/13_wikipedia.py", line 4, in <module>
    import pandas as pd
ModuleNotFoundError: No module named 'pandas'
[2023-12-31T12:48:35.027-0300] {processor.py:842} WARNING - No viable dags retrieved from /home/felipe/airflow/dags/13_wikipedia.py
[2023-12-31T12:48:36.438-0300] {processor.py:183} INFO - Processing /home/felipe/airflow/dags/13_wikipedia.py took 2.030 seconds
[2023-12-31T12:53:03.498-0300] {processor.py:161} INFO - Started process (PID=38920) to work on /home/felipe/airflow/dags/13_wikipedia.py
[2023-12-31T12:53:03.667-0300] {processor.py:830} INFO - Processing file /home/felipe/airflow/dags/13_wikipedia.py for tasks to queue
[2023-12-31T12:53:03.888-0300] {logging_mixin.py:188} INFO - [2023-12-31T12:53:03.778-0300] {dagbag.py:538} INFO - Filling up the DagBag from /home/felipe/airflow/dags/13_wikipedia.py
[2023-12-31T12:53:04.627-0300] {logging_mixin.py:188} INFO - [2023-12-31T12:53:04.397-0300] {dagbag.py:348} ERROR - Failed to import: /home/felipe/airflow/dags/13_wikipedia.py
Traceback (most recent call last):
  File "/home/felipe/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/felipe/airflow/dags/13_wikipedia.py", line 4, in <module>
    import pandas as pd
ModuleNotFoundError: No module named 'pandas'
[2023-12-31T12:53:04.747-0300] {processor.py:842} WARNING - No viable dags retrieved from /home/felipe/airflow/dags/13_wikipedia.py
[2023-12-31T12:53:09.047-0300] {processor.py:183} INFO - Processing /home/felipe/airflow/dags/13_wikipedia.py took 6.020 seconds
