[2023-12-31T09:31:15.887-0300] {processor.py:161} INFO - Started process (PID=31607) to work on /home/felipe/airflow/dags/19_postgre_operator.py
[2023-12-31T09:31:15.889-0300] {processor.py:830} INFO - Processing file /home/felipe/airflow/dags/19_postgre_operator.py for tasks to queue
[2023-12-31T09:31:15.897-0300] {logging_mixin.py:188} INFO - [2023-12-31T09:31:15.891-0300] {dagbag.py:538} INFO - Filling up the DagBag from /home/felipe/airflow/dags/19_postgre_operator.py
[2023-12-31T09:31:15.921-0300] {logging_mixin.py:188} INFO - [2023-12-31T09:31:15.919-0300] {dagbag.py:348} ERROR - Failed to import: /home/felipe/airflow/dags/19_postgre_operator.py
Traceback (most recent call last):
  File "/home/felipe/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/felipe/airflow/dags/19_postgre_operator.py", line 14, in <module>
    extract_gz = BashOperator(
  File "/home/felipe/.local/lib/python3.10/site-packages/airflow/models/baseoperator.py", line 437, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/home/felipe/.local/lib/python3.10/site-packages/airflow/operators/bash.py", line 152, in __init__
    super().__init__(**kwargs)
  File "/home/felipe/.local/lib/python3.10/site-packages/airflow/models/baseoperator.py", line 437, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/home/felipe/.local/lib/python3.10/site-packages/airflow/models/baseoperator.py", line 798, in __init__
    raise AirflowException(
airflow.exceptions.AirflowException: Invalid arguments were passed to BashOperator (task_id: extract_gz). Invalid arguments were:
**kwargs: {'template_searchpath': '/tmp'}
[2023-12-31T09:31:15.926-0300] {processor.py:842} WARNING - No viable dags retrieved from /home/felipe/airflow/dags/19_postgre_operator.py
[2023-12-31T09:31:16.010-0300] {processor.py:183} INFO - Processing /home/felipe/airflow/dags/19_postgre_operator.py took 0.140 seconds
[2023-12-31T09:34:01.318-0300] {processor.py:161} INFO - Started process (PID=31726) to work on /home/felipe/airflow/dags/19_postgre_operator.py
[2023-12-31T09:34:01.320-0300] {processor.py:830} INFO - Processing file /home/felipe/airflow/dags/19_postgre_operator.py for tasks to queue
[2023-12-31T09:34:01.321-0300] {logging_mixin.py:188} INFO - [2023-12-31T09:34:01.320-0300] {dagbag.py:538} INFO - Filling up the DagBag from /home/felipe/airflow/dags/19_postgre_operator.py
[2023-12-31T09:34:01.339-0300] {logging_mixin.py:188} INFO - [2023-12-31T09:34:01.337-0300] {dagbag.py:348} ERROR - Failed to import: /home/felipe/airflow/dags/19_postgre_operator.py
Traceback (most recent call last):
  File "/home/felipe/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/felipe/airflow/dags/19_postgre_operator.py", line 14, in <module>
    extract_gz = BashOperator(
  File "/home/felipe/.local/lib/python3.10/site-packages/airflow/models/baseoperator.py", line 437, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/home/felipe/.local/lib/python3.10/site-packages/airflow/operators/bash.py", line 152, in __init__
    super().__init__(**kwargs)
  File "/home/felipe/.local/lib/python3.10/site-packages/airflow/models/baseoperator.py", line 437, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/home/felipe/.local/lib/python3.10/site-packages/airflow/models/baseoperator.py", line 798, in __init__
    raise AirflowException(
airflow.exceptions.AirflowException: Invalid arguments were passed to BashOperator (task_id: extract_gz). Invalid arguments were:
**kwargs: {'template_searchpath': '/tmp'}
[2023-12-31T09:34:01.339-0300] {processor.py:842} WARNING - No viable dags retrieved from /home/felipe/airflow/dags/19_postgre_operator.py
[2023-12-31T09:34:01.399-0300] {processor.py:183} INFO - Processing /home/felipe/airflow/dags/19_postgre_operator.py took 0.090 seconds
[2023-12-31T09:38:10.471-0300] {processor.py:161} INFO - Started process (PID=32147) to work on /home/felipe/airflow/dags/19_postgre_operator.py
[2023-12-31T09:38:10.479-0300] {processor.py:830} INFO - Processing file /home/felipe/airflow/dags/19_postgre_operator.py for tasks to queue
[2023-12-31T09:38:10.480-0300] {logging_mixin.py:188} INFO - [2023-12-31T09:38:10.480-0300] {dagbag.py:538} INFO - Filling up the DagBag from /home/felipe/airflow/dags/19_postgre_operator.py
[2023-12-31T09:38:10.506-0300] {logging_mixin.py:188} INFO - [2023-12-31T09:38:10.499-0300] {dagbag.py:348} ERROR - Failed to import: /home/felipe/airflow/dags/19_postgre_operator.py
Traceback (most recent call last):
  File "/home/felipe/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/felipe/airflow/dags/19_postgre_operator.py", line 14, in <module>
    extract_gz = BashOperator(
  File "/home/felipe/.local/lib/python3.10/site-packages/airflow/models/baseoperator.py", line 437, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/home/felipe/.local/lib/python3.10/site-packages/airflow/operators/bash.py", line 152, in __init__
    super().__init__(**kwargs)
  File "/home/felipe/.local/lib/python3.10/site-packages/airflow/models/baseoperator.py", line 437, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/home/felipe/.local/lib/python3.10/site-packages/airflow/models/baseoperator.py", line 798, in __init__
    raise AirflowException(
airflow.exceptions.AirflowException: Invalid arguments were passed to BashOperator (task_id: extract_gz). Invalid arguments were:
**kwargs: {'template_searchpath': '/tmp'}
[2023-12-31T09:38:10.508-0300] {processor.py:842} WARNING - No viable dags retrieved from /home/felipe/airflow/dags/19_postgre_operator.py
[2023-12-31T09:38:10.668-0300] {processor.py:183} INFO - Processing /home/felipe/airflow/dags/19_postgre_operator.py took 0.207 seconds
[2023-12-31T09:39:43.068-0300] {processor.py:161} INFO - Started process (PID=32240) to work on /home/felipe/airflow/dags/19_postgre_operator.py
[2023-12-31T09:39:43.070-0300] {processor.py:830} INFO - Processing file /home/felipe/airflow/dags/19_postgre_operator.py for tasks to queue
[2023-12-31T09:39:43.078-0300] {logging_mixin.py:188} INFO - [2023-12-31T09:39:43.077-0300] {dagbag.py:538} INFO - Filling up the DagBag from /home/felipe/airflow/dags/19_postgre_operator.py
[2023-12-31T09:39:43.100-0300] {logging_mixin.py:188} INFO - [2023-12-31T09:39:43.097-0300] {dagbag.py:348} ERROR - Failed to import: /home/felipe/airflow/dags/19_postgre_operator.py
Traceback (most recent call last):
  File "/home/felipe/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/felipe/airflow/dags/19_postgre_operator.py", line 14, in <module>
    extract_gz = BashOperator(
  File "/home/felipe/.local/lib/python3.10/site-packages/airflow/models/baseoperator.py", line 437, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/home/felipe/.local/lib/python3.10/site-packages/airflow/operators/bash.py", line 152, in __init__
    super().__init__(**kwargs)
  File "/home/felipe/.local/lib/python3.10/site-packages/airflow/models/baseoperator.py", line 437, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/home/felipe/.local/lib/python3.10/site-packages/airflow/models/baseoperator.py", line 798, in __init__
    raise AirflowException(
airflow.exceptions.AirflowException: Invalid arguments were passed to BashOperator (task_id: extract_gz). Invalid arguments were:
**kwargs: {'template_searchpath': '/tmp'}
[2023-12-31T09:39:43.101-0300] {processor.py:842} WARNING - No viable dags retrieved from /home/felipe/airflow/dags/19_postgre_operator.py
[2023-12-31T09:39:43.238-0300] {processor.py:183} INFO - Processing /home/felipe/airflow/dags/19_postgre_operator.py took 0.180 seconds
[2023-12-31T09:51:05.667-0300] {processor.py:161} INFO - Started process (PID=32689) to work on /home/felipe/airflow/dags/19_postgre_operator.py
[2023-12-31T09:51:05.697-0300] {processor.py:830} INFO - Processing file /home/felipe/airflow/dags/19_postgre_operator.py for tasks to queue
[2023-12-31T09:51:05.709-0300] {logging_mixin.py:188} INFO - [2023-12-31T09:51:05.699-0300] {dagbag.py:538} INFO - Filling up the DagBag from /home/felipe/airflow/dags/19_postgre_operator.py
[2023-12-31T09:51:05.819-0300] {logging_mixin.py:188} INFO - [2023-12-31T09:51:05.789-0300] {dagbag.py:348} ERROR - Failed to import: /home/felipe/airflow/dags/19_postgre_operator.py
Traceback (most recent call last):
  File "/home/felipe/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/felipe/airflow/dags/19_postgre_operator.py", line 14, in <module>
    extract_gz = BashOperator(
  File "/home/felipe/.local/lib/python3.10/site-packages/airflow/models/baseoperator.py", line 437, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/home/felipe/.local/lib/python3.10/site-packages/airflow/operators/bash.py", line 152, in __init__
    super().__init__(**kwargs)
  File "/home/felipe/.local/lib/python3.10/site-packages/airflow/models/baseoperator.py", line 437, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/home/felipe/.local/lib/python3.10/site-packages/airflow/models/baseoperator.py", line 798, in __init__
    raise AirflowException(
airflow.exceptions.AirflowException: Invalid arguments were passed to BashOperator (task_id: extract_gz). Invalid arguments were:
**kwargs: {'template_searchpath': '/tmp'}
[2023-12-31T09:51:05.827-0300] {processor.py:842} WARNING - No viable dags retrieved from /home/felipe/airflow/dags/19_postgre_operator.py
[2023-12-31T09:51:06.157-0300] {processor.py:183} INFO - Processing /home/felipe/airflow/dags/19_postgre_operator.py took 0.520 seconds
[2023-12-31T09:54:58.488-0300] {processor.py:161} INFO - Started process (PID=32907) to work on /home/felipe/airflow/dags/19_postgre_operator.py
[2023-12-31T09:54:58.496-0300] {processor.py:830} INFO - Processing file /home/felipe/airflow/dags/19_postgre_operator.py for tasks to queue
[2023-12-31T09:54:58.498-0300] {logging_mixin.py:188} INFO - [2023-12-31T09:54:58.498-0300] {dagbag.py:538} INFO - Filling up the DagBag from /home/felipe/airflow/dags/19_postgre_operator.py
[2023-12-31T09:54:58.537-0300] {logging_mixin.py:188} INFO - [2023-12-31T09:54:58.528-0300] {dagbag.py:348} ERROR - Failed to import: /home/felipe/airflow/dags/19_postgre_operator.py
Traceback (most recent call last):
  File "/home/felipe/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/felipe/airflow/dags/19_postgre_operator.py", line 14, in <module>
    extract_gz = BashOperator(
  File "/home/felipe/.local/lib/python3.10/site-packages/airflow/models/baseoperator.py", line 437, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/home/felipe/.local/lib/python3.10/site-packages/airflow/operators/bash.py", line 152, in __init__
    super().__init__(**kwargs)
  File "/home/felipe/.local/lib/python3.10/site-packages/airflow/models/baseoperator.py", line 437, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/home/felipe/.local/lib/python3.10/site-packages/airflow/models/baseoperator.py", line 798, in __init__
    raise AirflowException(
airflow.exceptions.AirflowException: Invalid arguments were passed to BashOperator (task_id: extract_gz). Invalid arguments were:
**kwargs: {'template_searchpath': '/tmp'}
[2023-12-31T09:54:58.539-0300] {processor.py:842} WARNING - No viable dags retrieved from /home/felipe/airflow/dags/19_postgre_operator.py
[2023-12-31T09:54:58.657-0300] {processor.py:183} INFO - Processing /home/felipe/airflow/dags/19_postgre_operator.py took 0.179 seconds
[2023-12-31T09:59:38.957-0300] {processor.py:161} INFO - Started process (PID=33120) to work on /home/felipe/airflow/dags/19_postgre_operator.py
[2023-12-31T09:59:38.959-0300] {processor.py:830} INFO - Processing file /home/felipe/airflow/dags/19_postgre_operator.py for tasks to queue
[2023-12-31T09:59:38.967-0300] {logging_mixin.py:188} INFO - [2023-12-31T09:59:38.960-0300] {dagbag.py:538} INFO - Filling up the DagBag from /home/felipe/airflow/dags/19_postgre_operator.py
[2023-12-31T09:59:38.998-0300] {logging_mixin.py:188} INFO - [2023-12-31T09:59:38.989-0300] {dagbag.py:348} ERROR - Failed to import: /home/felipe/airflow/dags/19_postgre_operator.py
Traceback (most recent call last):
  File "/home/felipe/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/felipe/airflow/dags/19_postgre_operator.py", line 14, in <module>
    extract_gz = BashOperator(
  File "/home/felipe/.local/lib/python3.10/site-packages/airflow/models/baseoperator.py", line 437, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/home/felipe/.local/lib/python3.10/site-packages/airflow/operators/bash.py", line 152, in __init__
    super().__init__(**kwargs)
  File "/home/felipe/.local/lib/python3.10/site-packages/airflow/models/baseoperator.py", line 437, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/home/felipe/.local/lib/python3.10/site-packages/airflow/models/baseoperator.py", line 798, in __init__
    raise AirflowException(
airflow.exceptions.AirflowException: Invalid arguments were passed to BashOperator (task_id: extract_gz). Invalid arguments were:
**kwargs: {'template_searchpath': '/tmp'}
[2023-12-31T09:59:38.999-0300] {processor.py:842} WARNING - No viable dags retrieved from /home/felipe/airflow/dags/19_postgre_operator.py
[2023-12-31T09:59:39.109-0300] {processor.py:183} INFO - Processing /home/felipe/airflow/dags/19_postgre_operator.py took 0.170 seconds
[2023-12-31T10:01:05.038-0300] {processor.py:161} INFO - Started process (PID=33227) to work on /home/felipe/airflow/dags/19_postgre_operator.py
[2023-12-31T10:01:05.046-0300] {processor.py:830} INFO - Processing file /home/felipe/airflow/dags/19_postgre_operator.py for tasks to queue
[2023-12-31T10:01:05.048-0300] {logging_mixin.py:188} INFO - [2023-12-31T10:01:05.047-0300] {dagbag.py:538} INFO - Filling up the DagBag from /home/felipe/airflow/dags/19_postgre_operator.py
[2023-12-31T10:01:05.079-0300] {logging_mixin.py:188} INFO - [2023-12-31T10:01:05.077-0300] {dagbag.py:348} ERROR - Failed to import: /home/felipe/airflow/dags/19_postgre_operator.py
Traceback (most recent call last):
  File "/home/felipe/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/felipe/airflow/dags/19_postgre_operator.py", line 14, in <module>
    extract_gz = BashOperator(
  File "/home/felipe/.local/lib/python3.10/site-packages/airflow/models/baseoperator.py", line 437, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/home/felipe/.local/lib/python3.10/site-packages/airflow/operators/bash.py", line 152, in __init__
    super().__init__(**kwargs)
  File "/home/felipe/.local/lib/python3.10/site-packages/airflow/models/baseoperator.py", line 437, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/home/felipe/.local/lib/python3.10/site-packages/airflow/models/baseoperator.py", line 798, in __init__
    raise AirflowException(
airflow.exceptions.AirflowException: Invalid arguments were passed to BashOperator (task_id: extract_gz). Invalid arguments were:
**kwargs: {'template_searchpath': '/tmp'}
[2023-12-31T10:01:05.086-0300] {processor.py:842} WARNING - No viable dags retrieved from /home/felipe/airflow/dags/19_postgre_operator.py
[2023-12-31T10:01:05.177-0300] {processor.py:183} INFO - Processing /home/felipe/airflow/dags/19_postgre_operator.py took 0.150 seconds
[2023-12-31T10:02:14.239-0300] {processor.py:161} INFO - Started process (PID=33327) to work on /home/felipe/airflow/dags/19_postgre_operator.py
[2023-12-31T10:02:14.247-0300] {processor.py:830} INFO - Processing file /home/felipe/airflow/dags/19_postgre_operator.py for tasks to queue
[2023-12-31T10:02:14.248-0300] {logging_mixin.py:188} INFO - [2023-12-31T10:02:14.248-0300] {dagbag.py:538} INFO - Filling up the DagBag from /home/felipe/airflow/dags/19_postgre_operator.py
[2023-12-31T10:02:14.279-0300] {logging_mixin.py:188} INFO - [2023-12-31T10:02:14.277-0300] {dagbag.py:348} ERROR - Failed to import: /home/felipe/airflow/dags/19_postgre_operator.py
Traceback (most recent call last):
  File "/home/felipe/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/felipe/airflow/dags/19_postgre_operator.py", line 14, in <module>
    extract_gz = BashOperator(
  File "/home/felipe/.local/lib/python3.10/site-packages/airflow/models/baseoperator.py", line 437, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/home/felipe/.local/lib/python3.10/site-packages/airflow/operators/bash.py", line 152, in __init__
    super().__init__(**kwargs)
  File "/home/felipe/.local/lib/python3.10/site-packages/airflow/models/baseoperator.py", line 437, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/home/felipe/.local/lib/python3.10/site-packages/airflow/models/baseoperator.py", line 798, in __init__
    raise AirflowException(
airflow.exceptions.AirflowException: Invalid arguments were passed to BashOperator (task_id: extract_gz). Invalid arguments were:
**kwargs: {'template_searchpath': '/tmp'}
[2023-12-31T10:02:14.280-0300] {processor.py:842} WARNING - No viable dags retrieved from /home/felipe/airflow/dags/19_postgre_operator.py
[2023-12-31T10:02:14.387-0300] {processor.py:183} INFO - Processing /home/felipe/airflow/dags/19_postgre_operator.py took 0.159 seconds
[2023-12-31T10:03:20.138-0300] {processor.py:161} INFO - Started process (PID=33391) to work on /home/felipe/airflow/dags/19_postgre_operator.py
[2023-12-31T10:03:20.147-0300] {processor.py:830} INFO - Processing file /home/felipe/airflow/dags/19_postgre_operator.py for tasks to queue
[2023-12-31T10:03:20.148-0300] {logging_mixin.py:188} INFO - [2023-12-31T10:03:20.147-0300] {dagbag.py:538} INFO - Filling up the DagBag from /home/felipe/airflow/dags/19_postgre_operator.py
[2023-12-31T10:03:20.179-0300] {logging_mixin.py:188} INFO - [2023-12-31T10:03:20.177-0300] {dagbag.py:348} ERROR - Failed to import: /home/felipe/airflow/dags/19_postgre_operator.py
Traceback (most recent call last):
  File "/home/felipe/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/felipe/airflow/dags/19_postgre_operator.py", line 14, in <module>
    extract_gz = BashOperator(
  File "/home/felipe/.local/lib/python3.10/site-packages/airflow/models/baseoperator.py", line 437, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/home/felipe/.local/lib/python3.10/site-packages/airflow/operators/bash.py", line 152, in __init__
    super().__init__(**kwargs)
  File "/home/felipe/.local/lib/python3.10/site-packages/airflow/models/baseoperator.py", line 437, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/home/felipe/.local/lib/python3.10/site-packages/airflow/models/baseoperator.py", line 798, in __init__
    raise AirflowException(
airflow.exceptions.AirflowException: Invalid arguments were passed to BashOperator (task_id: extract_gz). Invalid arguments were:
**kwargs: {'template_searchpath': '/tmp'}
[2023-12-31T10:03:20.186-0300] {processor.py:842} WARNING - No viable dags retrieved from /home/felipe/airflow/dags/19_postgre_operator.py
[2023-12-31T10:03:20.279-0300] {processor.py:183} INFO - Processing /home/felipe/airflow/dags/19_postgre_operator.py took 0.151 seconds
[2023-12-31T10:04:30.078-0300] {processor.py:161} INFO - Started process (PID=33473) to work on /home/felipe/airflow/dags/19_postgre_operator.py
[2023-12-31T10:04:30.086-0300] {processor.py:830} INFO - Processing file /home/felipe/airflow/dags/19_postgre_operator.py for tasks to queue
[2023-12-31T10:04:30.088-0300] {logging_mixin.py:188} INFO - [2023-12-31T10:04:30.087-0300] {dagbag.py:538} INFO - Filling up the DagBag from /home/felipe/airflow/dags/19_postgre_operator.py
[2023-12-31T10:04:30.119-0300] {logging_mixin.py:188} INFO - [2023-12-31T10:04:30.117-0300] {dagbag.py:348} ERROR - Failed to import: /home/felipe/airflow/dags/19_postgre_operator.py
Traceback (most recent call last):
  File "/home/felipe/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/felipe/airflow/dags/19_postgre_operator.py", line 14, in <module>
    extract_gz = BashOperator(
  File "/home/felipe/.local/lib/python3.10/site-packages/airflow/models/baseoperator.py", line 437, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/home/felipe/.local/lib/python3.10/site-packages/airflow/operators/bash.py", line 152, in __init__
    super().__init__(**kwargs)
  File "/home/felipe/.local/lib/python3.10/site-packages/airflow/models/baseoperator.py", line 437, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/home/felipe/.local/lib/python3.10/site-packages/airflow/models/baseoperator.py", line 798, in __init__
    raise AirflowException(
airflow.exceptions.AirflowException: Invalid arguments were passed to BashOperator (task_id: extract_gz). Invalid arguments were:
**kwargs: {'template_searchpath': '/tmp'}
[2023-12-31T10:04:30.126-0300] {processor.py:842} WARNING - No viable dags retrieved from /home/felipe/airflow/dags/19_postgre_operator.py
[2023-12-31T10:04:30.218-0300] {processor.py:183} INFO - Processing /home/felipe/airflow/dags/19_postgre_operator.py took 0.159 seconds
[2023-12-31T10:05:41.077-0300] {processor.py:161} INFO - Started process (PID=33553) to work on /home/felipe/airflow/dags/19_postgre_operator.py
[2023-12-31T10:05:41.079-0300] {processor.py:830} INFO - Processing file /home/felipe/airflow/dags/19_postgre_operator.py for tasks to queue
[2023-12-31T10:05:41.087-0300] {logging_mixin.py:188} INFO - [2023-12-31T10:05:41.087-0300] {dagbag.py:538} INFO - Filling up the DagBag from /home/felipe/airflow/dags/19_postgre_operator.py
[2023-12-31T10:05:41.119-0300] {logging_mixin.py:188} INFO - [2023-12-31T10:05:41.117-0300] {dagbag.py:348} ERROR - Failed to import: /home/felipe/airflow/dags/19_postgre_operator.py
Traceback (most recent call last):
  File "/home/felipe/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/felipe/airflow/dags/19_postgre_operator.py", line 14, in <module>
    extract_gz = BashOperator(
  File "/home/felipe/.local/lib/python3.10/site-packages/airflow/models/baseoperator.py", line 437, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/home/felipe/.local/lib/python3.10/site-packages/airflow/operators/bash.py", line 152, in __init__
    super().__init__(**kwargs)
  File "/home/felipe/.local/lib/python3.10/site-packages/airflow/models/baseoperator.py", line 437, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/home/felipe/.local/lib/python3.10/site-packages/airflow/models/baseoperator.py", line 798, in __init__
    raise AirflowException(
airflow.exceptions.AirflowException: Invalid arguments were passed to BashOperator (task_id: extract_gz). Invalid arguments were:
**kwargs: {'template_searchpath': '/tmp'}
[2023-12-31T10:05:41.119-0300] {processor.py:842} WARNING - No viable dags retrieved from /home/felipe/airflow/dags/19_postgre_operator.py
[2023-12-31T10:05:41.228-0300] {processor.py:183} INFO - Processing /home/felipe/airflow/dags/19_postgre_operator.py took 0.168 seconds
[2023-12-31T10:06:51.619-0300] {processor.py:161} INFO - Started process (PID=33668) to work on /home/felipe/airflow/dags/19_postgre_operator.py
[2023-12-31T10:06:51.627-0300] {processor.py:830} INFO - Processing file /home/felipe/airflow/dags/19_postgre_operator.py for tasks to queue
[2023-12-31T10:06:51.629-0300] {logging_mixin.py:188} INFO - [2023-12-31T10:06:51.628-0300] {dagbag.py:538} INFO - Filling up the DagBag from /home/felipe/airflow/dags/19_postgre_operator.py
[2023-12-31T10:06:51.667-0300] {logging_mixin.py:188} INFO - [2023-12-31T10:06:51.659-0300] {dagbag.py:348} ERROR - Failed to import: /home/felipe/airflow/dags/19_postgre_operator.py
Traceback (most recent call last):
  File "/home/felipe/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/felipe/airflow/dags/19_postgre_operator.py", line 14, in <module>
    extract_gz = BashOperator(
  File "/home/felipe/.local/lib/python3.10/site-packages/airflow/models/baseoperator.py", line 437, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/home/felipe/.local/lib/python3.10/site-packages/airflow/operators/bash.py", line 152, in __init__
    super().__init__(**kwargs)
  File "/home/felipe/.local/lib/python3.10/site-packages/airflow/models/baseoperator.py", line 437, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/home/felipe/.local/lib/python3.10/site-packages/airflow/models/baseoperator.py", line 798, in __init__
    raise AirflowException(
airflow.exceptions.AirflowException: Invalid arguments were passed to BashOperator (task_id: extract_gz). Invalid arguments were:
**kwargs: {'template_searchpath': '/tmp'}
[2023-12-31T10:06:51.668-0300] {processor.py:842} WARNING - No viable dags retrieved from /home/felipe/airflow/dags/19_postgre_operator.py
[2023-12-31T10:06:51.778-0300] {processor.py:183} INFO - Processing /home/felipe/airflow/dags/19_postgre_operator.py took 0.170 seconds
[2023-12-31T10:08:04.627-0300] {processor.py:161} INFO - Started process (PID=33746) to work on /home/felipe/airflow/dags/19_postgre_operator.py
[2023-12-31T10:08:04.629-0300] {processor.py:830} INFO - Processing file /home/felipe/airflow/dags/19_postgre_operator.py for tasks to queue
[2023-12-31T10:08:04.638-0300] {logging_mixin.py:188} INFO - [2023-12-31T10:08:04.637-0300] {dagbag.py:538} INFO - Filling up the DagBag from /home/felipe/airflow/dags/19_postgre_operator.py
[2023-12-31T10:08:04.677-0300] {logging_mixin.py:188} INFO - [2023-12-31T10:08:04.668-0300] {dagbag.py:348} ERROR - Failed to import: /home/felipe/airflow/dags/19_postgre_operator.py
Traceback (most recent call last):
  File "/home/felipe/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/felipe/airflow/dags/19_postgre_operator.py", line 14, in <module>
    extract_gz = BashOperator(
  File "/home/felipe/.local/lib/python3.10/site-packages/airflow/models/baseoperator.py", line 437, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/home/felipe/.local/lib/python3.10/site-packages/airflow/operators/bash.py", line 152, in __init__
    super().__init__(**kwargs)
  File "/home/felipe/.local/lib/python3.10/site-packages/airflow/models/baseoperator.py", line 437, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/home/felipe/.local/lib/python3.10/site-packages/airflow/models/baseoperator.py", line 798, in __init__
    raise AirflowException(
airflow.exceptions.AirflowException: Invalid arguments were passed to BashOperator (task_id: extract_gz). Invalid arguments were:
**kwargs: {'template_searchpath': '/tmp'}
[2023-12-31T10:08:04.677-0300] {processor.py:842} WARNING - No viable dags retrieved from /home/felipe/airflow/dags/19_postgre_operator.py
[2023-12-31T10:08:04.778-0300] {processor.py:183} INFO - Processing /home/felipe/airflow/dags/19_postgre_operator.py took 0.162 seconds
[2023-12-31T11:28:24.997-0300] {processor.py:161} INFO - Started process (PID=33926) to work on /home/felipe/airflow/dags/19_postgre_operator.py
[2023-12-31T11:28:25.075-0300] {processor.py:830} INFO - Processing file /home/felipe/airflow/dags/19_postgre_operator.py for tasks to queue
[2023-12-31T11:28:25.106-0300] {logging_mixin.py:188} INFO - [2023-12-31T11:28:25.077-0300] {dagbag.py:538} INFO - Filling up the DagBag from /home/felipe/airflow/dags/19_postgre_operator.py
[2023-12-31T11:28:25.396-0300] {logging_mixin.py:188} INFO - [2023-12-31T11:28:25.375-0300] {dagbag.py:348} ERROR - Failed to import: /home/felipe/airflow/dags/19_postgre_operator.py
Traceback (most recent call last):
  File "/home/felipe/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/felipe/airflow/dags/19_postgre_operator.py", line 14, in <module>
    extract_gz = BashOperator(
  File "/home/felipe/.local/lib/python3.10/site-packages/airflow/models/baseoperator.py", line 437, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/home/felipe/.local/lib/python3.10/site-packages/airflow/operators/bash.py", line 152, in __init__
    super().__init__(**kwargs)
  File "/home/felipe/.local/lib/python3.10/site-packages/airflow/models/baseoperator.py", line 437, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/home/felipe/.local/lib/python3.10/site-packages/airflow/models/baseoperator.py", line 798, in __init__
    raise AirflowException(
airflow.exceptions.AirflowException: Invalid arguments were passed to BashOperator (task_id: extract_gz). Invalid arguments were:
**kwargs: {'template_searchpath': '/tmp'}
[2023-12-31T11:28:25.414-0300] {processor.py:842} WARNING - No viable dags retrieved from /home/felipe/airflow/dags/19_postgre_operator.py
[2023-12-31T11:28:25.986-0300] {processor.py:183} INFO - Processing /home/felipe/airflow/dags/19_postgre_operator.py took 1.051 seconds
[2023-12-31T11:30:28.186-0300] {processor.py:161} INFO - Started process (PID=34196) to work on /home/felipe/airflow/dags/19_postgre_operator.py
[2023-12-31T11:30:28.204-0300] {processor.py:830} INFO - Processing file /home/felipe/airflow/dags/19_postgre_operator.py for tasks to queue
[2023-12-31T11:30:28.206-0300] {logging_mixin.py:188} INFO - [2023-12-31T11:30:28.205-0300] {dagbag.py:538} INFO - Filling up the DagBag from /home/felipe/airflow/dags/19_postgre_operator.py
[2023-12-31T11:30:28.247-0300] {logging_mixin.py:188} INFO - [2023-12-31T11:30:28.245-0300] {dagbag.py:348} ERROR - Failed to import: /home/felipe/airflow/dags/19_postgre_operator.py
Traceback (most recent call last):
  File "/home/felipe/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/felipe/airflow/dags/19_postgre_operator.py", line 14, in <module>
    extract_gz = BashOperator(
  File "/home/felipe/.local/lib/python3.10/site-packages/airflow/models/baseoperator.py", line 437, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/home/felipe/.local/lib/python3.10/site-packages/airflow/operators/bash.py", line 152, in __init__
    super().__init__(**kwargs)
  File "/home/felipe/.local/lib/python3.10/site-packages/airflow/models/baseoperator.py", line 437, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/home/felipe/.local/lib/python3.10/site-packages/airflow/models/baseoperator.py", line 798, in __init__
    raise AirflowException(
airflow.exceptions.AirflowException: Invalid arguments were passed to BashOperator (task_id: extract_gz). Invalid arguments were:
**kwargs: {'template_searchpath': '/tmp'}
[2023-12-31T11:30:28.254-0300] {processor.py:842} WARNING - No viable dags retrieved from /home/felipe/airflow/dags/19_postgre_operator.py
[2023-12-31T11:30:28.376-0300] {processor.py:183} INFO - Processing /home/felipe/airflow/dags/19_postgre_operator.py took 0.202 seconds
[2023-12-31T11:31:59.795-0300] {processor.py:161} INFO - Started process (PID=34316) to work on /home/felipe/airflow/dags/19_postgre_operator.py
[2023-12-31T11:31:59.804-0300] {processor.py:830} INFO - Processing file /home/felipe/airflow/dags/19_postgre_operator.py for tasks to queue
[2023-12-31T11:31:59.806-0300] {logging_mixin.py:188} INFO - [2023-12-31T11:31:59.805-0300] {dagbag.py:538} INFO - Filling up the DagBag from /home/felipe/airflow/dags/19_postgre_operator.py
[2023-12-31T11:31:59.845-0300] {logging_mixin.py:188} INFO - [2023-12-31T11:31:59.837-0300] {dagbag.py:348} ERROR - Failed to import: /home/felipe/airflow/dags/19_postgre_operator.py
Traceback (most recent call last):
  File "/home/felipe/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/felipe/airflow/dags/19_postgre_operator.py", line 14, in <module>
    extract_gz = BashOperator(
  File "/home/felipe/.local/lib/python3.10/site-packages/airflow/models/baseoperator.py", line 437, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/home/felipe/.local/lib/python3.10/site-packages/airflow/operators/bash.py", line 152, in __init__
    super().__init__(**kwargs)
  File "/home/felipe/.local/lib/python3.10/site-packages/airflow/models/baseoperator.py", line 437, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/home/felipe/.local/lib/python3.10/site-packages/airflow/models/baseoperator.py", line 798, in __init__
    raise AirflowException(
airflow.exceptions.AirflowException: Invalid arguments were passed to BashOperator (task_id: extract_gz). Invalid arguments were:
**kwargs: {'template_searchpath': '/tmp'}
[2023-12-31T11:31:59.846-0300] {processor.py:842} WARNING - No viable dags retrieved from /home/felipe/airflow/dags/19_postgre_operator.py
[2023-12-31T11:31:59.965-0300] {processor.py:183} INFO - Processing /home/felipe/airflow/dags/19_postgre_operator.py took 0.189 seconds
[2023-12-31T11:33:27.986-0300] {processor.py:161} INFO - Started process (PID=34414) to work on /home/felipe/airflow/dags/19_postgre_operator.py
[2023-12-31T11:33:27.996-0300] {processor.py:830} INFO - Processing file /home/felipe/airflow/dags/19_postgre_operator.py for tasks to queue
[2023-12-31T11:33:28.005-0300] {logging_mixin.py:188} INFO - [2023-12-31T11:33:28.004-0300] {dagbag.py:538} INFO - Filling up the DagBag from /home/felipe/airflow/dags/19_postgre_operator.py
[2023-12-31T11:33:28.054-0300] {logging_mixin.py:188} INFO - [2023-12-31T11:33:28.037-0300] {dagbag.py:348} ERROR - Failed to import: /home/felipe/airflow/dags/19_postgre_operator.py
Traceback (most recent call last):
  File "/home/felipe/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/felipe/airflow/dags/19_postgre_operator.py", line 14, in <module>
    extract_gz = BashOperator(
  File "/home/felipe/.local/lib/python3.10/site-packages/airflow/models/baseoperator.py", line 437, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/home/felipe/.local/lib/python3.10/site-packages/airflow/operators/bash.py", line 152, in __init__
    super().__init__(**kwargs)
  File "/home/felipe/.local/lib/python3.10/site-packages/airflow/models/baseoperator.py", line 437, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/home/felipe/.local/lib/python3.10/site-packages/airflow/models/baseoperator.py", line 798, in __init__
    raise AirflowException(
airflow.exceptions.AirflowException: Invalid arguments were passed to BashOperator (task_id: extract_gz). Invalid arguments were:
**kwargs: {'template_searchpath': '/tmp'}
[2023-12-31T11:33:28.055-0300] {processor.py:842} WARNING - No viable dags retrieved from /home/felipe/airflow/dags/19_postgre_operator.py
[2023-12-31T11:33:28.225-0300] {processor.py:183} INFO - Processing /home/felipe/airflow/dags/19_postgre_operator.py took 0.260 seconds
[2023-12-31T11:34:53.825-0300] {processor.py:161} INFO - Started process (PID=34507) to work on /home/felipe/airflow/dags/19_postgre_operator.py
[2023-12-31T11:34:53.834-0300] {processor.py:830} INFO - Processing file /home/felipe/airflow/dags/19_postgre_operator.py for tasks to queue
[2023-12-31T11:34:53.836-0300] {logging_mixin.py:188} INFO - [2023-12-31T11:34:53.835-0300] {dagbag.py:538} INFO - Filling up the DagBag from /home/felipe/airflow/dags/19_postgre_operator.py
[2023-12-31T11:34:53.875-0300] {logging_mixin.py:188} INFO - [2023-12-31T11:34:53.866-0300] {dagbag.py:348} ERROR - Failed to import: /home/felipe/airflow/dags/19_postgre_operator.py
Traceback (most recent call last):
  File "/home/felipe/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/felipe/airflow/dags/19_postgre_operator.py", line 14, in <module>
    extract_gz = BashOperator(
  File "/home/felipe/.local/lib/python3.10/site-packages/airflow/models/baseoperator.py", line 437, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/home/felipe/.local/lib/python3.10/site-packages/airflow/operators/bash.py", line 152, in __init__
    super().__init__(**kwargs)
  File "/home/felipe/.local/lib/python3.10/site-packages/airflow/models/baseoperator.py", line 437, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/home/felipe/.local/lib/python3.10/site-packages/airflow/models/baseoperator.py", line 798, in __init__
    raise AirflowException(
airflow.exceptions.AirflowException: Invalid arguments were passed to BashOperator (task_id: extract_gz). Invalid arguments were:
**kwargs: {'template_searchpath': '/tmp'}
[2023-12-31T11:34:53.876-0300] {processor.py:842} WARNING - No viable dags retrieved from /home/felipe/airflow/dags/19_postgre_operator.py
[2023-12-31T11:34:53.986-0300] {processor.py:183} INFO - Processing /home/felipe/airflow/dags/19_postgre_operator.py took 0.172 seconds
[2023-12-31T11:36:16.586-0300] {processor.py:161} INFO - Started process (PID=34629) to work on /home/felipe/airflow/dags/19_postgre_operator.py
[2023-12-31T11:36:16.596-0300] {processor.py:830} INFO - Processing file /home/felipe/airflow/dags/19_postgre_operator.py for tasks to queue
[2023-12-31T11:36:16.605-0300] {logging_mixin.py:188} INFO - [2023-12-31T11:36:16.604-0300] {dagbag.py:538} INFO - Filling up the DagBag from /home/felipe/airflow/dags/19_postgre_operator.py
[2023-12-31T11:36:16.655-0300] {logging_mixin.py:188} INFO - [2023-12-31T11:36:16.645-0300] {dagbag.py:348} ERROR - Failed to import: /home/felipe/airflow/dags/19_postgre_operator.py
Traceback (most recent call last):
  File "/home/felipe/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/felipe/airflow/dags/19_postgre_operator.py", line 14, in <module>
    extract_gz = BashOperator(
  File "/home/felipe/.local/lib/python3.10/site-packages/airflow/models/baseoperator.py", line 437, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/home/felipe/.local/lib/python3.10/site-packages/airflow/operators/bash.py", line 152, in __init__
    super().__init__(**kwargs)
  File "/home/felipe/.local/lib/python3.10/site-packages/airflow/models/baseoperator.py", line 437, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/home/felipe/.local/lib/python3.10/site-packages/airflow/models/baseoperator.py", line 798, in __init__
    raise AirflowException(
airflow.exceptions.AirflowException: Invalid arguments were passed to BashOperator (task_id: extract_gz). Invalid arguments were:
**kwargs: {'template_searchpath': '/tmp'}
[2023-12-31T11:36:16.656-0300] {processor.py:842} WARNING - No viable dags retrieved from /home/felipe/airflow/dags/19_postgre_operator.py
[2023-12-31T11:36:16.785-0300] {processor.py:183} INFO - Processing /home/felipe/airflow/dags/19_postgre_operator.py took 0.210 seconds
[2023-12-31T11:37:39.255-0300] {processor.py:161} INFO - Started process (PID=34718) to work on /home/felipe/airflow/dags/19_postgre_operator.py
[2023-12-31T11:37:39.265-0300] {processor.py:830} INFO - Processing file /home/felipe/airflow/dags/19_postgre_operator.py for tasks to queue
[2023-12-31T11:37:39.266-0300] {logging_mixin.py:188} INFO - [2023-12-31T11:37:39.265-0300] {dagbag.py:538} INFO - Filling up the DagBag from /home/felipe/airflow/dags/19_postgre_operator.py
[2023-12-31T11:37:39.315-0300] {logging_mixin.py:188} INFO - [2023-12-31T11:37:39.306-0300] {dagbag.py:348} ERROR - Failed to import: /home/felipe/airflow/dags/19_postgre_operator.py
Traceback (most recent call last):
  File "/home/felipe/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/felipe/airflow/dags/19_postgre_operator.py", line 14, in <module>
    extract_gz = BashOperator(
  File "/home/felipe/.local/lib/python3.10/site-packages/airflow/models/baseoperator.py", line 437, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/home/felipe/.local/lib/python3.10/site-packages/airflow/operators/bash.py", line 152, in __init__
    super().__init__(**kwargs)
  File "/home/felipe/.local/lib/python3.10/site-packages/airflow/models/baseoperator.py", line 437, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/home/felipe/.local/lib/python3.10/site-packages/airflow/models/baseoperator.py", line 798, in __init__
    raise AirflowException(
airflow.exceptions.AirflowException: Invalid arguments were passed to BashOperator (task_id: extract_gz). Invalid arguments were:
**kwargs: {'template_searchpath': '/tmp'}
[2023-12-31T11:37:39.316-0300] {processor.py:842} WARNING - No viable dags retrieved from /home/felipe/airflow/dags/19_postgre_operator.py
[2023-12-31T11:37:39.435-0300] {processor.py:183} INFO - Processing /home/felipe/airflow/dags/19_postgre_operator.py took 0.199 seconds
[2023-12-31T11:39:01.565-0300] {processor.py:161} INFO - Started process (PID=34807) to work on /home/felipe/airflow/dags/19_postgre_operator.py
[2023-12-31T11:39:01.574-0300] {processor.py:830} INFO - Processing file /home/felipe/airflow/dags/19_postgre_operator.py for tasks to queue
[2023-12-31T11:39:01.576-0300] {logging_mixin.py:188} INFO - [2023-12-31T11:39:01.575-0300] {dagbag.py:538} INFO - Filling up the DagBag from /home/felipe/airflow/dags/19_postgre_operator.py
[2023-12-31T11:39:01.625-0300] {logging_mixin.py:188} INFO - [2023-12-31T11:39:01.615-0300] {dagbag.py:348} ERROR - Failed to import: /home/felipe/airflow/dags/19_postgre_operator.py
Traceback (most recent call last):
  File "/home/felipe/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/felipe/airflow/dags/19_postgre_operator.py", line 14, in <module>
    extract_gz = BashOperator(
  File "/home/felipe/.local/lib/python3.10/site-packages/airflow/models/baseoperator.py", line 437, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/home/felipe/.local/lib/python3.10/site-packages/airflow/operators/bash.py", line 152, in __init__
    super().__init__(**kwargs)
  File "/home/felipe/.local/lib/python3.10/site-packages/airflow/models/baseoperator.py", line 437, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/home/felipe/.local/lib/python3.10/site-packages/airflow/models/baseoperator.py", line 798, in __init__
    raise AirflowException(
airflow.exceptions.AirflowException: Invalid arguments were passed to BashOperator (task_id: extract_gz). Invalid arguments were:
**kwargs: {'template_searchpath': '/tmp'}
[2023-12-31T11:39:01.626-0300] {processor.py:842} WARNING - No viable dags retrieved from /home/felipe/airflow/dags/19_postgre_operator.py
[2023-12-31T11:39:01.765-0300] {processor.py:183} INFO - Processing /home/felipe/airflow/dags/19_postgre_operator.py took 0.211 seconds
[2023-12-31T11:40:25.274-0300] {processor.py:161} INFO - Started process (PID=34923) to work on /home/felipe/airflow/dags/19_postgre_operator.py
[2023-12-31T11:40:25.284-0300] {processor.py:830} INFO - Processing file /home/felipe/airflow/dags/19_postgre_operator.py for tasks to queue
[2023-12-31T11:40:25.286-0300] {logging_mixin.py:188} INFO - [2023-12-31T11:40:25.285-0300] {dagbag.py:538} INFO - Filling up the DagBag from /home/felipe/airflow/dags/19_postgre_operator.py
[2023-12-31T11:40:25.346-0300] {logging_mixin.py:188} INFO - [2023-12-31T11:40:25.335-0300] {dagbag.py:348} ERROR - Failed to import: /home/felipe/airflow/dags/19_postgre_operator.py
Traceback (most recent call last):
  File "/home/felipe/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/felipe/airflow/dags/19_postgre_operator.py", line 14, in <module>
    extract_gz = BashOperator(
  File "/home/felipe/.local/lib/python3.10/site-packages/airflow/models/baseoperator.py", line 437, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/home/felipe/.local/lib/python3.10/site-packages/airflow/operators/bash.py", line 152, in __init__
    super().__init__(**kwargs)
  File "/home/felipe/.local/lib/python3.10/site-packages/airflow/models/baseoperator.py", line 437, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/home/felipe/.local/lib/python3.10/site-packages/airflow/models/baseoperator.py", line 798, in __init__
    raise AirflowException(
airflow.exceptions.AirflowException: Invalid arguments were passed to BashOperator (task_id: extract_gz). Invalid arguments were:
**kwargs: {'template_searchpath': '/tmp'}
[2023-12-31T11:40:25.354-0300] {processor.py:842} WARNING - No viable dags retrieved from /home/felipe/airflow/dags/19_postgre_operator.py
[2023-12-31T11:40:25.545-0300] {processor.py:183} INFO - Processing /home/felipe/airflow/dags/19_postgre_operator.py took 0.290 seconds
[2023-12-31T11:41:56.406-0300] {processor.py:161} INFO - Started process (PID=35025) to work on /home/felipe/airflow/dags/19_postgre_operator.py
[2023-12-31T11:41:56.445-0300] {processor.py:830} INFO - Processing file /home/felipe/airflow/dags/19_postgre_operator.py for tasks to queue
[2023-12-31T11:41:56.464-0300] {logging_mixin.py:188} INFO - [2023-12-31T11:41:56.455-0300] {dagbag.py:538} INFO - Filling up the DagBag from /home/felipe/airflow/dags/19_postgre_operator.py
[2023-12-31T11:41:56.575-0300] {logging_mixin.py:188} INFO - [2023-12-31T11:41:56.556-0300] {dagbag.py:348} ERROR - Failed to import: /home/felipe/airflow/dags/19_postgre_operator.py
Traceback (most recent call last):
  File "/home/felipe/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/felipe/airflow/dags/19_postgre_operator.py", line 14, in <module>
    extract_gz = BashOperator(
  File "/home/felipe/.local/lib/python3.10/site-packages/airflow/models/baseoperator.py", line 437, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/home/felipe/.local/lib/python3.10/site-packages/airflow/operators/bash.py", line 152, in __init__
    super().__init__(**kwargs)
  File "/home/felipe/.local/lib/python3.10/site-packages/airflow/models/baseoperator.py", line 437, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/home/felipe/.local/lib/python3.10/site-packages/airflow/models/baseoperator.py", line 798, in __init__
    raise AirflowException(
airflow.exceptions.AirflowException: Invalid arguments were passed to BashOperator (task_id: extract_gz). Invalid arguments were:
**kwargs: {'template_searchpath': '/tmp'}
[2023-12-31T11:41:56.584-0300] {processor.py:842} WARNING - No viable dags retrieved from /home/felipe/airflow/dags/19_postgre_operator.py
[2023-12-31T11:41:56.996-0300] {processor.py:183} INFO - Processing /home/felipe/airflow/dags/19_postgre_operator.py took 0.640 seconds
[2023-12-31T11:43:31.296-0300] {processor.py:161} INFO - Started process (PID=35136) to work on /home/felipe/airflow/dags/19_postgre_operator.py
[2023-12-31T11:43:31.306-0300] {processor.py:830} INFO - Processing file /home/felipe/airflow/dags/19_postgre_operator.py for tasks to queue
[2023-12-31T11:43:31.316-0300] {logging_mixin.py:188} INFO - [2023-12-31T11:43:31.315-0300] {dagbag.py:538} INFO - Filling up the DagBag from /home/felipe/airflow/dags/19_postgre_operator.py
[2023-12-31T11:43:31.376-0300] {logging_mixin.py:188} INFO - [2023-12-31T11:43:31.365-0300] {dagbag.py:348} ERROR - Failed to import: /home/felipe/airflow/dags/19_postgre_operator.py
Traceback (most recent call last):
  File "/home/felipe/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/felipe/airflow/dags/19_postgre_operator.py", line 14, in <module>
    extract_gz = BashOperator(
  File "/home/felipe/.local/lib/python3.10/site-packages/airflow/models/baseoperator.py", line 437, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/home/felipe/.local/lib/python3.10/site-packages/airflow/operators/bash.py", line 152, in __init__
    super().__init__(**kwargs)
  File "/home/felipe/.local/lib/python3.10/site-packages/airflow/models/baseoperator.py", line 437, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/home/felipe/.local/lib/python3.10/site-packages/airflow/models/baseoperator.py", line 798, in __init__
    raise AirflowException(
airflow.exceptions.AirflowException: Invalid arguments were passed to BashOperator (task_id: extract_gz). Invalid arguments were:
**kwargs: {'template_searchpath': '/tmp'}
[2023-12-31T11:43:31.384-0300] {processor.py:842} WARNING - No viable dags retrieved from /home/felipe/airflow/dags/19_postgre_operator.py
[2023-12-31T11:43:31.554-0300] {processor.py:183} INFO - Processing /home/felipe/airflow/dags/19_postgre_operator.py took 0.272 seconds
[2023-12-31T11:45:13.286-0300] {processor.py:161} INFO - Started process (PID=35278) to work on /home/felipe/airflow/dags/19_postgre_operator.py
[2023-12-31T11:45:13.296-0300] {processor.py:830} INFO - Processing file /home/felipe/airflow/dags/19_postgre_operator.py for tasks to queue
[2023-12-31T11:45:13.305-0300] {logging_mixin.py:188} INFO - [2023-12-31T11:45:13.304-0300] {dagbag.py:538} INFO - Filling up the DagBag from /home/felipe/airflow/dags/19_postgre_operator.py
[2023-12-31T11:45:13.355-0300] {logging_mixin.py:188} INFO - [2023-12-31T11:45:13.346-0300] {dagbag.py:348} ERROR - Failed to import: /home/felipe/airflow/dags/19_postgre_operator.py
Traceback (most recent call last):
  File "/home/felipe/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/felipe/airflow/dags/19_postgre_operator.py", line 14, in <module>
    extract_gz = BashOperator(
  File "/home/felipe/.local/lib/python3.10/site-packages/airflow/models/baseoperator.py", line 437, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/home/felipe/.local/lib/python3.10/site-packages/airflow/operators/bash.py", line 152, in __init__
    super().__init__(**kwargs)
  File "/home/felipe/.local/lib/python3.10/site-packages/airflow/models/baseoperator.py", line 437, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/home/felipe/.local/lib/python3.10/site-packages/airflow/models/baseoperator.py", line 798, in __init__
    raise AirflowException(
airflow.exceptions.AirflowException: Invalid arguments were passed to BashOperator (task_id: extract_gz). Invalid arguments were:
**kwargs: {'template_searchpath': '/tmp'}
[2023-12-31T11:45:13.364-0300] {processor.py:842} WARNING - No viable dags retrieved from /home/felipe/airflow/dags/19_postgre_operator.py
[2023-12-31T11:45:13.545-0300] {processor.py:183} INFO - Processing /home/felipe/airflow/dags/19_postgre_operator.py took 0.280 seconds
[2023-12-31T11:46:50.496-0300] {processor.py:161} INFO - Started process (PID=35388) to work on /home/felipe/airflow/dags/19_postgre_operator.py
[2023-12-31T11:46:50.514-0300] {processor.py:830} INFO - Processing file /home/felipe/airflow/dags/19_postgre_operator.py for tasks to queue
[2023-12-31T11:46:50.524-0300] {logging_mixin.py:188} INFO - [2023-12-31T11:46:50.516-0300] {dagbag.py:538} INFO - Filling up the DagBag from /home/felipe/airflow/dags/19_postgre_operator.py
[2023-12-31T11:46:50.586-0300] {logging_mixin.py:188} INFO - [2023-12-31T11:46:50.575-0300] {dagbag.py:348} ERROR - Failed to import: /home/felipe/airflow/dags/19_postgre_operator.py
Traceback (most recent call last):
  File "/home/felipe/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/felipe/airflow/dags/19_postgre_operator.py", line 14, in <module>
    extract_gz = BashOperator(
  File "/home/felipe/.local/lib/python3.10/site-packages/airflow/models/baseoperator.py", line 437, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/home/felipe/.local/lib/python3.10/site-packages/airflow/operators/bash.py", line 152, in __init__
    super().__init__(**kwargs)
  File "/home/felipe/.local/lib/python3.10/site-packages/airflow/models/baseoperator.py", line 437, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/home/felipe/.local/lib/python3.10/site-packages/airflow/models/baseoperator.py", line 798, in __init__
    raise AirflowException(
airflow.exceptions.AirflowException: Invalid arguments were passed to BashOperator (task_id: extract_gz). Invalid arguments were:
**kwargs: {'template_searchpath': '/tmp'}
[2023-12-31T11:46:50.594-0300] {processor.py:842} WARNING - No viable dags retrieved from /home/felipe/airflow/dags/19_postgre_operator.py
[2023-12-31T11:46:50.755-0300] {processor.py:183} INFO - Processing /home/felipe/airflow/dags/19_postgre_operator.py took 0.280 seconds
[2023-12-31T11:48:58.366-0300] {processor.py:161} INFO - Started process (PID=35558) to work on /home/felipe/airflow/dags/19_postgre_operator.py
[2023-12-31T11:48:58.384-0300] {processor.py:830} INFO - Processing file /home/felipe/airflow/dags/19_postgre_operator.py for tasks to queue
[2023-12-31T11:48:58.386-0300] {logging_mixin.py:188} INFO - [2023-12-31T11:48:58.385-0300] {dagbag.py:538} INFO - Filling up the DagBag from /home/felipe/airflow/dags/19_postgre_operator.py
[2023-12-31T11:48:58.465-0300] {logging_mixin.py:188} INFO - [2023-12-31T11:48:58.454-0300] {dagbag.py:348} ERROR - Failed to import: /home/felipe/airflow/dags/19_postgre_operator.py
Traceback (most recent call last):
  File "/home/felipe/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/felipe/airflow/dags/19_postgre_operator.py", line 14, in <module>
    extract_gz = BashOperator(
  File "/home/felipe/.local/lib/python3.10/site-packages/airflow/models/baseoperator.py", line 437, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/home/felipe/.local/lib/python3.10/site-packages/airflow/operators/bash.py", line 152, in __init__
    super().__init__(**kwargs)
  File "/home/felipe/.local/lib/python3.10/site-packages/airflow/models/baseoperator.py", line 437, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/home/felipe/.local/lib/python3.10/site-packages/airflow/models/baseoperator.py", line 798, in __init__
    raise AirflowException(
airflow.exceptions.AirflowException: Invalid arguments were passed to BashOperator (task_id: extract_gz). Invalid arguments were:
**kwargs: {'template_searchpath': '/tmp'}
[2023-12-31T11:48:58.466-0300] {processor.py:842} WARNING - No viable dags retrieved from /home/felipe/airflow/dags/19_postgre_operator.py
[2023-12-31T11:48:58.645-0300] {processor.py:183} INFO - Processing /home/felipe/airflow/dags/19_postgre_operator.py took 0.301 seconds
[2023-12-31T11:51:04.784-0300] {processor.py:161} INFO - Started process (PID=35704) to work on /home/felipe/airflow/dags/19_postgre_operator.py
[2023-12-31T11:51:04.795-0300] {processor.py:830} INFO - Processing file /home/felipe/airflow/dags/19_postgre_operator.py for tasks to queue
[2023-12-31T11:51:04.805-0300] {logging_mixin.py:188} INFO - [2023-12-31T11:51:04.804-0300] {dagbag.py:538} INFO - Filling up the DagBag from /home/felipe/airflow/dags/19_postgre_operator.py
[2023-12-31T11:51:04.924-0300] {logging_mixin.py:188} INFO - [2023-12-31T11:51:04.896-0300] {dagbag.py:348} ERROR - Failed to import: /home/felipe/airflow/dags/19_postgre_operator.py
Traceback (most recent call last):
  File "/home/felipe/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/felipe/airflow/dags/19_postgre_operator.py", line 14, in <module>
    extract_gz = BashOperator(
  File "/home/felipe/.local/lib/python3.10/site-packages/airflow/models/baseoperator.py", line 437, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/home/felipe/.local/lib/python3.10/site-packages/airflow/operators/bash.py", line 152, in __init__
    super().__init__(**kwargs)
  File "/home/felipe/.local/lib/python3.10/site-packages/airflow/models/baseoperator.py", line 437, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/home/felipe/.local/lib/python3.10/site-packages/airflow/models/baseoperator.py", line 798, in __init__
    raise AirflowException(
airflow.exceptions.AirflowException: Invalid arguments were passed to BashOperator (task_id: extract_gz). Invalid arguments were:
**kwargs: {'template_searchpath': '/tmp'}
[2023-12-31T11:51:04.934-0300] {processor.py:842} WARNING - No viable dags retrieved from /home/felipe/airflow/dags/19_postgre_operator.py
[2023-12-31T11:51:05.256-0300] {processor.py:183} INFO - Processing /home/felipe/airflow/dags/19_postgre_operator.py took 0.500 seconds
[2023-12-31T11:53:51.436-0300] {processor.py:161} INFO - Started process (PID=35839) to work on /home/felipe/airflow/dags/19_postgre_operator.py
[2023-12-31T11:53:51.454-0300] {processor.py:830} INFO - Processing file /home/felipe/airflow/dags/19_postgre_operator.py for tasks to queue
[2023-12-31T11:53:51.466-0300] {logging_mixin.py:188} INFO - [2023-12-31T11:53:51.464-0300] {dagbag.py:538} INFO - Filling up the DagBag from /home/felipe/airflow/dags/19_postgre_operator.py
[2023-12-31T11:53:51.675-0300] {logging_mixin.py:188} INFO - [2023-12-31T11:53:51.605-0300] {dagbag.py:348} ERROR - Failed to import: /home/felipe/airflow/dags/19_postgre_operator.py
Traceback (most recent call last):
  File "/home/felipe/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/felipe/airflow/dags/19_postgre_operator.py", line 14, in <module>
    extract_gz = BashOperator(
  File "/home/felipe/.local/lib/python3.10/site-packages/airflow/models/baseoperator.py", line 437, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/home/felipe/.local/lib/python3.10/site-packages/airflow/operators/bash.py", line 152, in __init__
    super().__init__(**kwargs)
  File "/home/felipe/.local/lib/python3.10/site-packages/airflow/models/baseoperator.py", line 437, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/home/felipe/.local/lib/python3.10/site-packages/airflow/models/baseoperator.py", line 798, in __init__
    raise AirflowException(
airflow.exceptions.AirflowException: Invalid arguments were passed to BashOperator (task_id: extract_gz). Invalid arguments were:
**kwargs: {'template_searchpath': '/tmp'}
[2023-12-31T11:53:51.684-0300] {processor.py:842} WARNING - No viable dags retrieved from /home/felipe/airflow/dags/19_postgre_operator.py
[2023-12-31T11:53:51.954-0300] {processor.py:183} INFO - Processing /home/felipe/airflow/dags/19_postgre_operator.py took 0.530 seconds
[2023-12-31T11:55:49.435-0300] {processor.py:161} INFO - Started process (PID=35980) to work on /home/felipe/airflow/dags/19_postgre_operator.py
[2023-12-31T11:55:49.444-0300] {processor.py:830} INFO - Processing file /home/felipe/airflow/dags/19_postgre_operator.py for tasks to queue
[2023-12-31T11:55:49.454-0300] {logging_mixin.py:188} INFO - [2023-12-31T11:55:49.445-0300] {dagbag.py:538} INFO - Filling up the DagBag from /home/felipe/airflow/dags/19_postgre_operator.py
[2023-12-31T11:55:49.534-0300] {logging_mixin.py:188} INFO - [2023-12-31T11:55:49.524-0300] {dagbag.py:348} ERROR - Failed to import: /home/felipe/airflow/dags/19_postgre_operator.py
Traceback (most recent call last):
  File "/home/felipe/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/felipe/airflow/dags/19_postgre_operator.py", line 14, in <module>
    extract_gz = BashOperator(
  File "/home/felipe/.local/lib/python3.10/site-packages/airflow/models/baseoperator.py", line 437, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/home/felipe/.local/lib/python3.10/site-packages/airflow/operators/bash.py", line 152, in __init__
    super().__init__(**kwargs)
  File "/home/felipe/.local/lib/python3.10/site-packages/airflow/models/baseoperator.py", line 437, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/home/felipe/.local/lib/python3.10/site-packages/airflow/models/baseoperator.py", line 798, in __init__
    raise AirflowException(
airflow.exceptions.AirflowException: Invalid arguments were passed to BashOperator (task_id: extract_gz). Invalid arguments were:
**kwargs: {'template_searchpath': '/tmp'}
[2023-12-31T11:55:49.535-0300] {processor.py:842} WARNING - No viable dags retrieved from /home/felipe/airflow/dags/19_postgre_operator.py
[2023-12-31T11:55:49.714-0300] {processor.py:183} INFO - Processing /home/felipe/airflow/dags/19_postgre_operator.py took 0.291 seconds
[2023-12-31T11:57:33.784-0300] {processor.py:161} INFO - Started process (PID=36083) to work on /home/felipe/airflow/dags/19_postgre_operator.py
[2023-12-31T11:57:33.794-0300] {processor.py:830} INFO - Processing file /home/felipe/airflow/dags/19_postgre_operator.py for tasks to queue
[2023-12-31T11:57:33.804-0300] {logging_mixin.py:188} INFO - [2023-12-31T11:57:33.795-0300] {dagbag.py:538} INFO - Filling up the DagBag from /home/felipe/airflow/dags/19_postgre_operator.py
[2023-12-31T11:57:33.874-0300] {logging_mixin.py:188} INFO - [2023-12-31T11:57:33.854-0300] {dagbag.py:348} ERROR - Failed to import: /home/felipe/airflow/dags/19_postgre_operator.py
Traceback (most recent call last):
  File "/home/felipe/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/felipe/airflow/dags/19_postgre_operator.py", line 14, in <module>
    extract_gz = BashOperator(
  File "/home/felipe/.local/lib/python3.10/site-packages/airflow/models/baseoperator.py", line 437, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/home/felipe/.local/lib/python3.10/site-packages/airflow/operators/bash.py", line 152, in __init__
    super().__init__(**kwargs)
  File "/home/felipe/.local/lib/python3.10/site-packages/airflow/models/baseoperator.py", line 437, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/home/felipe/.local/lib/python3.10/site-packages/airflow/models/baseoperator.py", line 798, in __init__
    raise AirflowException(
airflow.exceptions.AirflowException: Invalid arguments were passed to BashOperator (task_id: extract_gz). Invalid arguments were:
**kwargs: {'template_searchpath': '/tmp'}
[2023-12-31T11:57:33.875-0300] {processor.py:842} WARNING - No viable dags retrieved from /home/felipe/airflow/dags/19_postgre_operator.py
[2023-12-31T11:57:34.055-0300] {processor.py:183} INFO - Processing /home/felipe/airflow/dags/19_postgre_operator.py took 0.301 seconds
[2023-12-31T11:59:19.655-0300] {processor.py:161} INFO - Started process (PID=36190) to work on /home/felipe/airflow/dags/19_postgre_operator.py
[2023-12-31T11:59:19.664-0300] {processor.py:830} INFO - Processing file /home/felipe/airflow/dags/19_postgre_operator.py for tasks to queue
[2023-12-31T11:59:19.674-0300] {logging_mixin.py:188} INFO - [2023-12-31T11:59:19.666-0300] {dagbag.py:538} INFO - Filling up the DagBag from /home/felipe/airflow/dags/19_postgre_operator.py
[2023-12-31T11:59:19.744-0300] {logging_mixin.py:188} INFO - [2023-12-31T11:59:19.726-0300] {dagbag.py:348} ERROR - Failed to import: /home/felipe/airflow/dags/19_postgre_operator.py
Traceback (most recent call last):
  File "/home/felipe/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/felipe/airflow/dags/19_postgre_operator.py", line 14, in <module>
    extract_gz = BashOperator(
  File "/home/felipe/.local/lib/python3.10/site-packages/airflow/models/baseoperator.py", line 437, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/home/felipe/.local/lib/python3.10/site-packages/airflow/operators/bash.py", line 152, in __init__
    super().__init__(**kwargs)
  File "/home/felipe/.local/lib/python3.10/site-packages/airflow/models/baseoperator.py", line 437, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/home/felipe/.local/lib/python3.10/site-packages/airflow/models/baseoperator.py", line 798, in __init__
    raise AirflowException(
airflow.exceptions.AirflowException: Invalid arguments were passed to BashOperator (task_id: extract_gz). Invalid arguments were:
**kwargs: {'template_searchpath': '/tmp'}
[2023-12-31T11:59:19.745-0300] {processor.py:842} WARNING - No viable dags retrieved from /home/felipe/airflow/dags/19_postgre_operator.py
[2023-12-31T11:59:19.955-0300] {processor.py:183} INFO - Processing /home/felipe/airflow/dags/19_postgre_operator.py took 0.331 seconds
[2023-12-31T12:01:07.064-0300] {processor.py:161} INFO - Started process (PID=36320) to work on /home/felipe/airflow/dags/19_postgre_operator.py
[2023-12-31T12:01:07.075-0300] {processor.py:830} INFO - Processing file /home/felipe/airflow/dags/19_postgre_operator.py for tasks to queue
[2023-12-31T12:01:07.085-0300] {logging_mixin.py:188} INFO - [2023-12-31T12:01:07.084-0300] {dagbag.py:538} INFO - Filling up the DagBag from /home/felipe/airflow/dags/19_postgre_operator.py
[2023-12-31T12:01:07.175-0300] {logging_mixin.py:188} INFO - [2023-12-31T12:01:07.155-0300] {dagbag.py:348} ERROR - Failed to import: /home/felipe/airflow/dags/19_postgre_operator.py
Traceback (most recent call last):
  File "/home/felipe/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/felipe/airflow/dags/19_postgre_operator.py", line 14, in <module>
    extract_gz = BashOperator(
  File "/home/felipe/.local/lib/python3.10/site-packages/airflow/models/baseoperator.py", line 437, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/home/felipe/.local/lib/python3.10/site-packages/airflow/operators/bash.py", line 152, in __init__
    super().__init__(**kwargs)
  File "/home/felipe/.local/lib/python3.10/site-packages/airflow/models/baseoperator.py", line 437, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/home/felipe/.local/lib/python3.10/site-packages/airflow/models/baseoperator.py", line 798, in __init__
    raise AirflowException(
airflow.exceptions.AirflowException: Invalid arguments were passed to BashOperator (task_id: extract_gz). Invalid arguments were:
**kwargs: {'template_searchpath': '/tmp'}
[2023-12-31T12:01:07.176-0300] {processor.py:842} WARNING - No viable dags retrieved from /home/felipe/airflow/dags/19_postgre_operator.py
[2023-12-31T12:01:07.405-0300] {processor.py:183} INFO - Processing /home/felipe/airflow/dags/19_postgre_operator.py took 0.379 seconds
[2023-12-31T12:03:04.064-0300] {processor.py:161} INFO - Started process (PID=36427) to work on /home/felipe/airflow/dags/19_postgre_operator.py
[2023-12-31T12:03:04.075-0300] {processor.py:830} INFO - Processing file /home/felipe/airflow/dags/19_postgre_operator.py for tasks to queue
[2023-12-31T12:03:04.085-0300] {logging_mixin.py:188} INFO - [2023-12-31T12:03:04.084-0300] {dagbag.py:538} INFO - Filling up the DagBag from /home/felipe/airflow/dags/19_postgre_operator.py
[2023-12-31T12:03:04.194-0300] {logging_mixin.py:188} INFO - [2023-12-31T12:03:04.175-0300] {dagbag.py:348} ERROR - Failed to import: /home/felipe/airflow/dags/19_postgre_operator.py
Traceback (most recent call last):
  File "/home/felipe/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/felipe/airflow/dags/19_postgre_operator.py", line 14, in <module>
    extract_gz = BashOperator(
  File "/home/felipe/.local/lib/python3.10/site-packages/airflow/models/baseoperator.py", line 437, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/home/felipe/.local/lib/python3.10/site-packages/airflow/operators/bash.py", line 152, in __init__
    super().__init__(**kwargs)
  File "/home/felipe/.local/lib/python3.10/site-packages/airflow/models/baseoperator.py", line 437, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/home/felipe/.local/lib/python3.10/site-packages/airflow/models/baseoperator.py", line 798, in __init__
    raise AirflowException(
airflow.exceptions.AirflowException: Invalid arguments were passed to BashOperator (task_id: extract_gz). Invalid arguments were:
**kwargs: {'template_searchpath': '/tmp'}
[2023-12-31T12:03:04.195-0300] {processor.py:842} WARNING - No viable dags retrieved from /home/felipe/airflow/dags/19_postgre_operator.py
[2023-12-31T12:03:04.425-0300] {processor.py:183} INFO - Processing /home/felipe/airflow/dags/19_postgre_operator.py took 0.390 seconds
[2023-12-31T12:06:10.024-0300] {processor.py:161} INFO - Started process (PID=36655) to work on /home/felipe/airflow/dags/19_postgre_operator.py
[2023-12-31T12:06:10.044-0300] {processor.py:830} INFO - Processing file /home/felipe/airflow/dags/19_postgre_operator.py for tasks to queue
[2023-12-31T12:06:10.055-0300] {logging_mixin.py:188} INFO - [2023-12-31T12:06:10.054-0300] {dagbag.py:538} INFO - Filling up the DagBag from /home/felipe/airflow/dags/19_postgre_operator.py
[2023-12-31T12:06:10.244-0300] {logging_mixin.py:188} INFO - [2023-12-31T12:06:10.224-0300] {dagbag.py:348} ERROR - Failed to import: /home/felipe/airflow/dags/19_postgre_operator.py
Traceback (most recent call last):
  File "/home/felipe/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/felipe/airflow/dags/19_postgre_operator.py", line 14, in <module>
    extract_gz = BashOperator(
  File "/home/felipe/.local/lib/python3.10/site-packages/airflow/models/baseoperator.py", line 437, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/home/felipe/.local/lib/python3.10/site-packages/airflow/operators/bash.py", line 152, in __init__
    super().__init__(**kwargs)
  File "/home/felipe/.local/lib/python3.10/site-packages/airflow/models/baseoperator.py", line 437, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/home/felipe/.local/lib/python3.10/site-packages/airflow/models/baseoperator.py", line 798, in __init__
    raise AirflowException(
airflow.exceptions.AirflowException: Invalid arguments were passed to BashOperator (task_id: extract_gz). Invalid arguments were:
**kwargs: {'template_searchpath': '/tmp'}
[2023-12-31T12:06:10.255-0300] {processor.py:842} WARNING - No viable dags retrieved from /home/felipe/airflow/dags/19_postgre_operator.py
[2023-12-31T12:06:10.694-0300] {processor.py:183} INFO - Processing /home/felipe/airflow/dags/19_postgre_operator.py took 0.740 seconds
[2023-12-31T12:09:26.924-0300] {processor.py:161} INFO - Started process (PID=37013) to work on /home/felipe/airflow/dags/19_postgre_operator.py
[2023-12-31T12:09:26.944-0300] {processor.py:830} INFO - Processing file /home/felipe/airflow/dags/19_postgre_operator.py for tasks to queue
[2023-12-31T12:09:26.965-0300] {logging_mixin.py:188} INFO - [2023-12-31T12:09:26.955-0300] {dagbag.py:538} INFO - Filling up the DagBag from /home/felipe/airflow/dags/19_postgre_operator.py
[2023-12-31T12:09:27.144-0300] {logging_mixin.py:188} INFO - [2023-12-31T12:09:27.115-0300] {dagbag.py:348} ERROR - Failed to import: /home/felipe/airflow/dags/19_postgre_operator.py
Traceback (most recent call last):
  File "/home/felipe/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/felipe/airflow/dags/19_postgre_operator.py", line 14, in <module>
    extract_gz = BashOperator(
  File "/home/felipe/.local/lib/python3.10/site-packages/airflow/models/baseoperator.py", line 437, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/home/felipe/.local/lib/python3.10/site-packages/airflow/operators/bash.py", line 152, in __init__
    super().__init__(**kwargs)
  File "/home/felipe/.local/lib/python3.10/site-packages/airflow/models/baseoperator.py", line 437, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/home/felipe/.local/lib/python3.10/site-packages/airflow/models/baseoperator.py", line 798, in __init__
    raise AirflowException(
airflow.exceptions.AirflowException: Invalid arguments were passed to BashOperator (task_id: extract_gz). Invalid arguments were:
**kwargs: {'template_searchpath': '/tmp'}
[2023-12-31T12:09:27.154-0300] {processor.py:842} WARNING - No viable dags retrieved from /home/felipe/airflow/dags/19_postgre_operator.py
[2023-12-31T12:09:27.575-0300] {processor.py:183} INFO - Processing /home/felipe/airflow/dags/19_postgre_operator.py took 0.720 seconds
[2023-12-31T12:10:54.305-0300] {processor.py:161} INFO - Started process (PID=37140) to work on /home/felipe/airflow/dags/19_postgre_operator.py
[2023-12-31T12:10:54.335-0300] {processor.py:830} INFO - Processing file /home/felipe/airflow/dags/19_postgre_operator.py for tasks to queue
[2023-12-31T12:10:54.364-0300] {logging_mixin.py:188} INFO - [2023-12-31T12:10:54.354-0300] {dagbag.py:538} INFO - Filling up the DagBag from /home/felipe/airflow/dags/19_postgre_operator.py
[2023-12-31T12:10:55.934-0300] {logging_mixin.py:188} INFO - [2023-12-31T12:10:55.915-0300] {dagbag.py:348} ERROR - Failed to import: /home/felipe/airflow/dags/19_postgre_operator.py
Traceback (most recent call last):
  File "/home/felipe/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/felipe/airflow/dags/19_postgre_operator.py", line 14, in <module>
    extract_gz = BashOperator(
  File "/home/felipe/.local/lib/python3.10/site-packages/airflow/models/baseoperator.py", line 437, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/home/felipe/.local/lib/python3.10/site-packages/airflow/operators/bash.py", line 152, in __init__
    super().__init__(**kwargs)
  File "/home/felipe/.local/lib/python3.10/site-packages/airflow/models/baseoperator.py", line 437, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/home/felipe/.local/lib/python3.10/site-packages/airflow/models/baseoperator.py", line 798, in __init__
    raise AirflowException(
airflow.exceptions.AirflowException: Invalid arguments were passed to BashOperator (task_id: extract_gz). Invalid arguments were:
**kwargs: {'template_searchpath': '/tmp'}
[2023-12-31T12:10:55.944-0300] {processor.py:842} WARNING - No viable dags retrieved from /home/felipe/airflow/dags/19_postgre_operator.py
[2023-12-31T12:10:56.155-0300] {processor.py:183} INFO - Processing /home/felipe/airflow/dags/19_postgre_operator.py took 1.901 seconds
[2023-12-31T12:11:37.515-0300] {processor.py:161} INFO - Started process (PID=37194) to work on /home/felipe/airflow/dags/19_postgre_operator.py
[2023-12-31T12:11:37.535-0300] {processor.py:830} INFO - Processing file /home/felipe/airflow/dags/19_postgre_operator.py for tasks to queue
[2023-12-31T12:11:37.554-0300] {logging_mixin.py:188} INFO - [2023-12-31T12:11:37.545-0300] {dagbag.py:538} INFO - Filling up the DagBag from /home/felipe/airflow/dags/19_postgre_operator.py
[2023-12-31T12:11:37.695-0300] {logging_mixin.py:188} INFO - [2023-12-31T12:11:37.664-0300] {dagbag.py:348} ERROR - Failed to import: /home/felipe/airflow/dags/19_postgre_operator.py
Traceback (most recent call last):
  File "/home/felipe/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/felipe/airflow/dags/19_postgre_operator.py", line 14, in <module>
    extract_gz = BashOperator(
  File "/home/felipe/.local/lib/python3.10/site-packages/airflow/models/baseoperator.py", line 437, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/home/felipe/.local/lib/python3.10/site-packages/airflow/operators/bash.py", line 152, in __init__
    super().__init__(**kwargs)
  File "/home/felipe/.local/lib/python3.10/site-packages/airflow/models/baseoperator.py", line 437, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/home/felipe/.local/lib/python3.10/site-packages/airflow/models/baseoperator.py", line 798, in __init__
    raise AirflowException(
airflow.exceptions.AirflowException: Invalid arguments were passed to BashOperator (task_id: extract_gz). Invalid arguments were:
**kwargs: {'template_searchpath': '/tmp'}
[2023-12-31T12:11:37.705-0300] {processor.py:842} WARNING - No viable dags retrieved from /home/felipe/airflow/dags/19_postgre_operator.py
[2023-12-31T12:11:38.005-0300] {processor.py:183} INFO - Processing /home/felipe/airflow/dags/19_postgre_operator.py took 0.530 seconds
[2023-12-31T12:12:20.874-0300] {processor.py:161} INFO - Started process (PID=37250) to work on /home/felipe/airflow/dags/19_postgre_operator.py
[2023-12-31T12:12:20.884-0300] {processor.py:830} INFO - Processing file /home/felipe/airflow/dags/19_postgre_operator.py for tasks to queue
[2023-12-31T12:12:20.905-0300] {logging_mixin.py:188} INFO - [2023-12-31T12:12:20.904-0300] {dagbag.py:538} INFO - Filling up the DagBag from /home/felipe/airflow/dags/19_postgre_operator.py
[2023-12-31T12:12:21.044-0300] {logging_mixin.py:188} INFO - [2023-12-31T12:12:21.014-0300] {dagbag.py:348} ERROR - Failed to import: /home/felipe/airflow/dags/19_postgre_operator.py
Traceback (most recent call last):
  File "/home/felipe/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/felipe/airflow/dags/19_postgre_operator.py", line 14, in <module>
    extract_gz = BashOperator(
  File "/home/felipe/.local/lib/python3.10/site-packages/airflow/models/baseoperator.py", line 437, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/home/felipe/.local/lib/python3.10/site-packages/airflow/operators/bash.py", line 152, in __init__
    super().__init__(**kwargs)
  File "/home/felipe/.local/lib/python3.10/site-packages/airflow/models/baseoperator.py", line 437, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/home/felipe/.local/lib/python3.10/site-packages/airflow/models/baseoperator.py", line 798, in __init__
    raise AirflowException(
airflow.exceptions.AirflowException: Invalid arguments were passed to BashOperator (task_id: extract_gz). Invalid arguments were:
**kwargs: {'template_searchpath': '/tmp'}
[2023-12-31T12:12:21.045-0300] {processor.py:842} WARNING - No viable dags retrieved from /home/felipe/airflow/dags/19_postgre_operator.py
[2023-12-31T12:12:21.375-0300] {processor.py:183} INFO - Processing /home/felipe/airflow/dags/19_postgre_operator.py took 0.540 seconds
[2023-12-31T12:12:59.955-0300] {processor.py:161} INFO - Started process (PID=37303) to work on /home/felipe/airflow/dags/19_postgre_operator.py
[2023-12-31T12:12:59.984-0300] {processor.py:830} INFO - Processing file /home/felipe/airflow/dags/19_postgre_operator.py for tasks to queue
[2023-12-31T12:13:00.004-0300] {logging_mixin.py:188} INFO - [2023-12-31T12:12:59.995-0300] {dagbag.py:538} INFO - Filling up the DagBag from /home/felipe/airflow/dags/19_postgre_operator.py
[2023-12-31T12:13:00.165-0300] {logging_mixin.py:188} INFO - [2023-12-31T12:13:00.134-0300] {dagbag.py:348} ERROR - Failed to import: /home/felipe/airflow/dags/19_postgre_operator.py
Traceback (most recent call last):
  File "/home/felipe/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/felipe/airflow/dags/19_postgre_operator.py", line 14, in <module>
    extract_gz = BashOperator(
  File "/home/felipe/.local/lib/python3.10/site-packages/airflow/models/baseoperator.py", line 437, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/home/felipe/.local/lib/python3.10/site-packages/airflow/operators/bash.py", line 152, in __init__
    super().__init__(**kwargs)
  File "/home/felipe/.local/lib/python3.10/site-packages/airflow/models/baseoperator.py", line 437, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/home/felipe/.local/lib/python3.10/site-packages/airflow/models/baseoperator.py", line 798, in __init__
    raise AirflowException(
airflow.exceptions.AirflowException: Invalid arguments were passed to BashOperator (task_id: extract_gz). Invalid arguments were:
**kwargs: {'template_searchpath': '/tmp'}
[2023-12-31T12:13:00.184-0300] {processor.py:842} WARNING - No viable dags retrieved from /home/felipe/airflow/dags/19_postgre_operator.py
[2023-12-31T12:13:00.534-0300] {processor.py:183} INFO - Processing /home/felipe/airflow/dags/19_postgre_operator.py took 0.610 seconds
[2023-12-31T12:13:42.774-0300] {processor.py:161} INFO - Started process (PID=37360) to work on /home/felipe/airflow/dags/19_postgre_operator.py
[2023-12-31T12:13:42.784-0300] {processor.py:830} INFO - Processing file /home/felipe/airflow/dags/19_postgre_operator.py for tasks to queue
[2023-12-31T12:13:42.795-0300] {logging_mixin.py:188} INFO - [2023-12-31T12:13:42.794-0300] {dagbag.py:538} INFO - Filling up the DagBag from /home/felipe/airflow/dags/19_postgre_operator.py
[2023-12-31T12:13:42.914-0300] {logging_mixin.py:188} INFO - [2023-12-31T12:13:42.874-0300] {dagbag.py:348} ERROR - Failed to import: /home/felipe/airflow/dags/19_postgre_operator.py
Traceback (most recent call last):
  File "/home/felipe/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/felipe/airflow/dags/19_postgre_operator.py", line 14, in <module>
    extract_gz = BashOperator(
  File "/home/felipe/.local/lib/python3.10/site-packages/airflow/models/baseoperator.py", line 437, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/home/felipe/.local/lib/python3.10/site-packages/airflow/operators/bash.py", line 152, in __init__
    super().__init__(**kwargs)
  File "/home/felipe/.local/lib/python3.10/site-packages/airflow/models/baseoperator.py", line 437, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/home/felipe/.local/lib/python3.10/site-packages/airflow/models/baseoperator.py", line 798, in __init__
    raise AirflowException(
airflow.exceptions.AirflowException: Invalid arguments were passed to BashOperator (task_id: extract_gz). Invalid arguments were:
**kwargs: {'template_searchpath': '/tmp'}
[2023-12-31T12:13:42.924-0300] {processor.py:842} WARNING - No viable dags retrieved from /home/felipe/airflow/dags/19_postgre_operator.py
[2023-12-31T12:13:43.245-0300] {processor.py:183} INFO - Processing /home/felipe/airflow/dags/19_postgre_operator.py took 0.510 seconds
[2023-12-31T12:14:27.724-0300] {processor.py:161} INFO - Started process (PID=37434) to work on /home/felipe/airflow/dags/19_postgre_operator.py
[2023-12-31T12:14:27.744-0300] {processor.py:830} INFO - Processing file /home/felipe/airflow/dags/19_postgre_operator.py for tasks to queue
[2023-12-31T12:14:27.764-0300] {logging_mixin.py:188} INFO - [2023-12-31T12:14:27.754-0300] {dagbag.py:538} INFO - Filling up the DagBag from /home/felipe/airflow/dags/19_postgre_operator.py
[2023-12-31T12:14:27.885-0300] {logging_mixin.py:188} INFO - [2023-12-31T12:14:27.855-0300] {dagbag.py:348} ERROR - Failed to import: /home/felipe/airflow/dags/19_postgre_operator.py
Traceback (most recent call last):
  File "/home/felipe/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/felipe/airflow/dags/19_postgre_operator.py", line 14, in <module>
    extract_gz = BashOperator(
  File "/home/felipe/.local/lib/python3.10/site-packages/airflow/models/baseoperator.py", line 437, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/home/felipe/.local/lib/python3.10/site-packages/airflow/operators/bash.py", line 152, in __init__
    super().__init__(**kwargs)
  File "/home/felipe/.local/lib/python3.10/site-packages/airflow/models/baseoperator.py", line 437, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/home/felipe/.local/lib/python3.10/site-packages/airflow/models/baseoperator.py", line 798, in __init__
    raise AirflowException(
airflow.exceptions.AirflowException: Invalid arguments were passed to BashOperator (task_id: extract_gz). Invalid arguments were:
**kwargs: {'template_searchpath': '/tmp'}
[2023-12-31T12:14:27.895-0300] {processor.py:842} WARNING - No viable dags retrieved from /home/felipe/airflow/dags/19_postgre_operator.py
[2023-12-31T12:14:28.224-0300] {processor.py:183} INFO - Processing /home/felipe/airflow/dags/19_postgre_operator.py took 0.540 seconds
[2023-12-31T12:15:21.424-0300] {processor.py:161} INFO - Started process (PID=37513) to work on /home/felipe/airflow/dags/19_postgre_operator.py
[2023-12-31T12:15:21.444-0300] {processor.py:830} INFO - Processing file /home/felipe/airflow/dags/19_postgre_operator.py for tasks to queue
[2023-12-31T12:15:21.464-0300] {logging_mixin.py:188} INFO - [2023-12-31T12:15:21.455-0300] {dagbag.py:538} INFO - Filling up the DagBag from /home/felipe/airflow/dags/19_postgre_operator.py
[2023-12-31T12:15:21.594-0300] {logging_mixin.py:188} INFO - [2023-12-31T12:15:21.565-0300] {dagbag.py:348} ERROR - Failed to import: /home/felipe/airflow/dags/19_postgre_operator.py
Traceback (most recent call last):
  File "/home/felipe/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/felipe/airflow/dags/19_postgre_operator.py", line 14, in <module>
    extract_gz = BashOperator(
  File "/home/felipe/.local/lib/python3.10/site-packages/airflow/models/baseoperator.py", line 437, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/home/felipe/.local/lib/python3.10/site-packages/airflow/operators/bash.py", line 152, in __init__
    super().__init__(**kwargs)
  File "/home/felipe/.local/lib/python3.10/site-packages/airflow/models/baseoperator.py", line 437, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/home/felipe/.local/lib/python3.10/site-packages/airflow/models/baseoperator.py", line 798, in __init__
    raise AirflowException(
airflow.exceptions.AirflowException: Invalid arguments were passed to BashOperator (task_id: extract_gz). Invalid arguments were:
**kwargs: {'template_searchpath': '/tmp'}
[2023-12-31T12:15:21.595-0300] {processor.py:842} WARNING - No viable dags retrieved from /home/felipe/airflow/dags/19_postgre_operator.py
[2023-12-31T12:15:21.905-0300] {processor.py:183} INFO - Processing /home/felipe/airflow/dags/19_postgre_operator.py took 0.530 seconds
[2023-12-31T12:16:09.835-0300] {processor.py:161} INFO - Started process (PID=37576) to work on /home/felipe/airflow/dags/19_postgre_operator.py
[2023-12-31T12:16:09.864-0300] {processor.py:830} INFO - Processing file /home/felipe/airflow/dags/19_postgre_operator.py for tasks to queue
[2023-12-31T12:16:09.884-0300] {logging_mixin.py:188} INFO - [2023-12-31T12:16:09.874-0300] {dagbag.py:538} INFO - Filling up the DagBag from /home/felipe/airflow/dags/19_postgre_operator.py
[2023-12-31T12:16:10.004-0300] {logging_mixin.py:188} INFO - [2023-12-31T12:16:09.965-0300] {dagbag.py:348} ERROR - Failed to import: /home/felipe/airflow/dags/19_postgre_operator.py
Traceback (most recent call last):
  File "/home/felipe/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/felipe/airflow/dags/19_postgre_operator.py", line 14, in <module>
    extract_gz = BashOperator(
  File "/home/felipe/.local/lib/python3.10/site-packages/airflow/models/baseoperator.py", line 437, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/home/felipe/.local/lib/python3.10/site-packages/airflow/operators/bash.py", line 152, in __init__
    super().__init__(**kwargs)
  File "/home/felipe/.local/lib/python3.10/site-packages/airflow/models/baseoperator.py", line 437, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/home/felipe/.local/lib/python3.10/site-packages/airflow/models/baseoperator.py", line 798, in __init__
    raise AirflowException(
airflow.exceptions.AirflowException: Invalid arguments were passed to BashOperator (task_id: extract_gz). Invalid arguments were:
**kwargs: {'template_searchpath': '/tmp'}
[2023-12-31T12:16:10.014-0300] {processor.py:842} WARNING - No viable dags retrieved from /home/felipe/airflow/dags/19_postgre_operator.py
[2023-12-31T12:16:10.284-0300] {processor.py:183} INFO - Processing /home/felipe/airflow/dags/19_postgre_operator.py took 0.530 seconds
[2023-12-31T12:16:54.514-0300] {processor.py:161} INFO - Started process (PID=37634) to work on /home/felipe/airflow/dags/19_postgre_operator.py
[2023-12-31T12:16:54.544-0300] {processor.py:830} INFO - Processing file /home/felipe/airflow/dags/19_postgre_operator.py for tasks to queue
[2023-12-31T12:16:54.575-0300] {logging_mixin.py:188} INFO - [2023-12-31T12:16:54.565-0300] {dagbag.py:538} INFO - Filling up the DagBag from /home/felipe/airflow/dags/19_postgre_operator.py
[2023-12-31T12:16:54.764-0300] {logging_mixin.py:188} INFO - [2023-12-31T12:16:54.705-0300] {dagbag.py:348} ERROR - Failed to import: /home/felipe/airflow/dags/19_postgre_operator.py
Traceback (most recent call last):
  File "/home/felipe/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/felipe/airflow/dags/19_postgre_operator.py", line 14, in <module>
    extract_gz = BashOperator(
  File "/home/felipe/.local/lib/python3.10/site-packages/airflow/models/baseoperator.py", line 437, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/home/felipe/.local/lib/python3.10/site-packages/airflow/operators/bash.py", line 152, in __init__
    super().__init__(**kwargs)
  File "/home/felipe/.local/lib/python3.10/site-packages/airflow/models/baseoperator.py", line 437, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/home/felipe/.local/lib/python3.10/site-packages/airflow/models/baseoperator.py", line 798, in __init__
    raise AirflowException(
airflow.exceptions.AirflowException: Invalid arguments were passed to BashOperator (task_id: extract_gz). Invalid arguments were:
**kwargs: {'template_searchpath': '/tmp'}
[2023-12-31T12:16:54.784-0300] {processor.py:842} WARNING - No viable dags retrieved from /home/felipe/airflow/dags/19_postgre_operator.py
[2023-12-31T12:16:55.124-0300] {processor.py:183} INFO - Processing /home/felipe/airflow/dags/19_postgre_operator.py took 0.660 seconds
[2023-12-31T12:17:45.424-0300] {processor.py:161} INFO - Started process (PID=37702) to work on /home/felipe/airflow/dags/19_postgre_operator.py
[2023-12-31T12:17:45.454-0300] {processor.py:830} INFO - Processing file /home/felipe/airflow/dags/19_postgre_operator.py for tasks to queue
[2023-12-31T12:17:45.464-0300] {logging_mixin.py:188} INFO - [2023-12-31T12:17:45.464-0300] {dagbag.py:538} INFO - Filling up the DagBag from /home/felipe/airflow/dags/19_postgre_operator.py
[2023-12-31T12:17:45.614-0300] {logging_mixin.py:188} INFO - [2023-12-31T12:17:45.584-0300] {dagbag.py:348} ERROR - Failed to import: /home/felipe/airflow/dags/19_postgre_operator.py
Traceback (most recent call last):
  File "/home/felipe/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/felipe/airflow/dags/19_postgre_operator.py", line 14, in <module>
    extract_gz = BashOperator(
  File "/home/felipe/.local/lib/python3.10/site-packages/airflow/models/baseoperator.py", line 437, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/home/felipe/.local/lib/python3.10/site-packages/airflow/operators/bash.py", line 152, in __init__
    super().__init__(**kwargs)
  File "/home/felipe/.local/lib/python3.10/site-packages/airflow/models/baseoperator.py", line 437, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/home/felipe/.local/lib/python3.10/site-packages/airflow/models/baseoperator.py", line 798, in __init__
    raise AirflowException(
airflow.exceptions.AirflowException: Invalid arguments were passed to BashOperator (task_id: extract_gz). Invalid arguments were:
**kwargs: {'template_searchpath': '/tmp'}
[2023-12-31T12:17:45.624-0300] {processor.py:842} WARNING - No viable dags retrieved from /home/felipe/airflow/dags/19_postgre_operator.py
[2023-12-31T12:17:45.924-0300] {processor.py:183} INFO - Processing /home/felipe/airflow/dags/19_postgre_operator.py took 0.559 seconds
[2023-12-31T12:18:38.675-0300] {processor.py:161} INFO - Started process (PID=37771) to work on /home/felipe/airflow/dags/19_postgre_operator.py
[2023-12-31T12:18:38.714-0300] {processor.py:830} INFO - Processing file /home/felipe/airflow/dags/19_postgre_operator.py for tasks to queue
[2023-12-31T12:18:38.744-0300] {logging_mixin.py:188} INFO - [2023-12-31T12:18:38.734-0300] {dagbag.py:538} INFO - Filling up the DagBag from /home/felipe/airflow/dags/19_postgre_operator.py
[2023-12-31T12:18:38.974-0300] {logging_mixin.py:188} INFO - [2023-12-31T12:18:38.944-0300] {dagbag.py:348} ERROR - Failed to import: /home/felipe/airflow/dags/19_postgre_operator.py
Traceback (most recent call last):
  File "/home/felipe/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/felipe/airflow/dags/19_postgre_operator.py", line 14, in <module>
    extract_gz = BashOperator(
  File "/home/felipe/.local/lib/python3.10/site-packages/airflow/models/baseoperator.py", line 437, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/home/felipe/.local/lib/python3.10/site-packages/airflow/operators/bash.py", line 152, in __init__
    super().__init__(**kwargs)
  File "/home/felipe/.local/lib/python3.10/site-packages/airflow/models/baseoperator.py", line 437, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/home/felipe/.local/lib/python3.10/site-packages/airflow/models/baseoperator.py", line 798, in __init__
    raise AirflowException(
airflow.exceptions.AirflowException: Invalid arguments were passed to BashOperator (task_id: extract_gz). Invalid arguments were:
**kwargs: {'template_searchpath': '/tmp'}
[2023-12-31T12:18:38.984-0300] {processor.py:842} WARNING - No viable dags retrieved from /home/felipe/airflow/dags/19_postgre_operator.py
[2023-12-31T12:18:39.454-0300] {processor.py:183} INFO - Processing /home/felipe/airflow/dags/19_postgre_operator.py took 0.840 seconds
[2023-12-31T12:25:15.770-0300] {processor.py:161} INFO - Started process (PID=37897) to work on /home/felipe/airflow/dags/19_postgre_operator.py
[2023-12-31T12:25:15.821-0300] {processor.py:830} INFO - Processing file /home/felipe/airflow/dags/19_postgre_operator.py for tasks to queue
[2023-12-31T12:25:15.950-0300] {logging_mixin.py:188} INFO - [2023-12-31T12:25:15.930-0300] {dagbag.py:538} INFO - Filling up the DagBag from /home/felipe/airflow/dags/19_postgre_operator.py
[2023-12-31T12:25:16.401-0300] {logging_mixin.py:188} INFO - [2023-12-31T12:25:16.291-0300] {dagbag.py:348} ERROR - Failed to import: /home/felipe/airflow/dags/19_postgre_operator.py
Traceback (most recent call last):
  File "/home/felipe/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/felipe/airflow/dags/19_postgre_operator.py", line 14, in <module>
    extract_gz = BashOperator(
  File "/home/felipe/.local/lib/python3.10/site-packages/airflow/models/baseoperator.py", line 437, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/home/felipe/.local/lib/python3.10/site-packages/airflow/operators/bash.py", line 152, in __init__
    super().__init__(**kwargs)
  File "/home/felipe/.local/lib/python3.10/site-packages/airflow/models/baseoperator.py", line 437, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/home/felipe/.local/lib/python3.10/site-packages/airflow/models/baseoperator.py", line 798, in __init__
    raise AirflowException(
airflow.exceptions.AirflowException: Invalid arguments were passed to BashOperator (task_id: extract_gz). Invalid arguments were:
**kwargs: {'template_searchpath': '/tmp'}
[2023-12-31T12:25:16.501-0300] {processor.py:842} WARNING - No viable dags retrieved from /home/felipe/airflow/dags/19_postgre_operator.py
[2023-12-31T12:25:17.880-0300] {processor.py:183} INFO - Processing /home/felipe/airflow/dags/19_postgre_operator.py took 2.260 seconds
[2023-12-31T12:26:32.511-0300] {processor.py:161} INFO - Started process (PID=37992) to work on /home/felipe/airflow/dags/19_postgre_operator.py
[2023-12-31T12:26:32.531-0300] {processor.py:830} INFO - Processing file /home/felipe/airflow/dags/19_postgre_operator.py for tasks to queue
[2023-12-31T12:26:32.551-0300] {logging_mixin.py:188} INFO - [2023-12-31T12:26:32.550-0300] {dagbag.py:538} INFO - Filling up the DagBag from /home/felipe/airflow/dags/19_postgre_operator.py
[2023-12-31T12:26:32.691-0300] {logging_mixin.py:188} INFO - [2023-12-31T12:26:32.670-0300] {dagbag.py:348} ERROR - Failed to import: /home/felipe/airflow/dags/19_postgre_operator.py
Traceback (most recent call last):
  File "/home/felipe/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/felipe/airflow/dags/19_postgre_operator.py", line 14, in <module>
    extract_gz = BashOperator(
  File "/home/felipe/.local/lib/python3.10/site-packages/airflow/models/baseoperator.py", line 437, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/home/felipe/.local/lib/python3.10/site-packages/airflow/operators/bash.py", line 152, in __init__
    super().__init__(**kwargs)
  File "/home/felipe/.local/lib/python3.10/site-packages/airflow/models/baseoperator.py", line 437, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/home/felipe/.local/lib/python3.10/site-packages/airflow/models/baseoperator.py", line 798, in __init__
    raise AirflowException(
airflow.exceptions.AirflowException: Invalid arguments were passed to BashOperator (task_id: extract_gz). Invalid arguments were:
**kwargs: {'template_searchpath': '/tmp'}
[2023-12-31T12:26:32.710-0300] {processor.py:842} WARNING - No viable dags retrieved from /home/felipe/airflow/dags/19_postgre_operator.py
[2023-12-31T12:26:33.070-0300] {processor.py:183} INFO - Processing /home/felipe/airflow/dags/19_postgre_operator.py took 0.610 seconds
[2023-12-31T12:27:07.701-0300] {processor.py:161} INFO - Started process (PID=38027) to work on /home/felipe/airflow/dags/19_postgre_operator.py
[2023-12-31T12:27:07.721-0300] {processor.py:830} INFO - Processing file /home/felipe/airflow/dags/19_postgre_operator.py for tasks to queue
[2023-12-31T12:27:07.750-0300] {logging_mixin.py:188} INFO - [2023-12-31T12:27:07.740-0300] {dagbag.py:538} INFO - Filling up the DagBag from /home/felipe/airflow/dags/19_postgre_operator.py
[2023-12-31T12:27:07.940-0300] {logging_mixin.py:188} INFO - [2023-12-31T12:27:07.900-0300] {dagbag.py:348} ERROR - Failed to import: /home/felipe/airflow/dags/19_postgre_operator.py
Traceback (most recent call last):
  File "/home/felipe/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/felipe/airflow/dags/19_postgre_operator.py", line 14, in <module>
    extract_gz = BashOperator(
  File "/home/felipe/.local/lib/python3.10/site-packages/airflow/models/baseoperator.py", line 437, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/home/felipe/.local/lib/python3.10/site-packages/airflow/operators/bash.py", line 152, in __init__
    super().__init__(**kwargs)
  File "/home/felipe/.local/lib/python3.10/site-packages/airflow/models/baseoperator.py", line 437, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/home/felipe/.local/lib/python3.10/site-packages/airflow/models/baseoperator.py", line 798, in __init__
    raise AirflowException(
airflow.exceptions.AirflowException: Invalid arguments were passed to BashOperator (task_id: extract_gz). Invalid arguments were:
**kwargs: {'template_searchpath': '/tmp'}
[2023-12-31T12:27:07.950-0300] {processor.py:842} WARNING - No viable dags retrieved from /home/felipe/airflow/dags/19_postgre_operator.py
[2023-12-31T12:27:08.400-0300] {processor.py:183} INFO - Processing /home/felipe/airflow/dags/19_postgre_operator.py took 0.740 seconds
[2023-12-31T12:27:41.711-0300] {processor.py:161} INFO - Started process (PID=38068) to work on /home/felipe/airflow/dags/19_postgre_operator.py
[2023-12-31T12:27:41.740-0300] {processor.py:830} INFO - Processing file /home/felipe/airflow/dags/19_postgre_operator.py for tasks to queue
[2023-12-31T12:27:41.770-0300] {logging_mixin.py:188} INFO - [2023-12-31T12:27:41.751-0300] {dagbag.py:538} INFO - Filling up the DagBag from /home/felipe/airflow/dags/19_postgre_operator.py
[2023-12-31T12:27:42.041-0300] {logging_mixin.py:188} INFO - [2023-12-31T12:27:41.991-0300] {dagbag.py:348} ERROR - Failed to import: /home/felipe/airflow/dags/19_postgre_operator.py
Traceback (most recent call last):
  File "/home/felipe/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/felipe/airflow/dags/19_postgre_operator.py", line 14, in <module>
    extract_gz = BashOperator(
  File "/home/felipe/.local/lib/python3.10/site-packages/airflow/models/baseoperator.py", line 437, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/home/felipe/.local/lib/python3.10/site-packages/airflow/operators/bash.py", line 152, in __init__
    super().__init__(**kwargs)
  File "/home/felipe/.local/lib/python3.10/site-packages/airflow/models/baseoperator.py", line 437, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/home/felipe/.local/lib/python3.10/site-packages/airflow/models/baseoperator.py", line 798, in __init__
    raise AirflowException(
airflow.exceptions.AirflowException: Invalid arguments were passed to BashOperator (task_id: extract_gz). Invalid arguments were:
**kwargs: {'template_searchpath': '/tmp'}
[2023-12-31T12:27:42.061-0300] {processor.py:842} WARNING - No viable dags retrieved from /home/felipe/airflow/dags/19_postgre_operator.py
[2023-12-31T12:27:42.601-0300] {processor.py:183} INFO - Processing /home/felipe/airflow/dags/19_postgre_operator.py took 0.970 seconds
[2023-12-31T12:28:23.580-0300] {processor.py:161} INFO - Started process (PID=38096) to work on /home/felipe/airflow/dags/19_postgre_operator.py
[2023-12-31T12:28:23.601-0300] {processor.py:830} INFO - Processing file /home/felipe/airflow/dags/19_postgre_operator.py for tasks to queue
[2023-12-31T12:28:23.621-0300] {logging_mixin.py:188} INFO - [2023-12-31T12:28:23.620-0300] {dagbag.py:538} INFO - Filling up the DagBag from /home/felipe/airflow/dags/19_postgre_operator.py
[2023-12-31T12:28:23.811-0300] {logging_mixin.py:188} INFO - [2023-12-31T12:28:23.780-0300] {dagbag.py:348} ERROR - Failed to import: /home/felipe/airflow/dags/19_postgre_operator.py
Traceback (most recent call last):
  File "/home/felipe/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/felipe/airflow/dags/19_postgre_operator.py", line 14, in <module>
    extract_gz = BashOperator(
  File "/home/felipe/.local/lib/python3.10/site-packages/airflow/models/baseoperator.py", line 437, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/home/felipe/.local/lib/python3.10/site-packages/airflow/operators/bash.py", line 152, in __init__
    super().__init__(**kwargs)
  File "/home/felipe/.local/lib/python3.10/site-packages/airflow/models/baseoperator.py", line 437, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/home/felipe/.local/lib/python3.10/site-packages/airflow/models/baseoperator.py", line 798, in __init__
    raise AirflowException(
airflow.exceptions.AirflowException: Invalid arguments were passed to BashOperator (task_id: extract_gz). Invalid arguments were:
**kwargs: {'template_searchpath': '/tmp'}
[2023-12-31T12:28:23.821-0300] {processor.py:842} WARNING - No viable dags retrieved from /home/felipe/airflow/dags/19_postgre_operator.py
[2023-12-31T12:28:24.231-0300] {processor.py:183} INFO - Processing /home/felipe/airflow/dags/19_postgre_operator.py took 0.721 seconds
[2023-12-31T12:28:57.570-0300] {processor.py:161} INFO - Started process (PID=38123) to work on /home/felipe/airflow/dags/19_postgre_operator.py
[2023-12-31T12:28:57.591-0300] {processor.py:830} INFO - Processing file /home/felipe/airflow/dags/19_postgre_operator.py for tasks to queue
[2023-12-31T12:28:57.620-0300] {logging_mixin.py:188} INFO - [2023-12-31T12:28:57.610-0300] {dagbag.py:538} INFO - Filling up the DagBag from /home/felipe/airflow/dags/19_postgre_operator.py
[2023-12-31T12:28:57.800-0300] {logging_mixin.py:188} INFO - [2023-12-31T12:28:57.761-0300] {dagbag.py:348} ERROR - Failed to import: /home/felipe/airflow/dags/19_postgre_operator.py
Traceback (most recent call last):
  File "/home/felipe/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/felipe/airflow/dags/19_postgre_operator.py", line 14, in <module>
    extract_gz = BashOperator(
  File "/home/felipe/.local/lib/python3.10/site-packages/airflow/models/baseoperator.py", line 437, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/home/felipe/.local/lib/python3.10/site-packages/airflow/operators/bash.py", line 152, in __init__
    super().__init__(**kwargs)
  File "/home/felipe/.local/lib/python3.10/site-packages/airflow/models/baseoperator.py", line 437, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/home/felipe/.local/lib/python3.10/site-packages/airflow/models/baseoperator.py", line 798, in __init__
    raise AirflowException(
airflow.exceptions.AirflowException: Invalid arguments were passed to BashOperator (task_id: extract_gz). Invalid arguments were:
**kwargs: {'template_searchpath': '/tmp'}
[2023-12-31T12:28:57.810-0300] {processor.py:842} WARNING - No viable dags retrieved from /home/felipe/airflow/dags/19_postgre_operator.py
[2023-12-31T12:28:58.261-0300] {processor.py:183} INFO - Processing /home/felipe/airflow/dags/19_postgre_operator.py took 0.780 seconds
[2023-12-31T12:29:29.601-0300] {processor.py:161} INFO - Started process (PID=38143) to work on /home/felipe/airflow/dags/19_postgre_operator.py
[2023-12-31T12:29:29.621-0300] {processor.py:830} INFO - Processing file /home/felipe/airflow/dags/19_postgre_operator.py for tasks to queue
[2023-12-31T12:29:29.650-0300] {logging_mixin.py:188} INFO - [2023-12-31T12:29:29.640-0300] {dagbag.py:538} INFO - Filling up the DagBag from /home/felipe/airflow/dags/19_postgre_operator.py
[2023-12-31T12:29:29.841-0300] {logging_mixin.py:188} INFO - [2023-12-31T12:29:29.801-0300] {dagbag.py:348} ERROR - Failed to import: /home/felipe/airflow/dags/19_postgre_operator.py
Traceback (most recent call last):
  File "/home/felipe/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/felipe/airflow/dags/19_postgre_operator.py", line 14, in <module>
    extract_gz = BashOperator(
  File "/home/felipe/.local/lib/python3.10/site-packages/airflow/models/baseoperator.py", line 437, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/home/felipe/.local/lib/python3.10/site-packages/airflow/operators/bash.py", line 152, in __init__
    super().__init__(**kwargs)
  File "/home/felipe/.local/lib/python3.10/site-packages/airflow/models/baseoperator.py", line 437, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/home/felipe/.local/lib/python3.10/site-packages/airflow/models/baseoperator.py", line 798, in __init__
    raise AirflowException(
airflow.exceptions.AirflowException: Invalid arguments were passed to BashOperator (task_id: extract_gz). Invalid arguments were:
**kwargs: {'template_searchpath': '/tmp'}
[2023-12-31T12:29:29.851-0300] {processor.py:842} WARNING - No viable dags retrieved from /home/felipe/airflow/dags/19_postgre_operator.py
[2023-12-31T12:29:30.271-0300] {processor.py:183} INFO - Processing /home/felipe/airflow/dags/19_postgre_operator.py took 0.720 seconds
[2023-12-31T12:30:10.240-0300] {processor.py:161} INFO - Started process (PID=38172) to work on /home/felipe/airflow/dags/19_postgre_operator.py
[2023-12-31T12:30:10.261-0300] {processor.py:830} INFO - Processing file /home/felipe/airflow/dags/19_postgre_operator.py for tasks to queue
[2023-12-31T12:30:10.281-0300] {logging_mixin.py:188} INFO - [2023-12-31T12:30:10.280-0300] {dagbag.py:538} INFO - Filling up the DagBag from /home/felipe/airflow/dags/19_postgre_operator.py
[2023-12-31T12:30:10.501-0300] {logging_mixin.py:188} INFO - [2023-12-31T12:30:10.470-0300] {dagbag.py:348} ERROR - Failed to import: /home/felipe/airflow/dags/19_postgre_operator.py
Traceback (most recent call last):
  File "/home/felipe/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/felipe/airflow/dags/19_postgre_operator.py", line 14, in <module>
    extract_gz = BashOperator(
  File "/home/felipe/.local/lib/python3.10/site-packages/airflow/models/baseoperator.py", line 437, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/home/felipe/.local/lib/python3.10/site-packages/airflow/operators/bash.py", line 152, in __init__
    super().__init__(**kwargs)
  File "/home/felipe/.local/lib/python3.10/site-packages/airflow/models/baseoperator.py", line 437, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/home/felipe/.local/lib/python3.10/site-packages/airflow/models/baseoperator.py", line 798, in __init__
    raise AirflowException(
airflow.exceptions.AirflowException: Invalid arguments were passed to BashOperator (task_id: extract_gz). Invalid arguments were:
**kwargs: {'template_searchpath': '/tmp'}
[2023-12-31T12:30:10.511-0300] {processor.py:842} WARNING - No viable dags retrieved from /home/felipe/airflow/dags/19_postgre_operator.py
[2023-12-31T12:30:10.950-0300] {processor.py:183} INFO - Processing /home/felipe/airflow/dags/19_postgre_operator.py took 0.780 seconds
[2023-12-31T12:30:47.990-0300] {processor.py:161} INFO - Started process (PID=38227) to work on /home/felipe/airflow/dags/19_postgre_operator.py
[2023-12-31T12:30:48.011-0300] {processor.py:830} INFO - Processing file /home/felipe/airflow/dags/19_postgre_operator.py for tasks to queue
[2023-12-31T12:30:48.030-0300] {logging_mixin.py:188} INFO - [2023-12-31T12:30:48.021-0300] {dagbag.py:538} INFO - Filling up the DagBag from /home/felipe/airflow/dags/19_postgre_operator.py
[2023-12-31T12:30:48.230-0300] {logging_mixin.py:188} INFO - [2023-12-31T12:30:48.191-0300] {dagbag.py:348} ERROR - Failed to import: /home/felipe/airflow/dags/19_postgre_operator.py
Traceback (most recent call last):
  File "/home/felipe/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/felipe/airflow/dags/19_postgre_operator.py", line 14, in <module>
    extract_gz = BashOperator(
  File "/home/felipe/.local/lib/python3.10/site-packages/airflow/models/baseoperator.py", line 437, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/home/felipe/.local/lib/python3.10/site-packages/airflow/operators/bash.py", line 152, in __init__
    super().__init__(**kwargs)
  File "/home/felipe/.local/lib/python3.10/site-packages/airflow/models/baseoperator.py", line 437, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/home/felipe/.local/lib/python3.10/site-packages/airflow/models/baseoperator.py", line 798, in __init__
    raise AirflowException(
airflow.exceptions.AirflowException: Invalid arguments were passed to BashOperator (task_id: extract_gz). Invalid arguments were:
**kwargs: {'template_searchpath': '/tmp'}
[2023-12-31T12:30:48.240-0300] {processor.py:842} WARNING - No viable dags retrieved from /home/felipe/airflow/dags/19_postgre_operator.py
[2023-12-31T12:30:48.681-0300] {processor.py:183} INFO - Processing /home/felipe/airflow/dags/19_postgre_operator.py took 0.750 seconds
[2023-12-31T12:31:26.701-0300] {processor.py:161} INFO - Started process (PID=38253) to work on /home/felipe/airflow/dags/19_postgre_operator.py
[2023-12-31T12:31:26.731-0300] {processor.py:830} INFO - Processing file /home/felipe/airflow/dags/19_postgre_operator.py for tasks to queue
[2023-12-31T12:31:26.751-0300] {logging_mixin.py:188} INFO - [2023-12-31T12:31:26.741-0300] {dagbag.py:538} INFO - Filling up the DagBag from /home/felipe/airflow/dags/19_postgre_operator.py
[2023-12-31T12:31:26.971-0300] {logging_mixin.py:188} INFO - [2023-12-31T12:31:26.931-0300] {dagbag.py:348} ERROR - Failed to import: /home/felipe/airflow/dags/19_postgre_operator.py
Traceback (most recent call last):
  File "/home/felipe/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/felipe/airflow/dags/19_postgre_operator.py", line 14, in <module>
    extract_gz = BashOperator(
  File "/home/felipe/.local/lib/python3.10/site-packages/airflow/models/baseoperator.py", line 437, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/home/felipe/.local/lib/python3.10/site-packages/airflow/operators/bash.py", line 152, in __init__
    super().__init__(**kwargs)
  File "/home/felipe/.local/lib/python3.10/site-packages/airflow/models/baseoperator.py", line 437, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/home/felipe/.local/lib/python3.10/site-packages/airflow/models/baseoperator.py", line 798, in __init__
    raise AirflowException(
airflow.exceptions.AirflowException: Invalid arguments were passed to BashOperator (task_id: extract_gz). Invalid arguments were:
**kwargs: {'template_searchpath': '/tmp'}
[2023-12-31T12:31:26.990-0300] {processor.py:842} WARNING - No viable dags retrieved from /home/felipe/airflow/dags/19_postgre_operator.py
[2023-12-31T12:31:27.481-0300] {processor.py:183} INFO - Processing /home/felipe/airflow/dags/19_postgre_operator.py took 0.840 seconds
[2023-12-31T12:32:05.160-0300] {processor.py:161} INFO - Started process (PID=38275) to work on /home/felipe/airflow/dags/19_postgre_operator.py
[2023-12-31T12:32:05.181-0300] {processor.py:830} INFO - Processing file /home/felipe/airflow/dags/19_postgre_operator.py for tasks to queue
[2023-12-31T12:32:05.210-0300] {logging_mixin.py:188} INFO - [2023-12-31T12:32:05.200-0300] {dagbag.py:538} INFO - Filling up the DagBag from /home/felipe/airflow/dags/19_postgre_operator.py
[2023-12-31T12:32:05.391-0300] {logging_mixin.py:188} INFO - [2023-12-31T12:32:05.351-0300] {dagbag.py:348} ERROR - Failed to import: /home/felipe/airflow/dags/19_postgre_operator.py
Traceback (most recent call last):
  File "/home/felipe/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/felipe/airflow/dags/19_postgre_operator.py", line 14, in <module>
    extract_gz = BashOperator(
  File "/home/felipe/.local/lib/python3.10/site-packages/airflow/models/baseoperator.py", line 437, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/home/felipe/.local/lib/python3.10/site-packages/airflow/operators/bash.py", line 152, in __init__
    super().__init__(**kwargs)
  File "/home/felipe/.local/lib/python3.10/site-packages/airflow/models/baseoperator.py", line 437, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/home/felipe/.local/lib/python3.10/site-packages/airflow/models/baseoperator.py", line 798, in __init__
    raise AirflowException(
airflow.exceptions.AirflowException: Invalid arguments were passed to BashOperator (task_id: extract_gz). Invalid arguments were:
**kwargs: {'template_searchpath': '/tmp'}
[2023-12-31T12:32:05.401-0300] {processor.py:842} WARNING - No viable dags retrieved from /home/felipe/airflow/dags/19_postgre_operator.py
[2023-12-31T12:32:05.871-0300] {processor.py:183} INFO - Processing /home/felipe/airflow/dags/19_postgre_operator.py took 0.770 seconds
[2023-12-31T12:32:49.631-0300] {processor.py:161} INFO - Started process (PID=38307) to work on /home/felipe/airflow/dags/19_postgre_operator.py
[2023-12-31T12:32:49.651-0300] {processor.py:830} INFO - Processing file /home/felipe/airflow/dags/19_postgre_operator.py for tasks to queue
[2023-12-31T12:32:49.680-0300] {logging_mixin.py:188} INFO - [2023-12-31T12:32:49.670-0300] {dagbag.py:538} INFO - Filling up the DagBag from /home/felipe/airflow/dags/19_postgre_operator.py
[2023-12-31T12:32:49.880-0300] {logging_mixin.py:188} INFO - [2023-12-31T12:32:49.831-0300] {dagbag.py:348} ERROR - Failed to import: /home/felipe/airflow/dags/19_postgre_operator.py
Traceback (most recent call last):
  File "/home/felipe/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/felipe/airflow/dags/19_postgre_operator.py", line 14, in <module>
    extract_gz = BashOperator(
  File "/home/felipe/.local/lib/python3.10/site-packages/airflow/models/baseoperator.py", line 437, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/home/felipe/.local/lib/python3.10/site-packages/airflow/operators/bash.py", line 152, in __init__
    super().__init__(**kwargs)
  File "/home/felipe/.local/lib/python3.10/site-packages/airflow/models/baseoperator.py", line 437, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/home/felipe/.local/lib/python3.10/site-packages/airflow/models/baseoperator.py", line 798, in __init__
    raise AirflowException(
airflow.exceptions.AirflowException: Invalid arguments were passed to BashOperator (task_id: extract_gz). Invalid arguments were:
**kwargs: {'template_searchpath': '/tmp'}
[2023-12-31T12:32:49.891-0300] {processor.py:842} WARNING - No viable dags retrieved from /home/felipe/airflow/dags/19_postgre_operator.py
[2023-12-31T12:32:50.411-0300] {processor.py:183} INFO - Processing /home/felipe/airflow/dags/19_postgre_operator.py took 0.840 seconds
[2023-12-31T12:33:35.191-0300] {processor.py:161} INFO - Started process (PID=38332) to work on /home/felipe/airflow/dags/19_postgre_operator.py
[2023-12-31T12:33:35.221-0300] {processor.py:830} INFO - Processing file /home/felipe/airflow/dags/19_postgre_operator.py for tasks to queue
[2023-12-31T12:33:35.250-0300] {logging_mixin.py:188} INFO - [2023-12-31T12:33:35.240-0300] {dagbag.py:538} INFO - Filling up the DagBag from /home/felipe/airflow/dags/19_postgre_operator.py
[2023-12-31T12:33:35.490-0300] {logging_mixin.py:188} INFO - [2023-12-31T12:33:35.441-0300] {dagbag.py:348} ERROR - Failed to import: /home/felipe/airflow/dags/19_postgre_operator.py
Traceback (most recent call last):
  File "/home/felipe/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/felipe/airflow/dags/19_postgre_operator.py", line 14, in <module>
    extract_gz = BashOperator(
  File "/home/felipe/.local/lib/python3.10/site-packages/airflow/models/baseoperator.py", line 437, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/home/felipe/.local/lib/python3.10/site-packages/airflow/operators/bash.py", line 152, in __init__
    super().__init__(**kwargs)
  File "/home/felipe/.local/lib/python3.10/site-packages/airflow/models/baseoperator.py", line 437, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/home/felipe/.local/lib/python3.10/site-packages/airflow/models/baseoperator.py", line 798, in __init__
    raise AirflowException(
airflow.exceptions.AirflowException: Invalid arguments were passed to BashOperator (task_id: extract_gz). Invalid arguments were:
**kwargs: {'template_searchpath': '/tmp'}
[2023-12-31T12:33:35.500-0300] {processor.py:842} WARNING - No viable dags retrieved from /home/felipe/airflow/dags/19_postgre_operator.py
[2023-12-31T12:33:36.000-0300] {processor.py:183} INFO - Processing /home/felipe/airflow/dags/19_postgre_operator.py took 0.890 seconds
[2023-12-31T12:34:19.821-0300] {processor.py:161} INFO - Started process (PID=38362) to work on /home/felipe/airflow/dags/19_postgre_operator.py
[2023-12-31T12:34:19.850-0300] {processor.py:830} INFO - Processing file /home/felipe/airflow/dags/19_postgre_operator.py for tasks to queue
[2023-12-31T12:34:19.871-0300] {logging_mixin.py:188} INFO - [2023-12-31T12:34:19.861-0300] {dagbag.py:538} INFO - Filling up the DagBag from /home/felipe/airflow/dags/19_postgre_operator.py
[2023-12-31T12:34:20.120-0300] {logging_mixin.py:188} INFO - [2023-12-31T12:34:20.071-0300] {dagbag.py:348} ERROR - Failed to import: /home/felipe/airflow/dags/19_postgre_operator.py
Traceback (most recent call last):
  File "/home/felipe/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/felipe/airflow/dags/19_postgre_operator.py", line 14, in <module>
    extract_gz = BashOperator(
  File "/home/felipe/.local/lib/python3.10/site-packages/airflow/models/baseoperator.py", line 437, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/home/felipe/.local/lib/python3.10/site-packages/airflow/operators/bash.py", line 152, in __init__
    super().__init__(**kwargs)
  File "/home/felipe/.local/lib/python3.10/site-packages/airflow/models/baseoperator.py", line 437, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/home/felipe/.local/lib/python3.10/site-packages/airflow/models/baseoperator.py", line 798, in __init__
    raise AirflowException(
airflow.exceptions.AirflowException: Invalid arguments were passed to BashOperator (task_id: extract_gz). Invalid arguments were:
**kwargs: {'template_searchpath': '/tmp'}
[2023-12-31T12:34:20.131-0300] {processor.py:842} WARNING - No viable dags retrieved from /home/felipe/airflow/dags/19_postgre_operator.py
[2023-12-31T12:34:20.670-0300] {processor.py:183} INFO - Processing /home/felipe/airflow/dags/19_postgre_operator.py took 0.910 seconds
[2023-12-31T12:35:05.370-0300] {processor.py:161} INFO - Started process (PID=38386) to work on /home/felipe/airflow/dags/19_postgre_operator.py
[2023-12-31T12:35:05.400-0300] {processor.py:830} INFO - Processing file /home/felipe/airflow/dags/19_postgre_operator.py for tasks to queue
[2023-12-31T12:35:05.430-0300] {logging_mixin.py:188} INFO - [2023-12-31T12:35:05.420-0300] {dagbag.py:538} INFO - Filling up the DagBag from /home/felipe/airflow/dags/19_postgre_operator.py
[2023-12-31T12:35:05.660-0300] {logging_mixin.py:188} INFO - [2023-12-31T12:35:05.610-0300] {dagbag.py:348} ERROR - Failed to import: /home/felipe/airflow/dags/19_postgre_operator.py
Traceback (most recent call last):
  File "/home/felipe/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/felipe/airflow/dags/19_postgre_operator.py", line 14, in <module>
    extract_gz = BashOperator(
  File "/home/felipe/.local/lib/python3.10/site-packages/airflow/models/baseoperator.py", line 437, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/home/felipe/.local/lib/python3.10/site-packages/airflow/operators/bash.py", line 152, in __init__
    super().__init__(**kwargs)
  File "/home/felipe/.local/lib/python3.10/site-packages/airflow/models/baseoperator.py", line 437, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/home/felipe/.local/lib/python3.10/site-packages/airflow/models/baseoperator.py", line 798, in __init__
    raise AirflowException(
airflow.exceptions.AirflowException: Invalid arguments were passed to BashOperator (task_id: extract_gz). Invalid arguments were:
**kwargs: {'template_searchpath': '/tmp'}
[2023-12-31T12:35:05.671-0300] {processor.py:842} WARNING - No viable dags retrieved from /home/felipe/airflow/dags/19_postgre_operator.py
[2023-12-31T12:35:06.210-0300] {processor.py:183} INFO - Processing /home/felipe/airflow/dags/19_postgre_operator.py took 0.910 seconds
[2023-12-31T12:36:01.341-0300] {processor.py:161} INFO - Started process (PID=38449) to work on /home/felipe/airflow/dags/19_postgre_operator.py
[2023-12-31T12:36:01.380-0300] {processor.py:830} INFO - Processing file /home/felipe/airflow/dags/19_postgre_operator.py for tasks to queue
[2023-12-31T12:36:01.421-0300] {logging_mixin.py:188} INFO - [2023-12-31T12:36:01.410-0300] {dagbag.py:538} INFO - Filling up the DagBag from /home/felipe/airflow/dags/19_postgre_operator.py
[2023-12-31T12:36:01.710-0300] {logging_mixin.py:188} INFO - [2023-12-31T12:36:01.651-0300] {dagbag.py:348} ERROR - Failed to import: /home/felipe/airflow/dags/19_postgre_operator.py
Traceback (most recent call last):
  File "/home/felipe/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/felipe/airflow/dags/19_postgre_operator.py", line 14, in <module>
    extract_gz = BashOperator(
  File "/home/felipe/.local/lib/python3.10/site-packages/airflow/models/baseoperator.py", line 437, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/home/felipe/.local/lib/python3.10/site-packages/airflow/operators/bash.py", line 152, in __init__
    super().__init__(**kwargs)
  File "/home/felipe/.local/lib/python3.10/site-packages/airflow/models/baseoperator.py", line 437, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/home/felipe/.local/lib/python3.10/site-packages/airflow/models/baseoperator.py", line 798, in __init__
    raise AirflowException(
airflow.exceptions.AirflowException: Invalid arguments were passed to BashOperator (task_id: extract_gz). Invalid arguments were:
**kwargs: {'template_searchpath': '/tmp'}
[2023-12-31T12:36:01.731-0300] {processor.py:842} WARNING - No viable dags retrieved from /home/felipe/airflow/dags/19_postgre_operator.py
[2023-12-31T12:36:02.391-0300] {processor.py:183} INFO - Processing /home/felipe/airflow/dags/19_postgre_operator.py took 1.130 seconds
[2023-12-31T12:36:58.340-0300] {processor.py:161} INFO - Started process (PID=38482) to work on /home/felipe/airflow/dags/19_postgre_operator.py
[2023-12-31T12:36:58.370-0300] {processor.py:830} INFO - Processing file /home/felipe/airflow/dags/19_postgre_operator.py for tasks to queue
[2023-12-31T12:36:58.401-0300] {logging_mixin.py:188} INFO - [2023-12-31T12:36:58.390-0300] {dagbag.py:538} INFO - Filling up the DagBag from /home/felipe/airflow/dags/19_postgre_operator.py
[2023-12-31T12:36:58.691-0300] {logging_mixin.py:188} INFO - [2023-12-31T12:36:58.630-0300] {dagbag.py:348} ERROR - Failed to import: /home/felipe/airflow/dags/19_postgre_operator.py
Traceback (most recent call last):
  File "/home/felipe/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/felipe/airflow/dags/19_postgre_operator.py", line 14, in <module>
    extract_gz = BashOperator(
  File "/home/felipe/.local/lib/python3.10/site-packages/airflow/models/baseoperator.py", line 437, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/home/felipe/.local/lib/python3.10/site-packages/airflow/operators/bash.py", line 152, in __init__
    super().__init__(**kwargs)
  File "/home/felipe/.local/lib/python3.10/site-packages/airflow/models/baseoperator.py", line 437, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/home/felipe/.local/lib/python3.10/site-packages/airflow/models/baseoperator.py", line 798, in __init__
    raise AirflowException(
airflow.exceptions.AirflowException: Invalid arguments were passed to BashOperator (task_id: extract_gz). Invalid arguments were:
**kwargs: {'template_searchpath': '/tmp'}
[2023-12-31T12:36:58.710-0300] {processor.py:842} WARNING - No viable dags retrieved from /home/felipe/airflow/dags/19_postgre_operator.py
[2023-12-31T12:36:59.420-0300] {processor.py:183} INFO - Processing /home/felipe/airflow/dags/19_postgre_operator.py took 1.180 seconds
[2023-12-31T12:38:13.280-0300] {processor.py:161} INFO - Started process (PID=38523) to work on /home/felipe/airflow/dags/19_postgre_operator.py
[2023-12-31T12:38:13.320-0300] {processor.py:830} INFO - Processing file /home/felipe/airflow/dags/19_postgre_operator.py for tasks to queue
[2023-12-31T12:38:13.351-0300] {logging_mixin.py:188} INFO - [2023-12-31T12:38:13.340-0300] {dagbag.py:538} INFO - Filling up the DagBag from /home/felipe/airflow/dags/19_postgre_operator.py
[2023-12-31T12:38:13.670-0300] {logging_mixin.py:188} INFO - [2023-12-31T12:38:13.620-0300] {dagbag.py:348} ERROR - Failed to import: /home/felipe/airflow/dags/19_postgre_operator.py
Traceback (most recent call last):
  File "/home/felipe/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/felipe/airflow/dags/19_postgre_operator.py", line 14, in <module>
    extract_gz = BashOperator(
  File "/home/felipe/.local/lib/python3.10/site-packages/airflow/models/baseoperator.py", line 437, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/home/felipe/.local/lib/python3.10/site-packages/airflow/operators/bash.py", line 152, in __init__
    super().__init__(**kwargs)
  File "/home/felipe/.local/lib/python3.10/site-packages/airflow/models/baseoperator.py", line 437, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/home/felipe/.local/lib/python3.10/site-packages/airflow/models/baseoperator.py", line 798, in __init__
    raise AirflowException(
airflow.exceptions.AirflowException: Invalid arguments were passed to BashOperator (task_id: extract_gz). Invalid arguments were:
**kwargs: {'template_searchpath': '/tmp'}
[2023-12-31T12:38:13.690-0300] {processor.py:842} WARNING - No viable dags retrieved from /home/felipe/airflow/dags/19_postgre_operator.py
[2023-12-31T12:38:14.420-0300] {processor.py:183} INFO - Processing /home/felipe/airflow/dags/19_postgre_operator.py took 1.280 seconds
[2023-12-31T12:47:25.698-0300] {processor.py:161} INFO - Started process (PID=38766) to work on /home/felipe/airflow/dags/19_postgre_operator.py
[2023-12-31T12:47:25.778-0300] {processor.py:830} INFO - Processing file /home/felipe/airflow/dags/19_postgre_operator.py for tasks to queue
[2023-12-31T12:47:25.858-0300] {logging_mixin.py:188} INFO - [2023-12-31T12:47:25.828-0300] {dagbag.py:538} INFO - Filling up the DagBag from /home/felipe/airflow/dags/19_postgre_operator.py
[2023-12-31T12:47:26.498-0300] {logging_mixin.py:188} INFO - [2023-12-31T12:47:26.388-0300] {dagbag.py:348} ERROR - Failed to import: /home/felipe/airflow/dags/19_postgre_operator.py
Traceback (most recent call last):
  File "/home/felipe/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/felipe/airflow/dags/19_postgre_operator.py", line 14, in <module>
    extract_gz = BashOperator(
  File "/home/felipe/.local/lib/python3.10/site-packages/airflow/models/baseoperator.py", line 437, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/home/felipe/.local/lib/python3.10/site-packages/airflow/operators/bash.py", line 152, in __init__
    super().__init__(**kwargs)
  File "/home/felipe/.local/lib/python3.10/site-packages/airflow/models/baseoperator.py", line 437, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/home/felipe/.local/lib/python3.10/site-packages/airflow/models/baseoperator.py", line 798, in __init__
    raise AirflowException(
airflow.exceptions.AirflowException: Invalid arguments were passed to BashOperator (task_id: extract_gz). Invalid arguments were:
**kwargs: {'template_searchpath': '/tmp'}
[2023-12-31T12:47:26.547-0300] {processor.py:842} WARNING - No viable dags retrieved from /home/felipe/airflow/dags/19_postgre_operator.py
[2023-12-31T12:47:28.398-0300] {processor.py:183} INFO - Processing /home/felipe/airflow/dags/19_postgre_operator.py took 2.910 seconds
[2023-12-31T12:49:55.918-0300] {processor.py:161} INFO - Started process (PID=38834) to work on /home/felipe/airflow/dags/19_postgre_operator.py
[2023-12-31T12:49:56.007-0300] {processor.py:830} INFO - Processing file /home/felipe/airflow/dags/19_postgre_operator.py for tasks to queue
[2023-12-31T12:49:56.127-0300] {logging_mixin.py:188} INFO - [2023-12-31T12:49:56.087-0300] {dagbag.py:538} INFO - Filling up the DagBag from /home/felipe/airflow/dags/19_postgre_operator.py
[2023-12-31T12:49:56.988-0300] {logging_mixin.py:188} INFO - [2023-12-31T12:49:56.828-0300] {dagbag.py:348} ERROR - Failed to import: /home/felipe/airflow/dags/19_postgre_operator.py
Traceback (most recent call last):
  File "/home/felipe/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/felipe/airflow/dags/19_postgre_operator.py", line 14, in <module>
    extract_gz = BashOperator(
  File "/home/felipe/.local/lib/python3.10/site-packages/airflow/models/baseoperator.py", line 437, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/home/felipe/.local/lib/python3.10/site-packages/airflow/operators/bash.py", line 152, in __init__
    super().__init__(**kwargs)
  File "/home/felipe/.local/lib/python3.10/site-packages/airflow/models/baseoperator.py", line 437, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/home/felipe/.local/lib/python3.10/site-packages/airflow/models/baseoperator.py", line 798, in __init__
    raise AirflowException(
airflow.exceptions.AirflowException: Invalid arguments were passed to BashOperator (task_id: extract_gz). Invalid arguments were:
**kwargs: {'template_searchpath': '/tmp'}
[2023-12-31T12:49:57.038-0300] {processor.py:842} WARNING - No viable dags retrieved from /home/felipe/airflow/dags/19_postgre_operator.py
[2023-12-31T12:49:58.638-0300] {processor.py:183} INFO - Processing /home/felipe/airflow/dags/19_postgre_operator.py took 3.020 seconds
