[2024-01-01T11:49:36.242-0300] {scheduler_job_runner.py:781} ERROR - Executor reports task instance <TaskInstance: stocksense.print_context scheduled__2024-01-01T07:00:00+00:00 [queued]> finished (failed) although the task says it's queued. (Info: None) Was the task killed externally?
